### ISSUE TITLE
One jenkins multiple teams

### ISSUE THREAD

**Issue by pkobes** [jenkinsci/slack-plugin#10]
Hi,

we have one Jenkins instance and multiple Slack teams (projects). Current plugin in global settings defines Slack "secrets" so you can't configure it for multiple teams.
So either put this to the build configuration or enable definition of Teams in th global settings where a value can be than picked for a specific build.
This is quite a showstopper for our case.

Can I expect the fix in a reasonable time or do we have to make a change ourselves?

thanks in advance

Peter

**Comment by kylefowler** [comment]
There is still the issue here of having multiple jenkins builds on the same instance posting to different rooms. You can specify a build to post to different rooms but it doesnt seem like you can have a single global config post to different rooms given that the integrations all have their own api tokens.

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released. A fix for this has been included in it. Please try out the new version and if it doesn't resolve this issue then ask for this to be re-opened and provide more details.

**Comment by spuniun** [comment]
I do not believe this is working.
We have Slack plugin 1.8 and jobs will only post to the first channel specified in the list. Any additional channels get nothing.

**Comment by cmeury** [comment]
Encountering the same issue as @spuniun.

**Comment by samrocketman** [comment]
@spuniun @cmeury see issue #98

**Comment by naitse** [comment]
Can you just specify the channel to be notified at the job configuration instead of being global? we have several teams using same jenkins and would be nice just to let them configure the channel to be notified at the job so there is no impact on the global configuration
