### ISSUE TITLE
Pass build parameters to Slack

### ISSUE THREAD

**Issue by mtwalsh** [jenkinsci/slack-plugin#108]
We use Jenkins for deployment and have a single job that deploys any of our projects based on a build parameter.  Rather than just knowing the job has run in Slack it would be great if the build parameter for the project could be passed too.

**Comment by mtwalsh** [comment]
Apologies, I've found this is already possible by setting a custom message after hitting the Advanced button when configuring the job.

**Comment by samrocketman** [comment]
Glad you found a work-around.
