### ISSUE TITLE
It is possible format custom message ?

### ISSUE THREAD

**Issue by joncolas** [jenkinsci/slack-plugin#109]
It is possible give format to custom message ? as described here:
https://slack.zendesk.com/hc/en-us/articles/202288908-Formatting-your-messages

**Comment by samrocketman** [comment]
Have you tried?

**Comment by joncolas** [comment]
yeah i tried this in the custom message field:
http://screencloud.net/v/ddzQ

and the ` ` not display inline fixed-width text

thanks in advance

**Comment by joncolas** [comment]
-i am trying to put en custom message field this:
https://screencloud.net/v/ddzQ

-Slack prints:
 \`Deploy started\`

-But it must print something like this:
http://screencloud.net/v/95Yc

some advices?

thanks in advance

**Comment by samrocketman** [comment]
Ah I get it.  I'll try it myself as well.  I don't actively develop this plugin.  I only maintain pull requests and releases.  Contributions are welcome!

I'll check to see if I can get it to format.

**Comment by joncolas** [comment]
thank you very much, awesome plugin.

*Jon Colás Gómez*. System Administrator
*SocialBro*

  ¿Nos sigues? @SocialBro_es <https://twitter.com/SocialBro_es>

Haz que Twitter trabaje para tu marca usando SocialBro
<http://es.socialbro.com/>
¡No te pierdas nuestros últimos posts en el blog de SocialBro!
<http://es.socialbro.com/blog-es>
<https://www.youtube.com/watchv=xRq8WbRLktY&list=PLTOntFbE_p_U6X53k7h3VH23a79O9ser2>
San Felipe 9, 3º Izda.
14003 Córdoba
España



2015-06-18 15:11 GMT+02:00 Sam Gleske <notifications@github.com>:

**Comment by danmandle** [comment]
@joncolas Your screenshots aren't up anymore.

It would be awesome to have a text field with the post-build actions that allows additional information to be sent using Jenkins variables. For example, I'm using this to let us know when a deploy happens, but the message doesn't have the build parameters, so I don't know what environment it was deployed to.

**Comment by samrocketman** [comment]
This issue as been addressed by  #127.  This should be fixed in the next release.

**Comment by mgedmin** [comment]
I'm confused: this was merged to master before the slack-1.8.1 release (which happened on 15 Nov 2015), but this issue is still open, and the milestone here says 2.0?  Also, my experiments show that `[url markup](http://.../)` is rendered raw and not converted to a link.  What happened?

**Comment by samrocketman** [comment]
I don't believe that `[url markup](http...)` is supported in Slack.  It didn't work the last time I checked.  Best to test with other markdown such as `*bold*` or `_italics_` text.

**Comment by woile** [comment]
I'm having this issue. Currently slack has support for `[...](url)` and it doesn't work. I've tried using the `sendAsText` with no success. Maybe worth talking a look again.

**Comment by stuartrowe** [comment]
The markdown for links is `<url|link>`.

**Comment by woile** [comment]
Thanks! Using `<url|text>` worked!
