### ISSUE TITLE
Multiple teams in one jenkins

### ISSUE THREAD

**Issue by azmelanar** [jenkinsci/slack-plugin#111]
Hi,

This issue already was discussed in #10, but slack plugin 1.7 not fixed it and 1.8 too.

For more information:

In current settings we can specify only one global team and token, but if another team want integration too, it will not work. Because we already have configuration for one team.

Maybe I something missing and this functional already released. But I don't see it.

Thank you!

**Comment by paulpv** [comment]
Ditto. Similarly, I can't seem to get the "multiple channels" feature to work. When I go to Slack and configure the Jenkins integration, it only lets me associate one channel per token. When I go to Jenkins and configure the Slack plugin, it only lets me enter one token, but says I can comma-delimit multiple channels, but when I test that, I only see the test message in the channel I configured on Slack.

**Comment by samrocketman** [comment]
@paulpv In the `master` branch, posting multiple channels has been bug fixed by #100.  It has yet to be released and will be in the 2.0 release.

@azmelanar multiple teams in one jenkins already works.  By using the advanced section of the settings in an individual job one can configure an additional team just for that job.

**Comment by samrocketman** [comment]
Marking invalid since this has already been released and I've tested it.

**Comment by azmelanar** [comment]
@samrocketman, you're right.

Yes, i miss 'Advanced' button for job.

Few screenshots:

![](http://dl2.joxi.net/drive/0010/2181/686213/150626/865d28429c.jpg)

![](http://dl2.joxi.net/drive/0010/2181/686213/150626/4a83926963.jpg)

@paulpv, maybe it will help you.

Thanks!
