### ISSUE TITLE
notify repeated instability

### ISSUE THREAD

**Issue by dtheodor** [jenkinsci/slack-plugin#112]
Hi,

I would like this plugin to notify me only _once_ when a build fails or becomes unstable, and then only send the next notification when the build becomes stable again. Otherwise the spam coming into the slack channel really makes this plugin unusable.

I see there is an option of "notify repeated failure" that probably works like that, but only for failures. I don't think that failures are all that common, at least not in our project. It's the test failures which result in build instability that are the common incident.

There must be interest in such a feature by others as well. Or is this already implemented somehow and I missed it?

**Comment by samrocketman** [comment]
I'll have to test notify repeated instability.  I'll do it when I get back from vacation (4th of July holiday in the U.S.).  I'll let you know of my results.

**Comment by samrocketman** [comment]
I've tested this and confirm that only notify repeated failures is implemented.  Contributions are welcome to address this issue.  I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by timja** [comment]
Given this feature request has been open for a long time and hasn't received any attention I'm going to close it.

Personally I think if a test fails the build should fail, that use case is addressed in this plugin with notify first failure only
