### ISSUE TITLE
selecting "Notify Repeated Failure" is ignored

### ISSUE THREAD

**Issue by bootandy** [jenkinsci/slack-plugin#113]
Plugin: Version 1.7. Jenkins 1.554.3. Chrome browser

Checking "Notify Repeated Failure" results in the tick in checkbox moving to "Include Test Summary" when the config is saved. 
Interestingly selecting both checkboxes leaves them both checked.

**Comment by samrocketman** [comment]
This bug has already been fixed in the 1.8 release.  Please upgrade to the latest version.  Duplicate of #66.
