### ISSUE TITLE
"no Slack configuration" for multi-configuration build

### ISSUE THREAD

**Issue by tdsmith** [jenkinsci/slack-plugin#114]
We have a multi-configuration build with the Matrix Project Plugin. Sending Slack notifications on build completion is only working occasionally; when it does not work (i.e. no notification is received at the completion of a build), this appears in the Jenkins log, naming one of the matrix configurations:

```
Jul 16, 2015 5:34:55 AM WARNING jenkins.plugins.slack.ActiveNotifier completed
Project version=yosemite has no Slack configuration.
```

I think occasionally the notification is firing from the parent node (and succeeding) and usually it's firing from a build slave (and failing). Is that likely? Can I configure my way out of this?

**Comment by samrocketman** [comment]
I'll have to configure a matrix build to test.  I'll let you know of the results.

**Comment by estyrke** [comment]
This happens to me too.

**Comment by timja** [comment]
please reopen if still an issue, closing because its old and no upvotes..
