### ISSUE TITLE
Enable globally + trigger settings defaults

### ISSUE THREAD

**Issue by francisdb** [jenkinsci/slack-plugin#117]
I don't want to modify every build to have slack notifications

If that is not possible at least have some defaults for the triggers so that the user only has to add the post build action.

**Comment by samrocketman** [comment]
Are you proposing having every job notify the same slack channel with the same settings?

**Comment by francisdb** [comment]
Yes, and if that is not possible to have some proper defaults for the job settings so that adding the post build action is enough.

**Comment by Blaisorblade** [comment]
> Are you proposing having every job notify the same slack channel with the same settings?

Jobs notify the same channel by default already (#118).

> that adding the post build action is enough.

The architecture of per-project settings could IMHO be improved more; my proposal is in #119.

**Comment by samrocketman** [comment]
It's this way for the slack channel settings.  But there's no globally default conditions on how slack should be notified via settings.

**Comment by samrocketman** [comment]
Refer to https://github.com/jenkinsci/jenkins-scripts/pull/89 as a workaround.

**Comment by timja** [comment]
Use job-dsl or something like https://github.com/jenkinsci/jenkins-scripts/pull/89
