### ISSUE TITLE
UI suggests twice that this integration connects to a single channel

### ISSUE THREAD

**Issue by Blaisorblade** [jenkinsci/slack-plugin#118]
I want each of my project to notify a different slack channel, or none at all — simply because different channels are for different projects. That's in fact possible, but UI choices and UI bugs makes this hard to discover.
- When I set up the Slack integration, I must pick a single channel. I assumed this restricted the integration to that channel; it turns out it doesn't, but that seems a potential security question with Slack (I can't restrict integrations to specific channels, so I must give them complete "spamming" trust; might be fine, but unobvious). (This part might be Slack's fault, but could be documented, and the rest isn't.)
- In the global Jenkins page, there's a "Channel" text field. Unless I look at the description, I won't learn that I can write the **channels** to notify (so the text field should be labeled "Channels"), and that it can be overriden per project.
- In the per-project settings, I can override the channels, but that's an advanced setting, so by default I won't see it. After filling that in, I pressed "Test connection" to see if Slack was able to post to that channel (I assumed it wouldn't). But "Test connection" only works if you copy the connection settings from the global page — unlike the actual connection, it does not use the global settings by default — which seems an actual bug.

**Comment by samrocketman** [comment]
Improvements to the documentation are always welcome.  It would also be nice if the [Slack wiki page][wiki] had some content to it.  It could point out some of these tips and tricks for configuring.

I welcome contributions to improve this.

[wiki]: https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin

**Comment by timja** [comment]
docs have been updated
