### ISSUE TITLE
Slack settings should be part of the post-build action

### ISSUE THREAD

**Issue by Blaisorblade** [jenkinsci/slack-plugin#119]
Slack settings should be part of the post-build action, because the current setup has two problems:

- It's possible to enable Slack settings for a project without the post-build actions. This status is bogus and should be impossible.
- Conversely, Slack settings appear even for projects when no Slack integration is desired.

It'd be better to turn those settings into settings for the action. It'd alternatively be better if the plugin did its notifications (when enabled) without requiring the user to add a post-build action explicitly—if that's allowed by Jenkins (I guess not).

**Comment by samrocketman** [comment]
`master` already has the settings moved into the post-build action.  See #79 and #106.  As always, contributions are welcome to improve the plugin.  I don't actively develop the plugin.  I only maintain pull requests and releases.  I'll close this as a duplicate because it was implemented in #79.
