### ISSUE TITLE
"success" instead of "back to normal" after aborted build

### ISSUE THREAD

**Issue by simon-weber** [jenkinsci/slack-plugin#123]
Here's some output from 1.8 after turning on notifications for aborted, failed, and back to normal (but not success):

```
build_status_test - #32 Failure after 41 ms (Open)
build_status_test - #33 Back to normal after 36 ms (Open)
build_status_test - #34 Failure after 57 ms (Open)
build_status_test - #35 Aborted after 49 ms (Open)
build_status_test - #36 Success after 34 ms (Open)
```

The last status should be back to normal, not success. It looks like this was introduced in the fix to https://github.com/jenkinsci/slack-plugin/issues/29.

**Comment by mattwilliams-stfc** [comment]
@simon-weber: see my pull request #131.
So far it makes sure that back to normal is shown if he build was previously unstable, do you want me to add another condition for aborted in there too?

**Comment by simon-weber** [comment]
If I understand your PR correctly, that's a slightly different situation. I'm going off of the behavior described in https://github.com/jenkinsci/slack-plugin/issues/29#issuecomment-72954729:
> The plugin only checks the status of the previous build. If you aborted it, it cannot currently guess what the status was before that. I'll look into checking the latest non-aborted status and patching the plugin asap.

So, in my original example, when checking the status of 36 the last non-aborted status is failure (from 34), so I expect a failure -> success transition and a "back to normal".

I think what you're describing introduces a false positive I wouldn't want. For example imagine this build sequence with messages on aborted, failed, and back to normal:
* 1: success: success (not reported)
* 2: aborted: aborted (not reported)
* 3: success: I want this treated as success (not reported), but the suggested change would make it back to normal (which would be reported).

**Comment by mattwilliams-stfc** [comment]
Sure, I see what you're saying.
 
If I get a bit of free time this week I might add that in, but I'm not sure if I should add that into my PR as it's already got a few different changes (which probably isn't best practice but it doesn't seem like PRs get seen too very often).

**Comment by mattwilliams-stfc** [comment]
@simon-weber: see the latest commit on my PR #131. Is that about what you were expecting?

**Comment by simon-weber** [comment]
Looks good! Thanks :+1:
