### ISSUE TITLE
Plugin does not play nicely with post-build actions inherited from another job

### ISSUE THREAD

**Issue by ntamas** [jenkinsci/slack-plugin#125]
The development version of the plugin does not seem to work correctly when its post-build action is added to a "job template" (i.e. another job) and the actual job just inherits the post-build actions by a "Use publishers from another job" post-build action. I'm pretty sure that it's not a configuration issue because the plugin works fine if the post-build action is explicitly added to the end of the job.

Jenkins 1.624, Slack plugin 2.0-SNAPSHOT

For what it's worth, the HipChat plugin (from which the Slack plugin was forked) works fine in this setup as well, so it may be worth seeing where the two plugins differ. For instance, the `publish` method in `SlackNotifier` seems different (although I'm no Jenkins developer so it's just a stab in the dark).

**Comment by Brantone** [comment]
I'm maintainer on template-project (https://github.com/jenkinsci/template-project-plugin) I thought there was a ticket lying around somewhere that mentioned this, but can't find it :(
Originally with release versions of both, the reason it wouldn't work is because the template-project doesn't pull in main job configs, just solely the post-build info ... With Slack's move to doing everything in post-build I'd hoped this would get solved, but haven't had time to test Slack's snapshot in conjunction template-project yet. Will keep an eye on this.

**Comment by ntamas** [comment]
Yes, I'm using the snapshot version - actually, the very reason I updated the plugin to the snapshot version is because I needed all the configuration stuff to be present in the post-build step so I could use it with job templates.

**Comment by samrocketman** [comment]
@ntamas by using the snapshot version of the plugin are you able to make use of this plugin with job templates?

**Comment by ntamas** [comment]
No - I have just tested the snapshot version (based on 53b9a1a), but the symptoms are the same: the plugin works if I add the post-build action explicitly to the end of the job but it does not work if the post-build action is "inherited" by a "Use publishers from another job" post-build action. The template project plugin is also updated to the latest stable version.

**Comment by samrocketman** [comment]
I welcome contributions to fix this issue.  I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by razitz** [comment]
+1

Jenkins 2.1, Slack plugin 2.0.1

**Comment by andrewbonney** [comment]
I've added what I hope is a fix for this in https://github.com/jenkinsci/slack-plugin/pull/361. Feedback appreciated.

**Comment by adamerstelle** [comment]
Really wanting this to be available, when is 2.4 going to be released?

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/slack-plugin/pull/361/files
