### ISSUE TITLE
Formatting/ escaping issue with Bitbucket Pull Request plugin

### ISSUE THREAD

**Issue by tnguyen14** [jenkinsci/slack-plugin#126]
I tried using the Bitbucket Pull Request plugin https://github.com/jenkinsci/bitbucket-pullrequest-builder-plugin, and the slack messages posted from this job is not escaped probably. This is what I see

```
#10 <a href="https://bitbucket.org/myorg/myrepo/pull-request/367">#367 Consolidate jsdoc and styleguide into a single doc</a> (Open)
```

I am not sure if this is an issue with this plugin, or the pull request plugin. I figured I should file this here first.

**Comment by samrocketman** [comment]
@tnguyen14 could you provide more details around this issue?  It's not clear how you're achieving this slack output.  Are you using the custom message and typing this out?  How is the slack message populating in this way?

**Comment by tnguyen14** [comment]
@samrocketman sorry for the slow response. I just add Slack Notifications as a Post-build action. No special customization of the message.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.
