### ISSUE TITLE
Parameterized builds

### ISSUE THREAD

**Issue by elyobo** [jenkinsci/slack-plugin#128]
A nice feature to have would be the ability to display some of the parameters for parameterized builds in the notifications; we have some jobs that do quite different things depending on the given parameters and they all appear to be the same in Slack, limiting the usefulness of the notifications.

**Comment by pmahajan-ee** [comment]
I second for Parameterized builds

**Comment by samrocketman** [comment]
Hello, I don't actively developer this plugin.  I do maintain pull requests and releases.  I welcome you to contribute this feature!  Seems like it would be useful.

Please base your work off of the latest master.  Contributions are welcome.

**Comment by elyobo** [comment]
Thanks @samrocketman.  I had a brief look through the code and realised that this is already sort of supported in a roundabout way via the custom messages feature (which I didn't notice documented anywhere).

You can set this by configuring your project, opening the advanced options for the slack plugin, enabling the custom message and then you can include environment variables in there using $VAR_NAME; the build parameters (at least the way ours are set up) are passed through as environment variables so at least for me I can achieve what I was looking for using the existing functionality.

Would you be open to a documentation PR to explain this somewhere?

**Comment by samrocketman** [comment]
Sure, the place to document it should be the plugin wiki on jenkins-co.org (it currently needs love).  If there's no documentation on the option itself then a PR to fix that is welcome as well.

**Comment by rmg** [comment]
What would be _really_ nice is if the [Token Macro Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin) was used instead of `EnvVars`.

Implementation wise, instead of:
```java
public MessageBuilder appendCustomMessage() {
  String customMessage = notifier.getCustomMessage();
  EnvVars envVars = build.getEnvironment(new LogTaskListener(logger, INFO));
  message.append(envVars.expand(customMessage));
  // ...
}
```

It is:
```java
public MessageBuilder appendCustomMessage() {
  String customMessage = notifier.getCustomMessage();
  LogTaskListener listener = new LogTaskListener(logger, INFO);
  message.append(TokenMacro.expandAll(build, listener, customMessage);
  // ...
}
```

Should be pretty easy to add to https://github.com/jenkinsci/slack-plugin/blob/72693fcaee1557b7daa610dda100133ff7fec5b4/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L302-L315 for anyone that has a dev environment set up it.

**Comment by rmg** [comment]
Token macro support would allow for cool things like combining with [Build Failure Analyzer](https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer#BuildFailureAnalyzer-TokenMacrointegration).

**Comment by rawadrifai** [comment]
Hey guys - I am adding a build step that injects an environment variable. I modify that variable in other following build steps, and then I have a post build action to post to slack. I post that variable value ($var_name). However, it is posting the initial value that I assigned to the variable in the "inject variable" step, and it doesn't acknowledge any changes happening throughput the build. Any idea how I can establish that?

**Comment by jordandev** [comment]
> Token macro support would allow for cool things like combining with [Build Failure Analyzer](https://wiki.jenkins-ci.org/display/JENKINS/Build+Failure+Analyzer#BuildFailureAnalyzer-TokenMacrointegration).

Yes. This would be great. Build Failure Analyzer messages are the same thing I want to be able to do.

**Comment by timja** [comment]
Token macro support adds this feature I believe, closing
