### ISSUE TITLE
Set status color in Slack message border

### ISSUE THREAD

**Issue by indirect** [jenkinsci/slack-plugin#13]
Slack allows the attachments parameter to [set a colored left-hand border](https://api.slack.com/docs/attachments) for each message. CI systems like Travis use this border to indicate the status of the build:

![image](https://cloud.githubusercontent.com/assets/78/3419075/ce7119e0-fe55-11e3-8975-51e3d0a3b514.png)

Please support this when Jenkins posts to Slack.

**Comment by alexsloan** [comment]
+1

**Comment by arielschiavoni** [comment]
+1
