### ISSUE TITLE
Global settings are saved within job configuration

### ISSUE THREAD

**Issue by dlmackin** [jenkinsci/slack-plugin#130]
When a job is modified, the current global slack notifier settings (eg team domain, build server URL) are saved within the job configuration. If the global settings are modified afterwards, the new changes won't propagate to existing jobs until they are next saved.

To reproduce this issue:
1. Configure a new job with slack notifier integration
2. Modify the global settings (eg changing the build server URL)
3. The job will not have the new settings
4. Re-save the job configuration
5. New settings are now applied

This issue was originally identified in #124

**Comment by samrocketman** [comment]
Contributions are welcome to resolve this issue!  I propose this issue be fixed by removing the global settings from the job entirely and just reference the global configuration.

I don't actively develop this plugin.  I contribute by maintaining pull requests and releases.

**Comment by timja** [comment]
Doesn't seem to do it anymore?
```
  <baseUrl></baseUrl>
      <teamDomain></teamDomain>
      <tokenCredentialId></tokenCredentialId>
      <botUser>false</botUser>
      <room></room>
```

That's on a job that relies on global config
