### ISSUE TITLE
Plugin Doesn't Send Notifications When Build Flow Job Start

### ISSUE THREAD

**Issue by VsegdaZhivoi** [jenkinsci/slack-plugin#140]
The job that runs other tasks doesn't notify in slack about start.

**Comment by samrocketman** [comment]
Thanks for filing this issue.  I don't actively develop this plugin.  I only maintain pull requests and releases.  I welcome contributions to resolve this issue via pull request.

**Comment by anorborg** [comment]
Any workaround for this?

**Comment by kmadel** [comment]
The hipchat plugin mentioned calling via a Groovy DSL for build flow or Workflow. I can attest that the following works from a Workflow script for Slack plugin as well (note, doesn't support sandbox mode and I thought it would just requires certain script approvals, but with sandbox mode on, results in a nullpointer - so may be non-sandbox only for now, so wouldn't work with Workflow script loaded from SCM for example):

```
node {
  def slack = new jenkins.plugins.slack.StandardSlackService("YOUR_TEAM_DOMAIN", "YOUR_TOKEN", "CHANNEL/ROOMs")
  slack.publish("This is a notification from the slack plugin using DSL in workflow", "green")
}
```

**Comment by timja** [comment]
Build flow is dead AFAIK...
