### ISSUE TITLE
Slack notification don't go to multiple rooms

### ISSUE THREAD

**Issue by rnikoopour** [jenkinsci/slack-plugin#143]
i'm trying to have slack notifications go to multiple channels, it looks like it was fixed here https://github.com/jenkinsci/slack-plugin/commit/87b7bd1b69f118538d425405ecb5889ee5a709a8

However, I have tried supplying to rooms using "#room1, #room2", "#room1 #room2", and "#room1; #room2" but it still only goes to #room1 and no messages go into #room2.  I looked through the logs and it doesn't even make an attempt to post to #room2.

I'm using v1.8

**Comment by samrocketman** [comment]
Duplicates #98.
