### ISSUE TITLE
@Nooba can't use your work for Slack 1.8.1 point release

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#145]
@Nooba I couldn't use your [`Nooba/slack-plugin:master`](https://github.com/Nooba/slack-plugin) branch as the basis for the `slack-1.8-stable` branch because the changes you made don't compile.

```
^_^[sam@autopsy:~/git/github/slack-plugin]$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Slack Notification Plugin
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [hpi:validate {execution: default-validate}]
[INFO] [enforcer:enforce {execution: enforce-maven}]
[INFO] [enforcer:display-info {execution: display-info}]
[INFO] Maven Version: 2.2.1
[INFO] JDK Version: 1.7.0_79 normalized as: 1.7.0-79
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.13.0-65-generic
[INFO] [localizer:generate {execution: default}]
[debug] execute contextualize
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 3 source files to /home/sam/git/github/slack-plugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/sam/git/github/slack-plugin/src/main/java/jenkins/plugins/slack/ActiveNotifier.java:[86,51] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
/home/sam/git/github/slack-plugin/src/main/java/jenkins/plugins/slack/ActiveNotifier.java:[86,51] error: cannot find symbol

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Mon Oct 26 23:48:20 PDT 2015
[INFO] Final Memory: 83M/215M
[INFO] ------------------------------------------------------------------------
```

Here's more info about the environment I normally use to compile the slack plugin for your reference.

```
^_^[sam@autopsy:~/git/github/slack-plugin]$ head -n1 /etc/issue
Ubuntu 14.04.3 LTS \n \l
^_^[sam@autopsy:~/git/github/slack-plugin]$ uname -rms
Linux 3.13.0-65-generic x86_64
^_^[sam@autopsy:~/git/github/slack-plugin]$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
^_^[sam@autopsy:~/git/github/slack-plugin]$ mvn -version
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.7.0_79
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.13.0-65-generic" arch: "amd64" Family: "unix"
^_^[sam@autopsy:~/git/github/slack-plugin]$ 
```

If you would like to continue this discussion @Nooba about backporting changes then please continue discussion here.  We shouldn't hijack the discussion from the other issue.

**Comment by Nooba** [comment]
You're right, that was totally my bad.
My fork has been updated to fix that.
Please note that i didn't get around mimicking your PR merges from Oct 27th, but can do if it helps you.

Also, As said before, both the changelog and pom.xml needs to be updated.
Changelog needs to be formatted to mirror previous changelogs formatting
pom.xml needs to update the scm section, as I temporarily put my fork as source.

Tell me if you need anything else.
Thanks

**Comment by samrocketman** [comment]
I've got a changelog already prepared and formatted from your former changes.  I wrote the changelog before testing the build and then opened the issue with you.

**Comment by samrocketman** [comment]
Is your `master` up to date?  If so I'll test it another time.  I would also appreciate any effort you're willing to spend on #106 as I think that's a more valuable use of time.

**Comment by Nooba** [comment]
It is. I just doubled-checked. I will leave it to you then.
I currently have no idea on how to write a migration for this (or a jenkins plugin fwiw). I'll keep it in mind, since as you said it would be a shame te just sweep it under the rug, and that's not the point. But unfortunately, don't expect anything from me anytime soon.

Regards

**Comment by samrocketman** [comment]
I have created the [`slack-1.8-stable`](https://github.com/jenkinsci/slack-plugin/tree/slack-1.8-stable) branch based on your work.  Thanks for doing this.  I'll have to thoroughly run through testing as much as I can before performing a 1.8.1 release.

I made two changes:

* Updated the [`pom.xml`][pom] to reflect a proper 1.8.1-SNAPSHOT version for the maven release plugin.
* Updated the [`CHANGELOG.md`][changelog] to reflect categorized release notes.

[changelog]: https://github.com/jenkinsci/slack-plugin/blob/slack-1.8-stable/CHANGELOG.md
[pom]: https://github.com/jenkinsci/slack-plugin/blob/slack-1.8-stable/pom.xml

**Comment by samrocketman** [comment]
If you perform any updates please base them off of the `1.8-stable` branch.

**Comment by samrocketman** [comment]
I have validated this for the slack 1.8.1 release.
