### ISSUE TITLE
Test Connection => Failure

### ISSUE THREAD

**Issue by graeson** [jenkinsci/slack-plugin#149]
Having similar problem to issue #91... Installed slack using jenkins-cli.jar and configured the plugin exactly as described on the slack integrations page (correct domain, token, and channel). Unfortunately, firing a "Test Connection" always returns "Failure". 

I tried restarting Jenkins, re-installing the plugin, and regenerating a new Slack token, but was not able to get passed the above mentioned "Failure". BTW, I am able to successfully post messages to slack from the same server using curl and an "Incoming Webhooks" integration.

Finally, running jenkins 1.638 and slack-plugin 1.8.

**Comment by samrocketman** [comment]
I can't replicate your issue.  I validated slack-plugin 1.8 fully works with 1.638 by bootstrapping Jenkins using https://github.com/samrocketman/jenkins-bootstrap-slack

You'll have to be a little more detailed in how I can replicate the issue using a fresh instance.  If this is an issue with upgrading slack then let me know the former version(s) of Jenkins/slack-plugin so that I may test out the upgrade.

**Comment by toabi** [comment]
I just noticed the same. In the jenkins logs I found:

```Error posting to Slack
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target```

I guess slacks TLS-Config is too new/good/whatever for Java

**Comment by mkjasinski** [comment]
The same. I found:

`javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested`

**Comment by Cataclysm18** [comment]
I had the same issue, solved it by adding the Slack certificarte

**Comment by mkjasinski** [comment]
Just I did.

**Comment by toabi** [comment]
@Cataclysm18 Could you be more specific? Which commands did you run?

**Comment by Cataclysm18** [comment]
@toabi Updated my comment

**Comment by toabi** [comment]
I did what @Cataclysm18 said and now it's working for me too. Thanks a lot!

**Comment by mabushey** [comment]
I have the same issue with "Test Connection" resulting in "Failure". I went through the steps by @Cataclysm18 but that didn't make a difference. I did change step 5 to: `cp /etc/ssl/certs/java/cacerts /var/lib/.keystore/cacerts` as $JAVA_HOME/jre/lib/security/cacerts was just a symlink to that.

**Comment by atul-tewari** [comment]
I am using Jenkins 2.60.2 and Slack Notification Plugin 2.2.  Issue still persists after @Cataclysm18's  solution.  Anyone know of a workaround?

**Comment by Cataclysm18** [comment]
I've just installed docker Jenkins 2.60.2 and Slack notification plugin and it seems to work without all the SSL issues. 
So maybe there is something else that's blocking the connection from Jenkins to Slack. could you share the Slack notification configuration?

![image](https://user-images.githubusercontent.com/7781866/29045614-c6079656-7bcc-11e7-96b9-866b05a9c525.png)

**Comment by atul-tewari** [comment]
Ah - I had the Base URL pointing to the SSL link.  I removed it and it worked.  Thanks for the screenshot

**Comment by timja** [comment]
looks very old, file a new issue if needed
