### ISSUE TITLE
Option to notify only on the first failed build

### ISSUE THREAD

**Issue by natesilva** [jenkinsci/slack-plugin#15]
We have some jobs that run on a timed schedule. If they fail, we get notifications each time. So our #jenkins channel fills up with lots of fail messages.

It would be nice to have an option like “Notify First Failure”. That way we could get notified (once!) when the job fails, and once when the job is back to normal, using the “Notify Back To Normal” option.

**Comment by samrocketman** [comment]
This feature could be implemented by providing an option to not notify slack if there has been no changes regardless of success or fail.  i.e. no commits have been made since the last build.

**Comment by peergum** [comment]
That should be fairly easy. I'll try to work on that asap.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by muanis** [comment]
Looks like this was closed by #46 , should we close this one as well?

**Comment by samrocketman** [comment]
Thanks for catching that.  Yeah, this one should be closed.

**Comment by dkaplan-pivotal** [comment]
Is there documentation for this somewhere?  I actually *would* like to be notified on each failure and can't figure out how to do this.

**Comment by samrocketman** [comment]
In the latest plugin check first failure and repeat failures settings.
