### ISSUE TITLE
Release slack plugin 1.8.1

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#150]
This issue is to track progress of releasing slack plugin 1.8.1.

TODO:

- [x] Configure your credentials in `~/.m2/settings.xml`. (outlined in [making a
      new release][plugin-release] doc)
- [x] Create a new issue to track the release and give it the label `maintainer communication`.
- [x] Create a release branch. `git checkout origin/slack-1.8-stable -b prepare_release`
- [x] Update the release notes in `CHANGELOG.md`.
- [x] Open a pull request from `prepare_release` branch to `slack-1.8-stable` branch.  Merge it.
- [x] Fetch the latest `slack-1.8-stable`.
- [x] Execute the release plugin.

    ```
    mvn org.apache.maven.plugins:maven-release-plugin:2.5:prepare org.apache.maven.plugins:maven-release-plugin:2.5:perform
    ```

- [x] Wait for the plugin to be released into the Jenkins Update Center.
- [x] Successfully perform an upgrade from the last stable plugin release to the current release.

I pin which version of the release plugin to use because of the working around common issues section of the [release document][plugin-release].

[plugin-release]: https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins

**Comment by samrocketman** [comment]
Encountering issues with publishing the plugin.

**Comment by samrocketman** [comment]
The error was 401 unauthorized.  It's because I mistakenly set `~/.m2/settings.xml` credentials for `repo.jenkins-ci.org` instead of `maven.jenkins-ci.org`.

**Comment by samrocketman** [comment]
The plugin has been released.  It will be roughly 8 hours before the release propagates to the Jenkins Update Center.

**Comment by samrocketman** [comment]
http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/slack/1.8.1/

**Comment by samrocketman** [comment]
I'll close this issue when it is in the update center and a successful plugin upgrade is performed.  The testing platform is https://github.com/samrocketman/jenkins-bootstrap-slack

**Comment by samrocketman** [comment]
cc @Nooba mentioning you since you played a major part in this release.  In case you want to track its progress.

**Comment by Nooba** [comment]
It wasn't but a mere suggestion and a few git shenanigans.
Thanks for the heads up though.

**Comment by samrocketman** [comment]
Upgrade successfully tested.  Seems the bug fixes got released without any issues.  It took me a while to test because I've been sick the past week.  In any case, glad nothing went wrong during that time.  I'll release the milestone as well.
