### ISSUE TITLE
Enhanced message attachment

### ISSUE THREAD

**Issue by eyalzf** [jenkinsci/slack-plugin#152]
One of the most popular Jenkins plugins is the enhanced mailer due to it's abilities to customize the messages in pretty much any form you'd like.

This is probably the thing I miss the most about this plugin. I would love to have a similar template engine in this plugin allowing adding attachments to the message so I could post them in slack as well

**Comment by samrocketman** [comment]
Thanks for the suggestion.  I don't actively develop this plugin.  I currently maintain pull requests and releases.  Slack plugin [release 1.8.1](https://github.com/jenkinsci/slack-plugin/blob/master/CHANGELOG.md#181-release-notes) includes enhanced formatting when posting to slack.  However, allowing arbitrary attachments to slack messages is not currently supported.  I welcome this contribution from anyone in the community!

**Comment by timja** [comment]
Closing this due to lack of interest in the community.
You have full control in pipeline, or custom message support in free style
