### ISSUE TITLE
Feature Request: Custom message per notification

### ISSUE THREAD

**Issue by cchar** [jenkinsci/slack-plugin#163]
We have notification for success and various types of failure. People are complaining about it being too noisy being mentioned even on successes. They want to be mentioned only if the build failed. However, we don't want to turn notifications off on success because if server goes down, we want to be able to tell quickly.

Is it possible to have custom messages  per notification?

**Comment by MilesRoberts** [comment]
depending on your exact use case you might be able to hack your way around this using the envinject plugin, but +1 for having this built in to the slack plugin.

**Comment by csogilvie** [comment]
I might have just written something for this which I referenced in Pull Request https://github.com/jenkinsci/slack-plugin/pull/169 as I needed to be able to do the same thing...

**Comment by djschny** [comment]
:+1: 

We are switching from HipChat to Slack and not being able to supply a per build message template to use is really hurting us. For example allowing you to do the following for each notification on a project:

`'$JOB_NAME #$BUILD_NUMBER $STATUS after $DURATION (<a href="$URL">Open</a>)'`

**Comment by samrocketman** [comment]
Possibly fixed by #169.
