### ISSUE TITLE
Ability to change host parameter

### ISSUE THREAD

**Issue by andrzejwp** [jenkinsci/slack-plugin#174]
There are several slack alternatives that include a slack-compatible API. I'm using Rocket.Chat and I would love to use the slack-plugin to handle the notifications. Could someone add a configuration option to change host="slack.com" to my own custom URL?

**Comment by chkal** [comment]
I would also love to see this.

But I'm not sure if the current implementation of the plugin really would work with Rocket.Chat just by changing the hostname part.

A Rocket.Chat WebHook looks like this:

    https://chat.example.com/hooks/<token>

And this plugin seems to post to something like this:

    https://chat.example.com/services/hooks/jenkins-ci?token=<token>

See: https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L41

Any idea?

**Comment by andrzejwp** [comment]
I've already tested it and it works.
I manually changed the url in src/main/java/jenkins/plugins/slack/StandardSlackService.java

```
String url = "https://rocket.chat.url/hooks/" + token;
```

recompiled, added the custom-built hpi file and everything works as expected.

**Comment by chkal** [comment]
Ah cool, sounds great. So basically providing some kind of "Base URL" would work fine. As an alternative for providing the slack subdomain.

**Comment by chkal** [comment]
It would be great to get feedback from the plugin maintainers about the idea of adding a config property "Base URL" which, if set to a non empty value, is used for the URL instead of generating a slack.com specific one with the "Team Domain" config property.

If you like that idea, I could prepare a pull request for that.

**Comment by samrocketman** [comment]
I don't think it would be a big deal to make it configurable.  I'm not against it.  Contributions welcome.

**Comment by andrzejwp** [comment]
@chkal you can check my PR or the fork itself at https://github.com/cdwv/slack-plugin. I can also send you the compiled plugin - drop me an email at andrzej (at) codewave dot eu

**Comment by chkal** [comment]
@andrzejwp Thanks a lot. I'm not so familiar with Jenkins plugin development, but I just reviewed the PR and it looks good to me. I'll try to find some time next week to give the plugin try, but I cannot promise anything. Anyway, thanks a lot for PR. :+1:

**Comment by MitchTalmadge** [comment]
👍

**Comment by timja** [comment]
done?
