### ISSUE TITLE
Cannot see failed build message

### ISSUE THREAD

**Issue by nagarakesh4** [jenkinsci/slack-plugin#176]
Plugin: Version 1.8.1 Jenkins 1.584

Plugin is not throwing failed build messages after first build failed. There is no Notify Repeated Failure option in configure job.

**Comment by segabor** [comment]
I can report the same. No build failure notifications so far.
Plugin: 1.8.1, Jenkins: 1.648

**Comment by vrsomisetty** [comment]
I have the same issue with both Success and Failure notifications. 
I can confirm the configuration is good as I do get Build start notification. Any resolution or suggestions please. 
Slack plug-in version 1.8.1

**Comment by endowzoner** [comment]
Same here. I could get Notify Build Start, Notify Back To Normal, Notify Success, test summary and commit list, if the build succeeds. If the build does not succeed, only the start notification is being sent.

Jenkins 1.602, Plugin 1.8.1

**Comment by samrocketman** [comment]
`Notify Repeated Failure` is in the advanced section of the Job Configuration page.
