### ISSUE TITLE
post a meesage as @Group

### ISSUE THREAD

**Issue by odedgol** [jenkinsci/slack-plugin#180]
Hi Guys . ! super nice plugin

I am PD at eBay and we would like to integrate it in our monitor ci

but one feature is super missing . 
in Slack when u post a message to @group all group member get notification (with red sign +1)
and no one need to configure the channel notification

can add another field (TO and be able to pick to whom the alert should be send)
like @myname or @groupname

this is super needed . 

Thanks!

**Comment by bgiorgini** [comment]
I also vote for this feature. Even better if the `To` can be configured to send the message to the user who triggered the job (or failed the build).

**Comment by timja** [comment]
Channel takes multiple values separated by a comma separated
