### ISSUE TITLE
Report claims

### ISSUE THREAD

**Issue by zkendall** [jenkinsci/slack-plugin#182]
I'm posting this here, because the the Claim Plugin repo doesn't have 'Issues' enabled.

> Under "Configure System", the "Claim" section. The '?' button gives the following tip:
> Groovy script to run when claims are changed. The variable action is bound to the hudson.plugins.claim.ClaimBuildAction instance for the claim.
> Here is an example that sends messages to the configured Slack channel.
> 
> // send claim changes to Slack
> def build = action.owner
> def notifier = build.project.publishers.find { k, v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }?.value
> if (notifier) {
>   def slackServiceClass = notifier.class.classLoader.loadClass('jenkins.plugins.slack.StandardSlackService')
>   def slackService = slackServiceClass.newInstance(notifier.teamDomain, notifier.authToken, notifier.room)
>   if (action.claimed) {
>     def sticky = action.isSticky() ? ', sticky' : ''
>     def assignedBy = (action.assignedBy == action.claimedBy) ? '' : ", assigned by ${action.assignedBy}"
>     slackService.publish("${action.claimedBy} claimed: ${build}${sticky}${assignedBy} (<${build.absoluteUrl}|Open>)\n${action.reason}", 'warning')
>   } else {
>     slackService.publish("claim dropped for: ${build} (<${build.absoluteUrl}|Open>)", 'danger')
>   }

This worked for a while, then it stopped working recently. I found an error in the git log about the closure on line 3. I was able to fix that by changing it to `build.project.publishers.get(0).find { v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }`. Now there is no error, but the claims are still not being reported to Slack (Other things, like build failures, are being reported successfully). 

Any ideas?

Jenkins ver. 1.632

**Comment by kmadel** [comment]
What versions of the Claim Plugin and what version of the Slack plugin?

**Comment by zkendall** [comment]
- Slack: 1.8.1.
- Claims: 2.8

**Comment by samrocketman** [comment]
Shot in the dark...  Rather than:

```groovy
build.project.publishers.get(0).find { v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }
```
You're only running the `.find` on the first item (`get(0)`).  I would _think_ that you want to search for it across the entire publishers list.  e.g.

```groovy
build.project.publishers.find { v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }
```

**Comment by samrocketman** [comment]
The constructor looks relevant for 1.8.1.  https://github.com/jenkinsci/slack-plugin/blob/slack-1.8.1/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L27-L32

**Comment by samrocketman** [comment]
You'll likely have to update that script.  I just bootstrapped Jenkins with slack plugin 1.8.1.  You can bootstrap it yourself with https://jenkins-slack-plugin.slack.com/messages/slack-plugin-testing/

I just executed the following on the script console.

```groovy
def project = Jenkins.instance.getItem('Test')
def notifier = project.publishers.find { k, v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }?.value
if(notifier) {
  def slackServiceClass = notifier.class.classLoader.loadClass('jenkins.plugins.slack.StandardSlackService')
  def slackService = slackServiceClass.newInstance(notifier.teamDomain, notifier.authToken, notifier.room)
  slackService.publish('This is a claims test...', 'danger')
}
```

You can see the result of that notification at https://jenkins-slack-plugin.slack.com/messages/slack-plugin-testing/ (note you can join our test slack instance by [clicking here](https://jenkins-slack-testing-signup.herokuapp.com/)).  Here's a screenshot of the posted result if you don't feel like joining our slack.

![screenshot](http://s21.postimg.org/7uzgcyx2t/screen.png)

**Comment by zkendall** [comment]
Thanks for the help.

But when I change it too

```groovy
def build = action.owner
def notifier = project.publishers.find { k, v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }?.value
```

Then I get
```
Mar 18, 2016 1:51:16 AM WARNING hudson.plugins.claim.AbstractClaimBuildAction evalGroovyScript
Error evaluating Groovy script
groovy.lang.MissingPropertyException: No such property: project for class: Script1
...
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:231)
	at Script1.run(Script1.groovy:3)
```

**Comment by zkendall** [comment]
Thanks for the help.

But when I change it too

```groovy
def project = action.owner.project
def notifier = project.publishers.find { k, v -> v.class.name == 'jenkins.plugins.slack.SlackNotifier' }?.value
```

Then I get
```
Error evaluating Groovy script
groovy.lang.MissingMethodException: No signature of method: Script1$_run_closure1.call() is applicable for argument types: (hudson.plugins.claim.ClaimPublisher) values: [hudson.plugins.claim.ClaimPublisher@7c479ee0]
...
at Script1.run(Script1.groovy:2)
```

**Comment by timja** [comment]
reopen if still needed, very old..

**Comment by symus** [comment]
It works well with freestyle job, but not working with maven project
