### ISSUE TITLE
Empty space before Slack messages

### ISSUE THREAD

**Issue by dashersw** [jenkinsci/slack-plugin#183]
I'm having empty spaces before most of the messages. I don't have the same problem with other Slack plugins. Is anyone else having the same issues?

![Screenshot](https://cloud.githubusercontent.com/assets/698308/13644471/4011a56a-e626-11e5-9175-836c80c8c803.png)

**Comment by kmadel** [comment]
I don't see that with 1.8.1 nor the 2.0-snapshot

**Comment by dashersw** [comment]
I've upgraded to 2.0 and it's still present. It looks like it prints ---------------- in that space.

This is the output when I copy / paste that part:

```

Jenkins BOT [6:58 PM] 
----------------
console-test - #56 Started by user Armagan Amcalar (Open)


[6:59] 
----------------
console-test - #56 Back to normal after 5 days 6 hr (Open)
No Tests found.


[6:59] 
----------------
No Changes.
```

**Comment by samrocketman** [comment]
It displays JUnit style tests which is XML collected by Jenkins.

**Comment by timja** [comment]
I've never seen this... Feel free to comment or reopen a new issue if its still a problem
