### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by kmadel** [jenkinsci/slack-plugin#184]
This issue is to track progress of releasing slack plugin 2.0.

TODO:

- [x] Create a new issue to track the release and give it the label `maintainer communication`.
- [x] Create a release branch. `git checkout origin/master -b prepare_release`
- [x] Update the release notes in `CHANGELOG.md`.
- [x] Open a pull request from `prepare_release` branch to `master` branch.  Merge it.
- [x] Fetch updated `master`.
- [x] Execute the release plugin.

    ```
    mvn org.apache.maven.plugins:maven-release-plugin:2.5:prepare org.apache.maven.plugins:maven-release-plugin:2.5:perform
    ```

- [x] Wait for the plugin to be released into the Jenkins Update Center.
- [x] Successfully perform an upgrade from the last stable plugin release to the current release.

I pin which version of the release plugin to use because of the working around common issues section of the [release document][plugin-release].

[plugin-release]: https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins

**Comment by samrocketman** [comment]
@kmadel you can bootstrap Jenkins with slack fully configured.  I have created a repo for doing this kind of testing.

https://github.com/samrocketman/jenkins-bootstrap-slack

It's got dummy jobs for testing as much functionality of the plugin as I could muster.

**Comment by kmadel** [comment]
@samrocketman Do you have a Jenkins Pipeline job ;)

Thanks, will check it out.

**Comment by kmadel** [comment]
Everything looks good for 2.0 based on preliminary tests. Happy updating!
