### ISSUE TITLE
Version 2.0 seems to break GitLab plugin webhook triggers

### ISSUE THREAD

**Issue by demaniak** [jenkinsci/slack-plugin#189]
I am not sure if this is a [Gitlab Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitLab+Plugin) issue, or a issue for this plugin.
Regardless, when I have Slack Plugin 2.0 installed with GitLab plugin 1.1.31, the webhook notifier from gitlab does not work. 
At all. 
NOTHING in jenkins logs that I can see even.

If I remove Slack plugin 2.0, gitlab plugin happily receives webhook notifications from our gitlab instance again.

With previous slack plugin version, everything was also fine.

**Comment by samrocketman** [comment]
Closing this issue in favor of #191.
