### ISSUE TITLE
Issue using credentials to store auth token

### ISSUE THREAD

**Issue by fgs-dbudwin** [jenkinsci/slack-plugin#195]
If we hardcode the `token` everything works as expected for sending messages about the build to Slack.  However, [using the `credentialsBinding` object for the Job DSL plugin](https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.wrapper.WrapperContext.credentialsBinding), _only_ the test results message will post to our channel in Slack.

From the logs we see that we're trying to post the starting messages to Slack using the following URL.

`https://[team name].slack.com/services/hooks/jenkins-ci?token=$SLACKTOKEN`

The issue being that our credentials stored in `$SLACKTOKEN` isn't being resolved until the environment has been setup for the build.  It appears that the Slack Notifier Plugin is trying to post to Slack before the build environment is setup, therefore it doesn't know how to resolve `$SLACKTOKEN` or any other credentials we may store.

Some other plugins do support credentials properly for setting up jobs using the [Job DSL plugin like the git plugin](https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.ScmContext.git).  See the `credentials` object in the Job DSL API for git: https://jenkinsci.github.io/job-dsl-plugin/#path/javaposse.jobdsl.dsl.helpers.ScmContext.git-remote-credentials

In the above example, I would give it the ID of the secret stored in the Credentials Binding plugin.

**Comment by samrocketman** [comment]
I'm not sure how you're using the credentialsBinding with your script or how you expect slack to behave with it.  If you need your Job DSL script to notify slack you could use something like this...

```groovy
import jenkins.model.Jenkins
def j = Jenkins.instance
//get the global slack configuration
def s = j.getExtensionList('jenkins.plugins.slack.SlackNotifier$DescriptorImpl')[0]
//use a class loader because Job DSL can only import classes from plugins which are explicit dependencies
def slackServiceClass = s.class.classLoader.loadClass('jenkins.plugins.slack.StandardSlackService')
//configure a new instance to notify slack using global slack settings
def slackService = slackServiceClass.newInstance(s.teamDomain, s.token, s.room)
//notify the channel
slackService.publish('Life is like a box of chocolates.', 'warning')
```

**Comment by fgsahoward** [comment]
@fgs-dbudwin and I were trying to accomplish basically this:
```groovy
job('Build job') {
  wrappers {
    credentialsBinding {
      string('SLACKTOKEN', 'some-guid-id-here')
    }
  }
  publishers {
    slackNotifications {
      ...
      integrationToken('$SLACKTOKEN')
      ...
    }
  }
}
```

The intended outcome here is that only the `Guid` id is in source control, and then `$SLACKTOKEN` is replaced with the actual secret token. The above approach works fine for posting the results of the build (i.e. success/failure), but as @fgs-dbudwin mentioned, the messages preceding the build (e.g. "Starting build after ....") do not post because `$SLACKTOKEN` cannot be resolved at that time.

The root of the problem here is that we need slack to know the integration tokens for each of our integrations, but we don't want to hard code those tokens into the jobs themselves.

**Comment by samrocketman** [comment]
Might I recommend getting your credentials on-the-fly during job creation.  e.g.

```groovy
//Job DSL script
import jenkins.model.Jenkins

String slackCredentialsId = 'slack-token-creds-id'
String found_slack_token = ''
def system_creds = Jenkins.instance.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0]
system_creds.getStore().getDomains().each { domain ->
  system_creds.getCredentials(domain).each { credential ->
    if(slackCredentialsId.equals(credential.id)) {
      found_slack_token = credential.getSecret()
    }
  }
}

println "Slack token credentials: ${found_slack_token}"
```
In the above example, you could simply make use of `found_slack_token` in your Job DSL script directly.

When using credentials embedded in Cloudbees Folders you would need to use a script like the following....
```groovy
import jenkins.model.Jenkins

String folder_name = 'test-folder'
String slackCredentialsId = 'slack-token-creds-id'
String found_slack_token = ''
def folder_creds = Jenkins.instance.getJob(folder_name).properties.find { v -> v.class.simpleName == 'FolderCredentialsProperty' }

folder_creds.getStore().getDomains().each { domain ->
  folder_creds.getCredentials(domain).each { credential ->
    if(slackCredentialsId.equals(credential.id)) {
      found_slack_token = credential.getSecret()
    }
  }
}

println "Slack token credentials: ${found_slack_token}"
```

**Comment by fgs-dbudwin** [comment]
Thank you for your suggestion, but the concern with this method is that if you view the `config.xml` file for the job, the secret will be in plain text which defeats the purpose in our case.  The Credentials Binding plugin for Jenkins that a lot of other plugins support is extremely useful to help hide secrets.  When viewing the `config.xml` file for the job, you'll see the name of a variable instead of the actual secret itself like in the example code posted by @fgsahoward the other day.

**Comment by samrocketman** [comment]
I see your point.  Perhaps a better solution would be to make use of `hudson.util.Secret` to encrypt the token setting so your concern is mitigated.  It should be a secure property anyways.

I'm going to create an enhancement request around this.

**Comment by fgs-dbudwin** [comment]
> Besides that, from what I recall if you configure a Jenkins configuration in slack then any user in slack can view this token in slack settings. So I'm not sure this is a real concern if the user is already a member of your Slack.

I think this is only true for the owner of the integration (it's possible to see that it exists though), at least this is true for our team.

**Comment by fgs-dbudwin** [comment]
I want to help develop this feature (or at least take a stab at it); however, I can't get any of the 2.X.X branches or master to build.  I can get 1.8.X branches to build.

The issue seems to be that `SlackSendStep.java` can't find `import jenkins.plugins.slack.Messages;` for some reason.  There doesn't seem to be a `Messages.java` file anywhere in the repo, but I could just be missing something as this isn't the type of development I'm familiar with.

The following screenshot is a clean `master` branch version of `SlackSendStep.java`.

![image](https://cloud.githubusercontent.com/assets/14611316/13988475/8164a1a4-f0e2-11e5-990d-11bc6e04932a.png)

This may be a new issue if it's actually a problem.  Any thoughts?

**Comment by samrocketman** [comment]
Interesting, I've not come across that failure.  Yet, if I grep through the entire repository history there's no mention of `class Messages` ever existing.

```bash
git show-ref | cut -d' ' -f1 | xargs git grep 'class Messages'
```

**Comment by fgs-dbudwin** [comment]
It's clearly "used" in the repo though, look at the `imports` in here: https://github.com/jenkinsci/slack-plugin/blob/5149c5ad3d4b6c311156bef62bf5bf6f212e3922/src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java

**Comment by samrocketman** [comment]
After some sleuthing with `git blame` it appears it was introduced in commit a9661980e52d5211497b5999c9ca65e8f4293e49.  Perhaps @kmadel can explain more.

**Comment by fgs-dbudwin** [comment]
Yup, I just came to the same conclussion in this PR #167

**Comment by samrocketman** [comment]
I performed a google search for...

```
"package jenkins.plugins.slack" AND "class Messages"
```
And found no results of a Java class.  If I do that for other classes I find results.  So I don't know where that class exists outside of the Slack plugin; because it doesn't within.

**Comment by fgs-dbudwin** [comment]
That's what I think.  I'm curious though how Jenkins is building though?  Should the build status be failing if it can't find a class?  Weird.

**Comment by fgs-dbudwin** [comment]
@fgsahoward pointed out that there is a `Messages.properties` file in the repo that has Keys with the same names as the functions being called statically on the `Messages` class.  I'm not sure how this is supposed to work, it's not how I've ever used a `*.properties` file before.

**Comment by kmadel** [comment]
@fgs-dbudwin As I mentioned in #201 - you need to manually add "target/generated-sources/localizer" directory to your source root to get this to work in an IDE.

**Comment by timja** [comment]
I believe fixed with secret support?
reopen if it doesn't meet your need thanks
