### ISSUE TITLE
Changing bot name and icon in post-build action

### ISSUE THREAD

**Issue by Signez** [jenkinsci/slack-plugin#2]
It would be great to enable admins to set the bot name (and its icon) in post-build action preferences.

These parameters could be send in each message payload using `username` and `icon_url` fields.

**Comment by samrocketman** [comment]
Can't the username and icon already be specified when the slack integration is configured?  What does this request add?

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by samrocketman** [comment]
Closing since this can already be done in slack outside of this plugin and there hasn't been a response to any questions.
