### ISSUE TITLE
Job DSL plugin support wasn't updated before release

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#200]
This issue requests that the slack plugin starts supporting the Job DSL plugin via extension points.  The Job DSL plugin [lists other plugins](https://jenkinsci.github.io/job-dsl-plugin/) which can be used as a reference.

**Comment by conslo** [comment]
it appears to already: https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.slackNotifications

It even links back to this repo. Though the configuration it produces is old, and pretty reliably causes the issue described in #188

**Comment by samrocketman** [comment]
Doing this work should fix bug #188.

**Comment by samrocketman** [comment]
I'm going to re-categorize this as a bug.

**Comment by meve** [comment]
Hi,

I created a fix for this in the job-dsl-plugin:
https://github.com/meve/job-dsl-plugin/commit/dd880f30ef5a6138350be2b06362be481036ec04

If I understand this correctly, the parameters for the slack plugin have moved from the properties section to the publishers section. I was able to get it to work like this, but would like you guys to say something about it as well.

**Comment by samrocketman** [comment]
You're correct that the parameters have essentially moved to the publishers section.  I imagine moving the functionality into the slack plugin is another solution.

**Comment by abridgett** [comment]
@meve maybe a good idea to send your patch to job-dsl-plugin (I can't see it included nor a PR), would help a fair few folk out I suspect :-)

**Comment by jspiewak** [comment]
The new [Automatically Generated DSL](https://github.com/jenkinsci/job-dsl-plugin/wiki/Automatically-Generated-DSL) feature addresses this [issue](https://issues.jenkins-ci.org/browse/JENKINS-34124)

It seems to be available as of 1.46, but is documented in the (forthcoming) 1.47 [Migration](https://github.com/jenkinsci/job-dsl-plugin/blob/master/docs/Migration.md).

**Comment by timja** [comment]
1.46 of job dsl supports this
