### ISSUE TITLE
Secure tokens with hudson.util.Secret

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#201]
As it stands, `config.xml` contains the slack API token in plain text.  The slack plugin should be enhanced so that the `<token>` is using `hudson.util.Secret`.  This way the config.xml will instead contain the AES128 encrypted value of the token rather than the plain-text version.

This enhancement comes from discussion in #195.

**Comment by samrocketman** [comment]
e.g.
```groovy
import hudson.util.Secret
Secret token = Secret.fromString("<encrypted or plain token>")
```

**Comment by fgs-dbudwin** [comment]
I wanted to let you know that I am working on this and I have it working locally.  I won't be able to start a PR for this change until I can get the `Messages` working like we discussed in Issue #195

**Comment by kmadel** [comment]
@fgs-dbudwin This is specifically a Jenkins Plugin construct based on the use of [localizer](https://java.net/projects/localizer/)

See https://wiki.jenkins-ci.org/display/JENKINS/Internationalization for more details and how to setup your IDE to support this construct.

**Comment by fgs-dbudwin** [comment]
Gotcha, thanks for the explanation.  It would be nice if that was explained (or the link was added) in the "Developer instructions" section of the README.

**Comment by timja** [comment]
This was done awhile ago
