### ISSUE TITLE
Upgrading from 1.8.1 to 2.0.1 breaks per-job configs

### ISSUE THREAD

**Issue by gabrielpreston** [jenkinsci/slack-plugin#205]
Slack settings for specific jobs were overwritten when upgrading from 1.8.1 to 2.0.1. Some jobs had different rooms configured in them that differed from the default config in Jenkins->Manage Jenkins->Configure System. This stopped notifications from being sent to the expected rooms and started flooding one room with all of the different Slack notifications from all of our different jobs.

**Comment by samrocketman** [comment]
I had a feeling that would happen.  This is due to the way the plugin stores global configuration in the job config (which it shouldn't and just reference the global configuration instead).

This is a direct result of merging #79 but not fixing #130 before releasing 2.x.

**Comment by oncletom** [comment]
Yeah, and actually I thought the plugin was broken because I could not find the per-job settings.

We have one Jenkins for several teams, and we were planning to dispatch notifications to different channels depending on the Job View.
