### ISSUE TITLE
Post to different channels depending on status

### ISSUE THREAD

**Issue by fredr** [jenkinsci/slack-plugin#207]
I would like to post to different channels depending on the job status.

i.e we have a #ci channel that lists everything that happens, but on failure I would like to post to our #dev channel so that the right people get notified about it.

The best way imo, would be if it was possible to add multiple post-build slack-actions, because then I could also configure different messages depending on the status.

**Comment by samrocketman** [comment]
I believe this is do-able if we could get the plugin working with the [Flexible Publish Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Flexible+Publish+Plugin).  See issue #41.

**Comment by fredr** [comment]
Excellent! Did not know about Flexible Publish! I'll close this in favour of #41
