### ISSUE TITLE
UI issues with Chrome 49.0.2623.110 m Jenkins 1.644 and plugin 2.0.1

### ISSUE THREAD

**Issue by ml019** [jenkinsci/slack-plugin#209]
Have installed 2.0.1 with Jenkins 1.644. 

In the Manage Jenkins -> Configure System -> Global Slack Notifier Settings, the help links and the "Test Configuration" button at the bottom of the screen are not hyperlinked. (The settings appear as the last block on the page - not sure if that's relevant - see below).

Similarly when I select "Slack Notifications"  in the Post-Build Actions, the "Advanced" button is not hyperlinked - again the section is the last before the save/apply buttons. However if I drag it up so that it is not the last item, the Advanced button becomes active again.

Repeating in FF 45.0.1, UI works as expected without a problem. Not sure if its a more general Jenkins bug or a plugin specific thing? 

BTW it seems the description of the plugin setup on its main Jenkins page is no longer consistent with the plugin, as all the project settings are in the Post-build step rather than there being separate project settings and post-build sections?

Thanks
Michael

**Comment by ml019** [comment]
Thinking this might be a Chrome thing where a portion of one monitor doesn't respond to mouse but if I move the window it starts working again. So scratch the issue.

comment about plugin setup documentation still relevant I think though?

**Comment by samrocketman** [comment]
The wiki is available for anyone to edit.  Documentation is sorely lacking at the moment.

**Comment by kmadel** [comment]
I would rather just use the GitHub README for documentation (and additional pages if necessary). I will ask that the README is updated as part of an PR that requires documentation.
