### ISSUE TITLE
Colours on Slack messages can't be discerned by colour-blind users

### ISSUE THREAD

**Issue by ceralena** [jenkinsci/slack-plugin#210]
These look almost identical to me:

![screen shot 2016-04-08 at 10 44 35 am](https://cloud.githubusercontent.com/assets/615299/14371118/ac40765e-fd77-11e5-9863-9e4e1bc24620.png)

I'm not sure exactly what a better solution would be, though. Maybe bolder for the failed job? A more obvious cue like 'FAIL' or 'SUCCESS'?

**Comment by samrocketman** [comment]
Good call, perhaps an option for customizing the color will help resolve this.

**Comment by nicorikken** [comment]
consider aligning with Jenkins color scheme (blue and red works just fine for most color-blind people).

**Comment by kmadel** [comment]
@ceralena What about prefixes:

- SUCCESS
- FAILURE

**Comment by ceralena** [comment]
The prefixes would help, but I think @samrocketman's suggestion of red and blue would have the most impact.

**Comment by samrocketman** [comment]
Correction, blue/red suggested by @nicorikken.  Which I agree is a great suggestion.  Perhaps configurable with a default of blue/red.

**Comment by ssbarnea** [comment]
I would vote for including hints in the text but keeping the default colours the same (reg/green). We do get notifications from other systems as well and all of them are using the same semaphore colours.

Making the Failure bold should be enough.

**Comment by nicorikken** [comment]
Apparently the predefined message colors are based on the predefined colors in Slack: https://api.slack.com/docs/message-attachments#color
As GitHub integration is also using its own coloring scheme for Slack messages, it seems fair to me to use the Jenkins color scheme. Unless Slack gets its act together on this issue, keeping a high level of accessibility for Jenkins seems a worthy goal to me. So blue/red and maybe grey. Right?
Then I think a basic case handling in https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java would do.

**Comment by timja** [comment]
Closing this issue as it is stale,
Feel free to send a PR adding the colours to the global configuration as configurable if this is still wanted.
Otherwise you have full control in pipeline
