### ISSUE TITLE
Feature request: Ability to specify different custom messages for build success and build failure

### ISSUE THREAD

**Issue by r0bbie** [jenkinsci/slack-plugin#212]
This would be a really helpful feature.

Example use case:
We want to have a custom message to output a link to download the produced build on S3, only if the build was successful.

**Comment by samrocketman** [comment]
I believe when #41 is resolved you should have this flexibility.

**Comment by rekahsoft** [comment]
I'm running version 2.01 of the slack-plugin for jenkins and this seems to not work. I am using the flexible-publishing plugin to deploy particular branches to the appropriate place. I'd like to display a message to my ci channel in slack saying "deployed $GIT_COMMIT to http://server.org" for one of the branches (which I check with the flexible-publishing plugin) and "deployed $GIT_COMMIT to http://server-staging.org" for the other. However the slack plugin options for both flexible-publish conditional action are always the same as the first conditional action that uses the slack-plugin.

**Comment by rekahsoft** [comment]
If you can point to where abouts I would need to make modifications I'd be happy to help out to rectify this issue :)

**Comment by samrocketman** [comment]
If I knew I would patch it right away.  It takes someone to debug and develop the solution.  I appreciate your enthusiasm.

**Comment by csogilvie** [comment]
I believe this could be fixed by #169 ?

**Comment by samrocketman** [comment]
@csogilvie Does #169 also address #41?

**Comment by csogilvie** [comment]
@samrocketman No, I suspect it probably doesn't.

**Comment by samrocketman** [comment]
Though I think your change does resolve this issue.

**Comment by agentgt** [comment]
I may fork this project and try to see if I can do what Email-Ext does with Jelly scripts. Sadly this new Jelly script support I think is Jenkins 2.9 (I think).
