### ISSUE TITLE
Parse variables about current build from JSON

### ISSUE THREAD

**Issue by dlednik** [jenkinsci/slack-plugin#214]
Hey!

I wan't to add more data to my slack message. Something like:

```
Tests finished in $duration seconds.
Test results: $failedCount/$totalCount
```

It would be great if this plugin would parse this values from job json page automaticaly:

```
http://server:port/job/jobName/83/testReport/api/json
```

which returns JSON like (just the beginig):

```
{
  "testActions" : [

  ],
  "duration" : 2768.8718,
  "empty" : false,
  "failCount" : 13,
  "passCount" : 267,
  "skipCount" : 0,
  "suites" : [
```

so this is where $passCount and $failCount would be retrieved from. But also calculate $totalCount internally as SUM of failCount, passCount and skipCount

I would try and write the code myself but I need some pointers in which file and which method I need to hook into.

**Comment by timja** [comment]
Closing as not sure how this would work, and this hasn't got any attention in 3 years
