### ISSUE TITLE
Feature request: multiple Slack channels

### ISSUE THREAD

**Issue by maiamcc** [jenkinsci/slack-plugin#215]
Is there currently a way to have a project send notifications to more than one Slack channel? If not, consider this a feature request!

**Comment by wimdeblauwe** [comment]
The docs state that you can use comma separated values:

> Enter the channel names to which notifications should be sent. Note that this can include names of channels OR channel id numbers, e.g. "#builds", and that **multiple values may appear comma separated**. While names are more readable, channel ids will not change over time and are therefore more resilient.

(emphasis mine)

**Comment by zekedroid** [comment]
That's awesome however how would one set up two separate post-build actions for the Slack plugin? Consider having one action which pushes the much more important build failures to a general channel, and ALL build statuses to a jenkins-dump channel. Is there a way to do that?

**Comment by samrocketman** [comment]
@zekedroid see #41

**Comment by samrocketman** [comment]
@maiamcc As @wimdeblauwe mentions posting to multiple channels is documented.  It actually accepts multiple characters as channel separators such as: comma, semicolon, space.

See https://github.com/jenkinsci/slack-plugin/blob/355842956c47806c516200a90a65cfead5879c9a/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L31

**Comment by filipre** [comment]
I am having troubles following this. This is what our settings look like

<img width="945" alt="screen shot 2018-03-15 at 22 58 20" src="https://user-images.githubusercontent.com/8502198/37467795-8655bd5a-28a4-11e8-8a0c-5db3010376c5.png">

If I try to add another channel using a `,` it tells me that this channel does not exist. Does this only work with `slackSend` ?

**Comment by darthsteven** [comment]
@filipre I think you're after the 'Project Channel' setting on the Jenkins plugin configuration form:

![test_hipchat-slack_job_config__jenkins_](https://user-images.githubusercontent.com/95782/37784870-b1908576-2df0-11e8-91de-3e0a5af47498.png)

This works nicely for me, and it doesn't seem to matter what the Slack side is set to :)

**Comment by jonathanappel** [comment]
@darthsteven that setting is global to jenkins correct? I can't have different pipelines posting to different channels?

**Comment by samrocketman** [comment]
@jonathanappel it is a _global default_ but can be overridden in either freestyle jobs or pipeline jobs.

For pipeline jobs, refer to the [`slackSend` step code](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java).

Here's an [example pipeline posting a `slackSend` status](https://github.com/samrocketman/jenkins-bootstrap-slack/blob/be2d2baaa2210aba6387320ea495c3bb9e28eee3/configs/job_JervisPipeline_config.xml#L38) for a build.  Note: this code is really old and I don't write pipeline code like that anymore.  I never bothered to update this project with my latest code style (I have no near term plans to update it).  But it gives you an idea on usage.
