### ISSUE TITLE
slack-plugin needs additional maintainer(s)

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/slack-plugin#223]
Based on the fact that this project got only one commit in more than two months even if it does 15 open PRs, I would assume that it lacks active maintenance.

Please give permission to merge PRs to few more people in order to revive the project.

If there are no others with more experience willing to do this, I could give a hand with the maintenance: reviewing PRs, testing, issue tracker and merging.

**Comment by samrocketman** [comment]
@ssbarnea I've said numerous times that I don't develop it and even recently I haven't been willing to merge PRs.  You're welcome to join and maintain.  @kmadel has to agree as well.

+2 from me.

**Comment by otuji** [comment]
I hope new version of slack-plugin including custom message feature.
please add @ssbarnea to maintainer and release new version.

**Comment by otuji** [comment]
How is new maintainer going?

**Comment by kmadel** [comment]
Sounds good, obviously there needs to be a release and I haven't been able to get to it for some time now.

**Comment by samrocketman** [comment]
@ssbarnea log into the `#jenkins` channel on irc.freenode.net and ask to be added as a maintainer to this project.  Refer them to this issue so they see Kurt and I signed off on it.

@otuji thanks for the poke.

**Comment by timja** [comment]
i am maintaining now, PR count is down
