### ISSUE TITLE
Configuration of Slack messaging should appear in Post-build actions

### ISSUE THREAD

**Issue by jwg4** [jenkinsci/slack-plugin#224]
The configuration form for slack messaging appears at the top of a job configuration page along with other general configurations. Slack messaging then has to be turned on in 'Post-Build actions'. Based on how other post-build actions are configured, shouldn't the settings appear underneath the post-build action and only appear if Slack messaging is added?

This would 
- reduce the page real estate if Slack is not used for a job.
- stop people from missing the post-build action, and think that they have Slack messaging turned on when they have ticked one or more boxes in the upper config, when in fact no messages will be sent.
- be more consistent with how other post-build actions are configured.

**Comment by frostmar** [comment]
From the changelog, I think this has been fixed:

https://github.com/jenkinsci/slack-plugin/blob/master/CHANGELOG.md
> Job level configuration was moved under post-build actions with support for migration from previous versions. (#79, #170)
