### ISSUE TITLE
Back to normal timings way off

### ISSUE THREAD

**Issue by gricey432** [jenkinsci/slack-plugin#225]
Having an ongoing issue with the 'back to normal after x time' messages. After upgrading to Jenkins 2 the timings are way off (eg 1 day 10 hours instead of 2 hours, 17 hours instead of 10 minutes)
I can't see a consistent offset to the times.

Plugin version 2.0.1
Jenkins version 2.2

**Comment by gricey432** [comment]
Here's a screenshot of the most recent one
http://imgur.com/kjvGpYfl.png

**Comment by gricey432** [comment]
Updated to
Plugin 2.0.1
Jenkins 2.8

Issue still occurs
http://i.imgur.com/sh2504k.png

**Comment by gricey432** [comment]
I read the changelog and looked at #129 which is closed but appears unfixed.
In [ActiveNotifier.java](https://github.com/jenkinsci/slack-plugin/blob/ae8e6e351fa4633e0d494187333298eaa3b41904/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L374) it is calculating the time from the last successful build which could have been days ago and have nothing to do with the breakage.
Wouldn't it make more sense for this to be the time since the last Failed build? I think this is what the closed issue #129 was suggesting.

So if my last successful build was 2 days ago, and then I broke it 20 minutes ago, I want to be told that it was fixed in 20 minutes, not 2 days.

**Comment by gricey432** [comment]
I've got a PR #228 but this plugin seems to be dead

**Comment by gricey432** [comment]
One last attempt at getting some feedback / merge on this before I'll go see if I can get some help on Jenkins IRC

**Comment by samrocketman** [comment]
@kmadel can you take a look at this?  @gricey432 apologies about not addressing this sooner.

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.
