### ISSUE TITLE
Programmatically modifying global Slack plugin settings

### ISSUE THREAD

**Issue by pdunnavant** [jenkinsci/slack-plugin#23]
I was just curious if there's any interest (aside from just me) in adding some way to modify the instance variables inside SlackNotifier.DescriptorImpl?
https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L81

I'm using Chef to manage my Jenkins instance, and I'd like to have Chef set the appropriate values for Slack as well. Most of these are managed via Groovy scripts submitted via the jenkins-cli.jar. Unfortunately, it looks like the only way to modify the Slack values would be by creating a RequestImpl to "fake out" the form submission. That's not really too desirable. Instead, this could be resolved by adding setters for those values (or some other method to modify them) similar to the mailer-plugin: https://github.com/jenkinsci/mailer-plugin/blob/master/src/main/java/hudson/tasks/Mailer.java#L201

I'd be happy to do this work and issue a pull request if there's any interest. Thoughts?

**Comment by samrocketman** [comment]
I don't actively develop the slack plugin and am only maintaining pull requests.  If this is a feature you want then feel free to contribute it!

**Comment by peergum** [comment]
Why don't you just create/edit/patch the config files with Chef? we use puppet to set up all our jenkins configs, and all it requires to make a change is to update the config and push.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by joelwilson** [comment]
I was just looking to see if this was possible - sad to see it isn't. :+1:

**Comment by samrocketman** [comment]
It would be useful if someone more knowledgeable described in detail how they would expect this behavior to work.  Programmatically configuring the slack plugin isn't exactly clear to me outside of configuration management.  Can you elaborate?

**Comment by glenjamin** [comment]
Due to the magic of groovy and some notes from http://blogs.mulesoft.org/fake-and-stub-objects-creation-using-groovy-2/, I was able to configure my slack integration as follows.

This is using the `jenkins_script` resource from the community jenkins cookbook (https://supermarket.chef.io/cookbooks/jenkins)

```groovy
def slack = Jenkins.instance.getExtensionList(
  jenkins.plugins.slack.SlackNotifier.DescriptorImpl.class
)[0]
def params = [
  slackTeamDomain: "<mydomain>",
  slackToken: "<mytoken>",
  slackRoom: "",
  slackBuildServerUrl: "",
  slackSendAs: ""
]
def req = [
  getParameter: { name -> params[name] }
] as org.kohsuke.stapler.StaplerRequest
slack.configure(req, null)

slack.save()
```

The main benefit of this approach is not having to take over management of the entire `config.xml` file.

**Comment by samrocketman** [comment]
Awesome :-D

**Comment by joelwilson** [comment]
@glenjamin  Thank you for posting this!

**Comment by schisamo** [comment]
@glenjamin It's even easier than that, you can skip the `StaplerRequest` layer completely. Here is the Groovy snippet we use here at Chef:

```ruby
slack_creds = encrypted_data_bag_item_for_environment('accounts', 'slack')

jenkins_script 'configure-slack-notifier' do
  command <<-GROOVY.flush
    jenkins = jenkins.model.Jenkins.getInstance()
    slack = jenkins.getDescriptorByType(jenkins.plugins.slack.SlackNotifier.DescriptorImpl)
    slack.teamDomain = "#{slack_creds['domain']}"
    slack.token = "#{slack_creds['api_token']}"
    slack.sendAs = "CHEF CI"
    slack.save()
  GROOVY
end
```

**Comment by glenjamin** [comment]
@schisamo oh wow, how does that work? All those fields are private!

**Comment by schisamo** [comment]
@glenjamin Groovy uses the getter and setter methods under the covers so `slack.token = 'foo'` is actually the Java `slack.setToken("foo")`. 

More here: http://www.groovy-lang.org/style-guide.html#_getters_and_setters

**Comment by glenjamin** [comment]
@schisamo I'm now even more confused - the Slack Descriptor doesn't have setters - that's what this whole issue was about!

**Comment by samrocketman** [comment]
Groovy creates setters and getters for private variables.  But having setters in Java wouldn't be a bad thing.

**Comment by ogavrisevs** [comment]
@glenjamin thank you for groovy example ! exactly what im been looking for.

**Comment by kmadel** [comment]
@pdunnavant Based on the provided examples I am closing this issue. Please reopen with an explanation if none of the above solutions work for you.

**Comment by ystreibel** [comment]
Hi, I would like to programmatically modify the global settings with the 2.27 version of plugin but I always have something wrong with my groovy script. I don't know, if this method is always available.

```
import jenkins.model.*
jenkins = Jenkins.instance

def slack = Jenkins.getInstance().getExtensionList(
  jenkins.plugins.slack.SlackNotifier.DescriptorImpl.class
)[0]

def params = [
  baseUrl: '',
  teamDomain: '<mydomain>',
  tokenCredentialId: '<mytoken>',
  botUser: 'true',
  sendAsText: 'false',
  iconEmoji: '',
  username: '',
  room: '<myroom>'
]
def req = [
  getParameter: { name -> params[name] }
] as org.kohsuke.stapler.StaplerRequest
slack.configure(req, null)

slack.save()
println 'Slack global settings configured.'
```

That's the error:
```
Jun 28, 2019 10:15:29 AM jenkins.util.groovy.GroovyHookScript execute
jenkins_1  | INFO: Executing /var/jenkins_home/init.groovy.d/slack.conf.groovy
jenkins_1  | Jun 28, 2019 10:15:30 AM jenkins.util.groovy.GroovyHookScript execute
jenkins_1  | WARNING: Failed to run script file:/var/jenkins_home/init.groovy.d/slack.conf.groovy
jenkins_1  | java.lang.UnsupportedOperationException
jenkins_1  | 	at org.codehaus.groovy.runtime.ConvertedMap.invokeCustom(ConvertedMap.java:52)
jenkins_1  | 	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
jenkins_1  | 	at com.sun.proxy.$Proxy64.bindJSON(Unknown Source)
jenkins_1  | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl.configure(SlackNotifier.java:765)
jenkins_1  | 	at jenkins.plugins.slack.SlackNotifier$DescriptorImpl$configure.call(Unknown Source)
jenkins_1  | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jenkins_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jenkins_1  | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
jenkins_1  | 	at slack_conf.run(slack.conf.groovy:21)
jenkins_1  | 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
jenkins_1  | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
jenkins_1  | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
jenkins_1  | 	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
jenkins_1  | 	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1  | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins_1  | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins_1  | 	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1091)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
Those groovy instructions are outdated, you're much better off using the configuration-as-code plugin instead:
https://github.com/jenkinsci/slack-plugin#configuration-as-code

**Comment by ystreibel** [comment]
Thanks! But I found a groovy working way => https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/configure-slack.groovy
