### ISSUE TITLE
Slack sends messages in English with duration in Dutch

### ISSUE THREAD

**Issue by amedee** [jenkinsci/slack-plugin#231]
Slack sends messages like this:

> ## leeroy BOT [10:49 AM]  
> 
> itext7-develop-integrationtests - #925 Back to normal after 3 dagen 17 uren (Open)
> Test Status:
>     Passed: 785, Failed: 0, Skipped: 5

"3 dagen 17 uren" is Dutch.

We are a team of developers in Belgium, Belarus and the USA.
Jenkins is hosted in Belgium.
The browser language of the person who configured Jenkins and the Slack plugin, is English.

**Expected result**: the Slack plugin sends duration in English.

**Comment by timja** [comment]
duration string come from jenkins core, I can't see anyway for us to say take a specific language, if you want the language to be english you will need to set the jenkins server language to be english, 
https://stackoverflow.com/a/8809141
