### ISSUE TITLE
add defaults for slackNotifier job DSL api

### ISSUE THREAD

**Issue by ulich** [jenkinsci/slack-plugin#232]
We are using the job dsl to describe our jobs. The `slackNotifications` method is deprecated in favor of the new `slackNotifier` method that comes from the extension points.

The old `slackNotifications` provided many defaults so we could configure e.g. the slackDomain, token, etc. globally in jenkins and then only add a small block like 

```
    publishers {
        slackNotifications {
            projectChannel('channel')
            notifyUnstable()
            notifyFailure()
            notifyBackToNormal()
        }
    }
```

but with the new `slackNotifier` method we have to specify all the properties:

```
ERROR: the following options are required and must be specified: teamDomain, authToken, buildServerUrl, sendAs, startNotification, notifyAborted, notifyNotBuilt, notifySuccess, notifyRepeatedFailure, includeTestSummary, commitInfoChoice, includeCustomMessage, customMessage
```

Is it possible to add defaults with extension points?

**Comment by samrocketman** [comment]
Feel free to subscribe to #296 for updates related to Slack Plugin 2.2 release.
