### ISSUE TITLE
Incorrect handling of Unicode characters

### ISSUE THREAD

**Issue by amedee** [jenkinsci/slack-plugin#233]
One of our developers is called Benoît. His name is in his commits.
When the Slack plugin sends a notification, it doesn't show the **î** character correctly, it is shown as **��**.

> ---
> 
> itext7-develop-compile - PL#606-e0928fa1 Changes:
> - Undo making PdfADocument a final class [Beno��t Lagae]

**Comment by frodeaa** [comment]
I'm unable to reproduce the bug

 `slackSend channel: '#test', color: '#439FE0', message: 'Hello Benoît'`

<img width="264" alt="screen shot 2016-10-21 at 20 51 58" src="https://cloud.githubusercontent.com/assets/45172/19608240/3f1c0fae-97d0-11e6-93a4-1c1387e4c0ac.png">

and with Notification message includes set to "commit list with authors only"

<img width="376" alt="screen shot 2016-10-21 at 21 03 11" src="https://cloud.githubusercontent.com/assets/45172/19608501/24d94b1e-97d2-11e6-9ec3-19d39a9a0005.png">

and with Notification message includes set to "commits list with authors and titles"
<img width="230" alt="screen shot 2016-10-21 at 21 06 36" src="https://cloud.githubusercontent.com/assets/45172/19608523/46d142e4-97d2-11e6-8fa0-bbb7dc421cdd.png">
