### ISSUE TITLE
Not showing changes when using multiple SCM

### ISSUE THREAD

**Issue by evenme** [jenkinsci/slack-plugin#234]
After implementing Jenkins build (triggered by GitLab webhooks) with multiple SCM (using 2 git repositories, one for the project and another one for the ansible deployment scripts), just once the changes appeared on the slack output. After that, it always shows as "No Changes.".

![screenshot from 2016-07-07 10-24-22](https://cloud.githubusercontent.com/assets/117922/16656573/35788e2e-442d-11e6-9145-c009e61b1c5e.png)

Also, the custom message repeats when starting and finishing the build (this only happens when it's triggered by GitLab, manual jobs doesn't duplicate, just shows "Started by user XPTO..."):

![screenshot from 2016-07-07 10-28-38](https://cloud.githubusercontent.com/assets/117922/16656722/c61c9222-442d-11e6-855e-9097e9fe43b6.png)

**Comment by timja** [comment]
reopen if this is still needed, otherwise not an issue if you use pipeline support..
