### ISSUE TITLE
ability to display custom message without "standard" message

### ISSUE THREAD

**Issue by stephenmenton** [jenkinsci/slack-plugin#239]
Pull #169 provides functionality I look forward to using. I would like the ability to only display the custom message, not have it appended after the standard message. My group is looking to have a large number of jobs reporting in a single window and wants concise, linked messages with specific information in a specific order. Forcing everything to be two lines forces scrolling twice as quickly.

**Comment by timja** [comment]
Pipeline allows full customisation, I would suggest using that instead
Otherwise the UI would be crazy...
