### ISSUE TITLE
user-defined color options

### ISSUE THREAD

**Issue by stephenmenton** [jenkinsci/slack-plugin#240]
I would like to be able to define custom colors for each status, as well as the option not to construct a status message with a color, by type. e.g. Start w/o color, user-defined colors for success, failure, aborted. 
This relates to Issue #210 but is perhaps more specific.

**Comment by timja** [comment]
You can use whatever colour you want in pipeline,
unlikely to add this much customisation to freestyle jobs

#210 should fix the colour blind issue
