### ISSUE TITLE
Outgoing web hook don't detect github projects

### ISSUE THREAD

**Issue by fwal** [jenkinsci/slack-plugin#244]
When prompting for `list projects` (or any other command) in slack using the outgoing web hook, projects created with [`github-organization-folder`](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Organization+Folder+Plugin) isn't listed in the response.

**Comment by dpires** [comment]
My best guess is the github-organization-folder plugin creates jobs as either a Job or Item.

https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/webhook/ListProjectsCommand.java#L44

When listing projects, the plugin gets a list of all jobs subclassing AbstractProject, so if the Job is a superclass of Job or Item, it won't be found.

**Comment by fwal** [comment]
Also having problems detecting pipeline projects

**Comment by fwal** [comment]
Side question: Should I even report this here or in Jira? ;)
