### ISSUE TITLE
Stop branch indexing from Multi-Branch plugin sending a Slack message

### ISSUE THREAD

**Issue by neilferreira** [jenkinsci/slack-plugin#250]
Hi all

I'm using this plugin for multi branch support: https://wiki.jenkins-ci.org/display/JENKINS/Multi-Branch+Project+Plugin

As it stands, when the branch indexing runs it sends a message into Slack.  I just need it to send me messages about the actual builds that it creates.

Any ideas?

**Comment by kmadel** [comment]
It appears that this is a multi-branch-project-plugin issue, not a slack plugin issue.
