### ISSUE TITLE
Is it possible to use with custom integration?

### ISSUE THREAD

**Issue by rafaeleyng** [jenkinsci/slack-plugin#255]
#216 makes me think that this is not possible. Could anyone confirm?

**Comment by samrocketman** [comment]
I'm not sure.  I've only ever used it with the Jenkins app in slack integrations.

**Comment by rafaeleyng** [comment]
I forgot to say, but I tried using the last part of the webhook url and it didn't work.

**Comment by kmadel** [comment]
See #249 - close in deference to that PR
