### ISSUE TITLE
Allow conditional posting based on variables

### ISSUE THREAD

**Issue by katerberg** [jenkinsci/slack-plugin#256]
It would be nice if I could choose whether the plugin posts to Slack based on parameters that I pass to the build. e.g. for my master build, I want to know if there is a failure, but for my bad-code branch, I want to be able to run the job but not notify the entire team when it fails.

**Comment by kmadel** [comment]
Use Pipeline Multibranch with and check env.BRANCH_NAME patterns to control notifications.
