### ISSUE TITLE
Slack notification is broken now

### ISSUE THREAD

**Issue by windy** [jenkinsci/slack-plugin#259]
I have a right configuration for slack notification, it has worked well from then.

But now it's broken, I test this, see the log as below:

``` bash
INFO: Posting: to #ci on 80pt using https://80pt.slack.com/services/hooks/jenkins-ci?token=xxxxxxxxxxxxxxxxx: Slack/Jenkins plugin: you're all set on http://dev.80percent.io:8080/ good
Oct 26, 2016 3:00:50 PM org.apache.commons.httpclient.HttpMethodBase readResponseBody
INFO: Response content length is not known
Oct 26, 2016 3:00:51 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed. Response:
```

Any advise for it ?  thx.

**Comment by kmadel** [comment]
Please provide more information:

- Jenkins core version
- Slack plugin version
- Any recent changes to your config - new plugins, updated plugins, etc.
- Steps to reproduce if possible

Thanks

**Comment by windy** [comment]
Jenkins core version: 2.19.3

Slack plugin version: 2.1

No new plugins or updated plugins recently.

I have no idea for this issue

**Comment by windy** [comment]
@kmadel For a long time locate this issue, I found a wrong slack team config for my slack notification. But I don't know when this config has changed.
