### ISSUE TITLE
Pipeline syntax support of variable expansion?

### ISSUE THREAD

**Issue by vinayan3** [jenkinsci/slack-plugin#260]
I have a pipeline which has a build parameter called `DEPLOYMENT_ENV`. I have this line and it isn't working as I expected it would be

```
env.DEPLOYMENT_ENV = DEPLOYMENT_ENV
slackSend channel: 'general', message: 'Deploy: Starting deployment of $DEPLOYMENT_ENV'
```

I have resorted to doing this now

```
slackSend channel: 'general', message: 'Deploy: Starting deployment of ' + DEPLOYMENT_ENV
```

This is just a simple example because I use to have more build arguments I'd like to put into the message. 

Any thoughts?

**Comment by ysegorov** [comment]
double quoted string is needed for this
something like
```
slackSend channel: 'general', message: "Deploy: Starting deployment of ${env.DEPLOYMENT_ENV}"
```
check [groovy docs](http://docs.groovy-lang.org/latest/html/documentation/index.html#_string_interpolation)

groovy noob here :)

**Comment by vinayan3** [comment]
Thank you so much! I should have RTFM.
