### ISSUE TITLE
Tagging user who ran the job

### ISSUE THREAD

**Issue by c0debreaker** [jenkinsci/slack-plugin#264]
Is there a feature where we can tag/notify the person who ran the job? The way we configured Jenkins is that it will send a notification to the #slack-channel which is fine. However, it only contains a link to open the corresponding job. How can the user who started the job also be included in the notification? Here is a sample of what I'd like to happen

Here is the before

```
clear_db - #929 Back to normal after 3 hr 17 min (Open)
```

How I want it to look like

```
clear_db - #929 Back to normal after 3 hr 17 min (Open) Job ran by @joe
```

**Comment by kmadel** [comment]
Would rather rely on something like https://github.com/jenkinsci/build-user-vars-plugin - but that doesn't currently work. Would need this [JENKINS-32532](https://issues.jenkins-ci.org/browse/JENKINS-32532), to be fixed to use that in conjunction with custom message.

**Comment by c0debreaker** [comment]
@kmadel I don't get the feature you mentioned. Is that an email notification where message will contain the values of the variable that got prepared on the job than ran? Most of us in the team are 99% online in Slack chat. We noticed that we always missed email notifications.

**Comment by Tomino2112** [comment]
@kmadel Thank you, that is the issue I was looking for. I can confirm that `build-user-vars-plugin` variables currently dont work in after build notifications

**Comment by c0debreaker** [comment]
Sorry, I almost forgot this post I made. Hopefully one of these days, it will work :)

**Comment by Tomino2112** [comment]
Im surprised jenkins doesnt give you name of user who executed task by
default

**Comment by c0debreaker** [comment]
Jenkins does provide the user who executed the task in Jenkins UI. I was asking the about tagging the user in a slack notification

**Comment by Tomino2112** [comment]
What is the variable to get the user? As far as  i know u have to use plugin

**Comment by c0debreaker** [comment]
I'll have to ask our devops what Slack plugin they installed

**Comment by c0debreaker** [comment]
This is all I see - http://imgur.com/a/j4vXI

**Comment by c0debreaker** [comment]
There is not much to it - http://imgur.com/a/PskAG

**Comment by Tomino2112** [comment]
There is nothing in the screenshots that would give you user who executed
the job

**Comment by c0debreaker** [comment]
Even after a year, we still have don't have a solution. All we do now is open the link in Slack which brings us to our Jenkins job. Look at the log and find the user. Then we will inform the user. It works but it sucks that we have to go to Jenkins just to find the person who made the merge.
