### ISSUE TITLE
Release new version of plugin

### ISSUE THREAD

**Issue by andrusha** [jenkinsci/slack-plugin#27]
It was 3 months since color-coding was merged and still from jenkins dashboard only the old version is available.

**Comment by samrocketman** [comment]
I'll be performing a release soon.  Waiting on a few last pull requests.

**Comment by samrocketman** [comment]
I've scheduled a [target release date of Feb 8th](https://github.com/jenkinsci/slack-plugin/milestones).

**Comment by samrocketman** [comment]
I don't actively develop this plugin.  I only maintain pull requests and releases from now on.

**Comment by orj** [comment]
I couldn't get version 1.2 to work.  Any progress on a new release?

**Comment by samrocketman** [comment]
Subscribe to #47 for updates on progress of the release.  I've attempted a release a few times.

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released. This a fix for this has been included in it. Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.
