### ISSUE TITLE
Notification only triggered on Notify Build Start even when other events specified

### ISSUE THREAD

**Issue by jonbartlett** [jenkinsci/slack-plugin#271]
Hi, 

I have slack notifications set for all events as a post-build action however the only one that ever appears is for "Notify Build Start". Other events are seemingly ignored.

There is nothing in the Jenkins log to indicate anything amiss with my setup.

Jenkins 2.19.4
Slack Notification Plugin 2.1

Thanks.

Jon.

![image](https://cloud.githubusercontent.com/assets/119513/21088204/5343f33c-c081-11e6-8ed9-bcf1f19f81ee.png)

![image](https://cloud.githubusercontent.com/assets/119513/21088213/66adbeee-c081-11e6-9ba8-d4b0a64ff98a.png)

**Comment by jonbartlett** [comment]
on further inspection of the log, the following entry seems to be coming from the Slack notification. Unsure if this is related to the issue or generated through the course of sending the single notification that is produced:

`INFO: SCM changes detected in SVN-CR19321. Triggering  #45

Dec 12, 2016 4:42:07 PM jenkins.plugins.slack.SlackNotifier prebuild

INFO: Invoking Started...

Dec 12, 2016 4:42:07 PM jenkins.plugins.slack.ActiveNotifier getChanges

INFO: Entry hudson.scm.SubversionChangeLogSet$LogEntry@62dc355b

Dec 12, 2016 4:42:07 PM org.apache.commons.httpclient.HttpMethodBase readResponseBody

INFO: Response content length is not known

Dec 12, 2016 4:42:19 PM hudson.model.Run execute

INFO: SVN-CR19321 #45 main build action completed: FAILURE
`

**Comment by blocknotes** [comment]
I have the same problem. In my logs I see:

```
Jan 03, 2017 4:36:55 PM hudson.model.Run execute
INFO: project-1 #27 main build action completed: FAILURE
Jan 03, 2017 4:43:49 PM jenkins.plugins.slack.SlackNotifier prebuild
INFO: Invoking Started...
Jan 03, 2017 4:44:14 PM hudson.model.Run execute
INFO: project-2 #12 main build action completed: FAILURE
Jan 03, 2017 4:59:26 PM hudson.model.Run execute
INFO: project-2 #13 main build action completed: FAILURE
```

I checked all the Notify flags but on the channel I receive only one message:
`project-2 - #12 Started by user Mat (Open)`

Any idea?

**Comment by blocknotes** [comment]
SOLVED: if had to check also "Notify Repeated Failure"

**Comment by nwsparks** [comment]
notify repeated failure fixed it for me as well. was banging my head against this for awhile before i found this thread. Thanks.

**Comment by jonbartlett** [comment]
Yep that worked for me as well.
