### ISSUE TITLE
help:  not able to get slack channel to work in groovy script.

### ISSUE THREAD

**Issue by tacoben** [jenkinsci/slack-plugin#273]
im not a pro at this - but i am trying to figure out what the correct param name for the slack channel is.

ive got this all working:

  slackTeamDomain: '<channel>',
  slackToken: '<token>',
  slackChannel: '#notifications',  <=== not working
  slackBuildServerUrl: 'http://localhost:8080/',
  slackSendAs: ''

**Comment by timja** [comment]
use configuration as code, instructions in the readme
