### ISSUE TITLE
Slack Message Attachments

### ISSUE THREAD

**Issue by arvalaan** [jenkinsci/slack-plugin#277]
Hi there,

Is it already possible to send a notification to Slack using it's Message Attachments functionality? Like the below for instance.

`attachments: "[
	{
		"fallback": "${project} ${env.BRANCH_NAME} execution #${env.BUILD_NUMBER}",
		"color": "#3BA553",
		"fields": [
			{
				"title": "Successful execution",
				"value": "<{env.BUILD_URL}|Execution #${env.BUILD_NUMBER}>",
				"short": true
			},
			{
				"title": "Project",
                "value": "${project}",
				"short": true
			},
			{
				"title": "Branch",
				"value": "${env.BRANCH_NAME}",
				"short": true
			},
			{
				"title": "Environment",
                "value": "<${env_url}|${env}>",
				"short": true
			}
		]
	}`

**Comment by yogeshlonkar** [comment]
Yes it is. I am able to send notification
```groovy
def attachmenPayload = [[
        fallback: "${project} execution #${env.BUILD_NUMBER}",
        color: colorCode,
        fields:[
            [
                title: "${project}",
                value: "Build <${env.BUILD_URL}| #${env.BUILD_NUMBER}> - ${message}",
                short: false
            ],
            [  
                title: "Branch",
                value: "${env.BRANCH_NAME}",
                short: true
            ],
            [  
                title: "Environment",
                value: "abc:xyz",
                short: true
            ]
        ]
    ]]
// Send notifications
slackSend(channel: '#test', color: colorCode, attachments: new JsonBuilder(attachmenPayload).toPrettyString() )
```

**Comment by RekhaSabbineni22** [comment]
Hi Yogesh,

I am trying to include the slack notification in Jenkins Pipeline.I am able to send messages to slack,but not able to send as attachments.

**Comment by davecarlson** [comment]
> Yes it is. I am able to send notification
> 
> ```groovy
> def attachmenPayload = [[
>         fallback: "${project} execution #${env.BUILD_NUMBER}",
>         color: colorCode,
>         fields:[
>             [
>                 title: "${project}",
>                 value: "Build <${env.BUILD_URL}| #${env.BUILD_NUMBER}> - ${message}",
>                 short: false
>             ],
>             [  
>                 title: "Branch",
>                 value: "${env.BRANCH_NAME}",
>                 short: true
>             ],
>             [  
>                 title: "Environment",
>                 value: "abc:xyz",
>                 short: true
>             ]
>         ]
>     ]]
> // Send notifications
> slackSend(channel: '#test', color: colorCode, attachments: new JsonBuilder(attachmenPayload).toPrettyString() )
> ```

what does the output of this look like ?

**Comment by yogeshlonkar** [comment]
> what does the output of this look like ?

Have a look at [this](https://github.com/yogeshlonkar/awesome-jenkins-utils/wiki#slack-it)
