### ISSUE TITLE
"Test Connection" button

### ISSUE THREAD

**Issue by maxlinc** [jenkinsci/slack-plugin#28]
I've seen several Jenkins plugins with a "Test Connection" button. See the [Gerrit Trigger](https://wiki.jenkins-ci.org/display/JENKINS/Gerrit+Trigger#GerritTrigger-AdministrativeSettings) for an example.

That would definitely be useful in this plugin to make sure you have the correct settings. I was trying to set this up and apparently specified an invalid channel. It took me a while to figure that out, since it is only in the system log, not the build log.

**Comment by samrocketman** [comment]
I don't actively develop this project.  However, I am now maintaining pull requests and releases.  Contributions are welcome!

**Comment by peergum** [comment]
Coming fix to do that...

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by samrocketman** [comment]
This was released in 1.7 however it does not currently work.  Please follow issue #51 for updates on when the fix is in for this issue.  I'm closing this issue so #51 will be where you should follow updates.

**Comment by peergum** [comment]
It DOES work in the general settings section
