### ISSUE TITLE
Slack Webhook Settings

### ISSUE THREAD

**Issue by eyalzek** [jenkinsci/slack-plugin#281]
![image](https://cloud.githubusercontent.com/assets/6243438/22293512/2b9f897a-e310-11e6-8f71-5adbdf301a78.png)

Seems like it isn't documented anywhere? What's the difference between that and the "Global Slack Notifier Settings" ?

**Comment by FernandoTBarros** [comment]
Where did you find it?

**Comment by eyalzek** [comment]
Under the `Manage Jenkins` view you have 2 slack sections;
`Slack Webhook Settings` & `Global Slack Notifier Settings`

**Comment by FernandoTBarros** [comment]
I guess I'm using an older version of the plugin. I'm still using Jenkins 1.6
Thanks for the info.

**Comment by samrocketman** [comment]
For now, please refer to #160 for more descriptions.  cc @dpires

**Comment by warden** [comment]
This is a different plugin that is basking on this plugin. `slack-plugin` provides notifications from Jenkins->Slack (outgoing), while the `jenkins-slack-webhook-plugin` provides Slack->Jenkins commands (incoming).
