### ISSUE TITLE
Send slack command message (/giphy)

### ISSUE THREAD

**Issue by jimmod** [jenkinsci/slack-plugin#282]
Hi,

Is sending slack command is supported.
Using
   slackSend (channel: "channel", message: "/giphy test")
will only result "/giphy test" as text, not executing giphy command

Do I use it wrong? Or the feature is not currently supported
Thank you in advance

**Comment by olivierto** [comment]
+1 
I would love to have this feature working <3
May be the string is escaped before send...

**Comment by dough29** [comment]
:+1:

**Comment by timja** [comment]
supported since 2.4

**Comment by svalchinov** [comment]
@timja Sorry I was looking for this as well. I can't locate version 2.4 of this plugin?

**Comment by timja** [comment]
2.18 is the latest version
https://github.com/jenkinsci/slack-plugin/releases

**Comment by robert-gleis** [comment]
I am also looking into this. `slackSend(channel: '#t_partyparrots_ci', message: "/giphy Noooo")` does not work for me. I guess that I have to configure something else however I cant figure out what it is. I would appreciate a hint into the right direction

**Comment by timja** [comment]
Try set sendAsText: true

**Comment by robert-gleis** [comment]
I tried that already however but it will only post the command as text the only difference is that the text is now without the grey bar at the left side

**Comment by timja** [comment]
Not sure, reopening as it was likely closed by accident in a bulk cleanup of old issues

**Comment by dmonaco05** [comment]
If not able to use giphy command how about at least allowing the giphy links to play?

**Comment by timja** [comment]
Closing as unsupported by the slack API
https://stackoverflow.com/a/35971294/4951015
https://stackoverflow.com/questions/35966648/how-can-i-make-it-so-that-slack-bots-can-use-giphy
