### ISSUE TITLE
Extra custom text for Failures only

### ISSUE THREAD

**Issue by camelinckx** [jenkinsci/slack-plugin#284]
On failures only allow a short custom message where I would include the @channel handle which would alert that something requires attention (even if channel is muted).

Context:
We like having all build notifications include the commit details (sucess or fail - already provided)
I want to keep the slack channel muted by default and be notified when something requires attention only.

**Comment by jgangemi** [comment]
see https://github.com/jenkinsci/slack-plugin/pull/169
