### ISSUE TITLE
Global variables are not interpreted in the field message of slackSend

### ISSUE THREAD

**Issue by mchaffotte** [jenkinsci/slack-plugin#286]
In a Jenkins file, global variables are not interpreted in the message field.

not working example
slackSend message: 'Build Started - ${JOB_NAME} ${BUILD_NUMBER}  (<${BUILD_URL}|Open>)'

working example
slackSend message: "Build Started - ${JOB_NAME} ${BUILD_NUMBER}  (<${BUILD_URL}|Open>)"

**Comment by StephenKing** [comment]
Welcome to Groovy, please read about [String Interpolation](http://docs.groovy-lang.org/latest/html/documentation/#_string_interpolation). It's a feature, not a bug.

**Comment by mchaffotte** [comment]
Thanks you for your response. I did not know that behaviour. I am still in trouble because in my declarative pipeline I use
archiveArtifacts 'build/distributions/myproject-${JOB_BASE_NAME}-${BUILD_NUMBER}.zip'
and the global variables are interpreted.

**Comment by samrocketman** [comment]
Not a bug.  Feature of groovy as @StephenKing pointed out.

**Comment by albertorm95** [comment]
@mchaffotte You have to use double quote to be able to Interpolate variables:
`message: "${JOB_NAME} - ${BUILD_DISPLAY_NAME} Started, (<${BUILD_URL}|Open>)"`

**Comment by dailytabs** [comment]
Snippet Generator spits it out with single quotes. Just saying...
