### ISSUE TITLE
Update Messages

### ISSUE THREAD

**Issue by mefynn** [jenkinsci/slack-plugin#288]
hey, it would be awesome, if the bot would update its messages
Message: Started
First Message Update: Success
Second Message Update: Commit Message and build number and user that pushed (@johndoe)

**Comment by samrocketman** [comment]
As in publish a message once and continue to update the existing message?  There is a similar request but instead using slack thread support.  See #279.  I think we should defer to that issue instead since it provides a similar ask but with a different implementation (in light of a new slack feature).

**Comment by mefynn** [comment]
yeah. idk if threading is the better way to go here... i would prefer, start->finished/result as updated messages.

**Comment by dccampbell** [comment]
Just wanted to comment how well I think this actually synergizes with #279. The initial post can be updated to reflect the current status of the build throughout, while other output and more details can be posted as thread responses. 

This keeps the Slack spam super minimal (only one thread per job), allows us to safely dump lots of useful info to the room w/o cluttering the view for everyone (via threaded replies), but also allows for at-a-glance view of the current build status (by updating the initial post).

**Comment by timja** [comment]
This is available through thread support or update message support can be tracked here:
https://github.com/jenkinsci/slack-plugin/issues/221
