### ISSUE TITLE
Fails to notice build transition when last build was cancelled?

### ISSUE THREAD

**Issue by kwerle** [jenkinsci/slack-plugin#29]
I have "Notify Back To Normal" enabled.

I had a build that was failing.  I started a new build in jenkins and then cancelled the build while it was in progress.

I then tweaked the build configuration in jenkins.

I did a new build and it succeeded.  I received no slack notification that the build had gone from broken to working.  I suspect that's because the last build had been cancelled.

**Comment by samrocketman** [comment]
I have not seen this issue in the 1.7-SNAPSHOT version.  It is currently stable if you want to build it and install it in your Jenkins instance to test it.  [slack-1.7 will be released this weekend](https://github.com/jenkinsci/slack-plugin/milestones).

**Comment by peergum** [comment]
The plugin only checks the status of the previous build. If you aborted it, it cannot _currently_ guess what the status was before that. I'll look into checking the latest non-aborted status and patching the plugin asap.

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released.  This a fix for this has been included in it.  Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.
