### ISSUE TITLE
New value for buildServerUrl does not take effect

### ISSUE THREAD

**Issue by nheinric** [jenkinsci/slack-plugin#3]
Jenkins: 1.549
Java: 1.7.0_51-b13
OS: OSX 10.7.5
Slack plugin: 1.2

Changing the buildServerUrl in my Jenkins config was not having any effect: all build notifications in Slack still referred to the URL that I entered when I first configured the plugin.

I realized that this is because, while `jenkins.plugins.slack.SlackNotifier.xml` was being updated properly, my job-specific config was not.

However, there is no field in the project configuration frontend to set the buildServerUrl parameter.

Removing and re-adding the "Slack Notifications" post-build action resolved the issue for me, in the end.

**Comment by samrocketman** [comment]
This has been fixed with #26.  The fix will be available in the next release slack-1.7.

**Comment by Nakilon** [comment]
Happened just now with

Jenkins ver. 1.627
and Slack Plugin v1.8

**Comment by samrocketman** [comment]
According to the original workaround you would remove and re-add slack notifications to the individual jobs.
