### ISSUE TITLE
Getting the user in Pipeline (Github Auth)

### ISSUE THREAD

**Issue by stuffandthings** [jenkinsci/slack-plugin#300]
I'm using the Github authentication plugin and if I add slack notifications in a regular freestyle project I get the expected result:
```
Job - #1 Started by user John Doe (Open)
```
Where John Doe is the Github user who started the build.

However, I am unable to get the user in my pipeline notification. I've tried using the build-user-env-plugin but I just get:
```
Job - #1 Started by user null (Open)
```

How do I inject the Github user in my message from a pipeline script?

**Comment by samrocketman** [comment]
Could you provide some source so that I don't need to spend time on figuring out what you're doing?  At the very least an example of how you're using it so I can test it with minimal effort.

**Comment by dermidgen** [comment]
@stuffandthings Here's an example from my stuff after `checkout scm`

```
            git_author_name = sh(returnStdout: true, script: 'git log --format="%an" | head -1').trim()
            git_author_email = sh(returnStdout: true, script: 'git log --format="%ae" | head -1').trim()
            gitCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
            shortCommit = gitCommit.take(6)

            slackSend color: 'good', message: "STARTED: Job '<${env.BUILD_URL}|${env.JOB_NAME} [${env.BUILD_NUMBER}]> at <${repo}/commit/${shortCommit}|${shortCommit}>'\nStarted by: <mailto:${git_author_email}|${git_author_name}>\n<${RUN_CHANGES_DISPLAY_URL}|Changelog>"
```
