### ISSUE TITLE
Use variable like this: slackSend channel: 'backend-${platform.name}'

### ISSUE THREAD

**Issue by valeriujieanu** [jenkinsci/slack-plugin#305]
Hi, 

I am trying to dynamically select the channel in my groovy script based on another variable I have set up.

```
slackSend channel: 'backend-${platform.name}', color: 'good', message: "[${buildIdSlack}] I've updated the infrastructure on *${platform.name}* platform"
```
It works in the message field, but not in the channel field.
`${platform.name}` returns `staging` , so it should actually be like below:
```
slackSend channel: 'backend-staging', color: 'good', message: "[${buildIdSlack}] I've updated the infrastructure on *staging* platform"
```

What do you think ?

**Comment by Caseledde** [comment]
You have to use double-quotes like you do in the message part:

`slackSend channel: "backend-${platform.name}", color: 'good', message: "[${buildIdSlack}] I've updated the infrastructure on *${platform.name}* platform"`

**Comment by samrocketman** [comment]
See Groovy string interpolation.  It's a feature of groovy.
