### ISSUE TITLE
Doesn't expand parameter values

### ISSUE THREAD

**Issue by Brantone** [jenkinsci/slack-plugin#31]
When working with condition job step, totally fubarrs ... stack trace to follow.

**Comment by alexandre-zia-movile** [comment]
Having the same issue with conditional step,

**Comment by alexandre-zia-movile** [comment]
stack trace here: http://pastebin.com/3bK14GGu

**Comment by samrocketman** [comment]
Any stack trace you can provide?

**Comment by samrocketman** [comment]
Versions would be good too:

* Jenkins version
* slack plugin version
* other related plugin versions to help other users debug this.

I do not actively develop this plugin.  I am maintaining pull requests and releases from now on.

**Comment by Brantone** [comment]
Apologies ... I had gotten job logs mixed up, actually not a stack trace, but this shows up in logs:

```
Feb 04, 2015 2:31:12 AM INFO jenkins.plugins.slack.StandardSlackService publish
Posting: to ${TEMP_SLACK} on [[SNIP]] using https://[[SNIP]].slack.com/services/hooks/jenkins-ci?token=[[SNIP]]: Login_Module_Clients_TEST - #99 Success after 47 sec (<http://[[SNIP]]/|Open>) green
```

Some values snipped for security reasons. 
* Jenkins version: 1.594
* Slack version: 1.2
* Other plugins: a bunch, but affecting this one are MultiJob + ez-template, except even done it with very simple projects.

**Comment by samrocketman** [comment]
@Brantone Can you test the latest release?  I have releases Slack Plugin 1.7.

**Comment by Brantone** [comment]
Digging into bit more the whole "Conditional job step" aspect is bit of misnomer ... it's more on use of parameters and substitution, I'm inclined to actually change title of the Issue to better reflect that.
Incidentally, the latest update to 1.7 introduced another bug ... when editing a job that uses Slack, if I hit "Test Connection" it produces a false positive. Written up as https://github.com/jenkinsci/slack-plugin/issues/51

**Comment by samrocketman** [comment]
> Digging into bit more the whole "Conditional job step" aspect is bit of misnomer ... it's more on use of parameters and substitution, I'm inclined to actually change title of the Issue to better reflect that.

I'm not sure I understand.  Can you please expand on that.  Rename the issue however you like so the problem is aptly described.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by Brantone** [comment]
Issue renamed ... root-cause for this, is that if I use parameters and set room to "${SLACK_ROOM}" it doesn't actually expand the parameter value. Sure, add me to that slack channel, that'd be great.
Email address made public so you can take a look.

**Comment by samrocketman** [comment]
Invite sent.

**Comment by Brantone** [comment]
Received, thx.

**Comment by Brantone** [comment]
Still waiting on merge

**Comment by samrocketman** [comment]
Around the 29th a company is having a hackathon and I asked if they would code review currently open PRs.  So I'm waiting for that.

**Comment by samrocketman** [comment]
Hello, 1.8 has been released. Can you please confirm that this bug is fixed for you?  I'm not sure how to effectively test this.  Can you please provide the steps to test it else confirm that it is fixed for you?

**Comment by Brantone** [comment]
I'll try to carve out some time to give 'er a go as my currently running instance already has the customizations in SNAPSHOT.

Repro:
1. Add new parameter: string
2. Provide name + value, where value = Slack channel name
3. Use `$PARAMETER` in place of Slack channel name
4. Run job and watch for result in Slack channel

**Comment by samrocketman** [comment]
Ah thanks, I'll try it out with a parameter :)
