### ISSUE TITLE
Global-level test-connection succeeds, but token required in project settings for posting to work

### ISSUE THREAD

**Issue by briantd** [jenkinsci/slack-plugin#311]
I'm experiencing a confounding issue where adding my slack token to the Project-level slack settings is mandatory.  No other Project-level slack settings are required for my integration to work.

I verified that the SAME token is used for both the Global and Project-level settings; and pressing the Test-Connection button for the Global-level settings (with token) in the System Configuration yields success.  Yet if I then remove the token from the Project-level settings, building the project no longer posts to the channel.

Jenkins ver. 2.32.2
Plugin ver. 2.2

**Comment by zushane** [comment]
Do you have "Is Bot User?" checked in the Global Lack Notifier Settings section of the system configuration? I had the same issue, until I unchecked that.

**Comment by bblondin** [comment]
I have the same issue...
It only works if I expose the token and if 'is bot user' is NOT checked. 

The test connection works with or without 'is bot user' checked

Jenkins ver. 2.46.2
Plugin ver. 2.2

**Comment by bblondin** [comment]
I downgraded the plugin version to 2.1 and everything is working as it should. Looks like an issue in version 2.2

**Comment by dach384** [comment]
Same here. I downgraded the plugin version from 2.2 to 2.1 and everything is working as it should.

**Comment by timja** [comment]
Bot user requires a separate slack app to be installed, its a bit complicated I'm seeing if slack will add it to the main app, but this is working fine in my experience...
