### ISSUE TITLE
Outdated README and Failure all the time (2.2 version)

### ISSUE THREAD

**Issue by cigano** [jenkinsci/slack-plugin#312]
I'm trying to configure Jenkins with Slack. The README image is:

![README](https://cloud.githubusercontent.com/assets/983526/17971458/ec296bf6-6aa8-11e6-8d19-06d9f1c9d611.png)

My actual is:

![Actual](https://cloud.githubusercontent.com/assets/1513436/24926803/719214b4-1ec2-11e7-9cd0-a7186ca8be24.png)

I tried other combinations, [tried this](https://github.com/jenkinsci/slack-plugin/issues/149#issuecomment-179881978) and no deal. I always have this simple and annoying "Failure" message.

**Comment by mordocai** [comment]
I saw this same issue and got it working by leaving base URL blank and otherwise having things like you do. Might try that if you haven't.

**Comment by CptDaniel** [comment]
I have this bug as well. I tried it with leaving the base URL blank, but it still doesn't work. I either get
`Slack post may have failed. Response: No hooks` when leaving the URL blank or
`Error posting to Slack
java.lang.IllegalStateException: Target host is null` when i put anything in it.

**Comment by eder7** [comment]
I have the same problem. Is there no workaround yet?

**Comment by CptDaniel** [comment]
The only "workaround" I'm aware is to go the old way by sending a message to a Slack incoming webhook instead.

**Comment by eder7** [comment]
Thanks for your answer @CptDaniel, but where do I put it in the configuration? There is just an `Outgoing Webhook Endpoint` in the system configuration...

**Comment by miketwenty1** [comment]
@cigano did you find a answer to your issue?  I'm running into the same thing.

**Comment by cigano** [comment]
Not yet. I'm not using Slack Integration in my Jenkins for now.

**Comment by yuriib** [comment]
Was dealing with the same issue. So I've found simple workaround (for integration with slack.com. Didn't check for other systems):

1. You need to specify direct URL for notifications in Jenkins for your slack system
Base URL - https://your-sub-domain.slack.com/services/hooks/jenkins-ci/
2. Populate other required fields (Team Subdomain, Integration Token, Chanel)
3. Click **Test Connection** button

After following this steps you may solve the issue

**Comment by CptDaniel** [comment]
WOW. It worked!!! Thank you very much.

**Comment by drmmr763** [comment]
had the same issues with this not working exactly as the documentation seemed to suggest it should. I finally got the global configuration working like this:

- BaseURL: EMPTY (this was the most important thing!)
- team domain: sub domain for your slack account ( should be `example` in `http://example.slack.com`
- integration token: EMPTY
- integration token credential ID: create the slack token in the Jenkins CI service, add as a "secret text" type credential in Jenkins
- Channel: default channel

At this point you should be able to successfully use the `test` command in the configuration page.

For my build project pipeline syntax, I have this:

```
 slackSend channel: "#my-channel", color: "good", message: "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"    
```

This will automatically pull the credentials from the global settings and send the message to the specified channel.

**Comment by lbrownell-gpsw** [comment]
The fix by @yuriib worked for me, but with one simple change:  Remove the trailing / in BASE_URL, e.g., https://your-sub-domain.slack.com/services/hooks/jenkins-ci.

What @drmmr763 suggested is how it *should* work, but wasn't for me.  BTW, this is with Jenkins 2.46.2, in case that matters.

Thanks all!

**Comment by markstos** [comment]
Fix by @yuriib worked for me, thanks.

**Comment by oliviamueller** [comment]
Thank you  @yuriib ! Finally worked for me, after hours of despair👍

**Comment by markstos** [comment]
@samrocketman There seems to be consensus here about the problem and a solution. What's the best way to move forward with the fix?

**Comment by samrocketman** [comment]
Hey @markstos, I've been trying to distance myself from maintaining this plugin.  If the fix is known then I'm sure the current maintainers will welcome a PR for the fix.

**Comment by markstos** [comment]
@samrocketman Who are the current maintainers? Most of the most recent commits belong to you.

**Comment by samrocketman** [comment]
Hey @markstos, refer to #320 and #324.  @kmadel and @gurumaia are now comaintainers.  I know I have the most recent commits but I've been encouraging others to take my place.  Sometimes I get a spurt of productivity and step up.

**Comment by gurumaia** [comment]
Hey @markstos I've been trying to step up but my work schedule has been a little cramped since I started maintaining this plugin, so I haven't had a chance to review the open issues. I'll try to take a look at it some time this week. But if you think there is a simple fix and would like to help, go ahead and fork the repo and post a PR with the proposed fix. Thanks!

**Comment by Resisty** [comment]
Hello,

Was this ever fixed? Does anybody have a reliable way to get this plugin to work? None of the workarounds are working for me. I have version 2.3 installed, but the `Test Connection` always fails with a known-good (I use it in an AWS ECS task regularly) integration token.

Here's my job's publisher config:
![screen shot 2018-03-14 at 6 06 14 pm](https://user-images.githubusercontent.com/5331616/37438886-730c02e2-27b2-11e8-9591-6aa0ed6bdaa4.png)

**Comment by jazzycamel** [comment]
Exact same issue as @Resisty 
I'm using plugin version 2.3 with Jenkins 2.107.3, no matter what settings I put where, I always get 'Failure' when testing the connection and no messages when configured jobs run. Any thought/help/alternative setups greatly appreciated.
