### ISSUE TITLE
It would be nice to get rid of `No Tests found` line when using `Custom Message`

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/slack-plugin#313]
Currently, the plugin adds `No Tests found` in the message when Custom Message is being used.

**Comment by dguzmanSM** [comment]
That is true, but you can get arid of it by un checking the options: Include Test Summary and Include Failed Tests, as you if you using custom Message, you should be already passing there the test results, or link to test reporter.

**Comment by timja** [comment]
Closing as solution provided, feel free to reopen if necessary but this hasn't had a lot of attention in 2 years
