### ISSUE TITLE
Update inconsistent documentation

### ISSUE THREAD

**Issue by wheelerlaw** [jenkinsci/slack-plugin#317]
The plugin [wiki page](https://plugins.jenkins.io/slack) is inconsistent with the configuration of the plugin itself.

The wiki:
![image](https://cloud.githubusercontent.com/assets/3081566/25731388/f0ff63f6-3113-11e7-9485-cec2ea5a14c4.png)

The actual plugin:
![image](https://cloud.githubusercontent.com/assets/3081566/25731421/32ceaf1c-3114-11e7-92ea-d97dad5100ee.png)

A better guide for setting up the plugin would be great.

**Comment by cmoscardi** [comment]
+1

**Comment by samrocketman** [comment]
Yeah, I agree.  In general, this whole plugin is a mess without much direction and I don't have the time to dedicate what it needs for an overhaul.  Contributions are welcome or if you're interested in becoming a maintainer let me know.

**Comment by timja** [comment]
wiki has been emptied, and pointed to the readme here which should be up to date
