### ISSUE TITLE
[Updated] Base URL not correctly set in certain situations

### ISSUE THREAD

**Issue by cmoscardi** [jenkinsci/slack-plugin#318]
Working on a standard slack channel with the latest versions, I am able to successfully test* but then receive no notification upon build success, failure, etc. (any configuration of notification does not go through)

Jenkins version: 2.46.1
Plugin version: 2.2

Notably, I do see 
```
May 09, 2017 9:07:52 PM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
```
in jenkins.log

Let me know what other information I can provide and happy to poke around.

*although I have to have _both_ the jenkins credentials and the raw string token set? Setting just the credentials leads to "success" but it's clearly not actually hitting the API (and I see no confirmation in the channel), and setting just the raw string leads to "failure".

**Comment by cmoscardi** [comment]
Ah. Figured it out by upping the log level. Without setting a base URL, like the test correctly posts as follows:
```
https://thedataincubator.slack.com/services/hooks/jenkins-ci?token=[token]: Slack/Jenkins plugin: you're all set on https://107.170.64.246/ good
```

However, the live test notification gets posted as:
```
https://slack.com/api/chat.postMessage?token=[token]&channel=data-incubator-builds&link_names=1&as_user=true&attachments=%5B%7B%22fallback%22%3A%22datacourse-image+-+%2331+Started+by+user+Christian+Moscardi+%28%3Chttps%3A%2F%2F107.170.64.246%2Fjob%2Fdatacourse-image%2F31%2Fdisplay%2Fredirect%7COpen%3E%29%22%2C%22text%22%3A%22datacourse-image+-+%2331+Started+by+user+Christian+Moscardi+%28%3Chttps%3A%2F%2F107.170.64.246%2Fjob%2Fdatacourse-image%2F31%2Fdisplay%2Fredirect%7COpen%3E%29%22%2C%22color%22%3A%22danger%22%2C%22mrkdwn_in%22%3A%5B%22pretext%22%2C%22text%22%2C%22fields%22%5D%7D%5D
```
And then, when I do set a BASE_URL, we're back to a good state:
```
Posting: to data-incubator-builds on thedataincubator using https://thedataincubator.slack.com/services/hooks/jenkins-ci/[token]: datacourse-image - #32 Started by user Christian Moscardi (<https://107.170.64.246/job/datacourse-image/32/display/redirect|Open>) danger
```

**Comment by cmoscardi** [comment]
Additionally, setting the BASE_URL negates the need for the raw string token, and using jenkins credentials is fine. So the specific bug seems to be that BASE_URL doesn't get set appropriately in certain situations.

**Comment by PH-F** [comment]
I have the same issue, the tests work fine, but no build status appears in slack.
Do i need to create a hook in slack to receive there notifiations?
