### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nykolaslima** [jenkinsci/slack-plugin#32]
There is no documentation about how to use this?

**Comment by samrocketman** [comment]
Slack provides integration documentation at https://my.slack.com/services/new/jenkins-ci which details how to use this plugin and configure it.  For now, that's the only documentation.  Feel free to contribute a wiki page to wiki.jenkins-ci.org.  I'm going to go ahead and close this issue.

I don't develop this plugin.  I only maintain pull requests and releases from now on.
