### ISSUE TITLE
Feature request: More logging in case of connection failures.

### ISSUE THREAD

**Issue by andrewspiers** [jenkinsci/slack-plugin#325]
I am trying to use version 2.2 of the Slack Plugin, with Jenkins 2.46.3.

The connection test fails. In the Jenkins logs, I can see that slack is returning a 404, and the whole response is also sent.

I cannot see exactly which URL the plugin is calling.
I cannot see the request headers that are sent.

Would it be possible to log these in the case of a connection error?

**Comment by prachikhadke** [comment]
I am also hitting this issue.

**Comment by jstoja** [comment]
Here I get a 302, no idea what's wrong...

**Comment by andrewspiers** [comment]
I meant to add, this plugin can actually log what it sends. I couldn't see these log messages in jenkins' logs of standard out. I did manage to get the logs viewable by configuring logging specifically for this plugin, from within Jenkins.

**Comment by timja** [comment]
Logging has been improved
