### ISSUE TITLE
currentBuild.durationString includes "and counting" in pipeline

### ISSUE THREAD

**Issue by echatman** [jenkinsci/slack-plugin#327]
I have this in my Jenkinsfile:
```groovy
    post {
        always {
            slackSend(channel: "...", message: "${env.JOB_NAME} [${currentBuild.displayName}] ${currentBuild.currentResult} after ${currentBuild.durationString} (<${currentBuild.absoluteUrl}|Open>)")
        }
    }
```

But the `currentBuild.durationString` always ends with "and counting", so the final notification looks like:

> jobName [buildName] SUCCESS after 1 min 29 sec and counting (Open)

**Comment by tnguyen14** [comment]
I'm seeing this issue as well. Is there a way to fix it?

**Comment by echatman** [comment]
Here's my workaround: `${currentBuild.durationString.replace(' and counting', '')}`

**Comment by pfink** [comment]
Btw, this is quite a wrong place to address this issue, as the slack plugin has nothing to do with this environment variable and its contents.

**Comment by timja** [comment]
^

**Comment by apeteri** [comment]
A small counterpoint: the HipChat notification plugin fixed this within their component.
https://issues.jenkins-ci.org/browse/JENKINS-40461

As the build is technically still running when notifications are sent, I don't think that it can be expected that the duration string message will be changed higher up the chain.

**Comment by spkane** [comment]
> `${currentBuild.durationString.replace(' and counting', '')}`

`${currentBuild.durationString.minus(' and counting')}`

is another more direct option to workaround this issue.

**Comment by NBZ4live** [comment]
Here another workaround:

```
import hudson.Util;
def buildDurationString = Util.getTimeSpanString(currentBuild.duration)
```

**Comment by e-boudhina** [comment]
Much appreciated, still useful even today.
