### ISSUE TITLE
Documentation of option "Base URL" is cryptic

### ISSUE THREAD

**Issue by tobilarscheid** [jenkinsci/slack-plugin#328]
Hi,

I feel like the help text for the base URL defined [here](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/webapp/help-projectConfig-slackBaseUrl.html) is pretty cryptic - in fact I don't have a clue what I can do with the Base URL. I left it empty now and the plugin seems to work okay. If anyone could provide a hint on what it really is for, I would be happy to provide a PR to update the help text.

Regards,

Tobi

**Comment by tobilarscheid** [comment]
Alright, figured out what it's for +1

**Comment by tsal** [comment]
We need a definitive, central answer for the configuration - I've seen two different responses on what base URL is for, and whether it should be set.  The plugin simply does NOT work as documented.
