### ISSUE TITLE
notify user instead of channel

### ISSUE THREAD

**Issue by jdeniau** [jenkinsci/slack-plugin#330]
Hi, 

Is it possible to notify only a user instead of a channel ? (this way we can notify the commiter of the project only instead of all channel)

**Comment by ericparton** [comment]
I'm interested in this as well; it would be really useful to be able to send notifications to the "culprits" like the old [instant messaging plugins](https://wiki.jenkins.io/display/JENKINS/Instant+Messaging+Plugin).

**Comment by puckel** [comment]
Hi,

You can notify user using `channel: '@user.name` instead of `channel: '#chan`

**Comment by michelene** [comment]
I tried using `@user` in a Freestyle job and it failed.

**Comment by timja** [comment]
@username or @<slack-user-id> will work

**Comment by froblesmartin** [comment]
I have been testing it, it works for users that doesn't have a space in it's username, but not for those who have :disappointed:

**Comment by timja** [comment]
use the slack member id, that will always work

**Comment by HolyxReid** [comment]
@<slack-user-id> implies you already have the slack user id, what if we want to use the one saved in the jenkins user profile
![Screenshot from 2019-12-20 15-38-07](https://user-images.githubusercontent.com/1293033/71261930-dd8a6300-233e-11ea-9a54-c41f13cecdaa.png) 
Is it possible to retrieve the slack userid from the person who started the build in a declarative pipe ?

**Comment by sshepel** [comment]
@timja but there is no way to get `slack-user-id` dynamically via plugin, am I right? 
And when you have username with white space pipeline step sends notification only to first part of the name (ex. @User Name).

**Comment by timja** [comment]
You can look it up via email by selecting a resolver and using a bot user,
this is built in: https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/user/EmailSlackUserIdResolver.java

https://github.com/jenkinsci/slack-plugin#bot-user-mode

**Comment by zyf0330** [comment]
Is there a plan to support username within space?

**Comment by dizeee** [comment]
In my case it kind of works, but only with user's full name, not display name, and the plugin still reports an error. Here's my code:
```
slackSend(
  color: '#439FE0',
  message: 'Hey there!',
  teamDomain: 'mydomain',
  tokenCredentialId: 'slack-creds-id',
  channel: '@Full Name'
)
```
I get the message in Slack, but also this error appears in pipeline log:
```
ERROR: Slack notification failed. See Jenkins logs for details.
```
And this in Jenkins log:
```
Jul 29, 2020 3:50:34 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null
Jul 29, 2020 3:50:34 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 400
```
