### ISSUE TITLE
Build status for plugin is Unknown now

### ISSUE THREAD

**Issue by vkotovv** [jenkinsci/slack-plugin#331]
Looks like the badge in Readme shows Unknown, because [this page](https://jenkins.ci.cloudbees.com/job/plugins/job/slack-plugin/) says:
```This project is currently disabled```

And [here](https://jenkins.ci.cloudbees.com/job/plugins/) is stated that Cloudbees CI for plugins is deprecated, now https://ci.jenkins.io/job/Plugins/ should be used. Project needs `Jenkinsfile` for this.

**Comment by timja** [comment]
fixed
