### ISSUE TITLE
Notify failure not working

### ISSUE THREAD

**Issue by yuri-wisestamp** [jenkinsci/slack-plugin#335]
Only the Notify Start is sending a notification to the channel. Notification for failure is not working.

**Comment by dennisjac** [comment]
I'm having the same problem. I can get an abort notification but failure notifications don't seem to work.

**Comment by AnneTheAgile** [comment]
did you all get it working? it works for me.

**Comment by yuri-wisestamp** [comment]
Hi guys,

forgot to update. To remedy this issue you need to config the plugin to notify you of failures as well (why isn't this the default? I don't know).

Go to your project configuration, scroll down to **Post-build actions**, expand the Slack section if needed, and check the *Notify failure*, like here:
![Config screen](https://user-images.githubusercontent.com/5073294/31650846-ee512dc0-b321-11e7-8551-88499ba7f837.png)

This is configured to notify only of success and failure. Hope it helps.
