### ISSUE TITLE
mvn hpi:run not installing plugin, bumping Jenkins version then hangs at ACL.impersonate.

### ISSUE THREAD

**Issue by eyelock** [jenkinsci/slack-plugin#336]
Hi,

I'm having a bash at Threaded Messages for the pipeline `slackSend` step https://github.com/jenkinsci/slack-plugin/issues/279 over at [1].

When I run `mvnDebug hpi:run` (or `mvn hpi:run`) the local plugin does not get installed as the Pipeline plugins require version 1.609.3.   I've bumped the version in the pom.xml to 1.609.3 (from 1.609.2) which then installs the pipeline plugins and the local slack plugin, but then I hit another problem in both my own branch [1] and the `master` branch.

Debug breakpoints are hit up until the call to `getHttpClient()` in the `StandardSlackService`.

From the build() call I can trace it down to `hudson.security.ACL` [3] (the `1.609.3` version) and then it just hangs.  Is this normal or experienced by anyone else for the method of debugging I am trying to use?

Thanks for help, first time looking to contribute/develop Jenkins plugin so all help welcome.

Cheers -- David

[1] https://github.com/jenkinsci/slack-plugin/compare/master...eyelock:feature/slack-notifier-threaded-messages
[2] https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L190
[3] http://javadoc.jenkins-ci.org/hudson/security/ACL.html#impersonate-org.acegisecurity.Authentication-

**Comment by eyelock** [comment]
Should note pausing the thread shows it parked in the Unsafe.park method.

**Comment by timja** [comment]
Old pom file version I assume, fixed now
