### ISSUE TITLE
Groovy scripts integration for custom message

### ISSUE THREAD

**Issue by AlexTalker** [jenkinsci/slack-plugin#337]
It would be totally cool if you integrate support of $SCRIPT as email-ext-plugin uses it
https://github.com/jenkinsci/email-ext-plugin
Even better would be if directories to search for groovy-based templates would be supported with compatibility to it(i.e. fallback to search path of the plugin if not found in our own dirs).
This will make customization very cool and totally replace email usage with slack 😄

**Comment by timja** [comment]
Token macro plugin support was added in 2.4
That may help with what you wanted?
