### ISSUE TITLE
Support for messaging individual users

### ISSUE THREAD

**Issue by agis-** [jenkinsci/slack-plugin#34]
When configuring the Slack integration, you can select particular users instead of channels. But this option is not anywhere in the Jenkins plugin configuration. Is it supported at all? If so, how is it used?

I've tried `<username>` & `@<username>` on the *Project Channel* setting but none of them worked (ie. no messages at all posted).

**Comment by samrocketman** [comment]
I don't actively develop this plugin.  I maintain pull requests and releases from now on.  Please feel free to contribute this feature!

**Comment by peergum** [comment]
`@username` should work in Project Channel. If several usernames are required, separate them with commas.

**Comment by samrocketman** [comment]
Next time I spin up my VM I'll test this.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by agis-** [comment]
`@<username>` indeed works. Thanks @peergum
