### ISSUE TITLE
bot user (chat.postMessage) channel name issue

### ISSUE THREAD

**Issue by bendenoz** [jenkinsci/slack-plugin#340]
Hi,

Have been having issue setting up the plugin with a bot token.

The issue is that the channel name is not escaped in the api call query string, so 

Channel: `#general` will fail

However `general` or `%23general` does work

/Benjamin

**Comment by joh-m** [comment]
have the same issue, you cannot change from webhook to bot user without changing your pipeline config. would be great if the plugin could just strip the hash character when acting as a bot user

**Comment by timja** [comment]
PRs welcome
