### ISSUE TITLE
What is the correct way to format a newline?

### ISSUE THREAD

**Issue by phillipjohnston** [jenkinsci/slack-plugin#343]
\n seems to cause my Jenkins pipeline job to fail and <br> gets rendered as text. How can I insert a new line into my slack message?

**Comment by timja** [comment]
Use a groovy multiline string:

```
slackSend channel: '#slack-plugin-testing', message: '''Hello
what's up
hi
'''
```

**Comment by AntoniusGolly** [comment]
What if the message shall contain variables?

**Comment by casz** [comment]
Use triple double quotes
```
slackSend channel: '#slack-plugin-testing', message: """Hello
what's up
hi
"""
```
