### ISSUE TITLE
Missing required parameter: "message"

### ISSUE THREAD

**Issue by tnguyen14** [jenkinsci/slack-plugin#351]
I followed the instructions on the README to send a slack notification from a declarative pipeline as such:

```
slackSend(channel: '#bots', attachments: getSlack(currentBuild).toString())
```
However, I got the following error from Jenkins
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 136: Missing required parameter: "message" @ line 136, column 4.
```

I am using version 2.3

**Comment by timja** [comment]
I assume this is because `message` is in the `DataboundContructor` which means it is mandatory, just needs moving from there, should be an easy fix
