### ISSUE TITLE
slackSend @mention not working as part of message

### ISSUE THREAD

**Issue by davetobin** [jenkinsci/slack-plugin#353]
When @ mentioning in a message using slackSend in a Jenkins Pipeline script, the mention `@<slackUsername>` only appears as plain text in the Slack notification. I previously provided @ mentions as part of "Custom Message" in an old style Jenkins job and it worked but does not seem to work with `slackSend`. Any ideas or does this just not work?

Example of what I'm trying to do:
```
slackSend ( message: 'I want to mention this @user as part of message', teamDomain: '<teamDomain>', token: '<token>', channel: '<channel>' )
```

**Comment by hexsel** [comment]
We also use this to notify the channel as high priority (using \@channel or \@here), I think the \@ symbol is getting escaped and it shouldn't...

**Comment by caylorme** [comment]
The slack API requires you to convert the user, group, or channel name into an ID before creating a formatted link in your message. 
https://api.slack.com/docs/message-formatting#linking_to_channels_and_users

That being said, the slack API also provides a way of automatically parsing these messages if you set a particular parameter in the request. See **Parsing Modes** from the previous link.

I think this relates to the following issue: https://github.com/jenkinsci/slack-plugin/issues/367
If we added the ability to set supported or arbitrary arguments to the final request to Slack, we could enable full parsing mode to support this.

**Comment by vanta** [comment]
`@here` works fine for me.

**Comment by ndh103** [comment]
Any update on this? I can see @here work but not for a specific user :)

**Comment by timja** [comment]
To notify a specific user you need to use their slack ID and enter it in this format:
`<@UET1JGZEZ>`

```
slackSend channel: '#tim-testing', message: '''<@UET1JGZEZ>
what's up
hi
'''
```

Auto parsing support to be tracked in: https://github.com/jenkinsci/slack-plugin/issues/367
