### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sjqnn** [jenkinsci/slack-plugin#354]
Documentation in the jenkins wiki doesnt match current global configuration options using latest version of the plugin(2.3). Also the terminology in the configuration options of the plugin doesn't match the current incoming webhook slack app documentation at all. It's very unclear how this plugin is actually supposed to be configured or used.

**Comment by ThomasWunderlich** [comment]
There's actually a few places where the documentation needs to be updated
1) In slack, when creating the Jenkins integration the documentation is outdated. Do the current maintainers have access to change that?
2) In the github README
3) In the Jenkins plugin page
3) In the descriptions added to Jenkins (ie when you click the ? icon)

I'd be willing to help improve the documentation. Would the best way be to update the README? Does that get automatically synced to the plugin wiki page?

**Comment by sjqnn** [comment]
@ThomasWunderlich considering they're out of sync, probably not 😞

**Comment by atrauzzi** [comment]
The state of the documentation in this git repo, the readme for the jenkins plugin and also inline with the plugin is horrible.

**Comment by dharkness** [comment]
Has anyone gotten the 2.3 plugin to work? The global settings ask for an *Outgoing* Webhook Token and Endpoint URL. I tried using the built-in Slack Jenkins CI app and configured Jenkins with the Token and Endpoint URL, but I get no messages. Note that Slack does not refer to these as Outgoing Webhooks AFAICT. 

So I created an *Incoming* Webhook URL in Slack, but that doesn't require a separate token and URL. I tried splitting the URL in Jenkins, but I still get no messages in Slack.

**Comment by timja** [comment]
I would like to:
1. bin the wiki documentation, confluence is too slow to be usable, editing is the worst
2. fixup any issues with readme docs
3. reach out to slack about updating their app config

Closing this issue out in favour of pull requests for docs updates
