### ISSUE TITLE
Option to Notify on "back to unstable" builds

### ISSUE THREAD

**Issue by apkatsikas** [jenkinsci/slack-plugin#355]
When a build goes from red -> yellow, would like an option to notify on this event, as "Back to Unstable". Was considering writing this myself and doing a PR if the team thinks this would be a worthy feature to incorporate. Consider this Issue an inquiry to openness to include this if I build it.

**Comment by zayass** [comment]
I think an option like this should be available.
Maybe naming can be better. But notification about build not more "red" is important.
At least in "Advanced" section

**Comment by timja** [comment]
There's too many options imo, use pipeline for advanced control
