### ISSUE TITLE
Choose What Channel to Post

### ISSUE THREAD

**Issue by GeorgeLopes** [jenkinsci/slack-plugin#358]
Hi Guys,

Thanks for the plugin, but i have one problem.

My team deploy a lot, and we are using the same channel on slack to monitoring errors on applications, systems and pipeline process from jenkins.

Have some method to choose if error or another thing occurs than send to channel B, if everything goes fine than channel A?

Thanks again for the great work

**Comment by kmadel** [comment]
Use Pipelines and then add some logic to set the channel accordingly.
