### ISSUE TITLE
Custom Message to accept user defined variables

### ISSUE THREAD

**Issue by navinjoy** [jenkinsci/slack-plugin#359]
In the Jenkins build script I am exporting some data into a variable and want to use the value of that in Slack Custom Message but thats not working.

Ex:

Build script:
`export myVar=hello`

Slack Custom Message:
`Your message is : $myVar`

I can include jenkins env variables though...like... $BUILD_URL #

**Comment by navinjoy** [comment]
closing this issue, found an alternative way to handle this.

**Comment by twall** [comment]
@navinjoy care to elaborate?

**Comment by ondrej-fabry** [comment]
And @navinjoy was never seen again.. _sigh_

**Comment by yuri-karpovich** [comment]
> closing this issue, found an alternative way to handle this.

Can you share?

**Comment by dooleyb1** [comment]
Also looking for a solution to this, anyone solve?

**Comment by xMort** [comment]
I solved it via [EnvInject](https://plugins.jenkins.io/envinject) plugin. Hopefully, you can use it in your setup.

First, I perform my build steps. Then in the dedicated shell builder, I write necessary data for custom notification text into the temporary file in the job workspace in the format of the key=value. 

Next, I will use `inject` builder (from the plugin linked above) to inject content of the temporary file to the environment variables of the job (you can find values of these variables with rest of the variables in _Environment variables_ tab of the job in Jenkins after it finishes). 

I can then access the variables from the file in the Slack's custom notification text parameter.

```
- job-template: my-job-template
    name: '{folder}/{library}'
    ..other job properties
    builders:
        - checkout
		...some other build steps
        - shell: |
            ...some shell code
            FIRST_PROPERTY="some data from the processed job"
            SECOND_PROPERTY="some other data from the processed job"

            echo FIRST_PROPERTY=$(echo $FIRST_PROPERTY) >> $WORKSPACE/my-vars.properties
            echo SECOND_PROPERTY=$(echo $SECOND_PROPERTY) >> $WORKSPACE/my-vars.properties
        - inject:
              properties-file: $WORKSPACE/my-vars.properties
    publishers:
        - slack:
              room: '#my-slack-room'
              notify-success: true
              include-custom-message: true
              custom-message: 'The content of $FIRST_PROPERTY and $SECOND_PROPERTY'
```

**Comment by ArvinB** [comment]
This does work for single lines, but for multiline environment variables using `Envinject` you have to have `/n/` at the end of each line and what really doesn't work is if your line has leading spaces. This gets trimmed off. So if you custom message were to include a formatted xml or json or yaml then this doesn't work very well.
