### ISSUE TITLE
build notifications have hyperlinks to the specific build console output

### ISSUE THREAD

**Issue by sharmavipul** [jenkinsci/slack-plugin#36]

**Comment by samrocketman** [comment]
Can you elaborate?  Your title isn't very descriptive.  What issue do you have?  Please provide the expected vs witnessed behavior.

**Comment by samrocketman** [comment]
Also, please provide all of the version numbers of the software (Jenkins version, slack plugin version, etc).

I don't actively develop this plugin.  I will be maintaining pull requests and releases from now on.

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released. This a fix for this has been included in it. Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.
