### ISSUE TITLE
Feature: Custom messages for success and failure

### ISSUE THREAD

**Issue by victor-accarini** [jenkinsci/slack-plugin#360]
Hi,

I would like to add a different custom message when my build fails or succeeds. As far as I know I can set a custom message that will be show in all cases.

I made something that works the way I want in victor-accarini/slack-plugin, but I would like a feedback from you guys since I'm not a Java dev.

Thanks!

PS: @gurumaia Are you still maintaining this plugin?

**Comment by nhathy** [comment]
Possibly fixed in #169
