### ISSUE TITLE
Is there an option to specify a JSON or XML file path?

### ISSUE THREAD

**Issue by z-ax** [jenkinsci/slack-plugin#363]
Want to generate custom JSON file for Slack message with attachments etc based on tests results to not follow the link every time to check what's going on. Didn't find it anywhere in docs.

Pretty much the same as for jUnit:
```
      post {
        always {
            junit 'test-report-junit.xml'
        }
        failure {
          slackSend 'test-report.json'
        }
      }
```

**Comment by timja** [comment]
I don't think this feature makes sense, closing in favour of:
https://github.com/jenkinsci/slack-plugin/issues/387

which would simplify the api for attachments
