### ISSUE TITLE
Ability to pass optional arguments to slack API's chat.PostMessage

### ISSUE THREAD

**Issue by caylorme** [jenkinsci/slack-plugin#367]
The following link shows additional arguments that can be passed to the slack API's chat.postMessage method that can modify it's behavior.
https://api.slack.com/methods/chat.postMessage

As an example, I'd like to be able to enable the `parse` and `link_names` options so that I do not  have to have pre-defined ID's of users, groups, and channels.

I'm currently using the slackSend DSL method.

**Comment by thangbn** [comment]
any update on this?

**Comment by timja** [comment]
Most parameters are now possible, closing in favour of issues / PRs for specific options

**Comment by AnotherStream** [comment]
How do you specifically set `parse = full` or` link_names = 1` in slackSend step?
The link will be correct for @UserId, but @UserName will be posted as a string as it is.

I checked ReadMe.md of slackSend step plugin api, but there is a description that @UserName is parsed correctly as well as @UserId.

**Comment by lukiszlak** [comment]
@AnotherStream Did you figured it out? Because im struggling with the same issue.
I want to mention user who started the job via Build User Vars Plugin but without link_names = 1 or parse set to full it's not possible
