### ISSUE TITLE
Jenkins CI not posting Build failure to slack

### ISSUE THREAD

**Issue by VenkatTMN** [jenkinsci/slack-plugin#368]
I have installed Jenkins plugin to my slack channel and slack notification plugin to my Jenkins. In the Global Slack notification setting, i have enabled 
'Notify Build Start'
'Notify Failure'
'Notify Success'
Here the problem is i always get 'success' message to my slack even the build fails and this make me to check the deployment statues every time after the build is done. 

I want 'Failure' message sent to my slack channel when the build fails. Please help me with this issue. Thanks

**Comment by EverardoCamacho** [comment]
Are you checking off "Notify Repeated Failure" under the Advanced settings?

**Comment by VenkatTMN** [comment]
Yes i have checked off "Notify Repeated Failure". but still the same.. i'm still getting the success message to slack even the build fails.


![capture](https://user-images.githubusercontent.com/36542223/36694204-a36b7a52-1b0b-11e8-89d4-72adf9a4a498.PNG)

**Comment by VenkatTMN** [comment]
This is how i'm getting Success message for the failure build.

![capture](https://user-images.githubusercontent.com/36542223/36694457-79d3105a-1b0c-11e8-95b8-c03f8f175387.PNG)

**Comment by evilDave** [comment]
I am having a similar problem, I have boxes checked for "Notify Failure" and "Notify Success", but I only get messages for success, not for failure. This did work when first set up, but now it doesn't any more. I have tried checking "Notify Repeated Failure" (which I do not actually want) but it makes no difference. Jenkins 2.112, Plugin 2.3

**Comment by cauvery** [comment]
Having the same issue. Not getting the slack messages for build failure.

**Comment by colbygk** [comment]
Also seeing this issue.

**Comment by prashanth-sams** [comment]
check if the settings are appropriate as mentioned in my post (it works for me)
https://devopsqa.wordpress.com/2018/07/10/jenkins-slack-notifiers/
For DSL try:
https://devopsqa.wordpress.com/2018/07/10/dsl-jenkins-slack-notifiers/

**Comment by kitfit-dave** [comment]
I have solved the problem in my case by removing the slack integration and adding it back again.

**Comment by evilDave** [comment]
I was able to solve he problem in my case by removing and adding again the Slack integration.

**Comment by timja** [comment]
should work fine as mentioned by others, please create a new issue showing your global and job config if not
