### ISSUE TITLE
Don't make 2 messages for 1 build when outputting committers

### ISSUE THREAD

**Issue by glajchs** [jenkinsci/slack-plugin#376]
![image](https://user-images.githubusercontent.com/2104019/41045360-440e2a3c-6976-11e8-913d-14e3d9d22da2.png)

This is annoying, makes it hard to read through the various builds, and is unnecessary.  These messages should be bundled into 1 slack message, not 2.

See `https://github.com/jenkinsci/slack-plugin/blob/9c57909027c04261417d984dd87e8184012062ac/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L108`

**Comment by kenji21** [comment]
My commit do this, I can send a PR if it looks good to maintainer

**Comment by glajchs** [comment]
I ended up forking and doing something similar kenji...but then I added some more stuff specific to our use cases.  Your change looks pretty clean and simple.  I'd vote for making it at PR!

**Comment by timja** [comment]
feel free to PR this @kenji21  looks good

**Comment by kenji21** [comment]
Just sent PR https://github.com/jenkinsci/slack-plugin/pull/448 with updated code to current master

**Comment by timja** [comment]
Closed in https://github.com/jenkinsci/slack-plugin/pull/448
