### ISSUE TITLE
Optional based on build parameter

### ISSUE THREAD

**Issue by dwelch2344** [jenkinsci/slack-plugin#38]
We've got Jenkins setup to deploy to a "dev" lane when an option boolean is checked. It'd be nice if we could set notifications to only happen when that checkbox is toggled.

**Comment by samrocketman** [comment]
If the slack plugin worked with the flexible publish plugin then this would be easy.  See and follow #41.

**Comment by samrocketman** [comment]
Since a contribution in #41 would resolve this I'm going to close this open issue.  Feel free to subscribe to #41 for any updates.

I do not actively develop this plugin.  I will be maintaining pull requests and releases from now on.
