### ISSUE TITLE
Inappropriate overwriting of "Integration Token Credential ID" by non administrator

### ISSUE THREAD

**Issue by aviscaerulea** [jenkinsci/slack-plugin#381]
1. Set the Integration Token Credential ID to Credential as a user with administrator authority
2. User with non-Administrator authority does not display Integration Token Credential ID.
3. A user with non-Administrator authority updates the job
4. The Integration Token Credential ID is overwritten with "None" and Slack notification will fail

My environment:
  Jenkins 2.89.4
  Slack Notification Plugin 2.3

**Comment by kmadel** [comment]
Fix per #372
