### ISSUE TITLE
Sometimes don't see test summary in Slack (with an amount of failed, passed and skipped tests)

### ISSUE THREAD

**Issue by tdurova** [jenkinsci/slack-plugin#382]
![scheenshot1](https://user-images.githubusercontent.com/13066866/41906262-ba63a712-793d-11e8-9911-4e42831a0cd9.jpg)
See screenshot. There is short info with an amount of failed/passed tests. But the same job with the same configuration in next runs after did not have such section in slack. What is the difference? I would like to have this summary for each run.

**Comment by timja** [comment]
is this still an issue?

**Comment by timja** [comment]
This is quite old, code released at this time was from 2017 I believe, if this is still an issue please comment here with more details / how to reproduce or open a new issue

**Comment by Impinku** [comment]
@timja @tdurova  I am still facing same issue, If you have a proper solution please let me know here.
