### ISSUE TITLE
Slack Build Failure notification not working

### ISSUE THREAD

**Issue by Mohitg06** [jenkinsci/slack-plugin#386]
Here is my issue:
I do not see any notification when my build fails.
Its a freestyle Jenkins project. 

I do get  slack notification for build start.

I am using Master  and worker  configuration with Docker.

is it possible that slack is not getting notifications from worker ?

**Comment by jasonbarnett667** [comment]
Is it possible you have some post-build actions that are failing before the notification goes out? I have seen that cause the notifications to not trigger.

**Comment by Mohitg06** [comment]
hmm, my post build notifications are working ..

**Comment by glebsts** [comment]
any solution to that? I have same problem with success notifications appearing and failure missing.

**Comment by jasonbarnett667** [comment]
You basically need to change the order, ie send notifications first and then do any other actions after.
