### ISSUE TITLE
Attachments should take Groovy objects and convert to JSON internally

### ISSUE THREAD

**Issue by bertjwregeer** [jenkinsci/slack-plugin#387]
Due to security, using `JsonBuilder` is something that an admin has to whitelist, however if it was built into the slackSend step to automatically convert groovy lists/maps into JSON itself then admins wouldn't need to get involved, and there would be no issue with `NonCPS` because `JsonBuilder` is not serializable.

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/slack-plugin/pull/536
