### ISSUE TITLE
message is ignored when attachments are present

### ISSUE THREAD

**Issue by chrylis** [jenkinsci/slack-plugin#389]
The Slack API supports passing a top-level `text` field (corresponding to `step.message`) even when attachments are provided; this is printed as a sort of header above the attachments (in contrast to `pretext` included in each attachment individually). However, when `step.attachments` is provided, `step.message` is ignored except to provide a `fallback` if not already set. It should be transmitted along with the attachments if both are provided.

**Comment by timja** [comment]
This what you were after?
https://github.com/jenkinsci/slack-plugin/pull/426

**Comment by chrylis** [comment]
I think so, thanks!
