### ISSUE TITLE
Messages are being truncated again.

### ISSUE THREAD

**Issue by novas0x2a** [jenkinsci/slack-plugin#390]
commit a9685813df28747cc044ea57a5a1dd9c22c3b4e7 silently reverted the fix (no mention in commit message, no mention in changelog) from #274 and #292.

**Comment by timja** [comment]
If someone can state a good usecase for this and send a PR we can get this fixed.
But
* Slack recommends you keep messages short and to the point.

4000 characters sounds like a reasonable limitation...

**Comment by timja** [comment]
probably fixed by https://github.com/jenkinsci/slack-plugin/pull/426
