### ISSUE TITLE
Customize message

### ISSUE THREAD

**Issue by codebynumbers** [jenkinsci/slack-plugin#4]
It would be cool to allow for customizing the message a bit. Specifically I'd like to include the branch name. But maybe there are other tokens people would include or exclude.

**Comment by jdonaldson10** [comment]
+1 for this. Zapier can work but an out of the box solution would be super helpful

**Comment by samrocketman** [comment]
@mikewoodworth @munkyboy @jmcquillan

#30 provides more info in the build summary such as commits with the author (optional check box in advanced settings).  

Also, from the last snapshot build a link is also included in the build message.

#25 provides the option to include the unit test summary of the build.

All of the above mentioned features will be [released in slack-1.7](https://github.com/jenkinsci/slack-plugin/milestones).

# Still missing

Including the branch name in the slack notifications.

Also, not sure how to provide better customization of the slack notifications.

Contributions are welcome.

**Comment by lfilho** [comment]
+1

**Comment by samrocketman** [comment]
I don't actively develop this plugin. I will be maintaining pull requests and releases from now on. Please feel free to contribute this feature!

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released.  This a fix for this has been included in it.  Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.

**Comment by samrocketman** [comment]
For the remaining requests I have opened a new issue.  #49 is where those still interested can subscribe and put in more detail about how they want the feature to behave.  As always, contributions are welcome because I will not be developing this feature.

**Comment by FaizVisram** [comment]
It would be great to be able to use a custom message; I, personally, want to be able to have a direct download link in Successful messages to specific build artifacts

**Comment by cchar** [comment]
I'd like to see it be able to 'mention' a person with the @username or @channel. I tried it in the custom message, but it doesn't come through as a mention, just plain text.

**Comment by samrocketman** [comment]
@cchar this issue is already closed.  Please feel free to open a new issue so that it can be addressed or contributed as a feature.
