### ISSUE TITLE
Invalid channel specified

### ISSUE THREAD

**Issue by fdstevex** [jenkinsci/slack-plugin#40]
I get this error in my Jenkins log whenever the plugin attempts to send a message to Slack:

Slack post may have failed. Response: Invalid channel specified

I've followed the steps in the setup page and believe everything is as it should be. Team domain and token are set, channel name is blank (tried using 'builds' and '#builds' as well), build server URL is /

Jan 13, 2015 10:34:44 AM WARNING jenkins.plugins.slack.StandardSlackService publish
Slack post may have failed. Response: Invalid channel specified

Not sure if this is a Slack problem or a plugin problem.

**Comment by samrocketman** [comment]
You have to configure a channel for slack to post to.  The exception to that will be in the next release where jobs can contain team, token, and channel overrides.  I'm going to go ahead and close this as invalid.

I do not actively develop this plugin.  I will be maintaining pull requests and releases from now on.

**Comment by fdstevex** [comment]
I did configure a channel to post to; I tried "builds" and "#builds" as well as blank.

Also, the page on Slack that shows instructions on how to configure the Jenkins Slack integration indicates that the channel field is optional.

I still haven't been able to get this to work.

**Comment by samrocketman** [comment]
Then I'll re-open this again.

**Comment by lokling** [comment]
I had the same case now and resolved it by removing the channel setting both on the project and on the global configuration in jenkins.

**Comment by samrocketman** [comment]
Need more information other than "same case" and "doesn't work".  Please provide the versions of sofware you're working in.  Jenkins, Slack Plugin, etc.

**Comment by lokling** [comment]
Yes, sorry - I simply wanted to provide a workaround.

Jenkins ver. 1.598, slack-plugin v 1.2 installed from within jenkins. 

The problems we were seeing with 1.2 was: 
- Error as in original report: "WARNING jenkins.plugins.slack.StandardSlackService publish
Slack post may have failed. Response: Invalid channel specified" 
- Using jenkins UI setting default slack channel, and per job channel to "" ( empty string) made it work, probably leaving channel empty and using the default on slack side.
- We are using Jenkins Groovy DSL to configure jobs, and also discovered the above workaround required "<room></room>" in xml. Not including this setting, or with <room/> there was errors in the plugin (Nullpointer).
- This afternoon I forked and built 1.7-snapshot and that resolved the issue with configuration. 

Let me know if I can help with more information.

**Comment by samrocketman** [comment]
@lokling Your testing with 1.7-snapshot was a great help.  Thank you!

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released.  This a fix for this has been included in it.  Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.

**Comment by tommed** [comment]
This same error is regressing in version 2.0.1.:

1. Install Slack Notification Plugin
2. Configure token, subdomain and build URL as expected
3. Tried #build, build and leaving it blank
4. Test connection returns Failure
5. Log shows:

> Posting: to #build on vigilantapps using https://vigilantapps.slack.com/services/hooks/jenkins-ci?token=XXXXXXXXXXXXXXX: Slack/Jenkins plugin: you're all set on / good
> 
> Apr 21, 2016 5:11:14 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
> 
> Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
> 
> Apr 21, 2016 5:11:14 PM WARNING jenkins.plugins.slack.StandardSlackService publish
> 
> Slack post may have failed. Response: Invalid channel specified

There is no where to place the channel in the project, so previous fix is not applicable.
Please re-open this ticket.

**Comment by samrocketman** [comment]
Have you tried in the post-build settings?  They've moved.

**Comment by tommed** [comment]
Yes, there's still no channels setting in post-build.

I've got it working after a while of just retrying the same settings over and over again?! Possibly stil a bug here through.

**Comment by timja** [comment]
please reopen if still an issue, cleaning up the repo and this looks to be fixed
