### ISSUE TITLE
Wiki says looking for maintainers despite pom.xml properly populated with developers.

### ISSUE THREAD

**Issue by AnneTheAgile** [jenkinsci/slack-plugin#402]
I am not sure which github repo controls the wiki pages? Maybe only the admins see that ? 

The useless overview page is correct since it includes almost zero info. 
https://plugins.jenkins.io/slack

The wiki, which includes changelong and excellent feedback / release info,  is wrong;
This plugin is up for adoption. Want to help improve this plugin? Click here to learn more!
https://wiki.jenkins.io/display/JENKINS/Slack+Plugin

The pom is correct; 
````
      The developers show up as current maintainers in the Jenkins wiki.
      https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin
      The id should be the jenkinsci.org username and not your GitHub username.
    -->
    <developers>
        <developer>
            <id>kmadel</id>
            <name>Kurt Madel</name>
            <email>kmadel@cloudbees.com</email>
            <url>https://github.com/kmadel</url>
            <roles>
                <role>maintainer</role>
            </roles>
            <timezone>America/New_York</timezone>
        </developer>
        <developer>
            <id>gurumaia</id>
            <name>Gustavo Maia</name>
            <email>gurumaia@gmail.com</email>
            <url>https://github.com/gurumaia</url>
            <roles>
                <role>maintainer</role>
            </roles>
            <timezone>America/Sao_Paulo</timezone>
        </developer>
    </developers>
</project>
````

**Comment by timja** [comment]
See https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin
The wiki will have a tag on it,

@kmadel 
@gurumaia 

Are you still maintaining this plugin?

I would be happy to help out on it

**Comment by gurumaia** [comment]
Quite frankly, I haven't been able to give this the attention it deserves.
If anyone is willing and able, I'd be glad to pass along and/or share the duties of maintaining the plugin.

**Comment by timja** [comment]
@gurumaia @kmadel I'd be happy to help co-maintaining this plugin

**Comment by timja** [comment]
@gurumaia @kmadel I've posted on the dev list would you be able to reply please?

**Comment by timja** [comment]
Fixed via https://github.com/jenkinsci/slack-plugin/pull/414 and updating the wiki
