### ISSUE TITLE
Documentation on sending messages directly to slack users unclear

### ISSUE THREAD

**Issue by c1505** [jenkinsci/slack-plugin#409]
Recently I had the need to send messages directly to slack users rather than to a channel and from using the plugin and reading documentation, it wasn't clear that it could be done and how.  

I already opened up a PR with some documentation changes to make it more visible that you can send messages directly to users #408 , but thought opening an issue may be helpful to for the sake of discussion, future discoverability,  and attention to the pull request.

**Comment by timja** [comment]
No need to open an issue and a PR, PR merged anyway
