### ISSUE TITLE
Send slack notification to channel after 5 consecutive build unstable

### ISSUE THREAD

**Issue by sushantlokhande** [jenkinsci/slack-plugin#413]
Requirement: 
In case of more than 5 continuous build unstable we should be able to send notification to slack channel.

How we can achieve this?
Please Help!!

**Comment by timja** [comment]
you can do this with pipeline by looking up the previous builds,
something like
https://stackoverflow.com/a/45777893

but you can't do this with free style builds and unlikely the option would be merged

**Comment by sushantlokhande** [comment]
Hi team,

Thanks for sharing it.. Already implemented it using Groovy scripts..
Code is mentioned below:

import jenkins.model.*;
import hudson.model.*;

manager.listener.logger.print("Job Name - ");
manager.listener.logger.println(manager.build.project.name);

int currentBuildNumber = manager.build.number;
boolean flag=true;
String currentBuildResult = manager.build.result.toString();

manager.listener.logger.print("Current build number - ");
manager.listener.logger.print(currentBuildNumber);
manager.listener.logger.print(" with result - ");
manager.listener.logger.println(currentBuildResult);

if(currentBuildResult == "SUCCESS")
{
    manager.listener.logger.println("Build Passed");
}
else
{
	def currentBuild = Thread.currentThread().executable;
	Run r = currentBuild;
	Run temp_run = null;
	String tempBuildResult = null;
	
	// check status of previous 4 builds
    for(i=1; i<5; i++) 
	{
		temp_run = r.getPreviousBuild();
		manager.listener.logger.print(temp_run.number + " - ");
		
		tempBuildResult = temp_run.result.toString();
		manager.listener.logger.println(tempBuildResult);

		r= temp_run;
		if(tempBuildResult == "SUCCESS")
		{
            flag=true;
            break;
        }
        else
		{
            flag=false;
            continue;
        }
    }
	
    if(flag == false)
	{
         manager.build.setResult(hudson.model.Result.FAILURE);
    }
}
