### ISSUE TITLE
Build Server URL > Jenkins URL

### ISSUE THREAD

**Issue by plentz** [jenkinsci/slack-plugin#42]
Instead of using a custom 'Build Server URL' parameter, we can't use the built in 'Jenkins URL'(Manage Jenkins > Jenkins Location)?

related #3

**Comment by samrocketman** [comment]
This makes sense.  It would take away the need to configure it and just use the Jenkins fronted URL.

**Comment by samrocketman** [comment]
https://github.com/jenkinsci/slack-plugin/blob/2da9e23204d5b561d0499d4c8d9159780a1e1aba/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L62

Seems should be changed there.

**Comment by samrocketman** [comment]
I do not actively develop this plugin.  I will maintain pull requests and releases from now on.  Please feel free to contribute this feature!

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.
