### ISSUE TITLE
NullPointerException After Message Sends

### ISSUE THREAD

**Issue by fishfacemcgee** [jenkinsci/slack-plugin#437]
Jenkins Version: 2.155
Plugin Version: 2.6 (I see 2.7's out, but there doesn't appear to be any changes that are related to this error)

Let me know what other information I can provide.

```
java.lang.NullPointerException
	at jenkins.plugins.slack.ActiveNotifier.completed(ActiveNotifier.java:146)
	at jenkins.plugins.slack.SlackNotifier.perform(SlackNotifier.java:360)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.cleanUp(Build.java:196)
	at hudson.model.Run.execute(Run.java:1857)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

This exception occurred on the first execution of a job. Haven't tried a new run just yet, but will update it fails on a repeat. As I mentioned in the issue title, the message successfully sent, too.

**Comment by timja** [comment]
What's in the config.xml for that job? specifically the SlackNotifier descriptor section?
Could you send a screenshot of your config 
Also try make a change to anything in the slack config on the job and then save it too

**Comment by fishfacemcgee** [comment]
@timja 

job-config xml original:
```xml
        <jenkins.plugins.slack.SlackNotifier plugin="slack@2.6">
            <baseUrl/>
            <botUser>false</botUser>
            <room>#developers</room>
            <startNotification>false</startNotification>
            <notifySuccess>false</notifySuccess>
            <notifyAborted>false</notifyAborted>
            <notifyNotBuilt>true</notifyNotBuilt>
            <notifyUnstable>true</notifyUnstable>
            <notifyRegression>true</notifyRegression>
            <notifyFailure>true</notifyFailure>
            <notifyBackToNormal>true</notifyBackToNormal>
            <notifyRepeatedFailure>true</notifyRepeatedFailure>
            <includeTestSummary>true</includeTestSummary>
            <includeFailedTests>false</includeFailedTests>
            <includeCustomMessage>false</includeCustomMessage>
        </jenkins.plugins.slack.SlackNotifier>
```

job-config-xml after a re-save:
```xml
    <jenkins.plugins.slack.SlackNotifier plugin="slack@2.6">
      <baseUrl></baseUrl>
      <teamDomain></teamDomain>
      <tokenCredentialId></tokenCredentialId>
      <botUser>false</botUser>
      <room>#developers</room>
      <startNotification>false</startNotification>
      <notifySuccess>false</notifySuccess>
      <notifyAborted>false</notifyAborted>
      <notifyNotBuilt>true</notifyNotBuilt>
      <notifyUnstable>true</notifyUnstable>
      <notifyRegression>true</notifyRegression>
      <notifyFailure>true</notifyFailure>
      <notifyBackToNormal>true</notifyBackToNormal>
      <notifyRepeatedFailure>true</notifyRepeatedFailure>
      <includeTestSummary>true</includeTestSummary>
      <includeFailedTests>false</includeFailedTests>
      <commitInfoChoice>NONE</commitInfoChoice>
      <includeCustomMessage>false</includeCustomMessage>
    </jenkins.plugins.slack.SlackNotifier>
```

job-config Jenkins Job DSL:
```groovy
        slackNotifier {
            baseUrl('')
            notifyFailure(true)
            notifyAborted(false)
            notifyNotBuilt(true)
            notifySuccess(false)
            notifyUnstable(true)
            notifyRegression(true)
            notifyBackToNormal(true)
            notifyRepeatedFailure(true)
            includeTestSummary(true)
            room('#developers')
        }
```

After re-saving the settings, there was no NPE. Looking at [the line of code that the exception's call stack refers to](https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L146), it looks like the issue is `commitInfoChoice` needs to be defined. Right now the Jenkins Job DSL plugin doesn't treat it as required, and it looks like it doesn't get the default of `NONE` applied via the DSL. I'll go ahead and update my DSL files to include `commitInfoChoice('NONE')` for now. Also, while I mention the DSL, it appears that some change after version 2.3 has marked baseUrl as a required property. I'm not familiar enough with how the Jenkins Job DSL plugin interacts with other plugins to know if that's more of an issue on their side of the fence or not, though.

**Comment by timja** [comment]
I guess there's at least 3 ways to fix this:

1. Put a null check on that line
2. Default the commitInfoChoice, nothing else has a default though atm
3. Update job dsl
4. Add to your config

**Comment by fishfacemcgee** [comment]
@timja For the time being I'm gonna go ahead and update my Job DSL files to include `commitInfoChoice`. If marking that setting as required is easy, that might be the best approach? In-app, it's a drop down list with no "empty" option, so it's impossible to not have it set, and (assuming that required flag would translate to Job DSL's parsing) would ensure it's set for folks that use the Job DSL. In either case, I've got the issue solved enough to avoid the NPE so I'm honestly OK if we want to chalk this up to user error and then if people in the future hit this NPE they can be pointed to this.

**Comment by timja** [comment]
thanks will close then, can reopen if people think a fix here is needed
