### ISSUE TITLE
Notification doesn't work after update to 2.10 and 2.11

### ISSUE THREAD

**Issue by viktorkholod** [jenkinsci/slack-plugin#455]
Plugin stopped sending notification after update to 2.10. Update to 2.11 doesn't fix the issue.
Jenkins 2.150.1
Slack Notification Plugin 2.11

<img width="1301" alt="screenshot 2018-12-20 12 30 51" src="https://user-images.githubusercontent.com/9060774/50279688-1f927780-0453-11e9-99a2-74eb98bf9be9.png">
<img width="718" alt="screenshot 2018-12-20 12 24 59" src="https://user-images.githubusercontent.com/9060774/50279615-dfcb9000-0452-11e9-85c4-6eeabd09b7a1.png">

**Comment by timja** [comment]
upgrading from which version?

Your config doesn't look right
You have slack compatible base url and teamDomain set.
Only one should be set and if you're using slack you should only set teamDomain

Have you actually configured a botUser?

Can you try removing the slack compatible app url and unset bot user

**Comment by dshvedchenko** [comment]
The same issue
Plugin 2.11 m jenkins 2.150.1
Slack compatible : empty
Is Not User : false
Test Connection works, but Publish step in Job went silent

**Comment by viktorkholod** [comment]
@timja I've updated the configuration according to your suggestions. I would confirm that it works only for the private channels.
I updated from version 2.6.

**Comment by timja** [comment]
It works for me on a public channel on the latest version of the slack plugin :(

https://jenkins-slack-plugin.slack.com/#tim-testing

**Comment by dshvedchenko** [comment]
@timja 
In my case Test connection works for private channel.
Publish does not work for same private channel.

**Comment by timja** [comment]
strange it works for me :(

![image](https://user-images.githubusercontent.com/21194782/50290650-3e4d3a00-0464-11e9-85d6-d08908de950d.png)

![image](https://user-images.githubusercontent.com/21194782/50290678-5329cd80-0464-11e9-8e4c-9cb1fedeb4ef.png)

![image](https://user-images.githubusercontent.com/21194782/50290706-69378e00-0464-11e9-8cba-7f1566da2a6c.png)

**Comment by dshvedchenko** [comment]
ok let me check with all ticks :)

**Comment by dshvedchenko** [comment]
with all ticks in Publish it start sending data

**Comment by dshvedchenko** [comment]
it does not send data Unless I enabled Notify Build Start.
but Build Start itself was not reported

**Comment by dshvedchenko** [comment]
maybe here is issue https://github.com/jenkinsci/slack-plugin/blob/129db5947201ca1730c02d7c42e5f7c6b352868a/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L443

**Comment by timja** [comment]
reproduced, not sure if that is the line but i'm narrowing it down atm

**Comment by timja** [comment]
narrowed down to this nasty if statement:
https://github.com/jenkinsci/slack-plugin/blob/f56cef49680df0eb5b234f0e4e4e23a3dcd12733/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L132

**Comment by timja** [comment]
maybe not grr

**Comment by timja** [comment]
@dshvedchenko can you test this please? https://github.com/jenkinsci/slack-plugin/pull/457

**Comment by dshvedchenko** [comment]
@timja  how ?

**Comment by dshvedchenko** [comment]
please, give me .hpi at least

**Comment by timja** [comment]
https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/PR-457/2/artifact/target/slack.hpi

**Comment by dshvedchenko** [comment]
Yes, now it work as expected;
without Buidl Started Notification On: only report about Success
when Build Started Notification On and Success On - it reports both events correctly

**Comment by KreAch3R** [comment]
Thanks for the reply. He just gets the "counting.." one @timja . The real issue (getting a success message after the build is finished) isn't solved.

**Comment by dshvedchenko** [comment]
We use FreeStyle jobs. Maybe it should run in finalize, and not in Complete phase

**Comment by timja** [comment]
Yup its not actually running after build finished, that seems to be how it is working for free style jobs

**Comment by KreAch3R** [comment]
My test that was throwing 3 notification was a FreeStyle Job. I am thinking that something in @dshvedchenko's configuration is broken and the last "Success" notification isn't firing.

**Comment by timja** [comment]
with a job that the only thing it does is checkout from github i only 2 get the 2 notifications, 
start and success and counting

**Comment by KreAch3R** [comment]
That's the behavior I get too, @timja . I don't understand, I can't get the 3 notifications with anything I try. I reverted jenkins and this plugin back to what I was using, and I still don't get the 3 notifications. More importantly, I don't get the end "Success" notification, which I always did. It feels like this is a Slack change that we fell onto. I'll keep trying to figure out what happened
