### ISSUE TITLE
slackSend is ignored after restart

### ISSUE THREAD

**Issue by lheeb** [jenkinsci/slack-plugin#456]
We formerly used plugin v2.3 on Jenkins v2.89.4. Due to us using Jenkins as a non-persistent Docker container, we decided to let all global configuration for Slack empty and pass them on every slackSend().
This is how we integrated it in our declarative Jenkins pipeline:
```groovy
post {
    failure {
      slackSend color: "danger",
              message: "Pipeline run *$currentBuild.displayName* failed for branch *$BRANCH_NAME*",
              baseUrl: "https://ourSpace.slack.com/services/hooks/jenkins-ci/",
              token: "ourToken",
              channel: "ourChannel"
    }
  }
```
It works perfectly. The message gets sent correctly to our Slack channel. Now we noticed, that after a restart or a redeployment of Jenkins, the Slack Plugin doesn't work anymore.  The pipeline correctly switches to the post-failure step, but slackSend() seems to be ignored:
```
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] }
[Pipeline] // stage
```
This behaviour can be fixed, if we make a change to the global configuration, save it, delete the configuration again and save it once more. Afterwards the example above is executed correctly again.

We updated the plugin to v2.11 (still using the same Jenkins version), but the behaviour stays the same.
Is this a known issue or are we perhaps missing something in the documentation?

**Comment by timja** [comment]
its not a known issue, it should work fine...

it may need debugging through the plugin though

**Comment by timja** [comment]
Closing as haven't heard anything,
I would suggest using teamDomain instead of baseUrl
