### ISSUE TITLE
Groovy configuration stopped working. 

### ISSUE THREAD

**Issue by btsteve** [jenkinsci/slack-plugin#458]
We are attempting to configure the plugin through a groovy script and this has been working fine, but stopped working the last time we tried to build out Jenkins machines. I am not a groovy expert did anything in the configuration of the plugin change. 
Jenkins 2.150.1
Slack Plugin: latest

Error:
"stderr": "\nERROR: Unexpected exception occurred while performing groovy command.\ngroovy.lang.MissingPropertyException: No such property: plugins for class: hudson.model.Hudson\n\tat org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)\n\tat org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)\n\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)\n\tat RemoteClass.run(RemoteClass:50)\n\tat groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)\n\tat groovy.lang.GroovyShell.run(GroovyShell.java:518)\n\tat groovy.lang.GroovyShell.run(GroovyShell.java:497)\n\tat hudson.cli.GroovyCommand.run(GroovyCommand.java:89)\n\tat hudson.cli.CLICommand.main(CLICommand.java:283)\n\tat hudson.cli.CliManagerImpl.main(CliManagerImpl.java:95)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)\n\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)\n\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)\n\tat hudson.remoting.UserRequest.perform(UserRequest.java:212)\n\tat hudson.remoting.UserRequest.perform(UserRequest.java:54)\n\tat hudson.remoting.Request$2.run(Request.java:369)\n\tat hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)\n\tat hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:66)\n\tat hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)\n\tat hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)\n\tat jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)\n\tat jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:748)",
    "stderr_lines": [
        "",
        "ERROR: Unexpected exception occurred while performing groovy command.",
        "groovy.lang.MissingPropertyException: No such property: plugins for class: hudson.model.Hudson",
        "\tat org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)",
        "\tat org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)",
        "\tat org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)",
        "\tat RemoteClass.run(RemoteClass:50)",
        "\tat groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)",
        "\tat groovy.lang.GroovyShell.run(GroovyShell.java:518)",
        "\tat groovy.lang.GroovyShell.run(GroovyShell.java:497)",
        "\tat hudson.cli.GroovyCommand.run(GroovyCommand.java:89)",
        "\tat hudson.cli.CLICommand.main(CLICommand.java:283)",
        "\tat hudson.cli.CliManagerImpl.main(CliManagerImpl.java:95)",
        "\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "\tat java.lang.reflect.Method.invoke(Method.java:498)",
        "\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)",
        "\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)",
        "\tat hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)",
        "\tat hudson.remoting.UserRequest.perform(UserRequest.java:212)",
        "\tat hudson.remoting.UserRequest.perform(UserRequest.java:54)",
        "\tat hudson.remoting.Request$2.run(Request.java:369)",
        "\tat hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)",
        "\tat hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:66)",
        "\tat hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)",
        "\tat hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)",
        "\tat jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)",
        "\tat jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)",
        "\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)",
        "\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)",
        "\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)",
        "\tat java.lang.Thread.run(Thread.java:748)"

Script:

`import com.cloudbees.jenkins.plugins.sshcredentials.impl.*
import com.cloudbees.plugins.credentials.*
import com.cloudbees.plugins.credentials.common.*
import com.cloudbees.plugins.credentials.domains.Domain
import com.cloudbees.plugins.credentials.impl.*
import jenkins.util.Secret
import java.nio.file.Files
import jenkins.model.Jenkins
import net.sf.json.JSONObject
import org.jenkinsci.plugins.plaincredentials.impl.*
import jenkins.model.*

if (args.length < 5) {
  throw new RuntimeException("usage: java -jar jenkins-cli.jar -s JENKINS_URL groovy setup-slack.groovy <base-url> <room> <send-as> <team-domain> <token-id>")
}

String baseUrl = args[0]
String room = args[1]
String sendAs = args[2]
String teamDomain = args[3]
String tokenId = args[4]
println(baseUrl)
println(room)
println(sendAs)
println(teamDomain)
println(tokenId)
JSONObject formData = ['slack': ['tokenCredentialId': tokenId]] as JSONObject

def slackParameters = [
  slackBaseUrl:             baseUrl,
  slackBotUser:             'true',
  slackRoom:                room,
  slackSendAs:              sendAs,
  slackTeamDomain:          teamDomain,
  slackToken:               '',
  slackTokenCredentialId:   tokenId
]
 
// get Jenkins instance
Jenkins jenkins = Jenkins.getInstance()
 
// get credentials domain
def domain = Domain.global()
 
// get credentials store
def store = jenkins.getExtensionList('com.cloudbees.plugins.credentials.SystemCredentialsProvider')[0].getStore()
 
// get Slack plugin
def slack = jenkins.getExtensionList(jenkins.plugins.slack.SlackNotifier.DescriptorImpl.class)[0]
 
// define form and request

def request = [getParameter: { name -> slackParameters[name] }] as org.kohsuke.stapler.StaplerRequest

// add Slack configuration to Jenkins
slack.configure(request, formData)
 
// save to disk
slack.save()
jenkins.save()`

**Comment by timja** [comment]
If you need to use a groovy script then you can use this:
https://github.com/jenkinsci/slack-plugin/issues/427#issuecomment-444024289

The previous method was a terrible idea (no idea why someone put it on the wiki...), it depended on the UI fields

The recommended approach is to use the configuration-as-code plugin with config something like this:
https://github.com/jenkinsci/slack-plugin#configuration-as-code

**Comment by timja** [comment]
Closing as solution provided, feel free to comment if you have issues. 
I may see it if its in the next hour or so, but otherwise I'm off for ~3 weeks and will have a look on my return

**Comment by btsteve** [comment]
Thanks for the quick response I just made the changes to the script you suggested and it work great. 
Have a great Holiday.
