### ISSUE TITLE
Global Configuration Instructions

### ISSUE THREAD

**Issue by jaydrogers** [jenkinsci/slack-plugin#469]
Hi there,

Thanks for maintaining this very helpful project. I see that there are instructions on how you can configure this plugin to run globally ([see number 5 on the README](https://github.com/jenkinsci/slack-plugin#install-instructions-for-slack-compatible-application))

![screen shot 2019-01-09 at 3 02 43 pm](https://user-images.githubusercontent.com/3174134/50928208-b6819c80-141f-11e9-9c1c-54f5e6b6848f.png)

I am not sure how I would configure Slack to run for every project on my Jenkins server. Any help would be appreciated.

If I can get this configured, I have no problem submitting a PR with detailed instructions how to configure this for everyone else. Thanks!

**Comment by timja** [comment]
If you want it to run on with project without manually adding it or using job dsl then you need this plugin: https://github.com/jenkinsci/global-slack-notifier-plugin

**Comment by jaydrogers** [comment]
Thanks a ton! I submitted a PR as well on this.
