### ISSUE TITLE
Test Connection uses global integration token instead of post build step integration token

### ISSUE THREAD

**Issue by Darknesskight** [jenkinsci/slack-plugin#475]
Jenkins 2.150.1
Slack Plugin 2.14

We are seeing an issue where the Test Connection button will use the global integration token instead of the integration token configured with the post-build step. The log confirms this as well. This behavior was not present on version 2.12 of the plugin. I did not test version 2.13 to see if it is also an issue there.

```
Posting: to build-node on slack-group using https://slack-group.slack.com/services/hooks/jenkins-ci?token=globalToken: [{"fallback":"Slack/Jenkins plugin: you're all set on https://server/","color":"good","fields":[{"short":false,"value":"Slack/Jenkins plugin: you're all set on https://server/"}],"mrkdwn_in":["pretext","text","fields"]}] good

Slack post may have failed. Response: null

Response Code: 404
```

**Comment by timja** [comment]
Are you using integration token credential ID or the direct text?

**Comment by Darknesskight** [comment]
Direct text. I did a test using the integration token credential ID and am seeing the same issue though. The slack global configuration is currently using direct text.

When testing with the integration token credential ID, I noticed some other issues which may be related.
- Building a job while specifying a direct text token in the job works fine. The token specified in the job is used.
- Building a job while specifying a integration token credential ID in the job does not work. The global direct text token is being used instead.
- Specifying both a direct text and integration token credential ID on the job causes the direct text token on the job to be used instead of the integration token credential ID.

If I have some time today I can test what happens if the global slack configuration is using an integration token credential ID instead of direct text.

**Comment by timja** [comment]
Thanks for the feedback, I'll try look on Friday.
Two rules that should be applied:
1. Job config should always take precedence
2. integration token text is deprecated and should not be used, to be removed at a future date

**Comment by Darknesskight** [comment]
I updated my global slack configuration to use an integration token credential id. This appears to make the Test Connection issue go away as long as the job also uses an integration token credential id. I'm wondering if this is an issue with how direct text is handled between the global configuration and the job's configuration as you imply in your first rule.

This has turned into a non-issue for me since I'm not planning on switching back to direct text. If you would like me to test an update I can do that though.

**Comment by timja** [comment]
Will leave this open for now, ideally the text mode would be removed and existing ones migrated into credentials...

**Comment by timja** [comment]
Global integration token has been removed, shouldn't be an issue anymore.
Still need to remove from jobs but that will be a change coming up soon hopefully
