### ISSUE TITLE
What name should I use for sending to @somebody?

### ISSUE THREAD

**Issue by rodrigc** [jenkinsci/slack-plugin#478]
Thank you for this great plugin.

I am using:
Jekins 2.138.3
Slack plugin 2.14

I was going through this blog post from Slack: https://api.slack.com/changelog/2017-09-the-one-about-usernames

and I was getting lost as to which `@name` to use when using `slackSend`.

I belong to an org where some users have accounts which were created before 2017, and
sometimes sending to their `@"short name"` works, and sometimes it doesn't.

In the Slack UI, I can see:
* Display Name
* a short name

I can also *Copy Member ID*, and see the member ID, and such as *UA3GX15ITL*.  
If I use `slackSend()` to `@UA3GX15ITL` seems to work.

Can you recommend to me how I can definitively find the `@whatever` that I can use
to `slackSend` to send to a specific user?  Ideally if it could be something I can see in the UI.
But if there is an API call I can use to see this information, that would be great.

Thanks for any guidance you can give.

**Comment by timja** [comment]
https://github.com/jenkinsci/slack-plugin#direct-message

To find user IDs I've always gone to the users profile and clicked copy member ID
There is probably also an API for it,

At the place I currently work we maintaining a mapping of github usernames to member ids:
https://github.com/hmcts/github-slack-user-mappings/blob/master/slack.json#L129

Note some people are using usernames as they have older accounts

**Comment by timja** [comment]
There's some code here for getting a user id from an email address if that's helpful:
https://github.com/jenkinsci/slack-plugin/pull/178/files#diff-282db0eb13a24d1729df3e194a35f6d7R131

**Comment by casz** [comment]
@timja we could introduce a field in Jenkins user profile where they can put their Slack ID or do the whole fetch their user ids.

We could even do a two-fold thing store their slack id in Jenkins user profile and fetch it if it is not there.

Then perhaps some method to either parse emails and replace it with slack user mentions or an actual pipeline step for getting the slack user id.

**Comment by timja** [comment]
Sounds like a really good idea @casz 
Either approach sound good
