### ISSUE TITLE
can you please add abilities for coloured attachments

### ISSUE THREAD

**Issue by ohadpartuck** [jenkinsci/slack-plugin#48]
https://api.slack.com/docs/attachments

**Comment by peergum** [comment]
Already looks like coloured attachments to me.
Could you pls be more specific?

**Comment by samrocketman** [comment]
Slack Plugin 1.7 has been released.  This a fix for this has been included in it.  Please try out new version and if it doesn't resolved this issue then ask for this to be re-opened and provide more details.
