### ISSUE TITLE
ERROR: Could not parse response from slack 

### ISSUE THREAD

**Issue by demoontz** [jenkinsci/slack-plugin#481]
Hello! im using declarative pipeline and have this error:

> run slackstepsend, step false, desc true
> Slack Send Pipeline step configured values from global config - baseUrl: true, teamDomain: true, token: true, channel: false, color: true
> ERROR: Could not parse response from slack, potentially because of invalid configuration (botUser: true and baseUrl set)

in logs all seems ok: 

> PM jenkins.plugins.slack.StandardSlackService publish
> INFO: Posting succeeded

but this code return null object:

```
def slackResponse = slackSend(channel: "@UE94MBP5K", message: "Hi bro! <3")
slackSend(channel: slackResponse.threadId, message: "Build still in progress")
```
what could it be?

**Comment by timja** [comment]
check the slack docs but I don't think threading is supported in direct messages

**Comment by demoontz** [comment]
i tried sent to channel and had this error again.

**Comment by demoontz** [comment]
Yes. with BotUser checked have error.

**Comment by timja** [comment]
Are you using a bot user though?

**Comment by timja** [comment]
https://github.com/jenkinsci/slack-plugin/pull/429#issuecomment-446413358

**Comment by demoontz** [comment]
it seems like i should create my own app instead of Jenkins CI app?

**Comment by timja** [comment]
Correct, for now anyway.
I'm having a call with someone from Slack next week to see if we can set it up for the main app

**Comment by demoontz** [comment]
ok, tnx u! i`ll wait.

**Comment by timja** [comment]
Hey sorry, it was scheduled for today, but something came up on the person at slack's send, rescheduled for next week

If you want to use now then you can follow instructions in the link above and use your own app

**Comment by timja** [comment]
There's no maintenance and you don't need to run anything on your end, just a view clicks in the slack app and then install it on your workspace

**Comment by timja** [comment]
You can get the bot user token from:
https://api.slack.com/apps/<app-id>/oauth?

You want the `Bot User OAuth Access Token`

**Comment by d1ndra** [comment]
I tried with that as well. `Is Bot User?` is checked, for slack compatible URL I tried both the hook for the app as well as the hook for the jenkins app. Try "Test Connection" keeps returning "Failure" if I use the oAuth token as the integration credential

**Comment by casz** [comment]
maybe to help users instead of throwing `could not parse response` perhaps show the actual response, there might be a hint :)

**Comment by timja** [comment]
@casz On master I've made a change to log the error in the test connection button
But there's probably more improvements that could be done

**Comment by timja** [comment]
@d1ndra I do actively use the plugin, (only the pipeline flow, not the freestyle project one)

don't set the slack compatible app url field, set the team domain instead

Also put a screen shot of your global config / pipeline config  here

**Comment by casz** [comment]
> don't set the slack compatible app URL field, set the team domain instead
You could add form validation if `botuser` is set do not allow `base URL` to be set and do not allow `team domain` to be empty.

❓ Why was it ever named `team domain` it is called `workspace` in slack terms. 🔀

**Comment by timja** [comment]
I've created https://github.com/jenkinsci/slack-plugin/issues/new 

No idea, the label should be changed in the UI

**Comment by d1ndra** [comment]
> don't set the slack compatible app url field, set the team domain instead

This was the issue, removed it and works like a charm. Thanks! @timja

**Comment by timja** [comment]
@demoontz any chance that's the same reason your one is failing?

**Comment by demoontz** [comment]
i removed Slack compatible app URL (optional) and set Team Subdomain like as "mycompany" and messages stoped coming. but pipeline work without errors. how i understand @d1ndra used his own slack app, not yours. im using urs jenkins-ci.

**Comment by timja** [comment]
You need to use your own one for now

**Comment by demoontz** [comment]
yeah, understand this, will try it later. tnx
