### ISSUE TITLE
Security issue - can post to any channel

### ISSUE THREAD

**Issue by gee72** [jenkinsci/slack-plugin#482]
When adding the app configuration in Slack, you choose a channel (as normal for many apps). However, this is ignored if you put a different channel in the Jenkins configuration - you can add the app to channel X but still post to channel Y.

This is obviously wrong, it means we can't control who can set up automation to a channel.

If this existing functionality is desired, then add an explicit "all channels" option in the Slack app configuration.

I raised this in the Slack website as well, but there's no confirmation or way to see if it has been noticed, so I hope this issue list is also OK to use.

**Comment by timja** [comment]
We just call the slack api, specifically chat.postMessage.
Note if you use the bot message mode then you have to invite the bot to each channel you want to use.

This is not related to the slack plugin, take it up with slack, or use bot user mode

**Comment by gee72** [comment]
Thanks - bot doesn't help, that is also defined by the developer on the Jenkins end.

**Comment by timja** [comment]
bot is invited to the channel in slack, nothing to do with jenkins

**Comment by gee72** [comment]
Yes, my point is that if the developer simply ignores the "bot" tickbox, they can post to any channel, bypassing the whole point of assigning an app to a channel.

This is clearly a security bug on the app end of things, I posted here because I assumed incorrectly that it was the same group.

**Comment by timja** [comment]
That's managed by slack, the app doesn't restrict the channel posting, and I'm sure there's plenty of jenkins instances out there relying on that.

The plugin only allows posting messages not reading content,
