### ISSUE TITLE
Better customization for slack messages

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#49]
Including the branch name in the slack notifications.

Also, not sure how to provide better customization of the slack notifications.

Contributions are welcome.

**Comment by DanaGoyette** [comment]
The most thorough way of allowing customization would be to extend "instant-messaging-plugin", the way "jabber-plugin" does:
https://github.com/jenkinsci/jabber-plugin
https://github.com/jenkinsci/instant-messaging-plugin

A simpler way would be to allow defining a custom message subject, with support for token macros.

Even more simply, if the plugin allows using build.getFullDisplayName() and/or build.getDescription(), other logic can take care of choosing the description.  Currently, the slack plugin is hardcoded to use build.getProject().getName(), which is particularly uninformative with foldered jobs.

Example project:
project.getFullName(): "product1/head"
project.getFullDisplayName(): "product1 » head"
build.getFullDisplayName():  "product1 » head #NN"
build.getDescription(): (can be whatever I want, such as a list of platforms)
Current slack notification: "head - #NN".  This format (with a dash) doesn't match anything in the Jenkins UI.  Also, I have other jobs named "product2/head" and "product3/head".

**Comment by samrocketman** [comment]
Feel free to make a contribution!  I don't actively develop this plugin.  I only manage pull requests and releases.

**Comment by samrocketman** [comment]
If you would like to be invited to https://jenkins-slack-plugin.slack.com/ for testing then just ask.

**Comment by digitalBush** [comment]
I was able to change the display by using the [Build Name Setter Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Build+Name+Setter+Plugin). That might not be exacly what you are after, but it was enough for our needs.

**Comment by thorntonrose** [comment]
I would like to see this, too. I have users for whom a job name does not have much meaning. I need to post a message that they can relate to, like "Main TV 2.20 has been deployed."

**Comment by saigyo** [comment]
+1 I have the same use case as thorntonrose: deploy jobs which deploy specific versions of the product, and groups of people want to be notified of the availability of the new version.

**Comment by samrocketman** [comment]
It's slated to be included.  I'm leaving it open until around the 29th for code review.

**Comment by wickett** [comment]
howdy!  One thing I would like to customize is to add the username to the build output

right now at the end of the build I get this message in slack:

```
myapp - #123 Success after 1 min 01 sec (Open)
```

It would be nice to customize this to something like:

```
myapp - #123 Success after 1 min 01 sec [changes by: John Johnson] (Open)
```

**Comment by wickett** [comment]
Another customization that would be nice is the ability to add slack emoji based on build status. :x: for failure or :white_check_mark: for success.

**Comment by samrocketman** [comment]
@wickett you can include the commit list with the slack message.  That calls out which users made the changes.  Is this not good enough?

**Comment by paulpv** [comment]
How to make a multi-line message?

**Comment by samrocketman** [comment]
@paulpv #103 solves the issue you're asking about.  It will be available in the 2.0 release.  It has yet to be released.

**Comment by FaizVisram** [comment]
@samrocketman I'm currently using an environment variable for the custom message; the message itself has \n but in Slack it's being outputted as a literal \n. Any ideas on how to fix it?

**Comment by samrocketman** [comment]
@FaizVisram According to the [Slack API multiline messages documentation](https://api.slack.com/docs/formatting#multiline_messages) including a `\n` in the message should produce a newline.  I wonder if there's some encoding going on in the background...

**Comment by samrocketman** [comment]
I tested and confirmed your issue @FaizVisram.  Please open a new issue describing the behavior.  Perhaps a user will contribute a solution for you.  Contributions are welcome.

**Comment by FaizVisram** [comment]
@samrocketman it seems as though the environment variable was taking it as a literal \n instead of parsing it as a new line. Had to re-write it to make it accept it as a new line. Thanks.

**Comment by samrocketman** [comment]
@FaizVisram can you open an issue describing the fix?

**Comment by FaizVisram** [comment]
@samrocketman Created: Issue #135

**Comment by Nakilon** [comment]
I've set _Custom message_ to `$MYVAR`
In the Shell step I did `export MYVAR=123`
The bot said into the channel: `$MYVAR` ..(

**Comment by samrocketman** [comment]
@Nakilon environment variables exported inside the shell don't get exported into the Jenkins runtime.  You'd have to set a build parameter MYVAR or a global variable MYVAR.

**Comment by Nakilon** [comment]
OK, I got it.
I wished it was a way to leave a message for slack from the shell script.

**Comment by samrocketman** [comment]
There is a way from the shell script.  You could technically use `curl` to write to slack from a shell script.  It wouldn't be via a Jenkins plugin but it's still do-able.

**Comment by mgedmin** [comment]
> Including the branch name in the slack notifications.

I'm doing that by setting a custom message to `Branch: $GIT_BRANCH, commit: $GIT_COMMIT`:
![ekrano nuotrauka is 2016-01-15 15-07-34](https://cloud.githubusercontent.com/assets/159967/12353703/c14c27e8-bb99-11e5-9b8c-152b1cc7ca5f.png)

This produces Slack notifications like

![ekrano nuotrauka is 2016-01-15 15-09-31](https://cloud.githubusercontent.com/assets/159967/12353750/039bd4f4-bb9a-11e5-9e47-ff78ae710184.png)

As you can see, there are some downsides:
- $GIT_BRANCH tends to be something like "origin/feature-foo", and there's no way to strip off the "origin/" prefix.
- $GIT_COMMIT is a full 40-character SHA-1 hash and there's no way to truncate it to the 1st 7 characters.

Any ideas about the best way to fix those?  It's fine if the best way turns out to be "bug the git plugin maintainers to add additional environment variables $GIT_BRANCH_SHORT and $GIT_COMMIT_SHORT".

**Comment by Jaceken** [comment]
@mgedmin 
Thanks! Short and nice way to add branch and commit name. 
For those who don't know where to find _Include Custom Message_ fiels:
(you need to have Slack Notification Plugin installed in you jenkins)

1. Enter job configuration screen
2. In _Slack Notifications_ section click _Advanced_
3. Select _Include Custom Message_ field

Now you can enter your custom message.

**Comment by Hassnain-Raza-Alvi** [comment]
The above comments does not work. In Slack it just displays the plain text as 
Current Branch: $GIT_BRANCH

Can anyone guide whats wrong here?

**Comment by karankh** [comment]
Where could I find full list of env. variables provides to us in jenkins for publishing on slack like -
GIT_BRANCH, GIT_CHANGE_AUTHOR 
@Jaceken

**Comment by mgedmin** [comment]
Some of the variables (e.g. GIT_BRANCH) are provided by Jenkins plugins.  I don't recall exactly which of the plugins I've used (GitHub Pull Request Builder plugin perhaps?).

IIRC I ran `env` as part of my Jenkins build in a shell script step to see the environment variables, some of which are set by Jenkins, and then tried the ones that seemed useful.

**Comment by MaikoHermans** [comment]
> @Nakilon environment variables exported inside the shell don't get exported into the Jenkins runtime. You'd have to set a build parameter MYVAR or a global variable MYVAR. There won't ever be support for that in this plugin due to the design of Jenkins.

@samrocketman I'm currently using the environment injection plugin to inject an environment from a bash command. I can use this everywhere but when slack posts it's message it still won't use the variable it will just say `$DIAWI_LINK`. Any clue how to fix this? I would say that this should work

**Comment by samrocketman** [comment]
This is a 2 year old issue.  If you like, open a new issue with additional details for the current maintainers.

**Comment by sumith08** [comment]
Can we send custom messages like git changelogs using jenkins pipeline?

**Comment by yuri-karpovich** [comment]
> > @Nakilon environment variables exported inside the shell don't get exported into the Jenkins runtime. You'd have to set a build parameter MYVAR or a global variable MYVAR. There won't ever be support for that in this plugin due to the design of Jenkins.
> 
> @samrocketman I'm currently using the environment injection plugin to inject an environment from a bash command. I can use this everywhere but when slack posts it's message it still won't use the variable it will just say `$DIAWI_LINK`. Any clue how to fix this? I would say that this should work

Have you found a workaround?

**Comment by calbertts** [comment]
> > > @Nakilon environment variables exported inside the shell don't get exported into the Jenkins runtime. You'd have to set a build parameter MYVAR or a global variable MYVAR. There won't ever be support for that in this plugin due to the design of Jenkins.
> > 
> > 
> > @samrocketman I'm currently using the environment injection plugin to inject an environment from a bash command. I can use this everywhere but when slack posts it's message it still won't use the variable it will just say `$DIAWI_LINK`. Any clue how to fix this? I would say that this should work
> 
> Have you found a workaround?

I'm looking for the same.

**Comment by VivaLaRobo** [comment]
> > > > @Nakilon environment variables exported inside the shell don't get exported into the Jenkins runtime. You'd have to set a build parameter MYVAR or a global variable MYVAR. There won't ever be support for that in this plugin due to the design of Jenkins.
> > > 
> > > 
> > > @samrocketman I'm currently using the environment injection plugin to inject an environment from a bash command. I can use this everywhere but when slack posts it's message it still won't use the variable it will just say `$DIAWI_LINK`. Any clue how to fix this? I would say that this should work
> > 
> > 
> > Have you found a workaround?
> 
> I'm looking for the same.

any updates?

**Comment by dezren39** [comment]
https://github.com/jenkinsci/slack-plugin/issues/359#issuecomment-459339094
