### ISSUE TITLE
Single Jenkins Slack App for Scripts AND Jenkins Plugin

### ISSUE THREAD

**Issue by grayaii** [jenkinsci/slack-plugin#496]
We want to post messages from Jenkins in 2 scenarios:

* Post build Step using the Jenkins Plugin and
* From a python script

Unfortunately, the Jenkins CI app made by Slack ONLY works for Jenkins Plugin:
https://my.slack.com/services/new/jenkins-ci
So I can't use that app's credentials in a random python script.

For instance, if I install https://my.slack.com/services/new/jenkins-ci, the credentials that it gives cannot be used in a random script:

```
import os
from slackclient import SlackClient

slack_token = os.environ["SLACK_API_TOKEN"]
sc = SlackClient(slack_token)

sc.api_call(
  "chat.postMessage",
  channel="C0XXXXXX",
  text="Hello from Python! :tada:"
)
```

And my own personal token cannot be used by the Jenkins Plugin, since it ONLY wants the integration token of the Jenkins CI app.

So this is forcing me to use 2 Jenkins CI apps:
One from https://my.slack.com/services/new/jenkins-ci to work with the Jenkins Slack Plugin, and my own custom app just to get the token to use in jenkins scripts.

Is there a way to simply use a single Jenkins Slack app for both the Jenkins Plugin AND random scripts?

**Comment by timja** [comment]
Yes, create your own app and then tick botUser true, adding the bot user oauth token instead of the integration token

**Comment by timja** [comment]
Looks like you have everything right that I can see,
Have a read through:
https://github.com/jenkinsci/slack-plugin/pull/429#issuecomment-446413358
and
https://github.com/jenkinsci/slack-plugin/issues/481

See if they help

**Comment by timja** [comment]
Its certainly possible, I've set it up on the jenkins-slack-plugin workspace

**Comment by grayaii** [comment]
that did it! I had to give my own app permissions! (and there was some weirdness on "team subdomain" vs "workspace name") on the main configuration page.  Looks like "workspace name" works for me, but not subdomain. Weird.
Thank you so much for getting to the bottom od this!
Feel free to close this out, if you haven't done so already :
)
