### ISSUE TITLE
Failed to download plugin since 1 hour or so

### ISSUE THREAD

**Issue by jorkzijlstra** [jenkinsci/slack-plugin#499]
Since an hour or so Im unable to down load the plugin anymore.

Getting:
`
 SEVERE: Failed to install Slack Notification
jenkins    | java.io.IOException: Failed to download from http://updates.jenkins-ci.org/download/plugins/slack/2.15/slack.hpi (redirected to: http://archives.jenkins-ci.org/plugins/slack/2.15/slack.hpi)
jenkins    | 	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1182)
jenkins    | 	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1719)
jenkins    | 	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1982)
jenkins    | 	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1693)
jenkins    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jenkins    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jenkins    | 	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:112)
jenkins    | 	at java.lang.Thread.run(Thread.java:748)
jenkins    | Caused by: java.io.IOException: Failed to load http://updates.jenkins-ci.org/download/plugins/slack/2.15/slack.hpi to /var/jenkins_home/plugins/slack.jpi.tmp
jenkins    | 	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1148)
jenkins    | 	... 7 more
jenkins    | Caused by: java.io.FileNotFoundException: http://archives.jenkins-ci.org/plugins/slack/2.15/slack.hpi
jenkins    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jenkins    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jenkins    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jenkins    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
jenkins    | 	at java.security.AccessController.doPrivileged(Native Method)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
jenkins    | 	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1141)
jenkins    | 	... 7 more
jenkins    | Caused by: java.io.FileNotFoundException: http://archives.jenkins-ci.org/plugins/slack/2.15/slack.hpi
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
jenkins    | 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
jenkins    | 	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
jenkins    | 	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
jenkins    | 	at java.net.URLConnection.getContentLength(URLConnection.java:485)
jenkins    | 	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1125)
jenkins    | 	... 7 more
`

or 
`
13:22:47 Failed in the last attempt (curl -sSfL --connect-timeout 20 --retry 3 --retry-delay 0 --retry-max-time 60 https://updates.jenkins.io/2.150/latest/slack.hpi -o /usr/share/jenkins/ref/plugins/slack.jpi)
`

**Comment by jorkzijlstra** [comment]
I'm guessing this has maybe something todo with the release from 45 minutes ago?

**Comment by timja** [comment]
2.14 is the latest at the update centre
http://archives.jenkins-ci.org/plugins/slack/

It takes time and sometimes there's infra problems

**Comment by jorkzijlstra** [comment]
I tried in the UI which I think i version specific and reverting to 2.150. 
I also tried it with the plugin.sh and using version `slack:latest`. For some reason this also takes 2.150 and not the dir `latest` from the link you provided. 

I guess we will have to wait until after the weekend. Thnx for the update

**Comment by jorkzijlstra** [comment]
@timja It seems its there now.

**Comment by timja** [comment]
Yup

**Comment by jorkzijlstra** [comment]
It does seem not to be backward compatible in combination with the https://github.com/jenkinsci/configuration-as-code-plugin.

We where still using the `token` option  (yes I know we shouldn't) and this got removed :(. I though a minor version upgrade normally implies it should be backward compatible. 

Have a nice weekend

**Comment by timja** [comment]
the token should get automatically migrated, the fields aren't removed and getters and setters are still there

since you're using configuration-as-code should be an easy fix to change anyway?

**Comment by casz** [comment]
@timja you migration does call save so it does indeed break downgrading, as plugin maintainer I would prefer to call save, so you don't have to carry around the deprecation forever.

**Comment by jorkzijlstra** [comment]
Weird, I upgraded from 2.14 to 2.15 and was getting a deprecated `token` exception and jenkins wouldn't boot up. Will stick with 2.14 for the weekend and will look into it next week.

**Comment by timja** [comment]
Little confused
You said it calls save and you would prefer to call save?

I would love not to carry it around forever 👍 

@jorkzijlstra I think that's a feature of jcasc 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/test/resources/io/jenkins/plugins/casc/impl/configurators/SelfConfiguratorTest.yml#L1-L5

Because you're using a deprecated attribute it forces you to update, if you want to continue on the new version and not have it fail you can configure it here:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/plugin/src/test/resources/io/jenkins/plugins/casc/impl/configurators/SelfConfiguratorTest.yml#L1-L5

**Comment by casz** [comment]
Oh your right @timja he has to use the JCasC feature for only warning about deprecation :smile: but as I said it my review comments it is best for the deprecated code to behave as the new attribute.

**Comment by timja** [comment]
will look at it next week most likely unless someone beats me to it.
The issues don't look critical

**Comment by jorkzijlstra** [comment]
@timja and @casz Thnx for the quick replies

**Comment by timja** [comment]
@jorkzijlstra its not a major version because it is compatible
migration code handles it, but jcasc is of the opinion that you shouldn't use deprecated fields.

**Comment by jorkzijlstra** [comment]
@timja thnx, I now understand. Thnx for setting me straight :).
