### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by fattymelt** [jenkinsci/slack-plugin#5]
"Failed to initialize campfire notifier - check your global campfire notifier configuration settings: javax.net.ssl.SSLProtocolException: Server returned wrong cipher suite for session"

See related info here -> https://issues.jenkins-ci.org/browse/JENKINS-19590

Essentially, the plugin installs fine, but when I go to set up the org name and key in "Configure System", I get the error above.

**Comment by samrocketman** [comment]
The word `campfire` does not appear in the source repository other than in the README.

```
^_^[sam@blaster:~/git/github/slack-plugin]$ grep -irl 'campfire' *
README.markdown
```

Since this is an old issue and it doesn't appear anybody else has confirmed the issue I'm closing it.
