### ISSUE TITLE
2.15 release - migrate Integration token into a credential but credential fails

### ISSUE THREAD

**Issue by mckaymatt** [jenkinsci/slack-plugin#507]
After upgrading from 2.14 to 2.15, jenkins could not longer post to slack. 
https://github.com/jenkinsci/slack-plugin/blob/master/CHANGELOG.md#215-release-notes-2019-01-01
The `tokenCredentialId` was set to what looks like a UUID, and the `token` was unset.  The error in the logs was about 1500 lines of html/js but the most relevant part was:
```
WARNING: Response Code: 404
```
I have admin privileges. 
This is the `jenkins.plugins.slack.SlackNotifier` system config before and after:

```<?xml version='1.1' encoding='UTF-8'?>
<jenkins.plugins.slack.SlackNotifier_-DescriptorImpl plugin="slack@2.3">
  <baseUrl>https://XXXXX.slack.com/services/hooks/jenkins-ci/</baseUrl>
  <teamDomain>XXXXX</teamDomain>
  <token>juXXXXXXXXXXXXXXXXXXXX</token>
  <tokenCredentialId></tokenCredentialId>
  <botUser>true</botUser>
  <room>#channel-XXXX</room>
</jenkins.plugins.slack.SlackNotifier_-DescriptorImpl>
```
```
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.plugins.slack.SlackNotifier_-DescriptorImpl plugin="slack@2.15">
  <baseUrl>https://xxxxx.slack.com/services/hooks/jenkins-ci/</baseUrl>
  <teamDomain>xxxxx</teamDomain>
  <tokenCredentialId>xxxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxx</tokenCredentialId>
  <botUser>true</botUser>
  <room>#channel-XXXX</room>
</jenkins.plugins.slack.SlackNotifier_-DescriptorImpl>
```
I'm not sure if the `tokenCredentialId`  should have read `slack-token`. A credential called `slack-token` was created.

**Comment by timja** [comment]
The UUID is the ID of the credential that was generated for you
Most likely the same reason as https://github.com/jenkinsci/slack-plugin/issues/481
But don't know why it doesn't work
if you add your token to a new credential does it work?

**Comment by mckaymatt** [comment]
It seems to work if I manually set up the new credential.

**Comment by timja** [comment]
try steps here to see what's wrong if you have time https://github.com/jenkinsci/slack-plugin/issues/480#issuecomment-461163749
