### ISSUE TITLE
java.lang.NumberFormatException: When using parametrized scheduler

### ISSUE THREAD

**Issue by KaminerD** [jenkinsci/slack-plugin#509]
Hi i'm still experiencing this issue in 2.15 when using the Parameterized Scheduler.
Parametrized scheduler arguments are as follows:
H/30 * * * * % REGRESSION=native_anomalies;BACKEND_URL=https://app.com;GIT_BRANCH=feature/anomalies-end-to-end;ENVIRONMENT=prod

(I think this may be the % between cron time specification and the given arguments)

`> git rev-list --no-walk 4299e6d91aecfbe9da8788292dab0eec4d419a0a # timeout=10 FATAL: can't parse argument number: GIT_BRANCH=feature/OO-5347/anomalies-end-to-end java.lang.NumberFormatException: For input string: "GIT_BRANCH=feature/OO-5347/anomalies-end-to-end" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:580) at java.lang.Integer.parseInt(Integer.java:615) at java.text.MessageFormat.makeFormat(MessageFormat.java:1427) Caused: java.lang.IllegalArgumentException: can't parse argument number: GIT_BRANCH=feature/OO-5347/anomalies-end-to-end at java.text.MessageFormat.makeFormat(MessageFormat.java:1429) at java.text.MessageFormat.applyPattern(MessageFormat.java:479) at java.text.MessageFormat.<init>(MessageFormat.java:362) at java.text.MessageFormat.format(MessageFormat.java:840) at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.escape(ActiveNotifier.java:545) at jenkins.plugins.slack.ActiveNotifier$MessageBuilder.append(ActiveNotifier.java:382) at jenkins.plugins.slack.ActiveNotifier.started(ActiveNotifier.java:69) at jenkins.plugins.slack.SlackNotifier.prebuild(SlackNotifier.java:459) at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:798) at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:793) at hudson.model.Build$BuildExecution.doRun(Build.java:145) at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504) at hudson.model.Run.execute(Run.java:1810) at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43) at hudson.model.ResourceController.execute(ResourceController.java:97) at hudson.model.Executor.run(Executor.java:429)`

Your help will be very much appreciated. thx

**Comment by timja** [comment]
Needs a PR similar to: https://github.com/jenkinsci/slack-plugin/pull/374/files
Along with tests which the previous change was missing
