### ISSUE TITLE
Selecting "Notify Failure" doesn't notify on failure

### ISSUE THREAD

**Issue by sandyscoffable** [jenkinsci/slack-plugin#518]
## Versions

Jenkins: 2.150.2
Slack Notification Plugin: 2.17

## Steps to reproduce

1. Configure global settings as per Slack integration instructions, configuring token in the Jenkins secret text credentials store etc. Configured to send to a channel e.g `#foo`
2. Test comes through to the Slack channel ✅. (This shows the connection details have been entered correctly) <br /><img width="360" alt="screenshot 2019-02-14 at 14 10 39" src="https://user-images.githubusercontent.com/20515901/52792049-5acfb200-3062-11e9-9cc2-293f348e527c.png">
3. Set up a basic freestyle Jenkins job
4. Configure Build section with execute shell that contains `exit 1` only (i.e will trigger a failure)
5. Set up a single Slack Notification post build action with "Notify Build Start" checked<br /><img width="1425" alt="screenshot 2019-02-14 at 14 16 44" src="https://user-images.githubusercontent.com/20515901/52792413-3de7ae80-3063-11e9-84f3-c24bc192a395.png">
6. Run the job. Notification of the job starting goes to the Slack channel ✅. (This shows the integration with the jenkins job works correctly)<br /><img width="429" alt="screenshot 2019-02-14 at 14 12 45" src="https://user-images.githubusercontent.com/20515901/52792174-a3876b00-3062-11e9-9803-2eae35ead7bb.png">
7. Change the configuration from "Notify Build Start" to "Notify Failure". <br /><img width="1421" alt="screenshot 2019-02-14 at 14 16 58" src="https://user-images.githubusercontent.com/20515901/52792412-3de7ae80-3063-11e9-8baa-21020f2f33d5.png">
8. Run the job.
9. No notification goes to the Slack channel ❌ 

## What should happen

The failure notification should appear in the Slack channel

## Console output (pretty much identical for steps 6 and 8)

<img width="566" alt="screenshot 2019-02-14 at 14 01 56" src="https://user-images.githubusercontent.com/20515901/52791605-3f17dc00-3061-11e9-9a6b-7fb8dd3b189c.png">

**Comment by sghill** [comment]
Did the first build fail? I assume so since the shell step is `exit 1`

I've run into this a few times - notify failure really means "notify on first failure only." There is an option under 'Advanced...' to notify on repeated failures that will work.

**Comment by timja** [comment]
The UI is clarified with https://github.com/jenkinsci/slack-plugin/pull/519

Ideally there would be another option added for notify on every failure.

more ideally there should just be one option but don't know if that would affect people's workflows

**Comment by sandyscoffable** [comment]
Thanks guys - the solution in #519 sorts this out 👍
