### ISSUE TITLE
Introduce an OnEveryFailure notification option

### ISSUE THREAD

**Issue by sghill** [jenkinsci/slack-plugin#520]
Adding a new option to subscribe to notifications on every failure would be helpful to most users of the plugin. Split from comments on PR #516:

Gah, there should be an OnEveryFailure one imo, this behaviour is just confusing
At least I can now tell what's going on with this code

_Originally posted by @timja in https://github.com/jenkinsci/slack-plugin/pull/516_

related: #519, #518, #136, #134, #15

**Comment by movedoa** [comment]
+1, very confunsing.
Also, wouldn't it make more sense to use a radioset for the 2 (then 3) options?
Afaik it doesn't make sense to have more than one active at a time.

**Comment by casz** [comment]
I think it would be better to have onEveryFailure and onFirstFailure.
Since onRepeatedFailure is covered by onEveryFailure...
Perhaps just convert onRepeatedFailure to onEveryFailure.

**Comment by philosowaffle** [comment]
+1 for `OnEveryFailure` or something equivalent.  Perhaps we could also get the README updated with the different configuration options and a description on how they work. That way, even if the config names are confusing, there is a reference document with a proper explanation.
