### ISSUE TITLE
No Integration Token item in Global Slack Notifier Settings - version2.16&2.18

### ISSUE THREAD

**Issue by esmiles** [jenkinsci/slack-plugin#524]
Hi team,

There is no Integration Token item in Global Slack Notifier Settings - version2.16&2.18.
I can not set integration Token to it.
Can you give some suggestions?
![image](https://user-images.githubusercontent.com/16774155/53227568-80d80080-36b9-11e9-83a2-7fed4b01f585.png)

**Comment by timja** [comment]
it says right there, use a credential

**Comment by ihd2911** [comment]
In app credentails in slack there are many items, which one i need to pass in secret?

**Comment by timja** [comment]
Are you using a bot user?
if so then, I "think"
it's "Bot User OAuth Access Token"
on the "Oauth and permissions" page else try the other one (OAuth Access Token)

else if it's the slack app it's "Token"
