### ISSUE TITLE
How to have multiple slack integrations with Jenkins?

### ISSUE THREAD

**Issue by KristianWindsor** [jenkinsci/slack-plugin#532]
Under Global Slack Notifier Settings, there is only one text field for the integration token. How do I use this plugin for posting to multiple channels?

Eg:
- #web-builds
- #backend-builds
- #android-builds

**Comment by timja** [comment]
Configure it on each build, see the README
https://github.com/jenkinsci/slack-plugin#freestyle-job

**Comment by KristianWindsor** [comment]
Like this?
```
slackSend (token: 'abcdefghijk', channel: 'web-builds', message: 'hello')
```
And this will overwrite any values set in the Global Slack Notifier Settings?

**Comment by timja** [comment]
yes but don't use token, for most usecases you should set a credential id globally
If you really need another one you can pass the credentialId to slackSend
The snippet generator will show you all the available options

**Comment by raviseal** [comment]
incoming webhook of slack is mapped to a channel, so how can we use the same incoming webhook to integrate with multiple channels?

**Comment by KristianWindsor** [comment]
Can you send a link to the snippet generator?

I'm still confused on how to configure this plugin with multiple channels. It sounds like I need to configure globally the different tokens with credentialIds, and then reference that credentialId?

Like this?
```
slackSend (credentialId: 'slackTokenWeb', channel: 'web-builds', message: 'hello')
```

**Comment by timja** [comment]
Credentials aren't tied to channels.

you can either do:
`slackSend (channel: 'web-builds,web-builds2', message: 'hello')`

```
slackSend (channel: 'web-builds', message: 'hello')
slackSend (channel: 'web-builds2', message: 'hello')

```

**Comment by timja** [comment]
Snippet generator can be found on any pipeline job page
Click "Pipeline Syntax"
jenkins-url/job/<the-job>/pipeline-syntax/

**Comment by KristianWindsor** [comment]
Okay I figured this out. You just need one token, and you can just specify the channel/user that's to be messaged.

The problem I was having was that the global configuration was not inheriting to the pipeline, so everything needs to be defined explicitly.

This works for me:
```
WithCredentials([string(credentialsId: 'theSlackToken', variable: 'slackCredentials')]) {
    slackSend (channel: '@johnsmith', message: 'hello there', color: '#3eb991', failOnError: true, teamDomain: 'myteamsubdomain', token: slackCredentials)
}
```

**Comment by sarabesh** [comment]
I think @KristianWindsor is partially right, but only for public channels. If you want to send to multiple private channels, u have to use seperate tokens corresponding to each private channel.

**Comment by Er-rajsingh** [comment]
hii, how to use slack notification for multibranch pipeline build?
