### ISSUE TITLE
Response Code: 404

### ISSUE THREAD

**Issue by KristianWindsor** [jenkinsci/slack-plugin#533]
This happens when clicking the `Test Connection` button. 
```
<<HTML page of Slack's "There's been a glitch!" page>>
Mar 04, 2019 6:16:13 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Response Code: 404
Mar 04, 2019 6:16:18 PM WARNING jenkins.plugins.slack.StandardSlackService publish
```
This is a pretty generic error - what exactly is being returned with 404?

**Comment by timja** [comment]
the slack api, normally because there's an issue with the credentials

https://github.com/jenkinsci/slack-plugin/issues/500

Currently credentials need to be at the global level
