### ISSUE TITLE
Send message to specific channel on build failure

### ISSUE THREAD

**Issue by borsch** [jenkinsci/slack-plugin#537]
As a developer I would like to receive private messages from jenkins on specific build status

Example: I have a channel #A where jenkins sends build status, however this channel can be muted since this is a little bit annoying to read MOSTLY useless notifications(by "useless" I mean it's not useful to receive message that build is successful 50 times per day), but this messages still needed just to know that build is running by schedule.
I want to receive private message when build is failure

Is it possible to add ability to configure notification for different build status?

**Comment by timja** [comment]
with declarative pipeline or scripted pipeline using `slackSend` yes.
Using a freestyle project: no
