### ISSUE TITLE
Is it possible to deliver messages under "Jenkins" instead of "Slackbot"?

### ISSUE THREAD

**Issue by KristianWindsor** [jenkinsci/slack-plugin#538]
I got the slack plugin to work with my Jenkins. 
However, the messages are delivered under the user "Slackbot". Is it within the scope of this plugin to have the messages delivered under a user called "Jenkins"?

**Comment by timja** [comment]
Yes if you use a botUser
It's more complicated to setup, see:
https://github.com/jenkinsci/slack-plugin/pull/429#issuecomment-446413358
