### ISSUE TITLE
Validation: Prevent color property when attachments are specified

### ISSUE THREAD

**Issue by KamalAman** [jenkinsci/slack-plugin#543]
Given the following config, the notification will be sent without a color being specified. If the attainments is removed, that color attribute will work

v2.18
```    
  slackSend channel: "#channel",
                color: "#E22",
                message: "Test",
                attachments: []
```

**Comment by timja** [comment]
Hi, when you send attachments you have complete control over the attachments.
I don't think it really makes sense to modify them.

We could block this with a validation error,

but I'm leaning towards just allowing it for now

I've updated the docs to not have color in them when using attachments:
https://github.com/jenkinsci/slack-plugin/commit/a355391d98e57be50de2e2287c95e6b549271eca

Do you think more is needed?

**Comment by timja** [comment]
Closing based on docs update
