### ISSUE TITLE
Back to normal notifications missed

### ISSUE THREAD

**Issue by nsleigh** [jenkinsci/slack-plugin#544]
For our builds we allow more that one build of the same type to run at the same time. If a build has failed, then two further builds run (started at different times) then then "back to normal" message is not sent.

The following slack notifications are set:
- Notify Unstable
- Notify First Failure Only
- Notify Repeated Failure Only
- Notify Back To Normal

So the sequence is:
1. Build 1 run and fails
2. Build 2 runs
3. While build 2 is running build 3 starts
4. Build 2 completes and fixes the build - **this doesn't trigger the "back to normal"**
5. Build 3 completes - no message sent (as expected).

In the log I see a message like this - note this comes from build **# 91**.
[Slack Notifications] found **# 91** as previous completed, non-aborted build

Is there any way around this?

**Comment by timja** [comment]
I guess potentially the back to normal code could check previous builds if the result on previous build is pending,
this isn't something I've come across before though...

**Comment by nsleigh** [comment]
The problem seems to be that the following code returns the current build if the previous build is running:
`do {`
`    previousBuild = previousBuild.getPreviousCompletedBuild();`
`} while (null != previousBuild && previousBuild.getResult() == Result.ABORTED);`

Afraid I don't know enough java to fix it.
