### ISSUE TITLE
Sending messages to channels with all numbers is broken

### ISSUE THREAD

**Issue by zandersmith-wp** [jenkinsci/slack-plugin#565]
- [x] Jenkins version 2.164.2

- [x] Plugin version 2.22

- [x] OS ubuntu 18.04

### Description

After upgrading to version 2.22 of the plugin (from 2.18), it looks as though sending messages to channels that are named with all numbers (i.e. channel name: 1234) has stopped working.

I have tried to send messages via a curl command as well using both the channel name (1234), channel name with a leading '#' (#1234), and the channel id (GSDFSF213blah). See the example curl command that I was using:

`curl -X POST -H 'Content-type: application/json' --data '{"channel":"1234","text":"test blah blah blah"}' https://blah.slack.com/services/hooks/jenkins-ci\?token\=1234abcd`

The response is 'invalid_channel'.

**Comment by timja** [comment]
Not sure...

I was able to send to 1234
![image](https://user-images.githubusercontent.com/21194782/56636841-e87edd80-6661-11e9-8387-f0c0308c58a9.png)

**Comment by timja** [comment]
Works for me
