### ISSUE TITLE
Not enough instructions for thread support

### ISSUE THREAD

**Issue by IdanAdar** [jenkinsci/slack-plugin#566]
It's not totally clear how to setup the "botUser" needed for sending messages to a thread...

**Comment by tarvitz** [comment]
I just keep an issue here as it seems similar to my one.

### tl;dr
slackSend gets null for threadId, ts, channelId response.

### issue description
Here I got a following pipeline to send message by using:

```groovy
pipeline {
    agent {
        node {
            label "any-node"
        }
    }
    stages {
        stage("slack message") {
            steps {
                script {
                    def response = slackSend channel: "@auser", message: "testing message"
                    echo "response: ${response.threadId} ${response.ts} ${response.channelId}"
                }
            }
        }
    }
}
```

An output:
```
Slack Send Pipeline step running, values are - baseUrl: https://<cut>.slack.com/services/hooks/jenkins-ci/, teamDomain: iponweb, channel: @auser, color: <empty>, botUser: false, tokenCredentialId: jenkinsci-app-slack-token
[Pipeline] echo
response: null null null
```

### Software
- slack plugin version: 2.22
- jenkins version: 2.150.1

I've inspected documentation and found that threadId should work but it does not, please correct me if I got wrong. I've tried by using another slack plugin (a lower versions), used botUser flag but got no success. 

Anyways, the plugin is great, thanks for a hard work :+1:

**Comment by timja** [comment]
You need to create another slack application and configure a bot user on it and set bot user to be true

There's instructions here:
https://github.com/jenkinsci/slack-plugin/pull/429#issuecomment-446413358

But they need improving and adding to the README

**Comment by tarvitz** [comment]
Oh, I see it might help, will try soon enough.

**Comment by tarvitz** [comment]
@timja thanks, works perfectly with custom application and OAuth integration.
