### ISSUE TITLE
Where to put the configuration as code yaml file

### ISSUE THREAD

**Issue by ORESoftware** [jenkinsci/slack-plugin#569]
Sorry for boring question, re this section: https://github.com/jenkinsci/slack-plugin#configuration-as-code

where do we put that yaml file?
For example, with plugins.txt using Docker we would do:

```Dockerfile
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
```

is there a similar place we can put the CaC yaml file?

**Comment by timja** [comment]
Hi

https://github.com/jenkinsci/configuration-as-code-plugin#getting-started
> If you do not set the CASC_JENKINS_CONFIG environment variable, the plugin will default to looking for a single config file in $JENKINS_ROOT/jenkins.yaml.

I'm going to close this as its not related to the slack plugin specifically, there's a gitter chat room for questions like this:

https://gitter.im/jenkinsci/configuration-as-code-plugin

**Comment by darmbrust** [comment]
Can you update the readme to point to those docs linked above?  Came here with the same question...

**Comment by timja** [comment]
done
