### ISSUE TITLE
Ability to specify which slack channel Jenkins job sends to

### ISSUE THREAD

**Issue by apritykin** [jenkinsci/slack-plugin#571]
### Your checklist for this issue

- [ x] Jenkins version

- [ x] Plugin version

- [x ] OS

### Description
Jenkins version - 2.73.2

Plugin version - 2.23

OS Ubuntu

I am currently able to configure my Jenkins to send to a slack channel. What I was wondering is if it is possible to configure multiple channels and specify per Jenkins Job what channel to send to?

**Comment by timja** [comment]
Yes in the advanced option for each job you can configure it
