### ISSUE TITLE
attachments block doesn't seem to be working/docs are misleading

### ISSUE THREAD

**Issue by gilmoregrills** [jenkinsci/slack-plugin#573]
### Your checklist for this issue

- [x] Jenkins version
2.121.2

- [x] Plugin version
2.3

- [x] OS
Linux/Ubuntu

### Description

I'm trying to use the `attachments` option to send a couple of buttons with my messages but when I add them all that happens is no messages are sent. No errors are thrown, and I can't see anything in the logs. Am I using them right?

```
def inputMessageAttachments = [
    [
        text: "Do you wish to apply these changes?",
        fallback: "Approve/Deny the terraform changes <${env.BUILD_URL}/console/|here>",
        color: '#ff0000'
        actions: [
            {
                type = "button"
                text = "Approve"
                url = "${env.BUILD_URL}input/${approvalId}/proceedEmpty"
            },
            {
                type = "button"
                text = "Deny"
                url = s"${env.BUILD_URL}input/${approvalId}/abort"
            }
        ]
    ]
]
slackSend(channel: '#terraform', attachments: inputMessageAttachments)
```
I tried a few different permutations of the above, but no joy 🤷‍♀ 

Am I structuring, for example, the actions objects the right way? Does this plugin support adding actions like this? The README still references passing in a JSONArray as a string, so it feels like some of the documentation could do with an update! 

If anyone can give me any quick pointers I'd be happy to update the docs a little 👍 

Thanks in advance!

**Comment by timja** [comment]
Please test on the latest version before raising an issue.
The README targets the latest version	

Where do you see in the README attachments being passed as a string and not an object

**Comment by gilmoregrills** [comment]
The readme on master right now says "Additionally you can pass a JSONArray as a String in order to send complex messages"

**Comment by timja** [comment]
Thanks, fixed, it was left over from before it was reworked to allow passing an object

**Comment by gilmoregrills** [comment]
Nice! I'll give it a test with the latest version of the plugin too, I thought we were actually on the latest so that might be why it didn't work. 

I think it would still be good to get a more involved example in the readme too, I don't think it's super clear how nested action blocks for buttons etc should work.

**Comment by timja** [comment]
If you get something that you feel is worth adding then please add it to the README

**Comment by gilmoregrills** [comment]
Sure I will, as soon as I can find out how/if nested action blocks are supposed to work!

**Comment by ianfixes** [comment]
I'd be curious to see a working example of attaching a button to a slack message, I'm struggling with that now.

**Comment by AlexRoberts** [comment]
@ianfixes I was having issues with the same thing. Based on the jenkins errors I was getting, I assumed it wasn't liking the curly braces in the api example you linked, and I had to pull the double quotes as well. (note: I'm using declarative if that matters)

so 
```[
    {
      "fallback": "Book your flights at https://flights.example.com/book/r123456",
      "actions": [
        {
          "type": "button",
          "text": "Book flights 🛫",
          "url": "https://flights.example.com/book/r123456"
        }
      ]
    }
  ]
```
Would now be
```
[
    [
      fallback: "Book your flights at https://flights.example.com/book/r123456",
      actions: [
        [
          type: "button",
          text: "Book flights 🛫",
          url: "https://flights.example.com/book/r123456"
        ]
      ]
    ]
  ]
]
```
I'm still not sure if I'm doing all of this properly, so again it would be nice to get an example for declarative 😄

**Comment by AlexRoberts** [comment]
I'm also having issues getting buttons to show up when I pass an internal site into the `url` parameter. 
So, I tried to replicate the issue using google's website.

Button shows up when I use the following:
`https://www.google.com/`
`https://google.com/`
`http://google.com/`

but doesn't when I use 
`www.google.com/` or 
`google.com`

I am able to get my button to show up by using `https://${BUILD_URL}` but that link is pointless for me, as it ends up something like `https://http//myjenkins:8080/job/etc`

**Comment by casz** [comment]
@gilmoregrills see this https://github.com/jenkinsci/slack-plugin/issues/579#issuecomment-497911084
