### ISSUE TITLE
Create channel in slack from slacksend. 

### ISSUE THREAD

**Issue by yuvi3814** [jenkinsci/slack-plugin#575]
### Your checklist for this issue

- [ Jenkins ver. 2.164.3] Jenkins version

- [ 2.23] Slack Plugin version

- [ Windows] OS

### Description

Can we create a channel in slack using slacksend. For some builds it's better to create channels for sending notifications.

**Comment by timja** [comment]
with slackSend you can use the `channel` field to send it to whichever channel you wish

**Comment by yuvi3814** [comment]
> 
> 
> with slackSend you can use the `channel` field to send it to whichever channel you wish

Slacksend only sends to a existing channel in slack. I want to create a channel in slack using slacksend.

**Comment by timja** [comment]
not possible afaik.
probably out of scope for this plugin,

If you send a PR with an option for it I can take a look at it, but closing this as I don't think it belongs here
