### ISSUE TITLE
Attachment buttons don't show up depending on URL content

### ISSUE THREAD

**Issue by AlexRoberts** [jenkinsci/slack-plugin#579]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

- [2.17] Jenkins version

- [2.23] Plugin version

- [Windows Server 2012] OS

I'm having issues getting buttons to show up when I pass an internal site into the `url` parameter.
So I tried to replicate the issue using google's website.

Button shows up when I use the following:
`https://www.google.com/`
`https://google.com/`
`http://google.com/`

but doesn't when I use
`www.google.com/` or
`google.com`

I am able to get my button to show up by using `https://${BUILD_URL}` but that link is pointless for me, as it ends up something like **https://http//myjenkins:8080/job/etc**

**Comment by casz** [comment]
This is not really this plugin's fault.
Slack is saying you should really use https for all your web services.

My suggestion is you use something like nginx to reverse proxy your Jenkins instance adding HTTPs and while you are at it, nginx can also hide the port.

https://wiki.jenkins.io/display/JENKINS/Jenkins+behind+an+NGinX+reverse+proxy#JenkinsbehindanNGinXreverseproxy-RunningfromasubdomainwithSSL

**Comment by AlexRoberts** [comment]
Thanks a bunch! Fully qualified domain worked for me!
