### ISSUE TITLE
Job configuration not inheriting global

### ISSUE THREAD

**Issue by syphernl** [jenkinsci/slack-plugin#58]
The info/tooltip of team domain/token on the job configuration page mentions that it inherits the values from global. This doesn't appear to be case. With empty fields (except for channel) the test says "success" but no messages are delivered.

After filling in the domain and token it does properly send the message.

**Comment by samrocketman** [comment]
The Test Connection button is a work in progress.  #51 is attempting to address some of it.

In practice, it does inherit the values from global when you're actually using it.  The Test Connection is still not quite there as far as actually testing the connection and producing failures when it doesn't succeed.
