### ISSUE TITLE
Strange characters in message title

### ISSUE THREAD

**Issue by REBELinBLUE** [jenkinsci/slack-plugin#586]
After upgrading from 2.24 to 2.26 on Jenkins 2.180 our notifications sent with the plugin have a strange character in the message where the folder separator would be

They were yesterday showing fine as 

```Miscellaneous » Production Deploy Notification - #177 Success after 26 ms and counting```

now they are showing as

```Miscellaneous BAD+BB Production Deploy Notification - #186 Success after 0.26 sec and counting (Open)```

**Comment by timja** [comment]
Any chance you can look at this @EricBartusch probably a regression in your refactor?

**Comment by EricBartusch** [comment]
Yeah, for sure. I'll take a look today

**Comment by REBELinBLUE** [comment]
Thanks! I reverted to 2.24 and the messages are again as expected

```Miscellaneous » Production Deploy Notification - #213 Success after 51 ms and counting (Open)```

**Comment by casz** [comment]
@EricBartusch https://api.slack.com/docs/message-formatting#how_to_escape_characters
You have to escape `&`, `<`, and `>`

**Comment by REBELinBLUE** [comment]
Not sure if it matters but the message is being sent via a notification configured on the job rather than via a declarative pipeline, and I have a custom message set

**Comment by timja** [comment]
@REBELinBLUE any chance you can test the built artifact from the PR and see if it fixes it for you?
https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/PR-587/2/artifact/target/slack.hpi

**Comment by REBELinBLUE** [comment]
Yep that fixed it

**Comment by khitrenovich** [comment]
@timja We see the same issue after upgrade. Do you plan to release this fix as a version?

**Comment by timja** [comment]
released now, thanks for the nudge. 2.27

**Comment by khitrenovich** [comment]
Thanks!
