### ISSUE TITLE
Accents error on slack

### ISSUE THREAD

**Issue by imifarago** [jenkinsci/slack-plugin#589]
- [x] Jenkins version 2.176.1 (debian stretch stable)

- [x] Plugin version 2.26

- [x] OS Debian 9

### Description

Accented characters encode is wrong when sending it to slack api.
For example, "ó" is shown as "BAD+3" on slack channel. "á" is "BAD+1". "é" is "BAD+9" etc...

**Comment by timja** [comment]
Fixed in 2.27, see https://github.com/jenkinsci/slack-plugin/issues/586

**Comment by imifarago** [comment]
Thanks
