### ISSUE TITLE
Automatically setup any post-build steps

### ISSUE THREAD

**Issue by mcandre** [jenkinsci/slack-plugin#59]
As a Jenkins newbie, I want the Slack plugin to automatically setup any post-build steps for me. I don't want to have to explicitly add a Slack post-build step to every job I manage, and I keep forgetting to do this.

**Comment by samrocketman** [comment]
I don't actively develop this plugin.  I only maintain pull requests and releases.  You're welcome to contribute this feature!

**Comment by peergum** [comment]
Agreed. This would be a complex development considering customization options plus the fact not all jobs require notifications usually...

**Comment by timja** [comment]
closing as unlikely to be added
