### ISSUE TITLE
Test connection with integration token (with credential)

### ISSUE THREAD

**Issue by imifarago** [jenkinsci/slack-plugin#590]
- [x] Jenkins version 2.176.1 (debian stretch stable)

- [x] Plugin version 2.24+

- [x] OS Debian 9

### Description

It fails, because doesn't send the Integration Token value in the ajax. When you add it as credential and choose it from the list, the test works.

The error is: "Client error : the token with the provided ID could not be found and no token was specified". However it works fine on post-build

**Comment by timja** [comment]
please use a credential...
I'll try create a PR soon to make the UI clearer that you shouldn't use the token method.

**Comment by imifarago** [comment]
With credential it works. But there is an option to not use credential (or override it) which not works at the moment. Fix it, or remove it, please. It's deceptive. Thanks
