### ISSUE TITLE
iconEmoji does not work on threaded messages properly

### ISSUE THREAD

**Issue by ben-gineer** [jenkinsci/slack-plugin#591]
### Your checklist for this issue

- [ x ] Jenkins version

- [ x ] Plugin version

- [ x ] OS

### Description

I like the new iconEmoji feature for bot users. However, there is an issue when used with threaded messages.

The notification which starts the request correctly supports the iconEmoji option.
Individual responses to this thread correctly support the iconEmoji option.
However, a failed response which is also sent to the channel only shows the default bot emoji.

For example, in this excerpt of the thread list:

<img width="306" alt="Screenshot 2019-06-22 at 09 08 23" src="https://user-images.githubusercontent.com/4173590/59961270-6843ef80-94cd-11e9-9c5b-d5c0dfd3285c.png">

<img width="306" alt="Screenshot 2019-06-22 at 09 04 26" src="https://user-images.githubusercontent.com/4173590/59961214-c6240780-94cc-11e9-94e1-e3eb92f0b375.png">

In this image, DeadPool icon is used for FAILED/UNSUCCESSFUL builds, and WonderWoman for STARTED/SUCCESS - and this works correctly as a direct response. However, the last FAILED response, which is also sent to the room has the default emoji for the bot user, rather than the passed in DeadPool emoji.

I'm using Jenkins 2.181 on Ubuntu Linux, with Plugin version 2.27.

Thanks

**Comment by timja** [comment]
any idea @EricBartusch ?

**Comment by EricBartusch** [comment]
Not sure, I'll take a look

**Comment by EricBartusch** [comment]
@ben-gineer can I get the relevant pipeline script that you're using?

**Comment by ben-gineer** [comment]
Sure:

We have a slackMessage step which sits in a global library and decorates the standard slackSend step. This also handles passing in threadids from other builds if necessary:

```
def call(Map config) {

    final COLOUR = [
            START   : 'warning',
            SUCCESS : 'good',
            UNSTABLE: '#7a3fcd',
            FAILURE : 'danger'
    ]

    final EMOJI = [
            START   : 'wonderwoman',
            SUCCESS : 'wonderwoman',
            UNSTABLE: 'hulk',
            FAILURE : 'deadpool'
    ]

    final MESSAGE = [
            START   : 'started',
            SUCCESS : 'successful',
            UNSTABLE: 'unstable',
            FAILURE : 'failed'
    ]

    if (!config.type) {
        config.type = 'SUCCESS'
    }

    def channels = config.channels?."$config.type" ?: config.channels?.'default'
    def slackResponse = [:]
    def postChannels = []

    (config.threads) ? config.threads.each { k, v -> postChannels.add(v.threadId) } :
            channels.replaceAll("\\s", "").tokenize(',').each { postChannels.add(it) }

    postChannels.each {
        slackResponse[it] = slackSend
                color: COLOUR."$config.type", botUser: true,
                channel: it, iconEmoji: EMOJI."$config.type", username: 'Jenkins',
                replyBroadcast: (config.type == 'FAILURE'),
                message: "${BUILD_DISPLAY_NAME} "
    }
    return slackResponse
}
```

Our pipeline which starts the thread gets the threadID, and adds as a build parameter:
```
slackThreads = slackMessage type: 'START',
                        channels: chatChannels,
                        channelTokens: chatChannelTokens

                buildParameters << stringParam(name: 'THREADID', value: slackThreads['my-room'].threadId)
```

The all the child pipeline jobs use this threadId to respond. We initialize the slackThreads based on passed parameters (note this supports multiple channels):
```
def chatChannels = [
                    START   : 'my-room',
                    SUCCESS : 'my-room',
                    UNSTABLE: 'my-room',
                    FAILURE : 'my-room',
            ]

def chatChannelTokens = [
                    '#my-room'    : '1234567890'
            ]

def slackThreads = [:]
    if (params.THREADID) {
        slackThreads << ['my-room'    : [threadId: params.THREADID]]
    }
```

Then our pipeline calls the steps as follows:

```
stage('Notify') {
                steps {
                    slackMessage threads: slackThreads, type: 'START'
                            channels: chatChannels, channelTokens: chatChannelTokens
                }
            }
```

and then later:
```
post {
            always {
                slackMessage threads: slackThreads, type: currentBuild.result,
                        channels: chatChannels, channelTokens: chatChannelTokens
            }
        }
```

If you can't fathom out the logic here, I may be able to simplify this example.

I think the bit to check is what happens to the emojii when replyBroadcast is set to try, as this is posting back to the original channel, rather than the thread. This seems to be where the emojii is not being picked up.

Thanks

**Comment by EricBartusch** [comment]
Thanks for the detailed response.  

One thing before I try to dig into this more: In your screenshot above, Deadpool is being used as the unstable icon, but your config says that should be Hulk. Is that a change between a few days ago and now?  If not, that is a little suspicious.

**Comment by ben-gineer** [comment]
Ah yes. This was indeed a change I made this morning. Thanks for spotting this!

**Comment by EricBartusch** [comment]
I have a hunch that this is a bug in the Slack API.  I was able to recreate the issue by setting replyBroadcast to true while adding to a thread like you thought.  I took a look at the json created and the icon_emoji was properly set.

**Comment by EricBartusch** [comment]
This is a known issue with the Slack API.  I contacted them after reproducing it via their tester app on the Slack website.  Here's the response I got:
![image](https://user-images.githubusercontent.com/28985923/60216009-90fe1900-982e-11e9-981a-31996c9e4399.png)

**Comment by ben-gineer** [comment]
Thanks for following this up.

**Comment by timja** [comment]
I'm going to close this as it is a bug in an upstream API we have no control over. Feel free to contact them so you also get notified when it gets fixed.
