### ISSUE TITLE
A JSONObject text must begin with

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/slack-plugin#594]
### Your checklist for this issue

- [x] Jenkins version
2.176.1

- [x] Plugin version
2.27

- [x] OS
Linux

### Description

This pipeline code:
```
slackSend(
            channel: '@myownname',
            color: 'good',
            message: 'test',
            token: 'mytoken')
```

does send a message but logs this error in the build  console:
```
15:43:21  ERROR: Slack notification failed with exception: ok
15:43:21  ERROR: Slack notification failed. See Jenkins logs for details.
```

and this trace in Jenkins system logs:
```
Jul 04, 2019 3:43:21 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Error posting to Slack
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:214)
	at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:140)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:317)
	at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:255)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
```

**Comment by antoinepourriot** [comment]
Hi
i am also experimenting that same problem
Jenkins ver. 2.184
Slack Notification Plugin 2.27
RHEL 7.6

**Comment by ravanscafi** [comment]
I have the same problem too.

**Comment by sknight80** [comment]
I have the same problem, too.  I can not solve it either if I play with the params. :( The worst part is my pipeline job is failing because of this. :(

**Comment by timja** [comment]
Can you please post your full config?
Including global config?

I can't reproduce this with sensible config.

![image](https://user-images.githubusercontent.com/21194782/61321750-18bebe00-a804-11e9-9f81-6760be096791.png)

```
slackSend(
            channel: '@UET1JGZEZ',
            color: 'good',
            message: 'test',
            token: '****')
```

Note you shouldn't use token, use tokenCredentialId (I just used it because it was in the original report)

**Comment by ravanscafi** [comment]
Here's my config:

![image](https://user-images.githubusercontent.com/6104262/61322824-f23d5a80-a7e4-11e9-872d-dfcb0f0d17dc.png)

I'm using `tokenCredentialId` indeed. Please notice the bottom, if I hit "Test Connection" I get a `Failure: ok`.

**Comment by timja** [comment]
clear slack compatible app url, and are you actually using a bot user?
the url you have in your app url suggests it's not a bot user.

**Comment by ravanscafi** [comment]
Minimal config:
![image](https://user-images.githubusercontent.com/6104262/61323123-9a532380-a7e5-11e9-97ce-86a549fa9a88.png)

Test works:
![image](https://user-images.githubusercontent.com/6104262/61323170-ae972080-a7e5-11e9-9394-8698c1c9e0b5.png)

Bot user flag has no impact on messages.

**Comment by timja** [comment]
so is it working now?

**Comment by ravanscafi** [comment]
It works in the sense that the message is delivered as stated on the issue, but the response from plugin is an error.

**Comment by timja** [comment]
Works for me =/
https://jenkins-slack-plugin.slack.com/messages/CLA447541/
![image](https://user-images.githubusercontent.com/21194782/61323598-4dcd0f80-a808-11e9-9a71-3c16cffa894f.png)

**Comment by timja** [comment]
This is the block of code:
```
 if (botUser && entity != null) {
                    responseString = EntityUtils.toString(entity);

                    org.json.JSONObject slackResponse = new org.json.JSONObject(responseString);
                    result = slackResponse.getBoolean("ok");
                }
```

it can only be entered if botUser is true, can you try save your config?
possibly it hasn't been updated if you just modified it on the fly?

**Comment by ravanscafi** [comment]
Sorry, I was out of the company for an event. In fact, when I saved and tested, it worked as expected.

**Comment by rodrigc** [comment]
I'm seeing the same problem with Jenkins 2.176.2 and Slack plugin 2.27:


```
WARNING: Error posting to Slack
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
    at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
    at org.json.JSONObject.<init>(JSONObject.java:194)
    at org.json.JSONObject.<init>(JSONObject.java:321)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:214)
    at jenkins.plugins.slack.StandardSlackService.publish(StandardSlackService.java:140)
    at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:317)
    at jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:255)
    at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by rodrigc** [comment]
It looks like on this line: https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L214 the code tries to construct a JSON object from a response string.
However, the the response could possible not be a valid JSON string.

It looks like the code also does not check the status of the response when trying to create a JSON object.  I don't know if the server will always respond with a valid JSON string.

It would be nice to clean these stacktraces up, since I use slack in many Jenkins jobs, and I am seeing hundreds of these exceptions.

**Comment by timja** [comment]
the problem is in valid configurations it handles it fine but if there's invalid configurations it doesn't handle it well 😢 

invalid configurations:
1. using the base url when using slack
2. doing crazy stuff with job dsl
3. selecting bot user true when not actually using a bot user

I completely understand that there's limitations in the documentation / validations / I can't control whatever crazy groovy is run against the plugin but what I would like is validation as early as possible and a clear error message if the call is unlikely to succeed

**Comment by rodrigc** [comment]
@timja thank you for accepting my patch.  I am looking at the logs on my Jenkins server, and I am seeing this:

```
Jul 31, 2019 5:51:46 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed.  Invalid JSON response: ok
Jul 31, 2019 5:51:46 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed. Response: ok
Jul 31, 2019 5:51:46 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Response Code: 200
```

So it looks like sometimes Slack responds with `ok` but does not supply a valid JSON response?

**Comment by timja** [comment]
It looks like mis-configuration to me, if you use a bot user then slack responds with json, if you don't use a bot user then slack responds with plain text

can you check your config both global and pipeline, feel free to post here and I can double check it

**Comment by rodrigc** [comment]
I have:
![image](https://user-images.githubusercontent.com/1895943/62234255-2dac5d00-b37f-11e9-9d9e-87fd8669afc8.png)

If I click the *Test Connection* button, it displays *Failure: ok*.
However, the slack message goes through properly to the channel.

**Comment by rodrigc** [comment]
Seems like a known issue in the Slack API:
* https://github.com/slackapi/node-slack-sdk/issues/501
* https://github.com/slackapi/node-slack-sdk/pull/480

**Comment by timja** [comment]
1. clear slack compatible app url
2. which app are you using to add your jenkins configuration? the standard one or a custom one

**Comment by casz** [comment]
suggestion move "Slack compatiable app URL" to advanced?

**Comment by rodrigc** [comment]
@timja: If I clear out the slack compatible app url, I get:

```
{"ok":false,"error":"invalid_auth","warning":"missing_charset","response_metadata":{"warnings":["missing_charset"]}}
```

so I had to put that back in.


I followed the instructions at https://github.com/jenkinsci/slack-plugin/blob/master/README.md#install-instructions-for-slack

to install.

**Comment by rodrigc** [comment]
In the Jenkins logs, I'm still seeing:

```
Aug 23, 2019 10:31:20 PM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed.  Invalid JSON response: ok
```

**Comment by timja** [comment]
Can you update your screenshot on your config? What sort of format if your credential in? i.e how long is it and is there a prefix?

**Comment by rodrigc** [comment]
When I removed `Slack compatible URL`, I ran into the problems which I mentioned here: https://github.com/jenkinsci/slack-plugin/issues/594#issuecomment-524481612 so I had to put that back in.

In terms of my credential, it is a string which is 24 characters long.  The string is just a jumble of letters and numbers, and there is no prefix in the credential.

**Comment by timja** [comment]
Not at my computer for the next week or so but I don’t think the credential should be 24 characters long, but it should be gibberish.
(It’s possible slack changed it to be longer though)

I assume you’re using the “Jenkins CI” slack app?
Can you confirm you unticked bot user when you removed slack compatible app url?
And also that you’re on the latest version as the UI was reworked to hopefully simplify it
