### ISSUE TITLE
Exception attempting Slack notification: null

### ISSUE THREAD

**Issue by Juholei** [jenkinsci/slack-plugin#595]
### Your checklist for this issue

- [x] Jenkins version 2.184

- [x] Plugin version 2.27

- [x] OS Red Hat Enterprise Linux Server release 7.4

### Description

We have Slack notification configured in Job DSL for our jobs. The notifications show up in the Jenkins UI fine, and the testing them from there works. In real jobs however the result is this in the logs: 

`[Slack Notifications] Exception attempting Slack notification: null`

The jobs have notification configured like this under publishers:
```
            slackNotifier {
                notifyEveryFailure(true)
                notifyBackToNormal(true)
                notifySuccess(true)
                room(slackChannel)
                teamDomain(slackDomain)
                tokenCredentialId(slackCredentialId)
            }
```
where slackChannel, slackDomain and slackCredentialId are variables where the values are configured. These all show up correctly in the Jenkins UI.

If I go to manually configure the job and save it without changing anything, the notifications start working. This needs to be done after every time a job changes and as far as I can tell for each job, so it is not a solution. How to fix this?

**Comment by Sector14** [comment]
Jenkins ver. 2.176.2
Slack Notification Plugin 2.27
OS Debian Stretch

I've also run into this. Slack is configured in the global settings so job contains just the notification flags:

```
        slackNotifier {
          startNotification(true)
          notifyAborted(true)
          notifyBackToNormal(true)
          notifyEveryFailure(true)
          notifyFailure(true)
          notifyNotBuilt(true)
          notifyRegression(true)
          notifyRepeatedFailure(true)
          notifySuccess(true)
          notifyUnstable(true)
        }
```

The start notifications are coming through fine, but there are no failure or success notifications. Console log shows:

```
Finished Calculation of disk usage of workspace in 0 seconds
[Slack Notifications] found #1 as previous completed, non-aborted build
[Slack Notifications] will send OnBackToNormalNotification because build matches and user preferences allow it
[Slack Notifications] Exception attempting Slack notification: null
Finished: SUCCESS
```
As with above, if configure is clicked on the generated job and it's manually saved with no changes made, then a build started, all notifications come through without issue.

**Comment by timja** [comment]
That means your xml config isn't setup right, can you create the job again, and get the XML config from disk, then save it and compare them.

**Comment by Sector14** [comment]
Here's a diff from a seed created job xml vs same job after clicking configure then save:
```
6a7
>     <hudson.plugins.disk__usage.DiskUsageProperty plugin="disk-usage@0.28"/>
8c9,10
<       <projectUrl>https://github.com/User/repo_name</projectUrl>
---
>       <projectUrl>https://github.com/User/repo_name/</projectUrl>
>       <displayName></displayName>
10d11
<     <hudson.plugins.disk__usage.DiskUsageProperty plugin="disk-usage@0.28"/>
28c29
<         <gitTool>Default</gitTool>
---
>         <submoduleCfg class="list"/>
87a89,92
>       <baseUrl></baseUrl>
>       <teamDomain></teamDomain>
>       <authToken></authToken>
>       <tokenCredentialId></tokenCredentialId>
88a94
>       <room></room>
89a96,97
>       <iconEmoji></iconEmoji>
>       <username></username>
101a110
>       <commitInfoChoice>NONE</commitInfoChoice>
102a112,117
>       <customMessage></customMessage>
>       <customMessageSuccess></customMessageSuccess>
>       <customMessageAborted></customMessageAborted>
>       <customMessageNotBuilt></customMessageNotBuilt>
>       <customMessageUnstable></customMessageUnstable>
>       <customMessageFailure></customMessageFailure>
```
One of those is likely responsible for the null exception.

**Comment by timja** [comment]
Which is which? is there a null pointer in the system logs?

**Comment by Sector14** [comment]
The diff was
```
diff pre_save.xml post_save.xml
```
So the > will be items added after the manual save.

**Comment by timja** [comment]
Yes jenkins logs, hmm, try adding: commitInfoChoice('NONE')

**Comment by Sector14** [comment]
commitInfoChoice('NONE') didn't help. However, 
```
includeCustomMessage(false)
```
has solved the problem.

**Comment by Juholei** [comment]
@timja I'm not sure I agree with this being closed. Shouldn't there be default values that work without having to configure features to be off? I.e. if includeCustomMessage is not configured to be true, it should be treated as false instead of the notifications being broken.

Adding includeCustomMessage(false) didn't fix the issue for me, either. I'm trying now with similar configuration to what @Sector14 posted earlier, with the includeCustomMessage(false) added. Will report what happens.
