### ISSUE TITLE
How to send success notification to channelA and failure notification to channelB

### ISSUE THREAD

**Issue by mjai39** [jenkinsci/slack-plugin#596]
### Your checklist for this issue

- [2.92 ] Jenkins version

- [ 2.3] Plugin version

- [RHEL 7.5 ] OS

### Description

We have Jenkins jobs which is configured by code pipeline.presently we are sending notification to multiple channels , since i want to send only failure messages to development channel instead success. Please give me suggestion to use cases.

**Comment by EricBartusch** [comment]
You could put the slackSend step in a `post` block.  Take a look here: https://jenkins.io/doc/book/pipeline/syntax/#post

Put a slackSend to development channel in a `failure` block.
