### ISSUE TITLE
Attachments marked as required in Blue Ocean

### ISSUE THREAD

**Issue by ZebraFlesh** [jenkinsci/slack-plugin#599]
### Your checklist for this issue

- [2.187] Jenkins version

- [2.28] Plugin version

- [Amazon Linux 4.14.97-90.72.amzn2.x86_64] OS

### Description

When running in the Blue Ocean interface, the Attachments field is marked as required. It can be left blank or it can filled out with an empty JSON array (literally, `[]`) if you're not using it.

**Comment by timja** [comment]
No idea why =/
It's not marked as required:
https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
