### ISSUE TITLE
Notification to use full project name

### ISSUE THREAD

**Issue by dave-miles** [jenkinsci/slack-plugin#60]
We use the [CloudBees Folders Plugin](https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin) a lot. Folders typically contain a project named 'build'. At present notifications don't include the full project name so can be ambiguous.

**Comment by samrocketman** [comment]
That definitely sounds useful.  I don't currently develop this plugin.  I only maintain pull requests and releases.  You're welcome to contribute this feature!

**Comment by samrocketman** [comment]
I just noticed pull request #61.  I'll test it out and if it works properly then I'll merge your change.  Thanks.

**Comment by peergum** [comment]
This relates to the customization of messages. Making the project name display in full might not be suitable for everyone. For better compatibility this should be an option.

**Comment by samrocketman** [comment]
I put the tag in the wrong place :)

**Comment by samrocketman** [comment]
@peergum what's the difference between the two?  I assume one shows the full path and the other does not (pending my own testing).  I would think that would make sense.

The way I imagine it is projects are organized by folders (like GitHub orgs or groups).  So if the project with the same name is in two different folders then one would not be able to differentiate between the two.

I don't want to put in too many options.  I'm starting to feel the plugin has a lot of options already and don't want to paralyze plugin users with feature creep.  I'll test PR #61 and see how it compares with/without the folder plugin.  Feel free to peer review PR #61.

**Comment by s0undt3ch** [comment]
+1

**Comment by timja** [comment]
61 was merged and released
