### ISSUE TITLE
Slack Notification not sending out

### ISSUE THREAD

**Issue by eltonlauhk01** [jenkinsci/slack-plugin#605]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

- [2.189] Jenkins version

- [2.29] Plugin version

- [OSX] OS

From build log, it doesn't give any hint on why no message is sent
```
16:46:07 [Slack Notifications] found #2284 as previous completed, non-aborted build
16:46:07 [Slack Notifications] will send OnUnstableNotification because build matches and user preferences allow it
```

Try test connection at global config, return `fail`

Tried Bot token, and User token, both not working

**Comment by timja** [comment]
Could you try with this version and check your configuration is correct?
https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/master/194/artifact/target/slack.hpi

The UI has been improved to clarify what you should be setting

**Comment by eltonlauhk01** [comment]
> Could you try with this version and check your configuration is correct?
> https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/master/194/artifact/target/slack.hpi
> 
> The UI has been improved to clarify what you should be setting

2.30-SNAPSHOT (private-bfa37f50-jenkins) works fine

Minor issue is the Jenkins Configure System (/configure) > Slack > `Test Connection` will print out a lot of HTML formatted error message
the `Test Connection` function normally under `Project` (/job/PROJECT_NAME/configure)

**Comment by timja** [comment]
I've just tested the test connection and it works fine for me in the global configuration.

**Comment by eltonlauhk01** [comment]
cannot reproduce the issue today, thanks for the update
