### ISSUE TITLE
Slack plugin version 2.30 breaks slack integration

### ISSUE THREAD

**Issue by dashfwd** [jenkinsci/slack-plugin#609]
- [x] Jenkins version
2.189
- [x] Plugin version
2.30
- [x] OS
Amazon Linux
### Description

When upgraded to the 2.30 version of the Slack plugin, notifications stopped working.  Console log reports:

ERROR: Slack notification failed with exception: java.lang.IllegalArgumentException: the token with the provided ID could not be found and no token was specified

In "Configure System" there was no credential selected.  Trying to select one in the drop-down resulted in no selections.  Trying to add a new credential worked, but the credential still didn't appear in the list, regardless of scope (I tried both scopes).  Reloading the page didn't work.

The only thing that did work was downgrading to Slack Plugin v2.28 and then re-selecting the existing credential.

**Comment by timja** [comment]
Reproduced, taking a look

**Comment by timja** [comment]
Fix has been released at 2.31

**Comment by Speakus** [comment]
v.2.41 also have same issue. I have to rollback to v.2.40
