### ISSUE TITLE
Update README screenshots

### ISSUE THREAD

**Issue by OrangeDog** [jenkinsci/slack-plugin#615]
### Your checklist for this issue

- [ ] Jenkins version (N/A)

- [ ] Plugin version (N/A)

- [ ] OS (N/A)

### Description

The configuration screenshots in the current version of the README do not match the current version of the app. In particular the title of the section has changed and the insecure token field has been removed.

**Comment by timja** [comment]
send a PR to update it?

**Comment by casz** [comment]
Feel free to send a PR :)

**Comment by timja** [comment]
Send a PR please if you wish to update it, no need for an issue
