### ISSUE TITLE
Test connection always failure

### ISSUE THREAD

**Issue by Abel0916** [jenkinsci/slack-plugin#622]
### Your checklist for this issue

- [2.189] Jenkins version

- [2.32] Plugin version

- [ubuntu] OS

### Description
Attach my config for the slack notification. Test connection always reports failure.
1. Slack token config correctly
2. Slack jenkins integration is setup.

What's wrong with my setting? Thanks in advance.
![slack](https://user-images.githubusercontent.com/7677731/64146696-85dbf080-ce50-11e9-9260-9880a461157e.png)

**Comment by casz** [comment]
You forgot to enter a workspace 😬

**Comment by Abel0916** [comment]
Thanks @casz what value it would be for the workspace field. Folder path? like /home/administrator/

**Comment by Abel0916** [comment]
Thanks for your answer, it works after fill the team in the workspace field.
