### ISSUE TITLE
Slack response code 400, message null, when using blocks

### ISSUE THREAD

**Issue by emexelem** [jenkinsci/slack-plugin#623]
### Your checklist for this issue

- [x ] Jenkins version: 2.176.3

- [ x] Plugin version: 2.32

- [ x] OS: Docker container running on Ubuntu 18.04 behind nginx

### Description

Sending slack notifications using blocks results in an error, and the different error messages are not helpful to identify the cause. Slack seems to send back an empty response with code 400.

The pipeline:
```
def blocks = [
	[
		"type": "section",
		"text": [
			"type": "mrkdwn",
			"text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*"
		]
	]
]

slackSend failOnError: true, blocks: blocks
```

The build console:
```
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: nglora, channel: #ci-notifications, color: <empty>, botUser: false, tokenCredentialId: slack-nglora, notifyCommitters: false, iconEmoji: <empty>, username: <empty>
[Pipeline] End of Pipeline
ERROR: Slack notification failed. See Jenkins logs for details.
```

In Jenkins log:
```
Slack post may have failed. Response: null
Sep 04, 2019 8:00:10 AM WARNING jenkins.plugins.slack.StandardSlackService publish
Response Code: 400
Sep 04, 2019 8:00:10 AM INFO org.jenkinsci.plugins.workflow.job.WorkflowRun finish
```

**Comment by timja** [comment]
Does the example in the readme work for you?

**Comment by emexelem** [comment]
Nope it does not, same error

**Comment by timja** [comment]
Does the attachments example work or a simple message?

**Comment by emexelem** [comment]
Yes, message and attachments work

**Comment by timja** [comment]
K, I’m not at my computer till Sunday will try reproduce then / next week.

**Comment by rmg** [comment]
I ran in to this and did some digging and debugging with `curl`.. As far as I can tell, the `/services/hooks/jenkins-ci` API endpoint that this plugin uses doesn't actually support blocks. It appears to be based on the webhooks API and only supports the older [`attachments` based formatting](https://api.slack.com/docs/message-attachments). In case anyone else tries to replicate, here's a time saver: the API relies on the `token` parameter and completely ignores the `Authorization` header.

To send messages with blocks, the regular `chat.postMessage` API needs to be used, and that requires `botUser` mode :-(

The tests for the blocks feature appears to rely on mocks, which is how I suspect this was missed.

**Comment by timja** [comment]
Ah thanks, it was missed because I probably only tested it with the bot user...

Yes I would like to have some non mocked functional tests as well though 

I’ll leave this open till the docs are updated with the limitation

**Comment by pascal-hofmann** [comment]
For me this also does not work with `botUser`. I get:

> Sep 11, 2019 10:14:10 AM WARNING jenkins.plugins.slack.StandardSlackService publish
Slack post may have failed.  Invalid JSON response: no_text
Sep 11, 2019 10:14:10 AM WARNING jenkins.plugins.slack.StandardSlackService publish
Slack post may have failed. Response: no_text
Sep 11, 2019 10:14:10 AM WARNING jenkins.plugins.slack.StandardSlackService publish
Response Code: 400

Jenkins is configured via JCASC with these settings:
`  slackNotifier:
    baseUrl: https://…
    tokenCredentialId: slack-integration-token
    botUser: true`

And I used the blocks example from the docs.


I'm using plugin version 2.32.

**Comment by fowlie** [comment]
So using blocks is not possible with this plugin? Are there any plans to support it in the future as the Slack API will replace attachments with blocks?

**Comment by timja** [comment]
> So using blocks is not possible with this plugin? Are there any plans to support it in the future as the Slack API will replace attachments with blocks?

Blocks are supported if you have your own slack app,
The default slack app is not using the standard API and is built directly into the slack code and doesn't support attachments

**Comment by nikitamendelbaum** [comment]
"feature requires the botUser" label should probably be added to blocks feature in readme

**Comment by timja** [comment]
> "feature requires the botUser" label should probably be added to blocks feature in readme

@nikitamendelbaum can you take a look at https://github.com/jenkinsci/slack-plugin/pull/638 and see if it covers everywhere that would make sense?
