### ISSUE TITLE
Changelog.md is not being updated since v2.19

### ISSUE THREAD

**Issue by froblesmartin** [jenkinsci/slack-plugin#627]
- [ ] Jenkins version

- [x] Plugin version: >2.19

- [ ] OS

### Description

[Changelog.md](https://github.com/jenkinsci/slack-plugin/blob/master/CHANGELOG.md) has not been updated since this version: 2.19 release notes (2019-03-16). Is there any new place where you post the changes?

**Comment by timja** [comment]
![image](https://user-images.githubusercontent.com/21194782/65324046-ef733300-dba2-11e9-98f7-7b4a81895410.png)
