### ISSUE TITLE
slackUploadFile doesn't work with threads

### ISSUE THREAD

**Issue by jharveysmith** [jenkinsci/slack-plugin#630]
### Your checklist for this issue

- [ x] Jenkins version

- [ x] Plugin version 

- [ x] OS

### Description
Jenkins Version: 2.190.1
Plugin Version: 2.34
OS: Jenkins running on Linux (ubuntu 18.04), browser (my web client) running on OSX

slackUploadFile can't add a file to a thread.  slackSend can create and add messages to a thread in the same jenkins job.  slackUploadFile can upload a file to a channel just fine too in this job, just not to a thread.

I am using declarative pipeline.  I have tried using slackUploadFile inside and script block and as a standalone step.  same results.

**Comment by timja** [comment]
I don't think you can upload a file to a thread in slack itself? doesn't it require you to upload it to the main chat?

**Comment by jharveysmith** [comment]
> I don't think you can upload a file to a thread in slack itself? doesn't it require you to upload it to the main chat?

I tested and I can upload a file to a thread using the UI.
<img width="387" alt="Screen Shot 2019-10-01 at 12 06 39 AM" src="https://user-images.githubusercontent.com/6226895/65941241-70ba9900-e3df-11e9-8fda-098dcfb57299.png">
