### ISSUE TITLE
Unexpected `invalid_auth` from Slack

### ISSUE THREAD

**Issue by martinnj** [jenkinsci/slack-plugin#631]
### Your checklist for this issue

- [x] Jenkins version -> `2.196`

- [x] Plugin version -> `2.34`

- [x] OS -> `4.14.138-114.102.amzn2.x86_64` (Amazon Linux 2) but runs in an Alpine docker container build from the Jenkins Alpine dockerfile. The interface itself is accessed through an nginx reverse proxy.

### Description

After filling the slack workspace out, and creating and selecting a "secret text" containing the token given by the [Jenkins Slack App](https://clerk.slack.com/apps/A0F7VRFKN-jenkins-ci)
I originally got "Ok" when hitting "Test Connection".

However, after 5 minutes time it stopped working.
I have tried to recreate the Slack App to make sure the token was still live, and I checked that the saved token was correct using `println(hudson.util.Secret.fromString("{encrypted token text from secrets.xml}").getPlainText())`.
Copying that token and using "Find" in the Slack plugin configuration yields a hit on the token field. So they match.

The log doesn't give any deeply insightful information (Logging all from namespace `jenkins.plugins.slack`):
```
Posting: to  on clerk using https://slack.com/api/chat.postMessage:  good

Oct 02, 2019 10:29:57 AM WARNING jenkins.plugins.slack.StandardSlackService publish

Slack post may have failed. Response: {"ok":false,"error":"invalid_auth"}

Oct 02, 2019 10:29:57 AM WARNING jenkins.plugins.slack.StandardSlackService publish

Response Code: 200

Oct 02, 2019 10:29:58 AM FINE jenkins.plugins.slack.StandardSlackService

Posting: to  on clerk using https://slack.com/api/chat.postMessage:  good

Oct 02, 2019 10:29:59 AM WARNING jenkins.plugins.slack.StandardSlackService publish

Slack post may have failed. Response: {"ok":false,"error":"invalid_auth"}

Oct 02, 2019 10:29:59 AM WARNING jenkins.plugins.slack.StandardSlackService publish

Response Code: 200

```

I think I've been over all the possible hiccups that can be caused by misconfiguration. So I'm posting the issue here. Let me know if you need anymore information. Or if anyone has any tips.

Also, please let me know if this is the wrong way to go about it.

**Comment by timja** [comment]
It shouldn't be posting to `https://slack.com/api/chat.postMessage`

Untick the `Custom slack app bot user` box

If that doesn't work then screenshot your configuration please and post here

**Comment by martinnj** [comment]
Mhmm... It wasn't originally checked. But setting and unsetting it seemed to work.
```
Oct 02, 2019 10:51:41 AM FINE jenkins.plugins.slack.StandardSlackService

Posting: to  on clerk using https://clerk.slack.com/services/hooks/jenkins-ci?token=ghmyrwbvgRt93oKI2r3ZMCDr:  good

Oct 02, 2019 10:51:41 AM FINE jenkins.plugins.slack.StandardSlackService

Posting succeeded

```

The config xml also had: `<botUser>false</botUser>`
But it seems to be working allright now, thank you!

Do you want to look into it or is it too likely I messed up the config somewhere along the way?

**Comment by timja** [comment]
not really, just need to get rid of having both modes 😢
