### ISSUE TITLE
Global configuration is not working

### ISSUE THREAD

**Issue by tvishwanatharkin** [jenkinsci/slack-plugin#632]
### Your checklist for this issue

- [ 2.176.4] Jenkins version

- [2.34 ] Plugin version

- [ Ubuntu 16.04 ] OS (Jenkins Docker)

### Description

After adding the required details in the Slack Notifier configuration, Test Connection still fails. Below is the log output

Oct 03, 2019 5:47:06 AM jenkins.plugins.slack.StandardSlackService correctMisconfigurationOfBaseUrl
WARNING: Overriding base url to team domain 'xxxx' this is due to mis-configuration, you don't need to set base url unless you're using a slack compatible app like mattermost
Oct 03, 2019 5:47:06 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Slack post may have failed. Response: null
Oct 03, 2019 5:47:06 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Response Code: 400

<img width="1308" alt="Screenshot 2019-10-03 at 11 15 03 AM" src="https://user-images.githubusercontent.com/23732956/66102547-5eec1800-e5d0-11e9-8502-3f7f06729cbf.png">

**Comment by casz** [comment]
Could you share your global config?

**Comment by casz** [comment]
Sounds like `Override url` is not empty. Can you please try and delete any content in that field and save again?

**Comment by tvishwanatharkin** [comment]
No luck even after setting override url as empty. Not sure if I'm missing any field.
In fact, the form doesn't contain override url. Test Connection is a pre-save action isn't it? So it should consider only the fields populated in the form

**Comment by timja** [comment]
anything in the logs?

**Comment by casz** [comment]
What is saved in the slack plugin XML file on disk?

**Comment by tvishwanatharkin** [comment]
I didn't troubleshoot it further. I just cleared the jenkins data volume and recreated it. It works fine now. However, wouldn't a 400 Bad Request from Slack contain some error? It can actually be shown in the logs. Ex: Auth error, default channel doesn't exist etc

**Comment by casz** [comment]
400 bad request can also come from the Java Library 😉

**Comment by tvishwanatharkin** [comment]
Closing as the issue is fixed
