### ISSUE TITLE
Ability to choose between JobURL, RunURL

### ISSUE THREAD

**Issue by alekskar** [jenkinsci/slack-plugin#634]
#### Feature request 
If Blue Ocean is installed default `Open` URL points to Blue Ocean endpoint.

``` 
       public MessageBuilder appendOpenLink() {
            String url = DisplayURLProvider.get().getRunURL(build);
            message.append(" (<").append(url).append("|Open>)");
            return this;
        }
```
[Code link](https://github.com/jenkinsci/slack-plugin/blob/c74472b77e0ce9f20c2486407810fb9aed6969b9/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L416:L419)
It would be great if GUI setting provides ability to modify this behavior and pick up ```getJobURL(build)``` method based on drop down menu  and point to standard Jenkins endpoint. 
Thanks in advance!

**Comment by timja** [comment]
Why? If you don't want it to go there you can uninstall blue ocean.

**Comment by casz** [comment]
As a user, you can change your preference for dispaly url.

The URL to do this is: `https://YOUR_JENKINS_URL/me/configure`

![image](https://user-images.githubusercontent.com/1661688/67222440-9e6a8f00-f42d-11e9-9a44-96beca4ecb4f.png)
