### ISSUE TITLE
"Global Slack Notifier Settings" does not appear in "Configure System"

### ISSUE THREAD

**Issue by ernix** [jenkinsci/slack-plugin#639]
### Your checklist for this issue

- [x] Jenkins version
Jenkins ver. 2.190.2

- [x] Plugin version
2.34

- [x] OS
CentOS Linux release 7.4.1708 (Core)

### Description

As the title said, it seems Jenkins is holding an old configuration after the update of this plugin.  There is no "Global Slack Notifier Settings" section, but "Slack".

<img width="741" alt="Screen Shot 2019-11-15 at 14 27 46" src="https://user-images.githubusercontent.com/343556/68919867-df4c8e00-07b6-11ea-8e23-44f44d6fa0e3.png">

How can I setup integration token?

**Comment by timja** [comment]
It’s now just called slack, I see one screenshot in the readme that needs updating is that why you thought you were using an on old version?

**Comment by ernix** [comment]
I thought Jenkins was "kindly" keeping plugin configuration after reinstall them.  The message, I got while removing plugins, has fooled me quite a long time.
https://wiki.jenkins.io/display/JENKINS/Removing+and+disabling+plugins
> Uninstalling a plugin, however, does not remove the configuration that the plugin might have created.

I've just solved the problem, Thanks anyway.
