### ISSUE TITLE
slackUploadFile is not working at all

### ISSUE THREAD

**Issue by madhukar93** [jenkinsci/slack-plugin#640]
### Your checklist for this issue

- [x] Jenkins version
Jenkins 2.191

- [x] Plugin version
Slack Notification Plugin 2.34

- [x] OS
 OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.4.0-1050-aws

### Description
slackUploadFile doesn't seem to be working.
```
slackUploadFile filePath: 'envs_to_delete.txt', initialComment: 'these environments will be deleted unless deployed to', channel: "${slack_channel}"
```

Though I see the log
<img width="743" alt="slack-upload-log" src="https://user-images.githubusercontent.com/7714050/69048535-b846c400-0a23-11ea-8008-0f1c0457c225.png">

slackSend works
```
slackSend channel: "${slack_channel}", color: "bad", message: "mft env cleanup job failed"
```
<img width="211" alt="slack-message" src="https://user-images.githubusercontent.com/7714050/69048606-e4fadb80-0a23-11ea-9557-db5b6503cf51.png">

I haven't seen anything interesting in the Jenkins server log to be able to tell if anything is going wrong.

**Comment by timja** [comment]
Have you created your own custom slack app and configured it?
> This feature requires botUser mode.

**Comment by madhukar93** [comment]
ah, that might be it

**Comment by kobozo** [comment]
Did you manage to get this working?

> ah, that might be it, missed this in the log.
> I'm using slack's jenkins app
> <img alt="jenkins-slack-app" width="749" src="https://user-images.githubusercontent.com/7714050/69051612-d2d06b80-0a2a-11ea-8404-1f7ab7bc2923.png">

**Comment by timja** [comment]
docs:
https://github.com/jenkinsci/slack-plugin#bot-user-mode
