### ISSUE TITLE
Requires administer permission to test connection with slack.

### ISSUE THREAD

**Issue by kool79** [jenkinsci/slack-plugin#641]
- [x] Jenkins version: 2.204
- [x] Plugin version latest at the moment 
- [x] OS jenkins: lilnux, client: win7x64, chrome

### Description
1. configure post-build notifications 
2. click "Test Connection"
3. expand "ERROR" link: 

![Screenshot - 18_11_2019 , 19_56_05](https://user-images.githubusercontent.com/4625317/69077307-05379400-0a3e-11ea-80a3-550ee80253f5.png)

**Comment by timja** [comment]
Not sure how you're hitting this, I was unable to reproduce it on 2.204
Can you please specify the actual plugin version and not latest?

The permissions I used to test it was:
![image](https://user-images.githubusercontent.com/21194782/69085220-95c1a480-0a3d-11ea-97b1-20d4e8397e6f.png)

What type of job are you configuring?

**Comment by timja** [comment]
Unable to reproduce, if you can provide more details please re-open with them
