### ISSUE TITLE
Test connection always reports failure

### ISSUE THREAD

**Issue by jjvdgeer** [jenkinsci/slack-plugin#645]
### Your checklist for this issue

- [x] Jenkins version 2.205

- [x] Plugin version 2.34

- [x] OS Windows 2012 R2

### Description

We had a working Jenkins/Slack integration until I did an update of Jenkins & plugins on 15.feb. Since then the integration hasn't worked anymore. I don't recall what versions I updated from, but I usually do updates every few days.

The configuration looks like this now:

![image](https://user-images.githubusercontent.com/10046122/69227851-d545d900-0b82-11ea-8682-830b8d81dc4b.png)

The credentials look like this:

![image](https://user-images.githubusercontent.com/10046122/69228307-9ebc8e00-0b83-11ea-8707-9b012c234111.png)

The integration settings look like this:

![image](https://user-images.githubusercontent.com/10046122/69228005-1f2ebf00-0b83-11ea-9f13-9f17a49420a5.png)

Any idea what is wrong here?

**Comment by timja** [comment]
Is there anything in the server logs?

**Comment by jjvdgeer** [comment]
Which log where? The logs I find in C:\Jenkins\logs\tasks that are updated today only contained som Started & Finished entries.

I tried again now, but for some reason the result now was an error (the screenshot says just 'Failure' but earlier on I'm pretty sure it showed some json stuff, but I couldn't reproduce that anymore).

Anyway, the error I get now says:

Test Connection
ERROR
HTTP ERROR 403 No valid crumb was included in the request
URI:	/descriptorByName/jenkins.plugins.slack.SlackNotifier/testConnection
STATUS:	403
MESSAGE:	No valid crumb was included in the request
SERVLET:	Stapler
Powered by Jetty:// 9.4.22.v20191022

Hm, thinking about it, this probably has something to do with me removing one of the Slack integrations as there were multiple, just in case that was the problem. But that problem seems now to have disappeared again. Might be a red herring, unsure.

**Comment by timja** [comment]
That error normally means one of two things:
1. your session has expired but you still have a page loaded, refresh the page to fix it
2. you have a reverse proxy which isn't handling the csrf tokens properly

**Comment by jjvdgeer** [comment]
We're not using a reverse proxy. But as I had lunch between the first error and the last, it seems probable there was an expired session. So it was a red herring, I suppose... But the initial problem remains.

**Comment by timja** [comment]
By logs I mean jenkins system logs, i.e. /var/log/jenkins/jenkins.log or equivalent or from viewing the logs in the UI

**Comment by jjvdgeer** [comment]
We're on Windows. I don't seem to find a file called jenkins.log, but there's a jenkins.err, it shows:

2019-11-20 11:47:25.664+0000 [id=11]	WARNING	j.p.slack.StandardSlackService#publish: Slack post may have failed. Response: null
2019-11-20 11:47:25.667+0000 [id=11]	WARNING	j.p.slack.StandardSlackService#publish: Response Code: 404

It looks identical to what the log through the UI shows.

**Comment by timja** [comment]
I assume there's something wrong in the config, can you update the credential to the value that slack gives you the "Token" field

And also try saving the jenkins global config

**Comment by jjvdgeer** [comment]
I've added and removed tokens several times without luck.

When you say saving the jenkins global config, you mean press the 'Save'-button before trying the 'Test connection' button, right? I've done that as well...

**Comment by timja** [comment]
does this help at all?
https://github.com/jenkinsci/slack-plugin/pull/646

**Comment by jjvdgeer** [comment]
Hmm, that's interesting. I added the extra logging and I see the URL that apparently is used:

nov 20, 2019 1:53:02 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #amis_builds on csam using https://csam.slack.com/services/hooks/jenkins-ci?token=********:  good
nov 20, 2019 1:53:03 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Slack post may have failed. Response: null
nov 20, 2019 1:53:03 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Response Code: 404

The part that is interesting is the token in the URL that I replaced with '********'. It is not the Slack token but it is my domain password. However, I've chosen the correct credentials in the settings UI... So it seems to be retrieving the wrong credentials for some reason.

**Comment by timja** [comment]
Yeah it's normally the token that is the interesting part, often it's null or the wrong token being used.

Any chance your browser is autofilling it when you save the credential?
Could you try use a different browser to update it possibly?

You're definitely using the right credential?

Try create a new one?

**Comment by jjvdgeer** [comment]
Hmm... I didn't think I was using fancy auto-fillin password stuff. However, using Chrome seems to work just fine. But not in my browser Vivaldi (which is based on Chromium as well).

So what's the problem here? Are the credentials being saved with something else than what I'm filling out in the webpage?

**Comment by jjvdgeer** [comment]
I've been experimenting a bit more. When I add credentials in Vivaldi, and go in the 'Secret'-field and type one character, a lot of * appear in the field, indicating that it is auto-filling in the password. Strange, I've never seen this behavious before. It usually has the password pre-filled in, not when you start typing it... Unsure what is happening here.

I didn't notice this before, as I just copy/pasted the password so it wasn't obvious to me it was using the wrong password.

Thanks for the help. Maybe I should raise this for the Vivaldi team...

**Comment by timja** [comment]
The latest version of jenkins (2.205) has a UI re-work to try stop browsers doing that:
https://jenkins.io/changelog/

**Comment by jjvdgeer** [comment]
Hmmm... but I am on 2.205...

**Comment by timja** [comment]
I guess it's more to stop inadvertent credential auto fill, but your browser changing it when you're trying to put something in isn't the intent of the feature:

![image](https://user-images.githubusercontent.com/21194782/69260625-1a383280-0bb8-11ea-9bca-8375b3e5650e.png)

**Comment by jjvdgeer** [comment]
That is not how it looks when one adds a new credential, which is what I was doing.
![image](https://user-images.githubusercontent.com/10046122/69408816-fb48b600-0d07-11ea-9ebe-9bafece659f5.png)

Press 'A' and it looks like this:

![image](https://user-images.githubusercontent.com/10046122/69408869-14e9fd80-0d08-11ea-978e-0f22b054865a.png)

**Comment by timja** [comment]
Closing anyway as it's fixed
