### ISSUE TITLE
Response: null, Response Code: 404 and Response: {"ok":false,"error":"invalid_auth"}

### ISSUE THREAD

**Issue by gremito** [jenkinsci/slack-plugin#649]
## overview
The settings were made with reference to the README.
but, when I run "Test Connection", I get the following error:

`Custom slack app bot user` -> OFF
```
WARNING j.p.slack.StandardSlackService#publish: Slack post may have failed. Response: null
WARNING j.p.slack.StandardSlackService#publish: Response Code: 404
```

`Custom slack app bot user` -> ON
```
WARNING j.p.slack.StandardSlackService#publish: Slack post may have failed. Response: {"ok":false,"error":"invalid_auth"}
WARNING j.p.slack.StandardSlackService#publish: Response Code: 200
```

`Settings`
<img width="476" alt="スクリーンショット 2019-12-19 14 14 15" src="https://user-images.githubusercontent.com/7971858/71146956-916dee80-226a-11ea-8e27-421de50ee993.png">

`.jenkins/jenkins.plugins.slack.SlackNotifier.xml`
```
<?xml version='1.1' encoding='UTF-8'?>
<jenkins.plugins.slack.SlackNotifier_-DescriptorImpl plugin="slack@2.35">
  <baseUrl></baseUrl>
  <teamDomain>[Workspace]</teamDomain>
  <tokenCredentialId>slack-token</tokenCredentialId>
  <botUser>false</botUser>
  <sendAsText>true</sendAsText>
  <iconEmoji></iconEmoji>
  <username></username>
  <room>#bot</room>
</jenkins.plugins.slack.SlackNotifier_-DescriptorImpl>
```

## env

- OS
  - macOS 10.15.1
- Jenkins 
  - 2.190.2
- slack-plugin
  - 2.35
- Maven 
  - 3.6.3
- Java
  - 11.0.2

## Description

The situation did not change even after uninstalling and installing again.
Also, I checked the following issue and did not resolve it.

- https://github.com/jenkinsci/slack-plugin/issues/323
- https://github.com/jenkinsci/slack-plugin/issues/480
- https://github.com/jenkinsci/slack-plugin/issues/525
- https://github.com/jenkinsci/slack-plugin/issues/594
- https://github.com/jenkinsci/slack-plugin/issues/623
- https://github.com/jenkinsci/slack-plugin/issues/631

**Comment by casz** [comment]
Did you approve the Jenkins app? `https://YOURWORKSPACE.slack.com/services/new/jenkins-ci`
Or have you created a custom slack app?

**Comment by gremito** [comment]
Thanks! Jenkins CI approved but did not create a custom Slack bot.
I finally understood the meaning of the legacy, and when I made a custom Slack bot, I succeeded in "Test Connection".

<img width="456" alt="スクリーンショット 2019-12-19 15 37 35" src="https://user-images.githubusercontent.com/7971858/71150765-a2702d00-2275-11ea-880e-8ad4ecac8930.png">
<img width="360" alt="スクリーンショット 2019-12-19 15 32 23" src="https://user-images.githubusercontent.com/7971858/71150671-676df980-2275-11ea-963b-fdb25f068eb0.png">

**Comment by timja** [comment]
Did you miss the docs in the readme or were they confusing? They were recently updated to add more info on this

**Comment by gremito** [comment]
I couldn't understand what the "legacy" was showing. So, I felt it would be better to explain the old version and the current setting method a little more clearly.
