### ISSUE TITLE
Call to contributors: document options

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#65]
This is a request to Jenkins Slack Plugin contributors to create jelly documentation for the plugin options.  I believe this would improve the overall user experience if some or all options included a help doc explaining what that option does.

The expected behavior is to be able to click the help button next to the option.  Here's a screen shot showing an example.

![jenkins_slack3](https://cloud.githubusercontent.com/assets/875669/6519746/be89c4ea-c386-11e4-92a9-7d0232a841ad.png)

All contributions welcome.  If you would like to be invited to the [Jenkins plugin slack](https://jenkins-slack-plugin.slack.com/) then let me know.  That slack org is meant to assist contributors with testing changes.

**Comment by timja** [comment]
Closing as all fields have help now, some PRs have been merged recently to improve the docs also
