### ISSUE TITLE
How to use notifyCommitters?

### ISSUE THREAD

**Issue by semenmiroshnichenko** [jenkinsci/slack-plugin#651]
# Your checklist for this issue

- [x] Jenkins version 2.209

- [x] Plugin version 2.35

- [x] OS Ubuntu 16.04

### Description

We are using Jenkins pipeline and want to notify the developer who made a commit about issues with their commit (if any). For doing that, I configured my Slack Id in my Jenkins Account like so 
![image](https://user-images.githubusercontent.com/3511513/71255930-a82a4900-232f-11ea-9705-a22c50666844.png) and asked other developers to do the same.

Then I set up a custom Slack app as described here https://github.com/jenkinsci/slack-plugin#bot-user-mode 

Now I can send private messages to users in our organization by it's slack id:
`slackSend channel: '<SlackId>', message: "Hello, Jenkins here!"`

But I want to notify the commiter. This `slackSend notifyCommitters: true, message: "Build done"` does not work: 

> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] stage
> [Pipeline] { (Notify)
> [Pipeline] slackSend
> Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: *********, channel: , color: <empty>, botUser: true, tokenCredentialId: ******************, notifyCommitters: true, iconEmoji: <empty>, username: <empty>
> ERROR: Slack notification failed with exception: {"ok":false,"error":"channel_not_found"}
> ERROR: Slack notification failed. See Jenkins logs for details.
> [Pipeline] }

How to configure it to notify committers but not use any channel?

**Comment by pramodhkp** [comment]
I have the same issue. Does anyone have an idea?

**Comment by timja** [comment]
Might be a bug, will check after holiday period

**Comment by casz** [comment]
in the meantime feel free to contribute, I can definitely approve any merge request (could look into getting release rights) 🙈

**Comment by timja** [comment]
Just did some testing on this, the most likely issue is that you need to select a "User ID resolver" in the advanced settings of the slack plugin.

Something else I noticed was that it doesn't work if you edit the file through GitHub, there's two fields that are set by the API, authorEmail and committerEmail.

If you edit it through the GitHub UI then the authorEmail is set to noreply@github.com and this functionality won't work. Possibly somewhere else in Jenkins should be updated to always look at the committerEmail field and ignore the authorEmail field

**Comment by semenmiroshnichenko** [comment]
I selected a "User ID resolver" checkbox and it works, thanks a lot!

**Comment by kenga** [comment]
Hi @casz / @timja , 
I found the plugin has code trying to resolve user's email in order to query slack for the user ID (i.e. slack workspace member ID):
https://github.com/jenkinsci/slack-plugin/blob/4eb91cac23b47ec7e603c36c9d59fdc7a8331f3c/src/main/java/jenkins/plugins/slack/user/EmailSlackUserIdResolver.java#L96

As shown in the above code, it loops through all available MailAddressResolver instances to try resolve the email address of the author of the commit. However, in my environment, we don't have any MailAddressResolver instances. Therefore this code does not always work, and it misses that the author email may actually be available in the commit. As checked, `MailAddressResolver.resolve(user)` did that before looping thru MailAddressResolver instances. By using `MailAddressResolver.resolve(user)`, i guess your code can be simplified a bit. But I am not sure if there is any reason for you not to use `MailAddressResolver.resolve(user)` directly. 

Please kindly help to check. Thanks for the good work!

**Comment by casz** [comment]
Because the code is designed to support different resolver.
Internally we have resolver using our Active Directory to lookup slack ids as we store users slack ids in our AD.

**Comment by kenga** [comment]
Yes @casz , but I think `MailAddressResolver.resolve(user)` has that logic too:
https://github.com/jenkinsci/mailer-plugin/blob/fd24527efb52d80649bbe7c4d2a9faa751b95c0d/src/main/java/hudson/tasks/MailAddressResolver.java#L123

**Comment by casz** [comment]
That the same logic as here: https://github.com/jenkinsci/slack-plugin/blob/4eb91cac23b47ec7e603c36c9d59fdc7a8331f3c/src/main/java/jenkins/plugins/slack/user/EmailSlackUserIdResolver.java#L62

**Comment by casz** [comment]
Please see: https://jenkins.io/doc/developer/extensions/mailer/ for reference

**Comment by kenga** [comment]
Thanks for the prompt reply.
Yes, I also noticed that. May I know any reason why not get the user email available directly in Jenkins, as in `MailAddressResolver.resolve(user)`?
https://github.com/jenkinsci/mailer-plugin/blob/fd24527efb52d80649bbe7c4d2a9faa751b95c0d/src/main/java/hudson/tasks/MailAddressResolver.java#L118

**Comment by casz** [comment]
Because as a dev I want to control which mail resolver I use.
I don't necessarily want to use MailAddressResolver.all() but rather LDAP's MailResolver directly.

**Comment by casz** [comment]
The code could be adapted to include the same code that is marked private sadly:
https://github.com/jenkinsci/mailer-plugin/blob/fd24527efb52d80649bbe7c4d2a9faa751b95c0d/src/main/java/hudson/tasks/MailAddressResolver.java#L183-L188

Feel free to send a PR.

**Comment by agaudreault-jive** [comment]
We have the same issue, we dont have any `MailAddressResolver`, but the Email User property is set correctly by other plugins. I dont think the goal of this plugin should be to resolve the User Email property again, but it should simply use the property when it is set.

Calling `MailAddressResolver.resolve(user)` seems like the best option and I dont understand why it would cause problem.
