### ISSUE TITLE
Jenkins-Slack integration as normal user or workspace owner/admin?

### ISSUE THREAD

**Issue by rodrigc** [jenkinsci/slack-plugin#656]
### Your checklist for this issue

- [2.204.1 ] Jenkins version

- [ 2.35] Plugin version

- [Linux ] OS

### Description

If I go to https://my.slack.com/services/new/jenkins-ci , and create an integration
under my user id (which is not a workspace owner or admin),
the default Slack behavior from Jenkins seems to restricted to channels that I am already in or
have access to.  For example, I need Jenkins to be able to send to private slack channels which I (as a normal user id) am not a member of.

If I want Jenkins to be able to slackSend() to any user or channel on a particular Slack workspace,
do I need to do the integration as a workspace owner or admin?

**Comment by timja** [comment]
that’s more of a question for slack, we just use the api they control the permissions side, if you are using an app you need to invite the user into the channel.

Last time I tried with the legacy integration you could message in any channel
