### ISSUE TITLE
Blocks don't accept JSON as string

### ISSUE THREAD

**Issue by floriangosse** [jenkinsci/slack-plugin#657]
### Your checklist for this issue

- [x] Jenkins version
2.204.1
- [x] Plugin version
2.35
- [x] OS
Linux

### Description

We use external files that generate the content for the messages we're sending. Right now we're using attachments which work find. But we want to change them to blocks which don't work in the same way.

Our scripts output simple JSON as a string which then is passed to `slackSend`. If we try to the same with blocks we get the following error:

```
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain:[TEAM-DOMAIN], channel: [CHANNEL], color: <empty>, botUser: true, tokenCredentialId: [TOKEN-CREDENTIAL-ID], notifyCommitters: false, iconEmoji: <empty>, username: <empty>
ERROR: Slack notification failed with exception: net.sf.json.JSONException: Invalid JSON String
ERROR: Slack notification failed with exception: {"ok":false,"error":"no_text"}
ERROR: Slack notification failed. See Jenkins logs for details.
```

I was able to reproduce it without any external tools just with the following instruction:

```groovy
slackSend(
    channel: '[CHANNEL]',
    blocks: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"plain_text\",\"text\":\"This is a plain text section block.\",\"emoji\":true}}]}"
)
```

**Comment by timja** [comment]
Hi, 

That's a deprecated feature of attachments and no plans for it to be implemented for blocks.

It's far simpler for people to just use plain groovy objects to format their message.

**Comment by floriangosse** [comment]
Thanks for the quick answer @timja.

It's sad that it's not possible anymore. This way we have to bloat up our Jenkinsfile instead of having the blocks generation in separate script files.

**Comment by timja** [comment]
I'm going to close this for now, if there's enough people who want this someone can contribute it, but currently no plans to support it
