### ISSUE TITLE
Notification "Notify Repeated Failure" checkbox is not saving

### ISSUE THREAD

**Issue by o5** [jenkinsci/slack-plugin#66]
Steps to reproduce:

1) Click to **Configure** job
2) Check **Notify Repeated Failure** in **Slack Notification**
3) Click to **Save**
4) **Include Test Summary** value is saved instead of **Notify Repeated Failure**

```
Slack Notification Plugin 1.7
Jenkins ver. 1.600
```

**Comment by samrocketman** [comment]
Pull request #63 addresses this.  Thanks for the report.

**Comment by samrocketman** [comment]
Hello, 1.8 has been released.  Can you please confirm that this bug is fixed for you?  My testing shows that it has.
