### ISSUE TITLE
Failure: {"ok":false,"error":"invalid_auth"} for Jenkins CI generated token

### ISSUE THREAD

**Issue by jianzhangbjz** [jenkinsci/slack-plugin#660]
### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] OS

### Description
By following this https://plugins.jenkins.io/slack, I generated a token via Jenkins CI:
![image](https://user-images.githubusercontent.com/15416633/73545415-47397900-4476-11ea-9983-552c39b5ca83.png)
And, set it in my Jenkins Credentials:
![image](https://user-images.githubusercontent.com/15416633/73545700-d2b30a00-4476-11ea-9a72-e75902e0ecf0.png)
But, it always fails when clicking the `Test Connection` button. Does anyone know how to fix it? Thanks! I have restarted Jenkins, but it still doesn't work.
![image](https://user-images.githubusercontent.com/15416633/73545463-59b3b280-4476-11ea-9bb5-cfb02b757744.png)

**Comment by timja** [comment]
Untick the custom slack app bot user option and it should work

**Comment by jianzhangbjz** [comment]
Actually, no, I have tested it. See below:
![image](https://user-images.githubusercontent.com/15416633/73546187-bd8aab00-4477-11ea-8424-cfc93b496d0e.png)

**Comment by jianzhangbjz** [comment]
It works after I clicked that `Save` button and re-run it. Thanks! One more question, if I want to use that Bot, what should I do? Thanks!
![image](https://user-images.githubusercontent.com/15416633/73546407-2540f600-4478-11ea-9ee2-5fab3fef4030.png)

**Comment by timja** [comment]
https://github.com/jenkinsci/slack-plugin#bot-user-mode
