### ISSUE TITLE
Error when send messages.

### ISSUE THREAD

**Issue by evertonevaristo** [jenkinsci/slack-plugin#663]
### Your checklist for this issue

- [2.204] Jenkins version 

- [2.36] Plugin version 

- [Ubuntu 16.4 ] OS

### Description

When send notifications with the plugin, i got the following message:

```
Slack Send Pipeline step running, values are - baseUrl: https://domain.slack.com/services/hooks/jenkins-ci/, teamDomain: <empty>, channel: **channel-builds**, color: red, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>
ERROR: Slack notification failed with exception: java.lang.IllegalArgumentException: the credential with the provided ID (slack-token) could not be found and no token was specified

```

**Comment by timja** [comment]
Ensure your token scope is global and not system.

**Comment by darede-git** [comment]
@timja is already global.

![image](https://user-images.githubusercontent.com/56449185/73801664-f38e9e80-4799-11ea-9ce9-c02dc6fa1e63.png)

**Comment by casz** [comment]
@darede-git can you please recreate the credential, as there were versions of the slack plugin that had migrated the plugin incrorrectly.

**Comment by evertonevaristo** [comment]
@casz I had tried, but i cant change in the jenkins console... they just show and empty box.

I also re-add, with different name, but cant choose

When I click in "test connection" he show this info

![image](https://user-images.githubusercontent.com/3372284/73802745-52a1e280-479d-11ea-91e2-f1ef71238f75.png)

**Comment by timja** [comment]
Can you create a new credential, specify an ID for it and then screenshot both the credential screen and the screen where you are testing the credential, also try hitting save and then testing it

**Comment by evertonevaristo** [comment]
@timja new credential added

![image](https://user-images.githubusercontent.com/3372284/73846268-04bfc580-4803-11ea-9955-44c2123bab7a.png)

When try to set this new token:

![image](https://user-images.githubusercontent.com/3372284/73846415-43558000-4803-11ea-990f-606bce86555e.png)

When clik in test connection, the old token it's issued

![image](https://user-images.githubusercontent.com/3372284/73846481-608a4e80-4803-11ea-8f7f-f17357612c4d.png)

**Comment by timja** [comment]
I need the actual credential screen to see what you have set

**Comment by evertonevaristo** [comment]
> I need the actual credential screen to see what you have set

This one?

![image](https://user-images.githubusercontent.com/3372284/73849841-5e2af300-4809-11ea-8608-669c266f2b7d.png)

**Comment by timja** [comment]
Your credential is of the wrong type, it needs to be secret text:
https://github.com/jenkinsci/slack-plugin#security

**Comment by evertonevaristo** [comment]
@timja thanks for the Help, actually, the problem was this:


![image](https://user-images.githubusercontent.com/3372284/73873039-9b09e080-482f-11ea-96e1-e3110d5a9b87.png)

The secrets text wasnt able on the credentials manager....

Thank You for the support.
