### ISSUE TITLE
docs are broken on jenkins pipeline site

### ISSUE THREAD

**Issue by guykisel** [jenkinsci/slack-plugin#664]
### Description

https://jenkins.io/doc/pipeline/steps/slack/

![image](https://user-images.githubusercontent.com/6760519/73789966-94f30180-4754-11ea-80b5-fe94fd0174f8.png)

fairly minor issue, but i was just looking up the args for `slackSend` and found this.

thanks for providing and maintaining this plugin! it's very useful.

**Comment by zbynek** [comment]
Problemis in documentationgenerator, notthe plugin itself, cf https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/19

**Comment by guykisel** [comment]
ah, thanks for the quick response!

**Comment by timja** [comment]
Fixed in above PR
