### ISSUE TITLE
Slack Uploader Plug In not recognizing path of artifacts.

### ISSUE THREAD

**Issue by vennemp** [jenkinsci/slack-plugin#667]
### Your checklist for this issue

- [ ] Jenkins version

- [x] Plugin version

- [ ] OS

### Description

Please describe your issue here.
I am using the slack upload plug in to upload a report from anchore to slack.  I used the path to archive with the $BUILD_NUMBER variable but but it does not recognize the variable and passes it directly.  Please advise. Please note also regular slack notifications are working fine.

Configuration of my slack action.
slackUploadFile channel: 'channel-dev', credentialId: 'slack', filePath: '/var/jenkins_home/jobs/PROJECT/builds/$BUILD_NUMBER/archive/AnchoreReport.PROJECT_$BUILD_NUMBER/anchoreengine-api-response-vulnerabilities-1.json', initialComment: 'Anchore Test Results'

Console output for action.
[Pipeline] slackUploadFile
Using dirname=/var/jenkins_home/workspace/PROJECT and includeMask=/var/jenkins_home/jobs/PROJECT/builds/$BUILD_NUMBER/archive/AnchoreReport.PROJECT_$BUILD_NUMBER/anchoreengine-api-response-vulnerabilities-1.json
No files found for mask=/var/jenkins_home/workspace/PROJECT

**Comment by vennemp** [comment]
Using Double quotes worked but it still can't find the file even though the path is correct

**Comment by timja** [comment]
The slackUpload step runs on the agent that the job ran in, it assumes the artifact you want to upload is in the agent's workspace,

The path you have provided looks like it is on the jenkins master

**Comment by vennemp** [comment]
yes i only have one node.  why does it not find the file though? I literally cat the piece from includeMask and it displays the contents of the file.  so I know the path it has is valid

**Comment by timja** [comment]
Try use a relative file path

**Comment by timja** [comment]
Closing as the step is run on the agent, master file paths won’t work.
