### ISSUE TITLE
User Id Look Up not working? 

### ISSUE THREAD

**Issue by chadjiang** [jenkinsci/slack-plugin#670]
### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] OS

### Description

Please describe your issue here.

tried User Id Look Up from example, but looks not working
def userId = slackUserIdFromEmail('spengler@ghostbusters.example.com')
slackSend(color: 'good', message: "<@$userId> Message from Jenkins Pipeline"), 
got this error: 

No such DSL method 'slackUserIdFromEmail' found among steps [archive, bat, build, catchError, checkout, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, getContext, git, .......

checked "Slack email User ID Resolver". 

Any idea?  Thanks.

**Comment by casz** [comment]
What version of the plugin are you using?

**Comment by chadjiang** [comment]
Slack Notification. 2.36
Jenkins ver. 2.204.2

thanks!

**Comment by casz** [comment]
You need to update to the latest 
https://github.com/jenkinsci/slack-plugin/releases/tag/slack-2.37

**Comment by chadjiang** [comment]
oh. Thank you!
