### ISSUE TITLE
slackUploadFile not working

### ISSUE THREAD

**Issue by ewolfe123** [jenkinsci/slack-plugin#671]
### Your checklist for this issue
- [x] Jenkins version
- [x] Plugin version
- [x] OS

### Description
**Environment**
* Jenkins Version: 2.190.3
* Plugin Version: 2.36
* OS: Alpine Linux v3.9 (Running in a Docker Container on MacOS 10.14.6)

**Configuration**
* Custom Jenkins App
    * `chat:write` and `files:write` bot token scopes enabled
* Jenkins Config
    * Bot User Enabled
    * Correct token selected

**Issue**
With all the variables having valid values, `slackUploadFile filePath: diffFileName, channel: slack_channel, credentialId: 'slack_token'` does not upload a file to the channel.

Jenkins output shows the following (paths and file names redacted):
```
[Pipeline] slackUploadFile
Using dirname=/var/jenkins_home/workspace/Job Name Here and includeMask=filename.txt
Adding file (only first one will be uploaded) /var/jenkins_home/workspace/Job Name Here/filename.txt
```

`slackSend` works just fine with the same token.

**Comment by timja** [comment]
is the file from the master or the agent? slackUploadFile runs on the agent

**Comment by ewolfe123** [comment]
@timja The file is in the workspace of the agent.

**Comment by timja** [comment]
is there an error message? or does it just say it uploaded it?

**Comment by ewolfe123** [comment]
@timja No error message. Nothing additional in the docker logs, either.

**Comment by k-vekos** [comment]
I am having the exact same problem. I don't see any mention of any file upload activity, failed or not, in `/log/Slack%20logs/` either.

**Comment by dnlek** [comment]
Hey guys did you try running the same command manually?
`curl -sSL -D - -X POST -F file=@<path_to_file> -F token=<bot_token> https://slack.com/api/files.upload`

For me the problem was lack of `files:write` - which is returned as 200 OK - so plugin doesn't show this message anywhere. I see that you have this permission - but maybe there will be other message.

Other thing is that - plugin could print out log in case it was 200 OK but response.ok != true.

**Comment by timja** [comment]
Thanks for the info @dnlek I've reproduced that issue, (it was caused by a change on slack side for new bots: https://api.slack.com/apps/AES7CA6RF/update-to-granular-scopes)

I've created a PR for it: https://github.com/jenkinsci/slack-plugin/pull/686

**Comment by timja** [comment]
released in https://github.com/jenkinsci/slack-plugin/releases/tag/slack-2.40

**Comment by sliide-jay** [comment]
plugin version :2.4
Jenkins: 2.235.1

i seem to have this issue. I've tried slack [api tester](https://api.slack.com/methods/files.upload/test), it works. But curl or slackUploadFile doesn't. Can't see any errors.

**Comment by timja** [comment]
Have you taken a look at the PR?

If it’s not fixed by that then you have a different issue and can you please open a new issue
