### ISSUE TITLE
Jenkins Slack integration shows Test Connection FAIL

### ISSUE THREAD

**Issue by shryta234** [jenkinsci/slack-plugin#672]
Hi All,

My Jenkins Slack integration was working perfectly till yesterday ,suddenly from today the notifications are not posted and I see Test Connection FAILURE.

Using the below:-
SLACK 2.3
JENKINS 1.651

Please help!
<img width="1321" alt="Screenshot 2020-03-06 at 1 41 48 PM" src="https://user-images.githubusercontent.com/31080566/76064966-af690680-5fb0-11ea-8616-0d5a4955e2ad.png">

**Comment by timja** [comment]
Please update your slack plugin that version is ancient

Then follow the troubleshooting steps if there’s still an issue
https://github.com/jenkinsci/slack-plugin/blob/master/README.md#troubleshooting-connection-failure

**Comment by shryta234** [comment]
Im using a old version of Jenkins,hence cannot upgrade to the latest version of Slack.
Also where I can see any logs of this Failure as I dont see it in console output of Jenkins?

**Comment by timja** [comment]
The Jenkins server logs

**Comment by saipradeep434** [comment]
@shryta234 did u find a solution for this. I see same issue today

**Comment by saipradeep434** [comment]
Please help me on this if u have a solution @shryta234

**Comment by timja** [comment]
Please create a new issue if you have gone through the troubleshooting steps in the README
