### ISSUE TITLE
SSLHandshakeException while posting to slack

### ISSUE THREAD

**Issue by Rashair** [jenkinsci/slack-plugin#673]
### Data
Jenkins version: 2.202
Plugin version: 2.37
OS: Linux

### Description

Jenkins is unable to send notifications to slack due to following exception:

![image](https://user-images.githubusercontent.com/33404585/76085613-af6a0600-5fb2-11ea-9a2c-cce44fb2aea5.png)

I tried to post message to my slack url via postman and it worked correctly.

**Comment by timja** [comment]
Do you have a corporate proxy?

**Comment by Rashair** [comment]
> Do you have a corporate proxy?

No

**Comment by SupergiantAndrew** [comment]
Hello, we have the same issue. It also started two days ago on 3/5. We don't have any sort of proxy. It was working perfectly until two days ago.

Jenkins: 2.204.3
Plugin: 2.37
OS: Windows 7

I was wondering if it was related to this?

https://api.slack.com/changelog/2019-07-deprecate-early-tls-versions

**Comment by timja** [comment]
What version of java are you using?

**Comment by SupergiantAndrew** [comment]
We’re using java runtime version 1.8.0_241-b07

**Comment by Jetersen** [comment]
I suspect the TLS change that was put in place is your issue.

https://slack.com/intl/en-gb/help/articles/360024438834-Transport-Layer-Security--TLS--in-Slack

**Comment by Jetersen** [comment]
To think that you can avoid change while the ecosystem around you is constantly changing

![](https://media.giphy.com/media/l3fZXTZdS6Ofi7U6A/giphy.gif)

**Comment by Jetersen** [comment]
Even though TLS 1.2 might be enabled by default in Java 8. I have to wonder if that is the case when it is running on Windows 7.

https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default

**Comment by Jetersen** [comment]
@timja perhaps we can help it along and tell apache client to use TLS 1.2 just to be safe.

**Comment by Rashair** [comment]
Putting `-Dhttps.protocols=TLSv1.2`  in jenkins config file did not help

**Comment by Jetersen** [comment]
I see, our http client builder was not configured correctly.

**Comment by Jetersen** [comment]
https://github.com/apache/httpcomponents-client/blob/c87a3488c45493c165c886bcd8b63b3724a1e2cc/httpclient/src/main/java/org/apache/http/impl/client/HttpClientBuilder.java#L957-L982

**Comment by Jetersen** [comment]
@Rashair you should not have to set `-Dhttps.protocols` as the default should include TLSv.12

Feel free to test: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/slack/2.38-rc549.98371e250a68/slack-2.38-rc549.98371e250a68.hpi

**Comment by SupergiantAndrew** [comment]
Thanks @Jetersen, unfortunately that didn't work for us. Still seeing the same handshake failure. let me know if there's further info we can provide.

**Comment by Jetersen** [comment]
Okay than it is not a code issue it is definitely an environment issue.

Please look into test on a different OS and java combination.

**Comment by Jetersen** [comment]
You could try adding `-Djavax.net.debug=ssl,handshake` to see exactly what is going on.

**Comment by timja** [comment]
Which vendor are you using for your java? I.e oracle, openjdk. Adoptopenjdk, azul? 

Possibly try a different one

**Comment by Jetersen** [comment]
I been using adoptopenjdk with no issues.

**Comment by WorldVM** [comment]
It Work's :) Thank you very much @Jetersen The Slack Version 2.38 fix the issue :)

**Comment by Jetersen** [comment]
@SupergiantAndrew would appreciate the logging with debugging ssl and handshake to understand why it is not working.

It could be that it does not trust the digicert or could be that it fails on TLS 1.2

**Comment by SupergiantAndrew** [comment]
Thanks @Jetersen and @timja for the support. I figured out what was wrong with our setup.

In our Jenkins.xml config, we had this argument: `-Djsse. enableSNIExtension=false`. The SNI extension is required for Slack now. I'm not sure if we had originally added that argument years ago or if it was a part of Jenkins installations as a workaround for what looks like a java 7 bug.

In any case, that resolved it for us. Thanks again!

**Comment by Jetersen** [comment]
@Rashair any updates on your end, would appreciate if you can try the HPI or use the `-Djavax.net.debug=ssl,handshake` to debug what's going on.

**Comment by Rashair** [comment]
> @Rashair any updates on your end, would appreciate if you can try the HPI or use the `-Djavax.net.debug=ssl,handshake` to debug what's going on.
I will give you logs tomorrow, I am unavailable at the moment

**Comment by Rashair** [comment]
It still does not work for me :/ 
I added debug option and received this:
![image](https://user-images.githubusercontent.com/33404585/76398933-076f8680-637e-11ea-8c76-b67b8b16a804.png)

**Comment by timja** [comment]
It looks like you have no available cipher that matches what slack supports, 
you likely need to update your OS or java

But can you provide more details about your OS and java version and vendor for java?

**Comment by Rashair** [comment]
Java:
![image](https://user-images.githubusercontent.com/33404585/76399346-c035c580-637e-11ea-9367-4c4f0cfe82b8.png)
OS: CentOS 6.10

**Comment by timja** [comment]
I would try updating your java to the latest 1.8 version, and probably swap to openjdk / adoptopenjdk / azul if you can due to licensing issues on newer oracle versions

**Comment by Rashair** [comment]
After updating java to openjdk 1.8.0_245 still same issue

**Comment by timja** [comment]
Take a look here: https://stackoverflow.com/a/6353956/4951015

Possibly try on an updated OS

It works on modern systems, CentOS 6 is reaching its end of life this year, and many packages on there are very old

**Comment by Jetersen** [comment]
I think we safely close this, please update your OS and Java distribution.
