### ISSUE TITLE
The credential with the provided ID () could not be found and no token was specified

### ISSUE THREAD

**Issue by CarlitosDroid** [jenkinsci/slack-plugin#678]
### Your checklist for this issue

- [x] Jenkins version: 2.204.2

- [x] Plugin version: 2.37

- [x] OS: Linux (jenkins docker container https://github.com/jenkinsci/docker)

### Description
Steps to reproduce:

1. In a Freestyle project in Jenkins
2. Go to Post-build Actions
3. Add "Add post-build action"
3. Add "Slack Notification" 
4. Click on "Advanced..."
5. "Credential" field doesn't recognize credentials, even if the scope is Global or System, always shows "-none-"
6. Click on "Test Connection"
7. An error is shown "The credential with the provided ID () could not be found and no token was specified"

**Evidence**

![Screen Shot 2020-03-09 at 9 25 02 PM](https://user-images.githubusercontent.com/10377529/76274320-55856c80-624e-11ea-9eda-770679e7a1ca.png)

**Comment by timja** [comment]
Can you add a screenshot of how your credential is setup?

**Comment by CarlitosDroid** [comment]
This is how I setup my credentials
![Screen Shot 2020-03-10 at 9 50 30 AM](https://user-images.githubusercontent.com/10377529/76324996-cc555080-62b4-11ea-9d4d-12fec2ca94b1.png)
![Screen Shot 2020-03-10 at 9 50 42 AM](https://user-images.githubusercontent.com/10377529/76324999-cd867d80-62b4-11ea-928b-11fbc7f2c97f.png)

 And when I go back to the "Add post-build action" in my job, again I can't be able to detect it, always "none": 
![Screen Shot 2020-03-10 at 9 51 14 AM](https://user-images.githubusercontent.com/10377529/76325113-f1e25a00-62b4-11ea-8ea5-3408582f0f3b.png)

**Comment by Jetersen** [comment]
You need to use secret text credential type.

**Comment by CarlitosDroid** [comment]
@Jetersen @timja now it's working fine by using **secret text** credential type, but I think that it should be also work with the other credential types.
Thank you very much!!!

![Screen Shot 2020-03-10 at 7 47 04 PM](https://user-images.githubusercontent.com/10377529/76371588-b6717b00-6308-11ea-9e95-92593551cf46.png)

![Screen Shot 2020-03-10 at 7 51 09 PM](https://user-images.githubusercontent.com/10377529/76371604-c1c4a680-6308-11ea-91a7-6e0d356d79e6.png)

**Comment by Jetersen** [comment]
No your slack token does not need the username, reason why we only support secret text.

**Comment by CarlitosDroid** [comment]
Thanks a lot @Jetersen

**Comment by Jetersen** [comment]
FYI I would always provide a meaningful ID as you will use the ID in your Jenkins pipeline

**Comment by fgm** [comment]
Final item missing was how to find the token in the current Slack UI : in the "incoming-webhooks" integration, its the part of the URL after "services/", xxxx/xxxx/xxx(24chars)xxx.
