### ISSUE TITLE
Configure page messed up

### ISSUE THREAD

**Issue by marc-guenther** [jenkinsci/slack-plugin#68]
Slack Plugin simply inserts its configuration options somewhere in the middle of the top section of the Jenkins Configure page.

There is no visible separator at the end of its section, making it quite difficult to find out which options belong to the plugin and which don't.

**Comment by samrocketman** [comment]
Hello, I don't actively develop the slack plugin.  I only maintain pull requests and releases.  I'm aware of this UI problem but this is the first issue raised about it.  Contributions are welcome to fix this!

**Comment by OwensCode** [comment]
I'm going to try take this one on in the next couple of days. If you're still keeping an eye on this, you're talking about the job configuration page, right? Not the global configuration, which seems to be okay.

**Comment by samrocketman** [comment]
I believe it is the job configuration page.  There's also an effort to group the configuration with the post build step in PR #79 which I think looks promising for a nice clean-up.

**Comment by OwensCode** [comment]
Unfortunately did not get very far on this, but I think #79 looks like a promising way to resolve this issue as well.

**Comment by timja** [comment]
resolved as part of https://github.com/jenkinsci/slack-plugin/pull/79
