### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by Saibamen** [jenkinsci/slack-plugin#681]
### Your checklist for this issue

- [x] Jenkins version: 2.204.5

- [x] Plugin version: 2.37

- [x] OS: Windows Server 2016

### Description

I have double messages on Slack.

#### Configuration:
![image](https://user-images.githubusercontent.com/905878/77831517-f4a3d280-712f-11ea-8c21-188717e55872.png)

#### Result:
![image](https://user-images.githubusercontent.com/905878/77831525-fd94a400-712f-11ea-957a-38997acc924d.png)

**Comment by Jetersen** [comment]
This is the troubled area:

https://github.com/jenkinsci/slack-plugin/blob/08a79ef1df21a62edbae643d50da0562ed399d17/src/main/java/jenkins/plugins/slack/SlackNotifier.java#L588-L592

I am rewriting it to not run finalized but however run only completed and adding the necessary notifications conditions.

**Comment by Jetersen** [comment]
@Saibamen are you using the slack app or your own custom bot?

**Comment by Jetersen** [comment]
Even with the slack app provided by slack I cannot get duplicated messages.

**Comment by Saibamen** [comment]
WTF? Why are you closing this issue without my answers to your question?...

This is my full settings:
![obraz](https://user-images.githubusercontent.com/905878/77850379-ab9c5e80-71c1-11ea-9a0a-f2f62ec89cf9.png)

**Comment by Jetersen** [comment]
I patched it. Feel free to test the latest HPI: https://ci.jenkins.io/job/Plugins/job/slack-plugin/job/master/246/artifact/org/jenkins-ci/plugins/slack/2.38-rc552.64e196e9c670/slack-2.38-rc552.64e196e9c670.hpi

**Comment by Jetersen** [comment]
Feel free to report back with the new HPI and please do include details from the fine logger.

https://jenkins.io/doc/book/system-administration/viewing-logs/

**Comment by Saibamen** [comment]
When release will be done?

**Comment by timja** [comment]
@jetersen were you planning on doing a PR for the update message from SlackResponse? I was waiting for that to release in case you wanted to make any breaking changes because the previous update message PR was never released

**Comment by jetersen** [comment]
Feel free to release my change is not blocking.

I doubt the PR will have any breaking changes.

**Comment by Saibamen** [comment]
Fixed
