### ISSUE TITLE
Release v2.38 not released in Jenkins Update Center

### ISSUE THREAD

**Issue by mmuehlberger** [jenkinsci/slack-plugin#684]
Apologies to be a nag, but it seems that the latest release (from 12 days ago) has not been released to the Jenkins Update Center or the Plugins directory.

I've been wishing for the ability to update Slack message for quite a while now and am eager to include this in our projects.

Would it be possible to kick off a release?

**Comment by timja** [comment]
> Apologies to be a nag, but it seems that the latest release (from 12 days ago) has not been released to the Jenkins Update Center or the Plugins directory.
> 
> I've been wishing for the ability to update Slack message for quite a while now and am eager to include this in our projects.
> 
> Would it be possible to kick off a release?

hmm, not sure what happened there, we'll be doing a new release soon for the addReactions support and the update messages will likely get a new feature to be a bit cleaner.

**Comment by timja** [comment]
released 2.39, it may take a couple of hours to appear on all mirrors
