### ISSUE TITLE
slackUserIdFromEmail returns null

### ISSUE THREAD

**Issue by NBE-SG** [jenkinsci/slack-plugin#688]
### Your checklist for this issue

- [x] Jenkins version
2.220
- [x] Plugin version
2.40
- [x] OS
Amazon Linux AMI 2018.03

### Description

Hi,

We are using your plugin **without** the custom slack app and it's working fine for the slackSend() method.

I'm trying to implement a simple pipeline which also calls the slackUserIdFromEmail() method.
Reading your documentation I set up a custom slack app and the sendSlack() method is still working, now I'm receiving slack messages from the app.

But **the slackUserIdFromEmail() method returns null**, though I tried to play with the settings to see if I could make it work by (un)ticking boxes or anything else.

I also logged everything from the "jenkins.plugins.slack" package, only the slackSend() log appears.
Has anyone an idea of what I might be doing wrong ?

Here's my test pipeline :
```groovy
pipeline {
   agent any

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World'
            script {
                def userId = slackUserIdFromEmail('myEmail')
                echo userId
                slackSend(color: 'good', channel:'@myUserId', message: 'Message from Jenkins Pipeline')
            }
         }
      }
   }
}
```

Here's the console result :
```
Running on Jenkins in /var/lib/jenkins/workspace/testslack
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Hello)
[Pipeline] echo
Hello World
[Pipeline] script
[Pipeline] {
[Pipeline] slackUserIdFromEmail
[Pipeline] echo
null
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: <empty>, channel: @myUserId, color: good, botUser: true, tokenCredentialId: xxx, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by NBE-SG** [comment]
Found the solution thanks to https://github.com/jenkinsci/slack-plugin/issues/683

You need to add users:read.email and users:read scopes added to your app.
This should be documented in the plugin.

**Comment by timja** [comment]
> Found the solution thanks to #683
> 
> You need to add users:read.email and users:read scopes added to your app.
> This should be documented in the plugin.

could you submit a PR to update: https://github.com/jenkinsci/slack-plugin#creating-your-app

**Comment by jetersen** [comment]
I updated the list in the issue, I'll see if can manage to add it in a meaningful way to the readme.
