### ISSUE TITLE
Some jobs do not trigger the notification

### ISSUE THREAD

**Issue by Nakilon** [jenkinsci/slack-plugin#69]
Two (probably the first I've configured) jobs keep pushing notifications, but others seem to just not trigger the plugin at all. Here is how I now configured the "FFFFFFFF" job, that successfully pushes notification, and the "slack_test" job in configured in the same way.

![2015-03-17 20 19 29](https://cloud.githubusercontent.com/assets/2870363/6693391/c1064e08-cce3-11e4-92bb-f3bae7757c11.png)

Both of them have `exit 1` in shell script to be executed, but only the "FFFFFFFF" job pushed notification.

    мар 17, 2015 6:13:40 PM INFO hudson.model.Run execute
    FFFFFFFF_Selenium_Tests #45 main build action completed: FAILURE
    мар 17, 2015 6:13:40 PM INFO jenkins.plugins.slack.StandardSlackService publish
    Posting: to #jenkins-ci on ******** using https://********.slack.com/services/hooks/jenkins-ci?token=********: FFFFFFFF_Selenium_Tests - #45 Failure after 0,12 секунд (<https://********/job/FFFFFFFF_Selenium_Tests/45/|Open>) danger
    мар 17, 2015 6:13:40 PM INFO jenkins.plugins.slack.StandardSlackService publish
    Posting succeeded

    мар 17, 2015 6:23:56 PM INFO hudson.model.Run execute
    slack_test #3 main build action completed: FAILURE

**Comment by samrocketman** [comment]
Do you have the post-build step for publishing the slack notification?  This is not part of the settings of the plugin.  Instead it is an explicit step you must add at the end of the job in the post-build section.

**Comment by Nakilon** [comment]
@samrocketman you are right! This was the issue.

**Comment by samrocketman** [comment]
Open a new issue for your desire to collapse some of the messaging, please.  You've got some good points here that I don't want lost.

**Comment by tokunbo** [comment]
@samrocketman I know your comment is 3 years old, but you just cured a headache for me.

**Comment by samrocketman** [comment]
@tokunbo You're welcome.  In general, I feel like the slack plugin is long overdue for a complete rewrite.  Unfortunately, I'm not sure I have the right skillset for the rewrite and I even stopped maintaining the plugin because of being spread thin across OSS projects.
