### ISSUE TITLE
Allow adding arbitrary fields to splunk log record payload

### ISSUE THREAD

**Issue by silvermy** [jenkinsci/slack-plugin#691]
### Your checklist for this issue

- [x ] Jenkins version

- [x ] Plugin version

- [x ] OS

### Description

My company is moving from a hosted to a SAAS version of Splunk. Our Jenkins (2.121.3.1 ) servers (Linux / CentOS 7) are equipped with the splunk plugin (2.0.1 ) and send log data to the configured collector.

In order to make the move, we need to change the collector URL (easy enough in the system configuration) but, also, add a field to the log payload - where the index name, source type, etc.. are specified.

How would I go about this? Specifically, this is the change we need to make to the http payload (assuming that is how Jenkins talks to Splunk via the plugin):

{
"index": "blah",
"host": "some-blah-host",
"sourcetype": "blah-monitor-dev",
"event": {
"hello" : "world"
}
"fields": { # fields is a valid splunk event metadata
"obs_mnkr" :"MONIKER" # obs_mnkr is a custom field metadata that customers would need to send
}
}

Note the "fields" element.

**Comment by timja** [comment]
This is the slack plugin, not the splunk plugin?
