### ISSUE TITLE
Issue with finding suitable plugin version for certain Jenkins version

### ISSUE THREAD

**Issue by SergiiTrybushnyi** [jenkinsci/slack-plugin#697]
Hi there!

We have Jenkins 2.160 and due to some reasons there is no chance to update it to the 2.164.3 which is required by the latest plugin release.

Could you please help me out with finding plugin version which will work with Jenkins 2.160? 

Thanks a lot!

**Comment by timja** [comment]
2.29 should work, but you really should update at this point...

**Comment by SergiiTrybushnyi** [comment]
I'd love to, but no chance at this moment.
Thanks though!
