### ISSUE TITLE
Slack Bot hide link

### ISSUE THREAD

**Issue by toni-lyttinen** [jenkinsci/slack-plugin#698]
Hello,

Would it be possible to add an option where you can hide the address of the Jenkins server to the plugin. I mean the "Open" hyperlink. Would be nice to see just the status without the link for security reasons. 

Thanks!

**Comment by timja** [comment]
You can use `slackSend` in pipeline for full customisation

**Comment by toni-lyttinen** [comment]
T

> You can use `slackSend` in pipeline for full customisation

Thx I will look into that!
