### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rodrigoreis22** [jenkinsci/slack-plugin#7]
Hi,

I did everything the guideline says to make this work. But it's not working.
I have a http proxy on my environment.. do you guys know or someone has already tested it behind a proxy?

My logs says:

Apr 16, 2014 1:42:41 PM INFO jenkins.plugins.slack.StandardSlackService publish
Posting: to  on walmartbr using https://xyz.slack.com/services/hooks/jenkins-ci?token=[TOKEN]: python_scripts-code_pull_test_build - #84 Success after 2 sec (</job/python_scripts-code_pull_test_build/84/|Open>) green

Apr 16, 2014 1:42:56 PM INFO jenkins.plugins.slack.StandardSlackService publish
Posting: to  on walmartbr using https://xyz.slack.com/services/hooks/jenkins-ci?token=[TOKEN]: python_scripts-deploy-dev - #125 Success after 1.3 sec (</job/python_scripts-deploy-dev/125/|Open>) green

**Comment by EdZilla** [comment]
Http Proxy setting where? Advanced tab for the plugin?

**Comment by rodrigoreis22** [comment]
If I remember well, the Advanced tab is a general Jenkins setting, not only for one plugin.

**Comment by EdZilla** [comment]
Thanks for the reply.
We got our jenkins slack plugin working. Our issue turned out to be
installing the slack certificate in our server keystore.



On Mon, Mar 30, 2015 at 12:31 PM, Rodrigo Reis <notifications@github.com>
wrote:

> If I remember well, the Advanced tab is a general Jenkins setting, not
> only for one plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/slack-plugin/issues/7#issuecomment-87782012>
> .
>



-- 
- Ed

**Comment by IPO-srh-sloan** [comment]
We got the slack plugin working by either passing in proxy settings on Jenkins startup (as per https://wiki.jenkins-ci.org/display/JENKINS/JenkinsBehindProxy) or by setting the proxy on the Manage Plugins -> Advanced tab. This applies not just to downloading plugins.

**Comment by fabricioferreira** [comment]
The proxy at my company requires authentication, and it is not working.
I get the following error message on the logs:

Jun 22, 2016 11:26:48 AM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: ntlm authentication scheme selected
Jun 22, 2016 11:26:48 AM org.apache.commons.httpclient.HttpMethodDirector processProxyAuthChallenge
INFO: No credentials available for NTLM <any realm>@proxy:80
Jun 22, 2016 11:26:48 AM jenkins.plugins.slack.StandardSlackService publish
WARNING: Error posting to Slack
