### ISSUE TITLE
slackUserIdFromEmail does not return slack user when using variable

### ISSUE THREAD

**Issue by irfanherfiandana** [jenkinsci/slack-plugin#708]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] OS

### Description

I'm using Jenkins 2.204.1 and plugin version 2.40 on Ubuntu server 16.04
I'm using slackUserIdFromEmail in Jenkins pipeline to mention committer when build started, the case is:

`def userId=slackuserIdFromEmail('me@example.com')`
it works as expected when the email is hardcoded in Jenkinsfile, everytime the build started, it will mention the related slack user

`def userId=slackuserIdFromEmail('$committerEmail')`
however, this result was always null

I checked with printenv, committerEmail variable was already filled with my email, but the userId value was null
Just to make sure, bot permission and slack plugin already configured because it works when the email is hardcoded.

Could you please advise?

**Comment by timja** [comment]
what sort of variable is `$committerEmail`? bash or pipeline?

bash won't be available
and inside the pipeline all you need is:

`slackuserIdFromEmail(committerEmail)`

**Comment by irfanherfiandana** [comment]
@timja Holy moly your solution worked like a charm!
why is it not need the $ sign vor getting the variable? Anyway, you can save your answer, maybe it's just my lack of experience :) 

here's the variable, just for documentation purpose:

```
committerEmail = sh (
      script: "git --no-pager show -s --format=\'%ae\'",
      returnStdout: true
      ).trim()
```

**Comment by timja** [comment]
$ is needed inside a bash script to access a variable but not in groovy.

The other issue you were having is because you were using single quotes which aren't interpolated.
