### ISSUE TITLE
Configuration looks good, Test Connection passes, no notifications occur

### ISSUE THREAD

**Issue by roxspring** [jenkinsci/slack-plugin#71]
In Jenkins "Configure System" I've setup appropriate slack settings.  Test Connection returns SUCCESS, although on further testing that seems to be the case no matter what nonsense I enter.

Some jobs are also configured to use the Slack Notifier but when running the console log has no mention of slack and slack is not notified.

How am I supposed to debug what's going on so that I can diagnose and resolve the problem?

Jenkins 1.580.3 + Slack Notifier 1.7.

**Comment by samrocketman** [comment]
Test connection always returns success in the Jenkins UI.  However, it does post to slack in the global configuration as a general test.  It is a contribution that still needs some polish so contributions are welcome.  To follow any progress for the test connection button please see issue #51.

There's three steps to account for when configuring the slack plugin.  This is all outlined in the slack integration documentation on the slack website for your team.

1. Configure the global settings for slack posting the job (or alternatively configuring the advanced settings in the plugin section of a job configuration).
2. Check the boxes in your slack configuration for what conditions the plugin should post to slack.
3. Add a post-build step for slack notification.  This is a step that you put in after your build scripts.

Other than that, standard troubleshooting applies such as testing connectivity, ensuring your token is correct, verify your domain names, etc.

**Comment by roxspring** [comment]
I've been trying to figure this out for ages but only just raised the issue yesterday. Only when raising this issue did I realise that the Test Connection is resulting in SUCCESS regardless of configuration validity. 

Turns out that our https connections our filtered and the master's JVM didn't trust the connection. It was only after fixing this that I discovered the Test Connection button is supposed to post a message in slack! 

That Test Connection button really needs to be altered so that it does not indicate a false positive. Additionally the result needs to indicate hat a message should have appeared in slack so that you can verify any claimed "SUCCESS". 



Thanks,

Rob

**Comment by samrocketman** [comment]
Agreed that Test Connection button needs improvement and fail locally.  I don't actively develop this plugin.  I only maintain pull requests and releases.  Contributions are welcome!
