### ISSUE TITLE
Posting messages as a thread and replies to it does not work

### ISSUE THREAD

**Issue by danechitoaie** [jenkinsci/slack-plugin#714]
### Your checklist for this issue

- [x] Jenkins version -> 2.222.1

- [x] Plugin version -> 2.40

- [x] OS -> Linux

### Description

I'm trying to post a message in a thread and it doesn't seem to be working. Here is the pipeline script that I'm using:
```
def slackResponse = slackSend(botUser: true, teamDomain: 'my-team', tokenCredentialId: '...123', channel: "we-be-testing", message: "Here is the primary message")
slackSend(botUser: true, teamDomain: 'my-team', tokenCredentialId: '...123', channel: slackResponse.threadId, message: "Thread reply #1")
slackSend(botUser: true, teamDomain: 'my-team', tokenCredentialId: '...123', channel: slackResponse.threadId, message: "Thread reply #2")
echo(slackResponse.threadId)
```

And I just get the messages posted as normal separate messages and not as a thread with two replies to it.
<img width="297" alt="Screenshot 2020-07-29 at 18 19 17" src="https://user-images.githubusercontent.com/10779010/88818969-08d40b00-d1c8-11ea-9e34-c60d46c52e56.png">

The `echo(slackResponse.threadId)` part returns `null` if I look in the console output of the build.
```
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: https://my-team.slack.com/services/hooks/jenkins-ci/, teamDomain: my-team, channel: we-be-testing, color: <empty>, botUser: true, tokenCredentialId: ...123, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: https://my-team.slack.com/services/hooks/jenkins-ci/, teamDomain: my-team, channel: , color: <empty>, botUser: true, tokenCredentialId: ...123, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: https://my-team.slack.com/services/hooks/jenkins-ci/, teamDomain: my-team, channel: , color: <empty>, botUser: true, tokenCredentialId: ...123, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
null
[Pipeline] End of Pipeline
Finished: SUCCESS
```

It looks like `slackResponse.threadId` is not populated. Any idea why?

**Comment by jetersen** [comment]
You cannot use the jenkins-ci slack app. You have to use a bot user for it to work.

jenkins-ci slack app is created by Slack with no extra features

**Comment by danechitoaie** [comment]
Thanks. I tried to use threads in the past and it wasn't working and I had no idea why so as I retried today and still failed I thought I should ask. I created a new app with bot user and will try to use that instead.
