### ISSUE TITLE
 Get null when call `slackUserIdFromEmail` method.

### ISSUE THREAD

**Issue by ohmerhe** [jenkinsci/slack-plugin#715]
### Your checklist for this issue

- [2.240] Jenkins version

- [2.40] Plugin version

- [macOS 10.15.3] OS

### Description

Slack plugin can send message success, but get null when call `slackUserIdFromEmail` method.

**Comment by timja** [comment]
are you using a slack app you've created yourself? and have you set the required permissions?

**Comment by ohmerhe** [comment]
No i am using Jenkins CI app provided by slack, it is strange this official app have no the required permissions.
