### ISSUE TITLE
Is it safe to upgrade from 2.29 to 2.40?

### ISSUE THREAD

**Issue by edbrannin** [jenkinsci/slack-plugin#716]
### Your checklist for this issue

- [x] Jenkins version: 2.222.3

- [x] Plugin version: 2.29

- [x] OS: Linux, I assume

### Description

I'd like to upgrade this plugin on my company's Jenkins from 2.29 to 2.40, but the Upgrade page shows this warning:

> Warning: the new version of this plugin claims to use a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details.

[The release notes](https://github.com/jenkinsci/slack-plugin/releases) don't seem to indicate what causes this warning.  (Unless it was the breaking change in 2.32 -- but someone in that change's issue is complaining about how the warning hadn't been enabled?)

Thank you for your time.

**Comment by timja** [comment]
Hi yes it's that version: https://github.com/jenkinsci/slack-plugin/blob/master/pom.xml#L22

the warning might have been added later.

That feature didn't even work so I highly doubt you could be affected...

**Comment by edbrannin** [comment]
Thank you!
