### ISSUE TITLE
Thread Icon Override

### ISSUE THREAD

**Issue by senkrad76** [jenkinsci/slack-plugin#720]
### Your checklist for this issue

- [X] Jenkins version

- [X] Plugin version

- [X] OS

### Description

Jenkins ver. 2.222.3
Slack Plugin 2.40
OS - I'm using Windows 10, but is the OS applicable?

When threading messages as follows, the "# replies" link's icon is not overridden, but remains the same as the **bot's app icon**, (even when overridden in the global slack setting as well). Inside the thread the icons appear as desired. Is there an option available to change this icon? Or make it the overridden icon from the first reply?
<pre><code>node {
    stage("Prepare") {
        def slackPipelineThread = slackSend(
            botUser: true,
            channel: 'matterhorn-pipelines-test', 
            username: 'Thread Test',
            iconEmoji: ':thumbsup',
            message: 'Test of bot user w/threads',
            //color: '#BADA55',
            //tokenCredentialId: 'DiscoBot'
        )
    }
    stage("Step1") {    
        slackSend(
            channel: slackPipelineThread.threadId,
            botUser: true,
            username: 'Step 1',
            iconEmoji: ':the_horns',
            message: "Thread Reply #1"
        )
    }
    stage("Step1") {    
        slackSend(
            channel: slackPipelineThread.threadId,
            botUser: true,
            username: 'Step 2',
            iconEmoji: ':crossed_fingers',
            message: "Thread Reply #2"
        )
    }
}</pre></code>

![badThreadIcons](https://user-images.githubusercontent.com/9276272/90559951-4090fb80-e153-11ea-9124-cd5a7a0749ff.png)

**Comment by timja** [comment]
Pretty sure this has been raised before and it’s a slack API limitation. Does it work with curl / the api tester?

**Comment by senkrad76** [comment]
I went through the issues, didn't see this one, there are similar ones, the as_user issue was similiar, but not the same I believe.

Haven't tried the with curl or api tester, I'll get back to you.

**Comment by senkrad76** [comment]
Checked curl and the api tester, same thing:

<pre><code>$: curl -s "https://slack.com/api/chat.postMessage?token=${TOKEN}&channel=${CHANNEL}&text=Start_of_Thread&bot_user=true&icon_emoji=:thumbsup"

{"ok":true,"channel":"XXXXXXXX","ts":"123.456","message":{"type":"message","subtype":"bot_message","text":"Start_of_Thread","ts":"123.456","username":"Thread_Bot","icons":{"emoji":":thumbsup"},"bot_id":"YYYYYYYYY"}}

$: curl -s "https://slack.com/api/chat.postMessage?token=${TOKEN}&channel=${CHANNEL}&thread_ts=123.456&text=Reply_to_Thread&bot_user=true&icon_emoji=:crossed_fingers"

{"ok":true,"channel":"XXXXXXXX","ts":"123.457","message":{"type":"message","subtype":"bot_message","text":"Reply_to_Thread","ts":"123.457","username":"Thread_Bot","icons":{"emoji":":crossed_fingers"},"bot_id":"YYYYYYYYY","thread_ts":"123.456"}}</code></pre>

The icon for the reply in the channel is the Apps Icon and not the overridden one.

**Comment by timja** [comment]
Didn’t quite understand that, are you getting the same issue calling the API or is it working for you?

**Comment by senkrad76** [comment]
Same issue

**Comment by timja** [comment]
FYI: https://github.com/jenkinsci/slack-plugin/issues/591#issuecomment-506050308

Feel free to contact Slack and nudge them on it.
