### ISSUE TITLE
Request: Add custom message

### ISSUE THREAD

**Issue by thorntonrose** [jenkinsci/slack-plugin#73]
Add a field for a custom message, such as "A new version of X is now available."

**Comment by samrocketman** [comment]
Not sure I understand your request.  Though message customization is, for the most part, addressed by #49.  I'm going to close this as a duplicate.  Please post a more thorough description of what you'd like.  Specifically what I don't understand is I don't personally see the reason why, "A new version of X is now available," would be a useful message when the plugin already reports successful builds.  By expanding on the reasoning it would make a convincing argument for someone who would maybe contribute the feature.

I don't actively develop this plugin.  I only maintain pull requests and releases.

**Comment by thorntonrose** [comment]
I would like a custom message instead of the built-in message, e.g. maintv-master-deploy - #22 Success after 42 ms, because I have users that won't get much value from a job name and status. They need to know that a new version of the app is available, perhaps with a link. I can do it with a post build Groovy script, but I would rather use the Slack plugin.

**Comment by samrocketman** [comment]
Fair enough.  I haven't considered cases like that.  It's good that you updated the other issue.  Hopefully someone will contribute it.
