### ISSUE TITLE
Response Code: 404 

### ISSUE THREAD

**Issue by ofirshtrull** [jenkinsci/slack-plugin#730]
### Your checklist for this issue

- [x] Jenkins version
2.235.5
- [x] Plugin version
2.42
- [ ] OS

### Description
my slack notifications have stoped with this error 

Sep 09, 2020 6:22:13 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to jenkins_deployments_be on xxxx:  {"attachments":[{"fallback":"Slack/Jenkins plugin: you're all set on https://shared-jenkins-builder.xxxxx.net/","color":"good","fields":[{"short":false,"value":"Slack/Jenkins plugin: you're all set on https://shared-jenkins-builder.xxxxx/"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"jenkins_deployments_be","username":"yyyy@xxxxx.com"}
Sep 09, 2020 6:22:13 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null
Sep 09, 2020 6:22:13 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 404

This happens in two of my jenkins servers
i also tried creating new tokens with no success

**Comment by ofirshtrull** [comment]
and btw I haven't changed anything on of my Jenkins still has slack notifications v2.41

**Comment by timja** [comment]
See this issue:
https://github.com/jenkinsci/slack-plugin/issues/728

Try more debug and possibly switch to a custom slack app.

**Comment by ofirshtrull** [comment]
Ok fixed the issue, still don't know what changed but I built a new integration
Thanks
