### ISSUE TITLE
addReaction errors when following the documented pattern.

### ISSUE THREAD

**Issue by aeos** [jenkinsci/slack-plugin#737]
### Your checklist for this issue

- [x] Jenkins version 2.255

- [x] Plugin version 2.37

- [x] OS Linux 4.19.112+

### Description
I feel somewhat like this is user error, but for the life of my I cannot see my mistake. When I run the following code:

```groovy
slackResponse = slackSend(message: jobInfo);
slackResponse.addReaction("jenkins_triggered");
```

I receive the following exception:
`hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: jenkins.plugins.slack.workflow.SlackResponse.addReaction() is applicable for argument types: (java.lang.String) `

However without the `addReaction` call it works just fine.

**Comment by jetersen** [comment]
Should it not be

```groovy
def slackResponse = slackSend(message: jobInfo);
slackResponse.addReaction("jenkins_triggered");
```

**Comment by jetersen** [comment]
This is another option

```groovy
def slackResponse = slackSend(message: jobInfo);
slackResponse.addReaction(emojiName: "jenkins_triggered");
```

**Comment by aeos** [comment]
thanks, I tried the second option and got another similar error. Here is the beginning of my build script for clarity:
`
node {
    def slackResponse = null;
    def err = null;
    def jobInfo = "${env.JOB_NAME} ${env.BUILD_DISPLAY_NAME} \n${env.BUILD_URL}"
    try
    {
        slackResponse = slackSend(message: jobInfo);
        slackResponse.addReaction(emojiName: "jenkins_triggered");

    } catch(caughtError) { echo caughtError.toString(); }

// STARTS THE ACTUAL BUILD
`

**Comment by jetersen** [comment]
@aeos Always good to read release notes as I noticed you were using v2.37 according to your checklist.
https://github.com/jenkinsci/slack-plugin/releases/tag/slack-2.39

**Comment by aeos** [comment]
Thank you, and sorry for wasting your time!
