### ISSUE TITLE
Pattern for sending to multiple threads

### ISSUE THREAD

**Issue by mariadb-JeffBachtel** [jenkinsci/slack-plugin#738]
### Your checklist for this issue

- [X] Jenkins version 2.249.2

- [X] Plugin version 2.43

- [X] OS Cloudbees Jenkins docker hub container

### Description

The slackResult from SlackSendStep contains a `.threadId` , but follow-on messages to that thread only go to one channel, if the original message was sent to multiple channels.

Is there a pattern for sending to threads in multiple channels?

**Comment by timja** [comment]
Only the last one is returned, if you want to publish to multiple rooms and threads then you need to do multiple `slackSend` calls

**Comment by mariadb-JeffBachtel** [comment]
Thanks, Tim
