### ISSUE TITLE
Send DM to App channel instead of Slack-Bot

### ISSUE THREAD

**Issue by ngerke** [jenkinsci/slack-plugin#743]
### Your checklist for this issue

- [x] Jenkins version 2.249.3

- [x] Plugin version: 2.43 

- [x] OS: Linux (Jenkins docker container)

### Description

If you know the channel ID it is possible to send DM's to the Jenkins App Channel instead of the Slack-Bot channel.
But I've no idea how to get the Jenkins App Channel ID for every users Jenkins App.

This is what I get:
![image](https://user-images.githubusercontent.com/31704359/99989902-76c5c300-2db3-11eb-8061-73e71a2cd47c.png)
This is what I want:
![image](https://user-images.githubusercontent.com/31704359/99989841-64e42000-2db3-11eb-902c-cad1f7229c18.png)

Is this already possible? 
I followed https://github.com/jenkinsci/slack-plugin#creating-your-app to create the Jenkins App

**Comment by timja** [comment]
it already goes to the app channel if you use the bot user mode and have created your own app.

![image](https://user-images.githubusercontent.com/21194782/99990464-bc7e8d80-2dab-11eb-966e-da3a43d0b802.png)

**Comment by jetersen** [comment]
The test message might go to the slack app, if you simply setup a build with slack notification it should work.

**Comment by ngerke** [comment]
Nope doesn't work for me, I musst be missing something:
```
pipeline {
    agent {
        label "master"
    }
    stages {
        stage('Test') {
            steps {
                script {
                    def userId = slackUserIdFromEmail('user@company.org')
                    slackSend(color: "good", channel: "${userId}", message: "<@$userId> Message from Jenkins Pipeline")        
                }
            }
        }
    }
}
```

![image](https://user-images.githubusercontent.com/31704359/100065456-19be2180-2e34-11eb-836c-77ad5a34a165.png)

![image](https://user-images.githubusercontent.com/31704359/100065350-f85d3580-2e33-11eb-9752-8fc1829950ab.png)

![image](https://user-images.githubusercontent.com/31704359/100065215-cc41b480-2e33-11eb-906e-96bf0f6a11ae.png)

**Comment by timja** [comment]
maybe add more scopes? i think there might be a bot scope?

Slack changes things every now and then for new installations.
It works on mine but it's quite an old one...

**Comment by ngerke** [comment]
Just for sanity, I deleted the app and the plugin and reinstalled/configured everything but I get the same result :cry:

**Comment by ngerke** [comment]
Ok i got it:
You shouldn't set the `Username` in the Jenkins Plugin. With the username empty, everything works as expected .

**Comment by timja** [comment]
> Ok i got it:
> You shouldn't set the `Username` in the Jenkins Plugin. With the username empty, everything works as expected .

probably more of a slack API thing, we don't do anything special, but good to know
