### ISSUE TITLE
Failed slack integration

### ISSUE THREAD

**Issue by nick3389** [jenkinsci/slack-plugin#748]
### Your checklist for this issue

- [ ] Jenkins version
2.164
- [ ] Plugin version 
2.45
- [ ] OS
macOS

### Description

I try to setup slack notifier but I always get a Failed status in Test connection. My setup is:
- I have an App in Slack for Jenkins from where I create an integration.
- For this integration I get an integration token
- I follow your freestyle project guide to setup slack secret key in jenkins
- I click Test connection and it fails. I see this in the Logger:

```
Jan 18, 2021 12:20:07 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null
Jan 18, 2021 12:20:07 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 400
```

What is wrong here?

**Comment by timja** [comment]
https://github.com/jenkinsci/slack-plugin#troubleshooting-connection-failure

**Comment by nick3389** [comment]
@timja I have checked this. I am using the Jenkins CI app made by Slack. If I check the slack bot user I get this:
```
Jan 18, 2021 12:29:14 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: {"ok":false,"error":"invalid_auth"}
Jan 18, 2021 12:29:14 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 200
```

Again it isn't working...

**Comment by jetersen** [comment]
The app by slack does not support all features, so the recommendation is create your own slack app that the plugin can use.

https://github.com/jenkinsci/slack-plugin#creating-your-app

**Comment by nick3389** [comment]
@jetersen Many thanks. It is ok now with a custom app.
