### ISSUE TITLE
Sending a message to a user fails using plugin with Response: null

### ISSUE THREAD

**Issue by chanukov** [jenkinsci/slack-plugin#750]
### Your checklist for this issue

- [X] Jenkins version 2.263.2

- [X] Plugin version 2.42

- [X] OS linux Bionic

### Description

pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                    slackSend (channel: '@achanukov', message: 'hello there')
            }
        }
    }
}

fails with
11:44:52  Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: ********, channel: @achanukov, color: <empty>, botUser: false, tokenCredentialId: jenkins-slack, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
11:44:52  ERROR: Slack notification failed. See Jenkins logs for details.

From a finest level Jenkins logger
Posting: to @achanukov on *******:  {"attachments":[{"fallback":"hello there","color":"","fields":[{"short":false,"value":"hello there"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"@achanukov","as_user":"true"}
Jan 25, 2021 6:49:23 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null

the same message works fine when i make #channel a channel instead of a user.

**Comment by timja** [comment]
If you want to post to a user use their user Id, slack deprecated usernames and they only work for old slack accounts
