### ISSUE TITLE
slackUserIdsFromCommitters returns empty list

### ISSUE THREAD

**Issue by xaithe** [jenkinsci/slack-plugin#757]
### Your checklist for this issue

- [x] Jenkins version: 2.277.1 

- [x] Plugin version 2.46

### Description

Hi,

I'm trying to tag users in a slack message when a build they triggered has failed.  I'm aware of slackUserIdFromEmail, however not everyone's git email matches the slack email so I was hoping to use slackUserIdsFromCommitters to retrieve the id from Jenkins user profiles. But when I do this, an empty list is returned.

```
stage('Id from Commiters') {
    steps {
        script {
            def userIds = slackUserIdsFromCommitters()
            def tagString = userIds.collect { "<@$it>" }.join(' ')
            slackSend(channel: '#channel-name', color: '#03c6fc', message: "${tagString} is testing tagging", botUser: true)
        }
    }
}
```

![image](https://user-images.githubusercontent.com/17811656/111765828-bea9b200-889c-11eb-8332-9f57de596962.png)

Is there a way to make this work, or will we need to maintain a map of github users and slack ids?

Cheers

**Comment by agaudreault-jive** [comment]
You need to set at least one resolver that will resolve the Ids. There is no default so you need to select the `EmailSlackUserIdResolver`

![image](https://user-images.githubusercontent.com/47184027/113933758-f6808700-97c2-11eb-96c6-cd855a6a524d.png)
