### ISSUE TITLE
Requested modifications to notifications

### ISSUE THREAD

**Issue by charlesmchen** [jenkinsci/slack-plugin#76]
It would be nice if the notifications included:
1. Links to the jenkins web UI.
2. The name of the slave that builds are running on.

**Comment by samrocketman** [comment]
It already includes links to the Jenkins web UI.  It's likely you do not have it configured correctly in your settings.  I'm not sure Jenkins shares what build slave a build is running on.  I've always gotten around this by adding `hostname` to my build scripts.

**Comment by samrocketman** [comment]
@charlesmchen were you able to figure out the configuration so that Jenkins links show up in the slack post?

**Comment by sjr** [comment]
@samrocketman I did not see any way to include a clickable link to jenkins UI in the slack message, can you please give a pointer to docs or a screen shot or instructions?

I was trying to set it up and got notifications like this:

```jenkins [BOT]
blah-dev - #751 Failure after 26 min (</job/blah-dev/751/|Open>)
```

with nothing clickable

**Comment by sjr** [comment]
Oh I was close, lol.

Jenkins > Configuration > Global Slack Notifier Settings > Build Server URL

Working fine now :-)

**Comment by samrocketman** [comment]
Great.  That should probably be updated from `/` to something like `https://yourbuildserver.com/` or something like that as an example.

**Comment by timja** [comment]
`Jenkins > Configuration > Global Slack Notifier Settings > Build Server URL` seems to have been removed
closing
