### ISSUE TITLE
slackUserIdFromEmail() Doesn't Work

### ISSUE THREAD

**Issue by marcelochaves95** [jenkinsci/slack-plugin#763]
### Version report

Jenkins and plugins versions report:
`Version 2.235.2`

## Description
Slack have added new scopes that might interest those who use a custom bot user.
Update guidance on the new bot scopes:

Hi,
We are using your plugin without the custom slack app and it's working fine for the `slackSend()` method.

I'm trying to implement a simple pipeline which also calls the `slackUserIdFromEmail()` method.

Reading your documentation I set up a custom slack app and the `sendSlack()` method is still working, now I'm receiving slack messages from the app.

But the `slackUserIdFromEmail()` method returns `null`, though I tried to play with the settings to see if I could make it work by (un)ticking boxes or anything else.

Has anyone an idea of what I might be doing wrong?

#### 1. Here is my test pipeline using `slackUserIdFromEmail()`:
```groovy
def notifySlack() {
    def userId = slackUserIdFromEmail('myEmailOnSlack')
    slackSend(color: "good", message: "Test: <@$userId> Message from Jenkins Pipeline")
}

node {
    notifySlack()
}
```
Slack result:
![Jenkins Bot](https://user-images.githubusercontent.com/30784247/118877003-4d9a7100-b8c4-11eb-8291-3d0b0192da7b.png)

#### 2. Here is my test pipeline using `Slack Member ID`:
```groovy
def notifySlack() {
    def userId = "UT3L4RST1"
    slackSend(color: "good", message: "Test: <@$userId> Message from Jenkins Pipeline")
}

node {
    notifySlack()
}
```
Slack result:
![Jenkins Bot 2](https://user-images.githubusercontent.com/30784247/118882214-5130f680-b8ca-11eb-9928-aaab87faea51.png)

#### These are the bot settings in the job that generated an error:
![Jenkins Config Job](https://user-images.githubusercontent.com/30784247/118877189-820e2d00-b8c4-11eb-8c8a-67b28600af99.png)

#### These are the general settings for the bot:
![Jenkins Bot General Config](https://user-images.githubusercontent.com/30784247/118877086-630f9b00-b8c4-11eb-8d92-7c703823e70c.png)

#### These are the permissions of my Jenkins Bot app:
<img width="664" alt="Permissions" src="https://user-images.githubusercontent.com/30784247/118883237-63f7fb00-b8cb-11eb-858e-a344c92662d7.png">

**Comment by Kazzer** [comment]
Plugin versions 2.45 and lower have an issue with the Slack API URL where it includes the token in the URL which was removed in the Slack API (it gets treated as an `invalid_auth` when included).
You didn't provide your plugin version, but I also had an issue with a very similar configuration to you; when I upgraded to plugin version 2.46+ (2.48 is latest right now) the step started working.

**Comment by marcelochaves95** [comment]
> Plugin versions 2.45 and lower have an issue with the Slack API URL where it includes the token in the URL which was removed in the Slack API (it gets treated as an `invalid_auth` when included).
> You didn't provide your plugin version, but I also had an issue with a very similar configuration to you; when I upgraded to plugin version 2.46+ (2.48 is latest right now) the step started working.
> 
> A really easy way I found to test this was to pass a single space as the email which will cause the step to fail and print out the URL it's attempting to use. If you see `?token=...` in it, you likely just need to update the plugin version.

@Kazzer I believe this is my problem. My plugin is version 2.40. I'll update the plugin and test it. Thank you very much!
