### ISSUE TITLE
Remove Reaction

### ISSUE THREAD

**Issue by PatrickDuncan** [jenkinsci/slack-plugin#765]
### Feature Request

There is `addReaction()`, but no `removeReaction()`. There's no way to automate removing a reaction which is needed for temporary reactions like `:loading`

- [ ] Add feature to remove an added reaction

**Comment by philippart-s** [comment]
Hi @timja,
I'm interrested to contribute to Jenkins plugins ans specialy this plugin.
Is it ok for you if I take this issue ?

Regards

Stef

**Comment by timja** [comment]
Go for it
