### ISSUE TITLE
slackSend Notification failing, Response Code 400

### ISSUE THREAD

**Issue by nagsudhakar** [jenkinsci/slack-plugin#766]
### Version report

Jenkins and plugins versions report:
Jenkins: v2.277.1
Slack Notification Plugin: v2.47 and v2.48

```
Copy/paste here....
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Paste here
```

### Reproduction steps

- Step 1...
- Step 2...

### Results

Expected result:

Actual result:

**Comment by timja** [comment]
fill out the template, you've provided no info
