### ISSUE TITLE
Support for colors when using blocks

### ISSUE THREAD

**Issue by JonatanPlesko** [jenkinsci/slack-plugin#768]
### Feature Request

Currently, if you're using blocks layout, colors are not available:

> Warning: This functionality is not supported if you are using the blocks layout mode

Is there a possibility of this being implemented at some point? Blocks seem to be the better way of building message layouts, but having no color coding for build status is quite a big downside.

**Comment by timja** [comment]
Not possible, see
https://api.slack.com/messaging/attachments-to-blocks#direct_equivalents

They suggest one alternative on the link

**Comment by mding5692** [comment]
For anyone searching, you can do something like this as suggested in the link but this saves you time:
```
attachments = [[
                        'color': '#FC2305',
                        'blocks': [
                            [
                                'type': 'context',
                                'elements': [
                                    [
                                        'type': 'mrkdwn',
                                        'text': 'hello'
                                    ]
                                ]
                            ]
                     ]]
```
Also the values `good`, `warning` and `danger` aren't supported in arguments (from my personal testing) so you have to use hexcodes
