### ISSUE TITLE
Unable to select a credential on the settings screen

### ISSUE THREAD

**Issue by leonardoluan** [jenkinsci/slack-plugin#772]
### Version report

Jenkins and plugins versions report:
```
Jenkins: Jenkins 2.289.2
Slack-Plugin: 2.48
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
MacOS Big Sur
```

### Reproduction steps

-Install the Slack Notification plugin
-Access System Configuration
-Go to the Slack Notification section and try to select a credential.

### Results

Expected result:
-Show Jenkins Credentials

Actual result:
-Nothing is displayed 

<img width="923" alt="Captura de Tela 2021-07-23 às 12 02 38 PM" src="https://user-images.githubusercontent.com/35734728/126801585-c4ca34de-ac74-4fc0-a8f9-b2b7212f9777.png">

**Comment by timja** [comment]
needs to be in the global scope and of type string.

you've not shown how your credential is setup

**Comment by leonardoluan** [comment]
This version of jenkins is not letting me select the string type.
I think I will need to downgrade

https://user-images.githubusercontent.com/35734728/126802222-0b2aec87-d7c4-4d64-9418-ecd6c9cf88e7.mov

**Comment by timja** [comment]
You need the https://plugins.jenkins.io/plain-credentials/ plugin

**Comment by leonardoluan** [comment]
tnks

**Comment by leonardoluan** [comment]
i already have this plugin but it seems to me to be a problem with my jenkins version, i will look for more.
