### ISSUE TITLE
Data retention period to the message

### ISSUE THREAD

**Issue by Woile** [jenkinsci/slack-plugin#777]
### Feature Request

Hello people, I'm using this wonderful plugin, and I was wondering if it is possible to add a way to make a message sent to expire. My main issue is that there's a limit of 10GB/user on slack paid, and I'm uploading images/videos to a channel, and it's just for regressions, so I'd like those files to expire automatically.

Thanks!

**Comment by timja** [comment]
is that a slack feature? link?

**Comment by Woile** [comment]
I'm not sure, I only found [this API call](https://api.slack.com/methods/files.upload) which does not support it :( but as I am not good with Java (nor slack's api) I don't know which API this plugin uses.

Or as a workaround make Jenkins send a request to delete the message, do you think this is possible to implement?

Feel free to close the ticket if you think the complexity is not worth it

Thanks!

**Comment by timja** [comment]
I think not worth it :)

**Comment by Woile** [comment]
Just for the sake of future readers, the only thing I found from slack is that you can set retention periods in specific channels. So I'm in contact with my admins to set a period for my regressions tests channel.
https://slack.com/help/articles/115005393586-Edit-message-retention-settings-for-specific-conversations
