### ISSUE TITLE
Getting Failure when testing connection

### ISSUE THREAD

**Issue by pdiaz85** [jenkinsci/slack-plugin#780]
### Version report

Jenkins and plugins versions report:

```
Jenkins Version Jenkins 2.319.1
Slack Plugin Version: 2.49
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Ubuntu 20.04
```

### Reproduction steps

- Installed Slack Plugin, when doing Test Connection trough configure option getting "Failed". With this showing in jenkins.log

2021-12-07 23:20:40.422+0000 [id=16]    WARNING j.p.slack.StandardSlackService#postToSlack: Slack post may have failed. Response: null
2021-12-07 23:20:40.422+0000 [id=16]    WARNING j.p.slack.StandardSlackService#postToSlack: Response Code: 400

Also configured a log recorder for "org.apache.http" which is showing:

'http-outgoing-6 << "HTTP/1.1 400 Bad Request[\r][\n]"'
and some lines below
'http-outgoing-6 << "invalid_channel[\r][\n]"'

which is weird because I just copied/pasted
channel name from slack
### Results

Expected result:

Successful message sent to Slack 

Actual result:
Failed status on Test Connection

**Comment by timja** [comment]
What configuration did you do in the slack side?

**Comment by pdiaz85** [comment]
i used this app  on slack
![image](https://user-images.githubusercontent.com/53443665/145220820-ddd65ace-880d-42bd-9c2b-05915620e68f.png)
also got the  "added an integration to this channel" message on the channel
i double checked  leading or trailing white spaces on Default channel / member id and there is non, tried with the # before channel name and without it , and got the same result

**Comment by timja** [comment]
Generally this is a better way to set it up (bot user mode):
https://github.com/jenkinsci/slack-plugin#bot-user-mode
