### ISSUE TITLE
Channel specific notifications error

### ISSUE THREAD

**Issue by jonneymendoza** [jenkinsci/slack-plugin#813]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Mac OS

### Reproduction steps

Run a Jenkins pipeline via Fastlane.

### Expected Results

Run the build pipeline and post messages to a specific slack channel

### Actual Results

Error:

ERROR: Slack notification failed. See Jenkins logs for details.

### Anything else?

This is the line on my jenkinsfile that fails

  slackSend color: 'danger', channel: '#lnw_natives_jenkins', message: 'Build failed <@U020V12LES1>'

**Comment by jonneymendoza** [comment]
> Please check: https://github.com/jenkinsci/slack-plugin#troubleshooting-connection-failure

It doesn't say its a connection error? It just says slack noficiation failed

**Comment by timja** [comment]
The same troubleshooting steps apply

**Comment by jonneymendoza** [comment]
OK I see the logs now and it says this:

`Slack post may have failed. Response: null
May 03, 2022 12:26:19 PM WARNING jenkins.plugins.slack.StandardSlackService publish
Response Code: 400`

**Comment by timja** [comment]
How have you set this up? Have you created a custom slack app?

**Comment by bcoveny** [comment]
@timja @jonneymendoza 

We are also experiencing this issue.  I will try and track down more specifics but wanted to provide some more information.  We were working without issues until performing updates to Jenkins core and plugins.

The following are the major changes revolving around the slack notifications:
   Jenkins updated from 2.342 -> 2.363
   JDK updated from 1.8 -> 1.11
   Slack Notification Plugin updated from 608.v19e3b_44b_b_9ff -> 616.v03b_1e98d13dd

Downgraded Slack Notification Plugin back to 608.v19e3b_44b_b_9ff and the same error is occurring.

> 2022-08-10 02:10:38.492+0000 [id=210]	WARNING	j.p.slack.StandardSlackService#postToSlack: Slack post may have failed. Response: null
2022-08-10 02:10:38.492+0000 [id=210]	WARNING	j.p.slack.StandardSlackService#postToSlack: Response Code: 400

We have not setup a custom app and followed the steps from the Slack app for Jenkins CI.  I was going to link to that but then saw it was a direct link into our Slack workspace apps and not generalized.

Not sure if anything particular here may stand out.  I will try tomorrow to follow the troubleshooting section and provide more information.

**Comment by bcoveny** [comment]
I figured out the issue to be groovy code for us.  Previously "it.value" would return `#channel` and now in the latest version of Jenkins it returns an array of ascii values. We use an ArrayList and iter over all entries because sometimes we post to multiple channels.  Removing the .value produces the expected result.

Sample Groovy Code ran in the Script console

```
import groovy.transform.Field

@Field ArrayList channelsMap = [:]  

channelsMap = ["#channel"]

channelsMap.each {
  println "channel: \"${it.value}\""
  println "channel: \"${it}\""
}
```

Sample Output
```
channel: "[35, 99, 104, 97, 110, 110, 101, 108]"
channel: "#channel"
Result: [#channel]
```
