### ISSUE TITLE
Call to contributors: more unit testing

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/slack-plugin#82]
Currently, I accept pull requests with no unit testing.  It would be good if more unit tests were written to exercise the code base.  It would certainly make me more confident when merging contributions.  Although I do, and will continue to, manually test the plugin when merging.  It is generally accepted as a software development best practice.

For those who don't know me, I don't actively develop this plugin.  I do maintain pull requests and releases.

**Comment by timja** [comment]
Closing as this is buried, In general I won't take PRs without test coverage unless they are tiny or docs
