### ISSUE TITLE
unable to send message to slack users

### ISSUE THREAD

**Issue by vadirajks** [jenkinsci/slack-plugin#821]
jenkins version : jenkins-2.332.3-1.1.noarch
plugin  version :  608.v19e3b_44b_b_9ff [Latest](https://github.com/jenkinsci/slack-plugin/releases/latest)
code: 
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                script {
                    def userIds = slackUserIdsFromCommitters()
                    def tagString = userIds.collect { "<@$it>" }.join(' ')
                    def userId = slackUserIdFromEmail("${currentBuild.getBuildCauses()[0].userId}")
                    echo userId
                    // slackSend(color: 'good', channel:'@$UserId', message: "Message from Jenkins Pipeline ${tagString},${userIds}")
                    // slackSend(color: 'good', channel:"@${userId}", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
                    // slackSend(color: 'good', channel:"@${currentBuild.getBuildCauses()[0].userName}", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
                    slackSend(color: 'good', channel:"@${currentBuild.getBuildCauses()[0].userId}", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
                    // slackSend(color: 'good', channel:"@Vadirajks", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
                    
                }
            }
        }
    }
}

```
log :
```

slackSend(color: 'good', channel:'@$UserId', message: "Message from Jenkins Pipeline ${tagString},${userIds}")
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: affle, channel: @$UserId, color: good, botUser: true, tokenCredentialId: slack-bot-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
ERROR: Slack notification failed with exception: {"ok":false,"error":"channel_not_found"}
ERROR: Slack notification failed. See Jenkins logs for details.

slackSend(color: 'good', channel:"@${userId}", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
it is send slack app channel:
test-jenkins-workflow-integration APP  1:30 PM
Message from Jenkins Pipeline ,[]
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: affle, channel: @U010XXXXXXX, color: good, botUser: true, tokenCredentialId: slack-bot-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>

slackSend(color: 'good', channel:"@${currentBuild.getBuildCauses()[0].userName}", message: "Message from Jenkins Pipeline ${tagString},${userIds}")
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: affle, channel: @Vadiraj K S, color: good, botUser: true, tokenCredentialId: slack-bot-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
ERROR: Slack notification failed with exception: {"ok":false,"error":"channel_not_found"}
ERROR: Slack notification failed. See Jenkins logs for details.

slackSend(color: 'good', channel:"@Vadirajks", message: "Message from Jenkins Pipeline ${tagString},${userIds}")

```
NOTE:
I has all IM perm,jenkins conf is correct and i am able to print userid

**Comment by vadirajks** [comment]
Hi timja, Thanks for the update!!.
I have replaced my USERID with this and expecting app should send message to me.
first 2 slackSend sent message to app directly and last one failed because there is no channel corresponding to that
why it is sending to app?
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                script {
                    slackSend(color: 'good', channel:"U01085XXXX", message: "Message from Jenkins Pipeline")
                    slackSend(color: 'good', channel:"@U01085XXXX", message: "Message from Jenkins Pipeline")
                    slackSend(color: 'good', channel:"#U01085XXXX", message: "Message from Jenkins Pipeline")
                }
            }
        }
    }
}
```
Please let me know how to send messages to end users.
NOTE: we are able to send message to channels without any problem.

**Comment by vadirajks** [comment]
> Use slacks member id: https://moshfeu.medium.com/how-to-find-my-member-id-in-slack-workspace-d4bba942e38c
> 
> You can also lookup from their email address: https://github.com/jenkinsci/slack-plugin#user-id-look-up
fyi, there is no problem with the lookups here.

**Comment by timja** [comment]
The second one is the correct syntax.

have you created your own slack app or are using the legacy built in one?

**Comment by vadirajks** [comment]
> The second one is the correct syntax.
> 
> have you created your own slack app or are you using the legacy built in one?
> 
> if you’ve built your own I would check the scopes, if you haven’t I would suggest switching check the README

Yes, we have created our own internal private slack app and is has all perm. 
The above example sends the message to app channel.
My question is how to send a message to the user(for example to myself from the bot user/app] not to the "app channel"?. There is no use in sending messages to the app channel. please let me know how to send message to users.

**Comment by vadirajks** [comment]
It looks like we need to some channel to send and there is no direct message to end user's.
Only way to send message is by using below call's which intern creates channel to send message[DM] to end user.
conversations.open
conversations.create
Note sure if it is a part of this plugin.

**Comment by timja** [comment]
what do you mean the  `app channel`.

The plugin supports dm'ing the user from the app, i.e. it should come from "Jenkins" as a dm to the user

**Comment by vadirajks** [comment]
I am getting message's here in the app channel.
Even though we have mentioned user id:
![image](https://user-images.githubusercontent.com/2026134/173227867-88d5c3e5-a2ab-487f-991f-580ec0bf4a14.png)

**Comment by timja** [comment]
yes that is what Slack does, what's the problem?

It's messaging the user directly that's not a channel, it's DM's between the app and the user

**Comment by vadirajks** [comment]
Sorry, I thought I would get a message on my window.
I apologize for my misunderstand and raising the question here. 
please close this issue and thanks for all your help's!!
