### ISSUE TITLE
slackUserIdFromEmail returns null

### ISSUE THREAD

**Issue by ivtashev** [jenkinsci/slack-plugin#822]
### Your checklist for this issue

- [ ] Jenkins version: 2.263

- [ ] Plugin version: 2.49

- [ ] OS: CentOS

### Description

slackUserIdFromEmail returns null when used with valid user emails. Note that the slackSend method works using the slack app/token credential. 

I manage a bunch of different Jenkins instances, all on the same version of the plugin/controller and slackUserIdFromEmail works with them and the dedicated slack app. 
Configuration: 
Bot Token Scopes: 
chat:write
chat:write.customize
commands
files:write
incoming-webhook
reactions:write
users:read
users:read.email

Jenkins Configuration: 
Custom slack app bot user: checked
User ID Resolver: Slack email User ID Resolver

**Comment by ivtashev** [comment]
I also added a log recorder (see cofiguration below), but could not see anything useful in the jenkins log, only entries from slack send.

**Comment by marcelochaves95** [comment]
@ivtashev I had the same problem. You need to update your Jenkins. Use version 2.46+.
I opened this issue last year #763.

**Comment by timja** [comment]
Can you paste the logs? Maybe include all of the slack plugin logs not specific classes

Also org.apache.http may be useful
