### ISSUE TITLE
Slack invalid Auth facing even after untick the custom bot button.

### ISSUE THREAD

**Issue by agrawalsmart7** [jenkinsci/slack-plugin#834]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Mac OS

### Reproduction steps

This is my configuration of Slack inside `Configure System`

<img width="1307" alt="Screenshot 2022-07-28 at 2 41 14 PM" src="https://user-images.githubusercontent.com/39085884/181468510-8612a05c-198f-48f7-aba7-1379a9ba5640.png">

### Expected Results

I was expected to receive the artifact file on slack channel but I didn't recieved. 

### Actual Results

Instead I faced invalid auth error.

<img width="719" alt="Screenshot 2022-07-28 at 2 38 18 PM" src="https://user-images.githubusercontent.com/39085884/181468774-c68e4197-1c9d-4341-9a57-b66bead655f5.png">

**Comment by agrawalsmart7** [comment]
And I was able to get notification on my slack channel but can not receive the artifact file. This is what I am receiving on slack.

Please help

<img width="519" alt="Screenshot 2022-07-28 at 2 44 38 PM" src="https://user-images.githubusercontent.com/39085884/181469088-c2b50ef2-223e-4b6c-963d-4de20fa329cb.png">

**Comment by agrawalsmart7** [comment]
Hi Anyone can help?

**Comment by timja** [comment]
The documentation states that uploading files requires bot user mode which you have disabled:
https://github.com/jenkinsci/slack-plugin#file-upload

**Comment by agrawalsmart7** [comment]
Hi timja, when I tick that button and tried to check the connection I am getting the same error. 

<img width="1230" alt="Screenshot 2022-07-29 at 12 19 03 PM" src="https://user-images.githubusercontent.com/39085884/181700071-04e59cb0-122a-4ebc-b85e-c1ee0030f13d.png">

**Comment by timja** [comment]
you have not said how you configured slack.

Please follow https://github.com/jenkinsci/slack-plugin#bot-user-mode if you haven't already

**Comment by agrawalsmart7** [comment]
Hi timja, Thanks for pointing me out. Its working. It was my bad. I just need to create a custom app. Thanks for helping in resolving it.
