### ISSUE TITLE
Support messages with blocks and attachments

### ISSUE THREAD

**Issue by nhurel** [jenkinsci/slack-plugin#848]
### What feature do you want to see added?

Hello,
When reading slack api documentation, it looks possible to send both `blocks` and `attachments` to the payload : https://api.slack.com/messaging/composing/layouts#building-attachments 

However, the jenkins plugin only sends one or the other (giving priority to attachments).

Would it be possible to add the possibility to send blocks and attachments in a single message ?

Thank you

**Comment by timja** [comment]
What's the reason for it?

**Comment by nhurel** [comment]
Attachments being legacy, I try to use blocks as much as I can but slack doesn't manage long messages formatted with block as good as it does with attachments. So I'd like to be able to format build information using block api but attach big chunk of text (eg a changlog) as an attachment

**Comment by nhurel** [comment]
awesome ! Thank you both for the quick resolution.
