### ISSUE TITLE
Use colors when stating the build result 

### ISSUE THREAD

**Issue by FlorianWilhelm** [jenkinsci/slack-plugin#85]
Right now slack notifications are just plain text and you must read them to know if your build failed etc. Different colors for warnings, broken and good builds would allow you to see if everything is alright with just one glimpse. It is possible to use colors in Slack with the help of [attachments](https://api.slack.com/docs/attachments).

**Comment by samrocketman** [comment]
This was already implemented in pull request #20 (Sept 2014) and released in Slack plugin version 1.7 #27 (Feb 2015).  What version of the plugin are you using?

**Comment by FlorianWilhelm** [comment]
@samrocketman Thanks for the fast response, I'll check back with our administrator and inform him that he might have deployed an old version on our Jenkins installation. I'll let you know when I have new information.

**Comment by samrocketman** [comment]
There are bugs that will be fixed in the 1.8 release which were introduced in 1.7.  Might want to wait for 1.8 or deploy the snapshot version.

**Comment by FlorianWilhelm** [comment]
Our admin deployed the latest stable version I guess. Now colored output works. Anything important regarding the bugs in version 1.7?

**Comment by samrocketman** [comment]
See #63 for an issue that currently affects 1.7.

**Comment by samrocketman** [comment]
Since this appears to have already been resolved I'm going to close this.
