### ISSUE TITLE
Jenkins Env Vars in Custom Message

### ISSUE THREAD

**Issue by entuland** [jenkinsci/slack-plugin#867]
### Jenkins and plugins versions report

Jenkins 2.346.2
Slack Notification 631.v40deea_40323b

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

Setting up Jenkins post build actions with a grovy script, relevant section here:

```
if (matcherClient?.matches()) {
    clientBuildId=matcherClient.group(1)
    manager.addShortText("Client: " + clientBuildId)
    manager.build.addAction(
        new ParametersAction([
            new StringParameterValue("CLIENT_BUILD_ID", clientBuildId)
        ])
    )
}
```

And this text in the Custom Message - Success textbox:

`Client: $CLIENT_BUILD_ID`

Following the instructions reported by the Slack Notification Plugin which read as follows:

> Enter a custom message that will be included with the notifications. Include build variables in the form Jenkins Environment Variables by putting $VAR_NAME where you want it to appear.
> (from Slack Notification Plugin)

### Expected Results

The manager.addShortText() function works just fine and shows the short text in the Jenkins interface (this actually works, just to see if the code runs at all and doesn't error out)

The message sent to slack should show something like this:

```Client: 12345```

Where 12345 should match the value put by addShortText()

### Actual Results

The message sent to slack reads _literally_ this:

```Client: $CLIENT_BUILD_ID```

as if the variable was not seen or processed at all.

### Anything else?

I have a feeling we are just failing to use the correct syntax to print the variable out, or the correct way to add the variable to the environment.

**Comment by thomasvincent** [comment]
`if (matcherClient?.matches()) {
    clientBuildId=matcherClient.group(1)
    manager.addShortText("Client: ${CLIENT_BUILD_ID}")
    manager.build.addAction(
        new ParametersAction([
            new StringParameterValue("CLIENT_BUILD_ID", clientBuildId)
        ])
    )
}
`
