### ISSUE TITLE
Notify multiple Slack instances

### ISSUE THREAD

**Issue by lkraider** [jenkinsci/slack-plugin#87]
Our team uses slack for communication, but sometimes our clients have their own slack instances that we use for a specific project.

The current plugin setup does not allow to notify multiple (or even different) slack instances, since the configuration is global.

This is a request to add multiple global slack instances, and the project config page to allow to select (check) each of those to be notified.

**Comment by samrocketman** [comment]
What plugin version are you using?  The latest slack plugin release 1.7 (Feb 2015) came with the ability to connect to multiple slack instances on a per job basis which overrides the global settings.  This is in the Advanced section of the slack configuration in the Job.

**Comment by lkraider** [comment]
Ok, found the feature. I was expecting the advanced options to be under the same widget as the "slack notification" part.

Regarding this request, while I would call it resolved for giving the feature, a suggestion would be to add to the global options the choice to add more slack instances, so that setting up each job is simpler for the user, with a drop-down list of options configured globally.

I would also prefer all slack options to be under the widget, as the advanced job options are already over-used by many extensions, which makes it hard to browse. Preferably with some default notifications already selected (build success/failure/unstable would be my choice for defaults).

**Comment by samrocketman** [comment]
Regarding your suggestion for a global list providing a drop-down box of slack instances this is a welcome feature.  I'll mark this thread as contributions welcome.

Regarding your request to have slack options moved inside of the post-build configuration step please check out #79 which aims to fill that need.

**Comment by lkraider** [comment]
Regarding the feature, I noticed the notification only goes to the Slack instance defined in the job page, not to all slack instances.

So this issue is a request to:
- make it possible to notify multiple instances for the same job
- global config of multiple instances

**Comment by samrocketman** [comment]
With the post build configuration step configuration (currently unmerged #79) with the flexible publish plugin I would imagine that such a thing is possible without any modifications to the slack plugin itself.

**Comment by samrocketman** [comment]
After some testing #79 does not fix with the flexible publish plugin.  It's nearly there.  When adding multiple slack post-build actions in the flexible publish area the configs can be tested independently.  But when an actual build is run it doesn't post to slack at all.

**Comment by timja** [comment]
Closing as this can be achieved by job configuration overriding or overriding in a pipeline

**Comment by IrmantasM** [comment]
@timja How do you override it in the pipeline?

**Comment by z0ph** [comment]
I'm interested in this feature, need to notify two different slack instances for a same job.

**Comment by timja** [comment]
`slackSend message: 'main-team'`
`slackSend message: 'other-team', teamDomain: 'my-other-team-domain'`

**Comment by IrmantasM** [comment]
> `slackSend message: 'main-team'`
> `slackSend message: 'other-team', teamDomain: 'my-other-team-domain'`

Thank you! And how do I pass token for "my-other-team-domain"? Reading README it seems like I need to pass in yaml configuration file, is that correct?

**Comment by timja** [comment]
> > `slackSend message: 'main-team'`
> > `slackSend message: 'other-team', teamDomain: 'my-other-team-domain'`
> 
> Thank you! And how do I pass token for "my-other-team-domain"? Reading README it seems like I need to pass in yaml configuration file, is that correct?

`tokenCredentialId`

**Comment by z0ph** [comment]
Hi, 
Thanks, its working properly using the follow syntax for me (example for job failed)

```bash
slackSend( message: "Deployment Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}>)", teamDomain: 'myteam', tokenCredentialId: 'YYXXX', color: 'danger', baseUrl: 'https://myteam.slack.com/services/hooks/jenkins-ci/', botUser: false)
```

**Comment by timja** [comment]
don't set teamDomain and baseUrl, just use teamDomain
