### ISSUE TITLE
Include Jenkins job description in message

### ISSUE THREAD

**Issue by MoreSolutions** [jenkinsci/slack-plugin#88]
It would be nice if the message included the Jenkins job description (if set). We use some auto-generated jobs that have meaningless names, so the descriptions are much more useful.

**Comment by samrocketman** [comment]
I just merged a custom message pull request #78.  Will this suffice or do you still have something else in mind?

**Comment by MoreSolutions** [comment]
Yes, that should take care of it. Thanks!
