### ISSUE TITLE
Add `file.upload v2` support for `slackUploadFile`

### ISSUE THREAD

**Issue by junseok-l2** [jenkinsci/slack-plugin#884]
### What feature do you want to see added?

Recently, we are facing 408 timeout error when uploading large file with `slackUploadFile`.

Other sdks solved this issue by adopting file.upload v2 API.
* java-slack-sdk -> https://github.com/slackapi/java-slack-sdk/pull/1065
* python-slack-sdk -> https://github.com/slackapi/python-slack-sdk/pull/1272

Replacing `slackUplaodFile` to python-slack-sdk's `files_upload_v2` solved our problem.

It would be wonderful if `slack-plugin` could support file.upload v2 API so that we do not need to use other sdk to upload files.

**Comment by timja** [comment]
Interesting!

Contributions are very welcome if anyone is interested to do this.

**Comment by jviolas** [comment]
**Note**: Slack announced that `file.upload` is now **_deprecated_** and **_will stop functioning next year on March 11, 2025_**.

The deprecation will also enter a new phase on May 8, 2024, in which newly created Slack apps will not be able to use `file.upload` API. Which means for users of the Jenkins plugin, that new users will not be able to use the `slackUploadFile` step. It should keep working for already existing configuration until full retirement of the API.

Full details on this changes: https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay

**Comment by timja** [comment]
Thanks for the update @jviolas 

I've ported the plugin to v2 in https://github.com/jenkinsci/slack-plugin/pull/961

Please test it out and give feedback, and @junseok-l2 I would be interested if large files work for you now.

**Comment by jviolas** [comment]
@timja Thanks for the fast update 🤩 

I just updated to the last version (711) and it doesn't seem to work for me. At first I thought it might be coming from the fact that I upload the file as a response in a Slack thread using the syntax `#channelName:ts` where `ts` is coming from the result of the `slackSend` step. I removed to just use the channelName, also tried using directly a slack channel ID, but nothing worked.
In the job build console logs, I only have 2 logs `Using dirname=xxx` and `Adding file=xxxx` and nothing else after that for this step. Not sure what else I can test. For info, just after the `slackUploadFile` step, I use an `input` step for some validation.

**Comment by timja** [comment]
if you can provide a minimal reproducer I'll try reproduce it.

**Comment by timja** [comment]
I've found 2 issues so far.

1. If you're including a # then remove it and it'll work (incoming fix)
2. Rate limiting is low for the conversations.list API needed for looking up channel IDs so a cache is needed

**Comment by jviolas** [comment]
As for a minimal scenario to reproduce, I'm not sure how to do it.
In my case, my pipeline (a scripted pipeline), use the folowing steps:
```
def slackResponse = slackSend channel: '#notifs-changes', blocks: blocks

slackUploadFile channel: "#notifs-changes:${slackResponse.ts}", filePath: 'infraChanges.txt', initialComment: '*Full changes*:'
                 
def inputResult = input message: "Do you want to deploy?", ok: 'OK', submitter: validatorEmails, submitterParameter: 'approvedBy'

```

**Comment by timja** [comment]
Works for me:

<img width="998" alt="image" src="https://github.com/jenkinsci/slack-plugin/assets/21194782/d2748f07-1c65-486d-81e1-d48d7729a58d">

(blocks are the sample one from the README)

```
node {
  sh "echo hey > blah.txt"
 
  def blocks = [
	[
		"type": "section",
		"text": [
			"type": "mrkdwn",
			"text": "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*"
		]
	],
    [
		"type": "divider"
	],
	[
		"type": "section",
		"text": [
			"type": "mrkdwn",
			"text": "*Farmhouse Thai Cuisine*\n:star::star::star::star: 1528 reviews\n They do have some vegan options, like the roti and curry, plus they have a ton of salad stuff and noodles can be ordered without meat!! They have something for everyone here"
		],
		"accessory": [
			"type": "image",
			"image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/c7ed05m9lC2EmA3Aruue7A/o.jpg",
			"alt_text": "alt text for image"
		]
	]
]

  
  def slackResponse = slackSend channel: '#slack-plugin-testing', blocks: blocks

  slackUploadFile channel: "#slack-plugin-testing:${slackResponse.ts}", filePath: 'blah.txt', initialComment: '*Full changes*:'

}
```

**Comment by timja** [comment]
> In the job build console logs

Have you checked the system logs?

Or a log recorder under `jenkins.plugins.slack` INFO

**Comment by timja** [comment]
I can reproduce with a new app. Looking into it.

**Comment by timja** [comment]
Add the `groups:read` scope

**Comment by jviolas** [comment]
Yes ! that's it. `channel:read` was not enough (but channel is a public channel), with `groups:read` it's working.

**Comment by jviolas** [comment]
Thanks for your help and again for the fast update of this plugins !!

**Comment by timja** [comment]
> Yes ! that's it. `channel:read` was not enough (but channel is a public channel), with `groups:read` it's working.

Yeah it also includes private channels in its lookup if its been added to them, annoyingly requires an extra scope.

This will give you a clear error message: https://github.com/jenkinsci/slack-plugin/pull/963

**Comment by timja** [comment]
https://github.com/jenkinsci/slack-plugin/pull/965 will resolve the caching issue for larger workspaces.
On my one with 1900 channels its very easy to get rate limited, bit painful and slow to test as once you're rate limited you're stuck for a bit -.-.
