### ISSUE TITLE
it is not getting unistalled

### ISSUE THREAD

**Issue by manoharjallepalli** [jenkinsci/slack-plugin#908]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 10

### Reproduction steps

step :1 -Deleted all the credentials in slack notifier.
step:2 - In manage jenkins I have selected option plugins.
step:3 - I have selected available plugins.
step:4 - searched slack notification and uninstalled it.
 

### Expected Results

Uninstallation of slack notifier need to be done.

### Actual Results

It is showing uninstallation pending and uninstallation is not getting done.

**Comment by timja** [comment]
Restart Jenkins
