### ISSUE TITLE
jenkins integration issue.

### ISSUE THREAD

**Issue by Mahadevan777** [jenkinsci/slack-plugin#923]
### Your checklist for this issue

- [x ] Jenkins version   Jenkins 2.414.1

- [x] Plugin version     
Slack Notification      Version684.v833089650554 latest 

version too.

- [ x] OS  windows and in ubuntu also

### Description

Please describe your issue here.
i am unable to complete the test connection it is getting failed. 5-6 times i tried it is getting failed .i dont know what to please help me to solve.  i followed 4-5 tutorials same thing i done but every time getting failure

![Screenshot (89)](https://github.com/jenkinsci/slack-plugin/assets/72142581/a5ba01b5-dd97-4dda-908f-bc0a9af9b9e2)
![Screenshot (88)](https://github.com/jenkinsci/slack-plugin/assets/72142581/2e52c451-c8fe-4778-aeda-4e24c4d96929)

**Comment by timja** [comment]
Try this: https://github.com/jenkinsci/slack-plugin?tab=readme-ov-file#bot-user-mode

**Comment by Mahadevan777** [comment]
Hi timja I did not get you. How to do this , I am beginner. I am not getting could you please give me steps how to resolve this issue, what is wrong with my setup.   Why this is occurring. Please help me to solve this

**Comment by Mahadevan777** [comment]
Hye hi timja issue got resolved actually in the place of workspace we should need to add subdomain which will show while adding an app to slack. that's the  mistake i had done. any how thank you
