### ISSUE TITLE
Custom message is not appended to the "notifyStart" message if changes were found

### ISSUE THREAD

**Issue by MoreSolutions** [jenkinsci/slack-plugin#94]
This is happening with the new v1.8 release. If changes were found since the previous build, then the custom message does not get appended to the text.

**Comment by samrocketman** [comment]
cc @philowest.  Thanks for the report.  I do not actively develop this plugin.  I only maintain pull requests and releases.  I'll go ahead and mark this as a bug.  I'll dig into it and see if I can figure out why that is.

**Comment by philowest** [comment]
I'll re-create tonight and see what's going on.

**Comment by MoreSolutions** [comment]
From what I saw, the "getChanges" method needs to add the custom message, if specified.
https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L139

**Comment by philowest** [comment]
So it was easy to recreate. Just not catered for in the implementation. Easy enough to fix, but I'd like to spend a bit of time on this and write some tests to cover all the scenarios. Should have something done in a couple of days.

**Comment by samrocketman** [comment]
Can you @MoreSolutions code review #95, please?

**Comment by MoreSolutions** [comment]
Looks good to me @samrocketman. Thanks!!

**Comment by kmadel** [comment]
Fixed via PR #95
