### ISSUE TITLE
Support for addReaction/removeReaction with threadId and ts

### ISSUE THREAD

**Issue by cf-sewe** [jenkinsci/slack-plugin#944]
### What feature do you want to see added?

I would like to add/remove reactions in a post step. Currently this is seemingly only possible via the response object. 
Therefore I would like to add the reaction emoji using stored ThreadId and Timestamp.

Alternatively, is there a way to store and share the slackResponse between different stages?
I [tried](https://github.com/jenkinsci/slack-plugin/issues/736#issuecomment-733010231) this approach, unsuccessful.

**Comment by timja** [comment]
It should be quite straightforward, just add a new step for it.

**Comment by cf-sewe** [comment]
I am not sure how you mean this. I get an error that slackResponse is not defined in my post  step:

```
  post {
    always {
      script {
        slackResponse.removeReaction("hourglass_flowing_sand")
        def statusEmoji = currentBuild.result == 'SUCCESS' ? "white_check_mark" : "x"
        def statusColor = currentBuild.result == 'SUCCESS' ? green : red
        def message = "Execution of pipeline completed with status ${currentBuild.result}, duration ${currentBuild.durationString}."
        slackResponse.addReaction(statusEmoji)
        slackSend(
          channel: slackResponse.threadId,
          color: statusColor,
          message: message
        )
      }
    }
  }
  ```

**Comment by timja** [comment]
i mean adding a new step for it

**Comment by cf-sewe** [comment]
I did not understand what timja meant.
However I used a workaround which resolves the issue for me.

Now I declare the required variable on top level of the declarative pipeline. 
Then I can use the declared variable in each step, to update the Slack notification reactions.
