### ISSUE TITLE
multiple notifications for job start

### ISSUE THREAD

**Issue by chrylis** [jenkinsci/slack-plugin#96]
I have the box checked to notify when builds start, and I always get multiple Slack messages:

```
Gallery build from pull request - #342 GitHub pull request #342 of commit d28d70c9ee16cc1190498b0f30ea308e1e313168, no merge conflicts.

Gallery build from pull request - #342 Started by changes from nobody, Christopher Smith (48 file(s) changed)
```

It would be simpler to have these post as a single message.

**Comment by samrocketman** [comment]
Thanks for the issue.  I've witnessed this behavior as well and agree.  I don't actively develop this plugin.  I only maintain pull requests and releases.  Contributions to fix it are always welcome!

**Comment by tterrag1098** [comment]
I'm going to attempt a PR for this, but I would like to have a proper testing environment set up to check my work. How do you guys do testing typically?

**Comment by samrocketman** [comment]
@tterrag1098 
```bash
git clone https://github.com/samrocketman/jenkins-bootstrap-slack.git
cd jenkins-bootstrap-slack
./slack_bootstrap.sh
```
Visit `https://localhost:8080`.  When you're done you can delete the environment with `gradle clean`.  This assumes you have groovy and gradle installed as prerequisites.

**Comment by tterrag1098** [comment]
Actually I found the logic error (see #137) and it was pretty simple, don't think it needs testing really. If it does though you can let me know and I'll try to do it.

**Comment by samrocketman** [comment]
No worries, I always manually test before merging due to lack of unit tests.
