### ISSUE TITLE
SlackUploadFile for channel threads are not working after latest update.

### ISSUE THREAD

**Issue by raghavanrrs** [jenkinsci/slack-plugin#966]

**Comment by timja** [comment]
Please provide more information on how to reproduce, your slack plugin version, your build log from when running the upload and system logs.

Have you added the new required scopes: https://github.com/jenkinsci/slack-plugin/releases/tag/711.v41060f587001

**Comment by raghavanrrs** [comment]
> Please provide more information on how to reproduce, your slack plugin version, your build log from when running the upload and system logs.
> 
> Have you added the new required scopes: https://github.com/jenkinsci/slack-plugin/releases/tag/711.v41060f587001

Issue: Unable to upload files to User channel (userID resolved from commits) threads, but can able to upload files to Group channels in a thread
Slack plugin version: [714.v62ffe7c796cd](https://plugins.jenkins.io/slack)

Jenkins version: Jenkins 2.454
Build Log:
[Pipeline] slackUploadFile ([hide](https://jenkins.dranywhere-dev.com/view/infra-build-view/job/terraform-prod/566/console#))
ERROR: Failed uploading file to slack, channel not found: <user_id>:1715237120.817939

Method:
slackUploadFile(channel: "${env.userId}" + ":" + slackUserResponse.ts , filePath: "changelog.txt", initialComment:  "<@$userId> Detailed summary of changes for Build ${env.BUILD_NUMBER}.")

Bot Permissions:
chat:write
chat:write.customize
chat:write.public
files:write
incoming-webhook
channels:read
groups:read
files:read
users:read
users:read.email

**Comment by timja** [comment]
Hi, apologies for this.

It appears this was an unintentional feature that Slack wasn't aware of

https://github.com/slackapi/python-slack-sdk/issues/1326#issuecomment-1424986841

I've tested the workaround they suggested in https://github.com/jenkinsci/slack-plugin/pull/967
It will work after a minor change I made to fallback to try what the user passed in if it can't be found in the channel ID cache.

You will need to adapt your code to message a user first then user the channel ID from the response, (see the updated docs in the PR)

**Comment by ctrongminh** [comment]
Hi @timja ,
Could you please help to share your bot testing API scope permission ?

**Comment by timja** [comment]
That `Hey` message successfully sent a message to the users private channel?

My testing bot has the config from the manifest here:
https://github.com/jenkinsci/slack-plugin#creating-your-app

**Comment by ctrongminh** [comment]
Hi @timja ,

The "Hey" is sent to Slackbot, and then the it timeouts for the slackUploadFile command (5-6 minutes).

With the file.upload V1, we received the "Hey" in Slackbot, and the files are sent in the Jenkins app (you can see in the image, there are Slackbot and Jenkins app, which is separated, not as one),

Please note that the Jenkins app is custom app, no the Jenkin CI from Slack

<img width="1333" alt="Screen Shot 2024-05-13 at 22 21 28" src="https://github.com/jenkinsci/slack-plugin/assets/28387246/fe1de22c-2266-4d74-9c6a-c11e82854cdc">

**Comment by timja** [comment]
can you print the channel ID I think it should start with a D?

something like:

`echo slackResponse.id`

or

`sh "echo $slackResponse.id"`

**Comment by ctrongminh** [comment]
yes, the slackResponse.channelId output to the ID which starts with D, for the user, it starts with U.
I even input the channelId to the slackUploadFile but still, got the channel_not_found

```
def slackResponse = slackSend channel: 'U05052SAR54', message: 'Hey', sendAsText: true
slackUploadFile filePath: "*.txt", channel: 'D050861H9N1'
```

**Comment by timja** [comment]
> Hi @timja ,
> 
> With the file.upload V1, we received the "Hey" in Slackbot, and the files are sent in the Jenkins app (you can see in the image, there are Slackbot and Jenkins app, which is separated, not as one),

Try change it to this:

```
def slackResponse = slackSend channel: 'U05052SAR54', message: 'Hey', sendAsText: true, botUser: true
slackUploadFile filePath: "*.txt", channel: 'D050861H9N1'
```

**Comment by raghavanrrs** [comment]
> > Hi @timja ,
> > With the file.upload V1, we received the "Hey" in Slackbot, and the files are sent in the Jenkins app (you can see in the image, there are Slackbot and Jenkins app, which is separated, not as one),
> 
> Try change it to this:
> 
> ```
> def slackResponse = slackSend channel: 'U05052SAR54', message: 'Hey', sendAsText: true, botUser: true
> slackUploadFile filePath: "*.txt", channel: slackResponse.id
> ```

throws error:

Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: dbab4939-33b7-4f42-a386-a34075775b95
groovy.lang.MissingPropertyException: No such field found: field jenkins.plugins.slack.workflow.SlackResponse id

**Comment by timja** [comment]
ah sorry channelId.

```
def slackResponse = slackSend channel: 'U05052SAR54', message: 'Hey', sendAsText: true, botUser: true
slackUploadFile filePath: "*.txt", channel: slackResponse.channelId
```

**Comment by ctrongminh** [comment]
Hi @timja ,

I think I found the root cause,

In our case, when we use slackSend to send message to the user, the chat is sent from SlackBot to the user, which results to the channel Id of the SlackBot.

However, for the slackUploadFile to work, we need to input the channel Id of the Jenkins Apps for that user. I tested it by manually inputting the Jenkins App Channel Id, for my user to the slackUploadFile.

With the checkbox "Custom slack app bot user", message will be sent to SlackBot. However, if we uncheck, the connection will fail
<img width="1141" alt="image" src="https://github.com/jenkinsci/slack-plugin/assets/28387246/002f5613-dfc3-4f80-a09c-99acb88acb35">

**Comment by timja** [comment]
If you send as custom slack app bot user then it should come from the app not slackbot.

That's what I was trying to test in the last sample I sent to see if explicitly setting it to true makes it work.

**Comment by ctrongminh** [comment]
thank you, let me try it with flag, I miss that,

"botUser: true"

**Comment by MatthewBooth** [comment]
I'm having a similar issue here, but instead of a user, I'm using a thread posted in a channel, using: `slackResponse.threadId` as the `channel:` value.

The response is the same:
```
Slack upload may have failed. Response: {"ok":false,"error":"channel_not_found"}
10:40:37  Failed to complete uploading file to Slack
```

**Comment by raghavanrrs** [comment]
> I'm having a similar issue here, but instead of a user, I'm using a thread posted in a channel, using: `slackResponse.threadId` as the `channel:` value.
> 
> The response is the same:
> 
> ```
> Slack upload may have failed. Response: {"ok":false,"error":"channel_not_found"}
> 10:40:37  Failed to complete uploading file to Slack
> ```

for Reply to a channel thread we are using `slackResponse.ts` which works in our case.

**Comment by MatthewBooth** [comment]
> > I'm having a similar issue here, but instead of a user, I'm using a thread posted in a channel, using: `slackResponse.threadId` as the `channel:` value.
> > The response is the same:
> > ```
> > Slack upload may have failed. Response: {"ok":false,"error":"channel_not_found"}
> > 10:40:37  Failed to complete uploading file to Slack
> > ```
> 
> for Reply to a channel thread we are using `slackResponse.ts` which works in our case.

Thanks, I'll try that. We mostly upload into threads.

Sorry to jump in on your issue, but it seems quite related.

I actually just tried this

```
sh("echo hey > file.txt")
slackUploadFile(filePath: 'file.txt', channel: '#cloud-engineering')
```

Straight into a channel and the result is:

```
[Pipeline] sh
 + echo hey
[Pipeline] slackUploadFile
ERROR: Failed uploading file to slack
[Pipeline] }
```

**Comment by timja** [comment]
For threads this works for me:

```
  sh "echo hey > blah.txt"
  def slackResponse = slackSend channel: '#jenkins-slack-plugin-testing', message: "hello"

  slackUploadFile channel: "#jenkins-slack-plugin-testing:${slackResponse.ts}", filePath: 'blah.txt', initialComment: '*Full changes*:'
```

**Comment by timja** [comment]
Which is documented here: https://github.com/jenkinsci/slack-plugin#threads-support

**Comment by MatthewBooth** [comment]
Still no joy :/

This resulted in a channel not found message:
```
def slackResponse = slackSend(channel: "cloud-engineering", message: "Here is the primary message")
slackSend(channel: slackResponse.threadId, message: "Thread reply #1")
slackSend(channel: slackResponse.threadId, message: "Thread reply #2")
slackUploadFile(filePath: 'file.txt', channel: "cloud-engineering:" + slackResponse.ts)
```
```
 + echo hey
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: cloud-engineering, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: C01RT3GFUV6:1715683388.219919, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: C01RT3GFUV6:1715683388.219919, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackUploadFile
 Using dirname=/home/ec2-user/workspace/TestJenkinsSandbox and includeMask=file.txt
 Adding file /home/ec2-user/workspace/TestJenkinsSandbox/file.txt
 ERROR: Failed uploading file to slack
 Slack upload may have failed. Response: {"ok":false,"error":"channel_not_found"}
 Failed to complete uploading file to Slack
```

I also tried `threadId` instead of `ts`, which just produced:

```
 ERROR: Failed uploading file to slack
```

**Comment by timja** [comment]
Can you show an example that matches what I sent?

```
  slackUploadFile channel: "#jenkins-slack-plugin-testing:${slackResponse.ts}", filePath: 'blah.txt', initialComment: '*Full changes*:'
```

**Comment by MatthewBooth** [comment]
Sure :)

```
sh("echo hey > blah.txt")
        
def slackResponse = slackSend(channel: "cloud-engineering", message: "Here is the primary message")
slackSend(channel: slackResponse.threadId, message: "Thread reply #1")
slackSend(channel: slackResponse.threadId, message: "Thread reply #2")
        
slackUploadFile channel: "#cloud-engineering:${slackResponse.ts}", filePath: 'blah.txt', initialComment: '*Full changes*:'
```

```
[Pipeline] sh
 + echo hey
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: cloud-engineering, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: C01RT3GFUV6:1715684261.131669, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackSend
 Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: SNIP, channel: C01RT3GFUV6:1715684261.131669, color: <empty>, botUser: true, tokenCredentialId: SNIP, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
 [Pipeline] slackUploadFile
 Using dirname=/home/ec2-user/workspace/TestJenkinsSandbox and includeMask=blah.txt
 Adding file /home/ec2-user/workspace/TestJenkinsSandbox/blah.txt
 ERROR: Failed uploading file to slack
 [Pipeline] }
 
 [Pipeline] // ansiColor
 [Pipeline] }
 Slack upload may have failed. Response: {"ok":false,"error":"channel_not_found"}
 Failed to complete uploading file to Slack
```

**Comment by timja** [comment]
There doesn't happen to be anything useful in the system logs?

**Comment by MatthewBooth** [comment]
> There doesn't happen to be anything useful in the system logs?

Ahh, ha!

```
Couldn't convert channel name to ID in Slack: {"needed":"channels:read,groups:read,mpim:read,im:read","provided":"chat:write,files:write,reactions:write,users:read,users:read.email","ok":false,"error":"missing_scope"}
```

**Comment by timja** [comment]
hmm damn, I tried to make sure those logs all made it into the build log, =/.

**Comment by MatthewBooth** [comment]
> hmm damn, I tried to make sure those logs all made it into the build log, =/.

No worries, I feel silly that I didn't think of that myself! I've updated the scopes on the bot user/app and will try again.

It makes sense now, as even a file upload to a channel was also failing.

**Comment by raghavanrrs** [comment]
@timja how to print the slacksend response in user-friendly. As currently we are getting only the hashed values.

**Comment by timja** [comment]
`sh "echo $slackResponse.channelId $slackResponse.ts"`

or
`sh "echo $slackResponse.threadId"`
