### ISSUE TITLE
Slack Notification Plugin doesn't seem to use Jenkins' HTTP proxy configuration

### ISSUE THREAD

**Issue by flabrie** [jenkinsci/slack-plugin#978]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```Red hat Enterprise Linux 7
Jenkins 2.461
Slack Notification Plugin 722.vd07f1ea_7ff40
  ```
</details>

We use the **Slack Notification Plugin** on several Jenkins service running on different systems (_macOS_ and _Linux_), using the same configuration. It works without issue on all _Jenkins_, except the one _RHEL_ 7 server behind an HTTP proxy.

_Jenkins_ is correctly setup with the proxy settings: all other plugins use it without issue. 

The `*.slack.com` domain name it correctly whitelisted by the proxy. We can even test is from the server command line using a curl command line:

 ```
$ echo ${https_proxy}
http://142.101.142.12:8080/
$ curl --request POST --data 'payload={"channel": "#tests", "username":  "Jenkins", "text": "This is a test..."}' https://hooks.slack.com/services/${token}
ok
```

But through _Jenkins_, we get a **Failure** message when the **Test Connection** button is used on the settings, and no notification are received. And we can find a 404 error in Jenkins' log: 

```
Jun 06, 2024 12:34:12 PM FINE jenkins.plugins.slack.StandardSlackService
Posting: to #jenkins on foobar:  {"attachments":[{"fallback":"Slack/Jenkins plugin: you're all set on https://foobar.com/","color":"good","fields":[{"short":false,"value":"Slack/Jenkins plugin: you're all set on https://foobar.com/"}],"mrkdwn_in":["pretext","text","fields"]}],"link_names":"1","unfurl_links":"true","unfurl_media":"true","channel":"#jenkins","username":"Jenkins CLP/CMF"}
Jun 06, 2024 12:34:12 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Slack post may have failed. Response: null
Jun 06, 2024 12:34:12 PM WARNING jenkins.plugins.slack.StandardSlackService postToSlack
Response Code: 404
```

And as mentioned above, the HTTP proxy settings are correctly set in _Jenkins_.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Red Hat Enterprise Linux 7

### Reproduction steps

1. Open a session on _Jenkins_
2. Go to **Settings / System**
3. Make sure the **HTTP Proxy Configuration** section is configured correctly
4. Go to the _Slack_ section, and fill the required fields to reach your _Slack_ team account
5. Hit the **Test Connection** button.

### Expected Results

Expecting Slack Notification Plugin to use Jenkins HTTP Proxy Configuration to send messages.

### Actual Results

Slack Notification Plugin doesn't seem to reach Slack Services

**Comment by timja** [comment]
Can you provide your Slack configuration and how you're sending messages through Jenkins?

I suspect its your slack configuration and not a proxy issue.

**Comment by flabrie** [comment]
Here you'll find the Slack configuration: <img width="1341" alt="Capture d’écran, le 2024-06-07 à 08 48 04" src="https://github.com/jenkinsci/slack-plugin/assets/81308/95ed6e19-4570-4f4c-a1f5-179ca29cd8c3">

I get the failure using the **Test Connection** button. And here it's a Jenkins job usage example: 
<img width="957" alt="Capture d’écran, le 2024-06-07 à 08 51 34" src="https://github.com/jenkinsci/slack-plugin/assets/81308/834cd4b7-9d77-42ff-9d11-d4deb32e7a75">

Nothing is set in the **Advanced** settings.

**Comment by timja** [comment]
The code path you are going down should be:

https://github.com/jenkinsci/slack-plugin/blob/d07f1ea7ff4009eba4b6dc9ca083feb846beaa8a/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L195

https://github.com/jenkinsci/slack-plugin/blob/d07f1ea7ff4009eba4b6dc9ca083feb846beaa8a/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L480-L484

https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/HttpClient.java#L38-L51

https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L200

From reading through I can't see anywhere a proxy is missed and I'd expect more people to have issues if  so.

**Comment by flabrie** [comment]
> Does getting updates for plugins work when you click check for updates? (to verify proxy configuration is right)
 
Yes, it works. All other plugins requiring to reach an external server uses the proxy successfully. Here is the HTTP proxy configuration: 
<img width="1212" alt="Capture d’écran, le 2024-06-07 à 08 59 47" src="https://github.com/jenkinsci/slack-plugin/assets/81308/8108b933-6c02-442e-b992-f50a05344b8a">

**Comment by flabrie** [comment]
> The code path you are going down should be:
> 
> https://github.com/jenkinsci/slack-plugin/blob/d07f1ea7ff4009eba4b6dc9ca083feb846beaa8a/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L195
> 
> https://github.com/jenkinsci/slack-plugin/blob/d07f1ea7ff4009eba4b6dc9ca083feb846beaa8a/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L480-L484
> 
> https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/HttpClient.java#L38-L51
> 
> https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/StandardSlackService.java#L200
> 
> From reading through I can't see anywhere a proxy is missed and I'd expect more people to have issues if so.

Yes, I see. Can you tell me what's the hostname the plugin try to reach? Or is it an IP address? Because only `*.slack.com` domain is whitelisted for this plugin on our proxy.

**Comment by timja** [comment]
for your configuration its coemobile.slack.com

All looks configured right
