### ISSUE TITLE
project needs the token again

### ISSUE THREAD

**Issue by refextu** [jenkinsci/slack-plugin#99]
the global token is not inhierted from the global configuration into the project configuration

**Comment by samrocketman** [comment]
I have verified this.  If the global configuration is configured and the advanced settings of the job are unconfigured the slack is not notified.

As a result of this issue I've created new labels: `HIGH`, `MEDIUM`, and `LOW` for prioritization.  I would consider the priority of this bug high.

I do not actively develop this plugin.  I only maintain pull requests and releases.  Contributions are welcome to fix this critical issue.

**Comment by samrocketman** [comment]
After testing I realize that I forgot to configure the post-build slack post.  The settings currently work as I expect them.  Can you please elaborate what you mean?  Are you attempting to configure in the advanced settings posting to a channel without configuring the authentication settings at all?

**Comment by DanielRedOak** [comment]
I think its more an issue of the inheritance working a bit different than expected.  If you provide any over ride for the 'advanced' fields such as a different channel, it doesnt seem to inherit any settings from the global config meaning every job with a non global channel name would also need to include settings for domain and token.

**Comment by DanielRedOak** [comment]
Ah, thats just for the 'test' button functionality.  Thats the clarification piece here.

**Comment by samrocketman** [comment]
Does this still require an enhancement?  Though I think with the latest master the issue is resolved.  I'll have to test it.

**Comment by timja** [comment]
works AFAIK
