### ISSUE TITLE
Slack plugin for Jenkins Terms and Conditions

### ISSUE THREAD

**Issue by nemoto-shintaro** [jenkinsci/slack-plugin#995]
I don't see anything on the page about the Slack plugin for Jenkins terms and conditions, can you tell me which ones (Apache, MIT, etc.) apply?

**Comment by timja** [comment]
see here:
https://github.com/jenkinsci/slack-plugin/blob/master/pom.xml#L28-L33

but yes it should be in the repository as well

**Comment by nemoto-shintaro** [comment]
Thank you very much for your prompt response!
Is it correct to understand that the MIT licence you have provided us with is the same as the one placed on the Jenkins page at the following link, including the Copyright?
(https://github.com/jenkinsci/jenkins?tab=MIT-1-ov-file#readme)

**Comment by timja** [comment]
Basically, years are different and contributors but yes its the same license.

**Comment by nemoto-shintaro** [comment]
We have checked the details about the licence.
Thank you very much for your help in preparing the licence page!
